### ISSUE TITLE
Security exception

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#1088]
Why it heppen, can you help?

Fatal Exception: java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
       at com.google.common.util.concurrent.AbstractFuture.g(AbstractFuture.java:21)
       at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:21)
       at com.kamancho.melisma.trending.presentation.MediaControllerWrapper$Base.getController(MediaControllerWrapper.kt:1)
       at com.kamancho.melisma.trending.presentation.MediaControllerWrapper$Base.setRepeatMode(MediaControllerWrapper.kt:1)
       at com.kamancho.melisma.main.presentation.PlayerCommunicationState$InflateWithoutPlaying.a(PlayerCommunicationState.kt:59)
       at com.kamancho.melisma.main.presentation.PlayerCommunication$Base.map(PlayerCommunication.kt:1)
       at com.kamancho.melisma.player.

Caused by java.lang.SecurityException: Session rejected the connection request.
       at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:60)
       at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:60)
       at androidx.media3.session.MediaController.release(MediaController.java:60)
       at androidx.media3.common.util.Util.postOrRun(Util.java:1)
       at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1)
       at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:20)
       at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:450)
       at androidx.media3.common.util.Util.postOrRun(Util.java:1)
       at androidx.media3.session.MediaControllerStub.

**Comment by marcbaechinger** [comment]
With the available information there is nothing more that I can say than that the session rejected the connection.

While the reason why the session was rejected is unclear, you can avoid the crash by checking the future before using the controller. More information in #423 

Closing as a duplicate of #423. Please read the comments there for more details and comment there if you need more information.

**Comment by BoikoIlya** [comment]
class Base @Inject constructor(
         private val controllerFuture: ListenableFuture<MediaController>,
     ) : MediaControllerWrapper {

         private val controller: MediaController?
             get() = if (controllerFuture.isDone) controllerFuture.get() else null  

override fun getCurrentMediaItemIndex(function: (Int) -> Unit) {
             if(controller!=null) function.invoke(controller?.currentMediaItemIndex?:-1)
             else controllerFuture.addListener({},{
                 function.invoke(controller?.currentMediaItemIndex?:-1)
             })
         }

i dont understand why it is crashing on some devices 

Caused by java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
       at com.google.common.util.concurrent.AbstractFuture.g(AbstractFuture.java:21)
       at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:21)
       at com.kamancho.melisma.trending.presentation.MediaControllerWrapper$Base.getController(MediaControllerWrapper.kt:1)
       at com.kamancho.melisma.trending.presentation.MediaControllerWrapper$Base.getCurrentMediaItemIndex$lambda$19(MediaControllerWrapper.kt:22)
       at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1)
       at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:91)

**Comment by BoikoIlya** [comment]
i am dooing that because i want to load last queue when app launches, maybe you have another way of that?
