### ISSUE TITLE
Future get Security exception 

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#1096]
```
 class Base @Inject constructor(
         private val controllerFuture: ListenableFuture<MediaController>,
     ) : MediaControllerWrapper {

         private val controller: MediaController?
             get() = if (controllerFuture.isDone) controllerFuture.get() else null  

override fun getCurrentMediaItemIndex(function: (Int) -> Unit) {
             if(controller!=null) function.invoke(controller?.currentMediaItemIndex?:-1)
             else controllerFuture.addListener({},{
                 function.invoke(controller?.currentMediaItemIndex?:-1)
             })
         }
```

i dont understand why it is crashing on some devices 

```
Caused by java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
       at com.google.common.util.concurrent.AbstractFuture.g(AbstractFuture.java:21)
       at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:21)
       at com.kamancho.melisma.trending.presentation.MediaControllerWrapper$Base.getController(MediaControllerWrapper.kt:1)
       at com.kamancho.melisma.trending.presentation.MediaControllerWrapper$Base.getCurrentMediaItemIndex$lambda$19(MediaControllerWrapper.kt:22)
       at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1)
       at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:91)
       at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:19)
       at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:63)
       at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:63)
       at androidx.media3.session.MediaController.release(MediaController.java:63)
       at androidx.media3.common.util.Util.postOrRun(Util.java:1)
       at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1)
       at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:20)
       at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$12(MediaControllerStub.java:450)
       at androidx.media3.common.util.Util.postOrRun(Util.java:1)
       at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:30)
       at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:1)
       at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0(MediaSessionService.java:99)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
```

```
    @Singleton
    @Provides
    fun provideControllerFuture(context: Context): ListenableFuture<MediaController> {
        return MediaController.Builder(
            context,
            SessionToken(context, ComponentName(context, PlayerService::class.java))
        ).buildAsync()
    }

 @Provides
    @Singleton
    fun provideMediaPlayer(
        context: Context,
        listener: ControllerListener,
    ): ExoPlayer {
        return ExoPlayer.Builder(context)
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(C.USAGE_MEDIA)
                    .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
                    .build()
                ,true)
            .setHandleAudioBecomingNoisy(true)
            .build().also {
                it.addListener(listener)
            }
    }

    @Provides
    @Singleton
    fun providePendingIntent(context: Context): PendingIntent {
        return TaskStackBuilder.create(context).run {
            addNextIntent(Intent(context, MainActivity::class.java))
            getPendingIntent(0, PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)
        }
    }

    @Provides
    @Singleton
    fun provideMediaSession(
        context: Context,
        player: ExoPlayer,
        pendingIntent: PendingIntent,
        callBack: MediaSessionCallBack,
    ): MediaSession {
        return MediaSession.Builder(context, player)
            .setSessionActivity(pendingIntent)
            .setCallback(callBack)
            .build()
    }
```

```
class MediaSessionCallBack @Inject constructor(
    private val temporaryTracksCache: TemporaryTracksCache,
    private val playbackResumptionRepository: PlaybackResumptionRepository,
    private val dispatchersList: DispatchersList,
    private val playerCommunication: PlayerCommunication,
    private val playingTrackIdCommunication: PlayingTrackIdCommunication,
    private val trackPlaybackPositionCommunication: TrackPlaybackPositionCommunication,
    private val controller: MediaControllerWrapper,
) : MediaSession.Callback {

    private var job: Job? = null
    private val scope = CoroutineScope(Dispatchers.IO)
    private val lastQueue = mutableListOf<MediaItem>()
    
    init {
        controller.getCurrentMediaItemIndex { currentMediaItemIndex ->
            Log.d("tag", ": currentMediaItemIndex $currentMediaItemIndex ${controller.mediaItemCount}")
            if (currentMediaItemIndex == -1 || currentMediaItemIndex==0 && controller.mediaItemCount==0) {

                job = scope.launch(dispatchersList.io()) {
                    val tracks = playbackResumptionRepository.fetchLastQueue()
                    val position = playbackResumptionRepository.fetchLastPosition()
                    val pos = if (position < 0) 0
                    else if (position > tracks.lastIndex) tracks.lastIndex
                    else position

                    if (tracks.isEmpty()) return@launch
                    val newQueue = tracks.map {
                        MediaItem.Builder()
                            .setMediaId(it.mediaId)
                            .build()
                    }

                    withContext(dispatchersList.ui()) {
                        playerCommunication.map(
                            PlayerCommunicationState.InflateWithoutPlaying(
                                newQueue,
                                tracks,
                                pos
                            )
                        )
                    }

                    lastQueue.clear()
                    lastQueue.addAll(tracks)

                }
            }
        }
    }

    override fun onSetMediaItems(
        mediaSession: MediaSession,
        controller: MediaSession.ControllerInfo,
        mediaItems: MutableList<MediaItem>,
        startIndex: Int,
        startPositionMs: Long,
    ): ListenableFuture<MediaSession.MediaItemsWithStartPosition> {

        val tracks =
            if (lastQueue.isEmpty()) temporaryTracksCache.readCurrentPageTracks()
            else lastQueue


        return Futures.immediateFuture(
            MediaSession.MediaItemsWithStartPosition(
                tracks,
                startIndex,
                startPositionMs
            )
        ).apply { lastQueue.clear() }

    }

    override fun onPlaybackResumption(
        mediaSession: MediaSession,
        controller: MediaSession.ControllerInfo,
    ): ListenableFuture<MediaSession.MediaItemsWithStartPosition> {
        job?.cancel()

        val tracks = scope.async(dispatchersList.io()) {
            playbackResumptionRepository.fetchLastQueue()
        }.asCompletableFuture().get()
        lastQueue.addAll(tracks)

        val position = scope.async(dispatchersList.io()) {
            playbackResumptionRepository.fetchLastPosition()
        }.asCompletableFuture().get()

        return if (tracks.isNotEmpty()) {
            val pos = if (position < 0) 0
            else if (position > tracks.lastIndex) tracks.lastIndex
            else position
            playerCommunication.map(PlayerCommunicationState.PlaybackResumption(tracks, pos))
            playingTrackIdCommunication.map(tracks[pos].mediaId)
            trackPlaybackPositionCommunication.clearPosition()
            Futures.immediateFuture(
                MediaSession.MediaItemsWithStartPosition(
                    tracks,
                    pos,
                    0
                )
            ).apply { lastQueue.clear() }
        } else super.onPlaybackResumption(mediaSession, controller)


    }

}
```

i am dooing that because i want to load last queue when app launches, maybe you have another way of that?

**Comment by marcbaechinger** [comment]
Sorry for not having mentioned that there is already a duplicate of this issue which is 423. To keep the information around one issue together, we can continue there. 

Closing as a duplicate of https://github.com/androidx/media/issues/423. Please read the comments there for more details and comment there if you need more information.
