### ISSUE TITLE
unique session id

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#1115]
Caused by java.lang.IllegalStateException: Session ID must be unique. ID=
       at androidx.media3.session.MediaSession.<init>(MediaSession.java:2)
       at androidx.media3.session.MediaSession$Builder.build(MediaSession.java:110)
       at com.kamancho.melisma.player.di.PlayerModule.provideMediaSession(PlayerModule.java:110)
       at com.kamancho.melisma.player.di.PlayerModule_ProvideMediaSessionFactory.provideMediaSession(PlayerModule_ProvideMediaSessionFactory.java:110)
       at com.kamancho.melisma.player.di.PlayerModule_ProvideMediaSessionFactory.get(PlayerModule_ProvideMediaSessionFactory.java:110)
       at com.kamancho.melisma.player.di.PlayerModule_ProvideMediaSessionFactory.get(PlayerModule_ProvideMediaSessionFactory.java:110)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:14)
       at com.kamancho.melisma.main.di.DaggerAppComponent$PlayerComponentImpl.injectPlayerService(DaggerAppComponent.java:45)
       at com.kamancho.melisma.main.di.DaggerAppComponent$PlayerComponentImpl.inject(DaggerAppComponent.java:45)
       at com.kamancho.melisma.player.presentation.PlayerService.onCreate(PlayerService.kt:45)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4705)
       at android.app.ActivityThread.access$1900(ActivityThread.java:273)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)

```
@Module
class PlayerModule {


    @Provides
    @PlayerServiceScope
    fun provideMediaPlayer(
        context: Context,
        listener: ControllerListener,
    ): ExoPlayer {
        return ExoPlayer.Builder(context)
            .setAudioAttributes(
                AudioAttributes.Builder()
                    .setUsage(C.USAGE_MEDIA)
                    .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)
                    .build()
                ,true)
            .setHandleAudioBecomingNoisy(true)
            .build().also {
                it.addListener(listener)
            }
    }

    @Provides
    @PlayerServiceScope
    fun providePendingIntent(context: Context): PendingIntent {
        val intent = Intent(context, MainActivity::class.java)
        intent.setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP)

        return PendingIntent.getActivity(
            context,
            111,
            intent,
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
        )
    }

    @Provides
    @PlayerServiceScope
    fun provideMediaSession(
        context: Context,
        player: ExoPlayer,
        pendingIntent: PendingIntent,
        callBack: MediaSessionCallBack,
    ): MediaSession {
        return MediaSession.Builder(context, player)
            .setSessionActivity(pendingIntent)
            .setCallback(callBack)
            .build()
    }



}
```

```
class PlayerService: MediaSessionService(){

    @Inject
    lateinit var player: ExoPlayer

    @Inject
    lateinit var mediaSession: MediaSession

    @SuppressLint("UnsafeOptInUsageError")
    override fun onCreate() {
        super.onCreate()

        (this.applicationContext as App).appComponent
            .playerComponent()
            .build()
            .inject(this)
    }


    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaSession = mediaSession

    override fun onTaskRemoved(rootIntent: Intent?) {
        if (!player.playWhenReady) {
             stopSelf()
        }
    }


    override fun onDestroy() {
        player.release()
        mediaSession.release()
        super.onDestroy()
    }


}
```

**Comment by marcbaechinger** [comment]
This exception is thrown when multiple sessions with the same IDs are created. 

If an app intentionally wants to create multiple sessions, then each session needs to get a unique session with `MediaSession.Builder.setId("uniqueSessionId")`.

If the ID is not explicitly set when building the session, then calling `build` multiple times produces this error. Releasing the first session fixes the problem. 

Looks like the dependency wiring builds the session twice unexpectedly?

**Comment by marcbaechinger** [comment]
I think this is the part you have to investigate in your app I'm afraid.

Looking at the DI code, I'd say it's not much work to just copy the code that creates the player and the session into `onCreate` and remove all the DI magic. If this then works, you can start moving to DI again if this really looks like it enhances design and readability of you app. If things are done under the hood by a frameworks, it is often obfuscating a bit what is going on. So going back  to charted grounds can help.

I'm closing this issue because I don't think it's a library issue and I don't have experience to help you with the DI approach.

**Comment by marcbaechinger** [comment]
We've added a [section](https://developer.android.com/media/media3/session/control-playback#unique-session-id) in the developer documentation around the requirement of the session ID being unique.
