### ISSUE TITLE
Freezes and OutOfMemoryError in ExoPlayer

### ISSUE THREAD

**Issue by steelbytes** [androidx/media#1131]
pixel 7 pro / android 14

get the uri of a large mp4/h265 using Intent.ACTION_OPEN_DOCUMENT.  Play it in ExoPlayer with `setEffects(OverlayEffect(TextureOverlay))`.  Skip back and forth a long way *lots* of times.  video freezes.  via ui trigger release of the player and make a new one (it's too fragile to reuse) and then get outofmemory error.  without skipping it doesn't freeze.  without effects it doesn't freeze.

```02-26 09:30:36.978 22929 24438 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 86016 free bytes and 84KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:355)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:283)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.effect.ExternalTextureManager.registerInputFrame(ExternalTextureManager.java:205)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.effect.DefaultVideoFrameProcessor.registerInputFrame(DefaultVideoFrameProcessor.java:504)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.exoplayer.video.CompositingVideoSinkProvider$VideoSinkImpl.registerInputFrame(CompositingVideoSinkProvider.java:348)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:1342)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1998)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:827)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:974)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1079)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:529)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
02-26 09:30:36.978 22929 24438 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by steelbytes** [comment]
cancel this bug report
