### ISSUE TITLE
Exoplayer media3 Drm clearkey Not working

### ISSUE THREAD

**Issue by xxanisxx** [androidx/media#1208]
this is my first time working on drm media so am try to make demo app
i did try to play WIDEVINE encryption work for me but when i test CLEARKEY cant make it work
the mdpurl with the key & keyid is working when i test it in jwplayer stream tester

https://developer-tools.jwplayer.com/stream-tester
### mdpUrl i use
https://linear210-de-dash1-prd-ak.cdn12.skycdp.com/345431/index_stereo.mpd
key: 000babeda3f2592ce71f7a976288ef9b
kid: b537b1141cef8d580f7e8a4efba57b65

### widevine code : (working)
```
fun widevinePlayer(){
        val licenseUri = "https://drm-widevine-licensing.axtest.net/AcquireLicense"
        val  mpdUrl = "https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd"
        val httpRequestHeaders : Map<String, String> = mapOf("X-AxDRM-Message" to "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImtleXMiOlt7ImlkIjoiOWViNDA1MGQtZTQ0Yi00ODAyLTkzMmUtMjdkNzUwODNlMjY2IiwiZW5jcnlwdGVkX2tleSI6ImxLM09qSExZVzI0Y3Iya3RSNzRmbnc9PSJ9XX19.4lWwW46k-oWcah8oN18LPj5OLS5ZU-_AQv7fe0JhNjA")

        val playerItem =  MediaItem.Builder()
            .setUri(mpdUrl)
            .setDrmConfiguration(
                MediaItem.DrmConfiguration.Builder(C.WIDEVINE_UUID)
                    .setLicenseUri(licenseUri)
                    .setMultiSession(true)
                    .setLicenseRequestHeaders(httpRequestHeaders)
                    .build()
            )
            .build()
        exoPlayer.setMediaItem(playerItem);
        exoPlayer.prepare();
        exoPlayer.play();
    }
```
### clearkey code : (not working)
```
fun clearkeyPlayer(){
        val drmKey = "b537b1141cef8d580f7e8a4efba57b65"
        val drmKeyId = "000babeda3f2592ce71f7a976288ef9b"
        val mpdUrl = "https://linear210-de-dash1-prd-ak.cdn12.skycdp.com/345431/index_stereo.mpd"

        val drmKeyBytes = drmKey.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        val encodedDrmKey = Base64.encodeToString(drmKeyBytes, Base64.DEFAULT)

        val drmKeyIdBytes = drmKeyId.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        val encodedDrmKeyId = Base64.encodeToString(drmKeyIdBytes, Base64.DEFAULT)

        val drmBody = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"${encodedDrmKey}\",\"kid\":\"${encodedDrmKeyId}\"}],\"type\":\"temporary\"}"
        val playerItem = MediaItem.Builder()
            .setUri(mpdUrl)
            .setDrmConfiguration(
                MediaItem.DrmConfiguration.Builder(C.CLEARKEY_UUID)
                    .setMultiSession(true)
                    .setKeySetId(drmBody.toByteArray())
//                    .setKeySetId(byteArrayOf(*drmKeyBytes, *drmKeyIdBytes))
                    .build()
            )
            .build()
        exoPlayer.setMediaItem(playerItem);
        exoPlayer.prepare();
        exoPlayer.play();
    }
```
### console logs
```
2024-03-21 01:08:07.129  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.0::IDrmFactory clearkey
2024-03-21 01:08:07.130  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.0::IDrmFactory default
2024-03-21 01:08:07.135  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.0::IDrmFactory widevine
2024-03-21 01:08:07.139  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.1::IDrmFactory clearkey
2024-03-21 01:08:07.142  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.1::IDrmFactory widevine
2024-03-21 01:08:07.148  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.2::IDrmFactory clearkey
2024-03-21 01:08:07.151  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.2::IDrmFactory widevine
2024-03-21 01:08:07.155  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.3::IDrmFactory clearkey
2024-03-21 01:08:07.160  6367-6395  DrmUtils                com.example.sabritest                I  found android.hardware.drm@1.3::IDrmFactory widevine
2024-03-21 01:08:07.720  6367-6442  MpdParser               com.example.sabritest                W  Ignoring <ContentProtection> with schemeIdUri="urn:mpeg:dash:mp4protection:2011" (ClearKey) due to missing required default_KID attribute.
2024-03-21 01:08:07.768  6367-6442  chatty                  com.example.sabritest                I  uid=10079(com.example.sabritest) ExoPlayer:Loade identical 1 line
2024-03-21 01:08:07.771  6367-6442  MpdParser               com.example.sabritest                W  Ignoring <ContentProtection> with schemeIdUri="urn:mpeg:dash:mp4protection:2011" (ClearKey) due to missing required default_KID attribute.
2024-03-21 01:08:07.974  6367-6395  MediaDrm-JNI            com.example.sabritest                E  Illegal state exception: Failed to restore keys: No license (-2001)
2024-03-21 01:08:07.975  6367-6395  DefaultDrmSession       com.example.sabritest                E  DRM session error
                                                                                                      android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: No license
                                                                                                          at android.media.MediaDrm.restoreKeys(Native Method)
                                                                                                          at androidx.media3.exoplayer.drm.FrameworkMediaDrm.restoreKeys(FrameworkMediaDrm.java:327)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.restoreKeys(DefaultDrmSession.java:475)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:439)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:327)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:732)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:632)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:514)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:460)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.onFormatResult(SampleQueue.java:945)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.peekSampleMetadata(SampleQueue.java:712)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.read(SampleQueue.java:428)
                                                                                                          at androidx.media3.exoplayer.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:395)
                                                                                                          at androidx.media3.exoplayer.BaseRenderer.readSource(BaseRenderer.java:524)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:992)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1102)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:541)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:223)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
2024-03-21 01:08:07.980  6367-6395  CryptoHal               com.example.sabritest                D  found drm@1.0 ICryptoFactory clearkey
2024-03-21 01:08:07.985  6367-6395  CryptoHal               com.example.sabritest                D  found drm@1.0 ICryptoFactory default
2024-03-21 01:08:07.985  6367-6395  CryptoHal               com.example.sabritest                D  found drm@1.0 ICryptoFactory widevine
2024-03-21 01:08:07.987  6367-6395  CryptoHal               com.example.sabritest                D  found drm@1.1 ICryptoFactory clearkey
2024-03-21 01:08:07.989  6367-6395  CryptoHal               com.example.sabritest                D  found drm@1.1 ICryptoFactory widevine
2024-03-21 01:08:07.999  6367-6395  CryptoHal               com.example.sabritest                E  Failed to make crypto plugin
2024-03-21 01:08:08.018  6367-6450  OMXClient               com.example.sabritest                I  IOmx service obtained
2024-03-21 01:08:08.028  6367-6449  SurfaceUtils            com.example.sabritest                D  connecting to surface 0xe7b84ba8, reason connectToSurface
2024-03-21 01:08:08.031  6367-6449  MediaCodec              com.example.sabritest                I  [OMX.google.h264.decoder] setting surface generation to 6519811
2024-03-21 01:08:08.031  6367-6449  SurfaceUtils            com.example.sabritest                D  disconnecting from surface 0xe7b84ba8, reason connectToSurface(reconnect)
2024-03-21 01:08:08.031  6367-6449  SurfaceUtils            com.example.sabritest                D  connecting to surface 0xe7b84ba8, reason connectToSurface(reconnect)
2024-03-21 01:08:08.038  6367-6450  ACodec                  com.example.sabritest                E  [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
2024-03-21 01:08:08.050  6367-6450  ACodec                  com.example.sabritest                I  codec does not support config priority (err -1010)
2024-03-21 01:08:08.094  6367-6395  ExoPlayerImplInternal   com.example.sabritest                E  Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:667)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:223)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.exoplayer.drm.DrmSession$DrmSessionException: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: No license
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.onError(DefaultDrmSession.java:557)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.restoreKeys(DefaultDrmSession.java:478)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:439)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:327)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:732)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:632)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:514)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:460)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.onFormatResult(SampleQueue.java:945)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.peekSampleMetadata(SampleQueue.java:712)
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.read(SampleQueue.java:428)
                                                                                                          at androidx.media3.exoplayer.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:395)
                                                                                                          at androidx.media3.exoplayer.BaseRenderer.readSource(BaseRenderer.java:524)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:992)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1102)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:541)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                          at android.os.Looper.loop(Looper.java:223) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                      Caused by: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: No license
                                                                                                          at android.media.MediaDrm.restoreKeys(Native Method)
                                                                                                          at androidx.media3.exoplayer.drm.FrameworkMediaDrm.restoreKeys(FrameworkMediaDrm.java:327)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.restoreKeys(DefaultDrmSession.java:475)
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:439) 
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:327) 
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:732) 
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:632) 
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:514) 
                                                                                                          at androidx.media3.exoplayer.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:460) 
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.onFormatResult(SampleQueue.java:945) 
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.peekSampleMetadata(SampleQueue.java:712) 
                                                                                                          at androidx.media3.exoplayer.source.SampleQueue.read(SampleQueue.java:428) 
                                                                                                          at androidx.media3.exoplayer.source.chunk.ChunkSampleStream.readData(ChunkSampleStream.java:395) 
                                                                                                          at androidx.media3.exoplayer.BaseRenderer.readSource(BaseRenderer.java:524) 
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:992) 
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814) 
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940) 
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1102) 
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:541) 
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                          at android.os.Looper.loop(Looper.java:223) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
2024-03-21 01:08:08.100  6367-6449  SurfaceUtils            com.example.sabritest                D  connecting to surface 0xe7b864d8, reason connectToSurface
2024-03-21 01:08:08.100  6367-6449  MediaCodec              com.example.sabritest                I  [OMX.google.h264.decoder] setting surface generation to 6519812
2024-03-21 01:08:08.100  6367-6449  SurfaceUtils            com.example.sabritest                D  disconnecting from surface 0xe7b864d8, reason connectToSurface(reconnect)
2024-03-21 01:08:08.100  6367-6449  SurfaceUtils            com.example.sabritest                D  connecting to surface 0xe7b864d8, reason connectToSurface(reconnect)
2024-03-21 01:08:08.100  6367-6449  SurfaceUtils            com.example.sabritest                D  disconnecting from surface 0xe7b84ba8, reason disconnectFromSurface
2024-03-21 01:08:08.120  6367-6449  SurfaceUtils            com.example.sabritest                D  disconnecting from surface 0xe7b864d8, reason disconnectFromSurface
```
### implementation
    def media3_version = "1.3.0"

    // For media playback using ExoPlayer
    implementation "androidx.media3:media3-exoplayer:$media3_version"
    // For building media playback UIs
    implementation "androidx.media3:media3-ui:$media3_version"
    // For DASH playback support with ExoPlayer
    implementation "androidx.media3:media3-exoplayer-dash:$media3_version"

what am doing wrong?
Is this approach correct ?

**Comment by icbaker** [comment]
> ```kt
> val encodedDrmKey = Base64.encodeToString(drmKeyBytes, Base64.DEFAULT)
> ```

You should use `Base64.URL_SAFE | Base64.NO_PADDING | Base64.NO_WRAP` as documented here:
* https://www.w3.org/TR/encrypted-media/#clear-key-license-format
* https://www.w3.org/TR/encrypted-media/#using-base64url

Your example key is `b537b1141cef8d580f7e8a4efba57b65` in hex which becomes `tTexFBzvjVgPfopO+6V7ZQ==` in non-URL-safe, padded base64 but should instead be `tTexFBzvjVgPfopO-6V7ZQ` in URL-safe, non-padded base64.

----

> ```kt
> .setKeySetId(drmBody.toByteArray())
> ```

This is not correct. This method is for passing a key set ID for offline playback, as documented: https://developer.android.com/reference/androidx/media3/common/MediaItem.DrmConfiguration.Builder#setKeySetId(byte[])

You need to provide a custom `MediaDrmCallback` implementation that returns your license response, probably using `LocalMediaDrmCallback`. See other issues with example code: https://github.com/androidx/media/issues/777#issuecomment-1787524054

----

Your DASH manifest is missing the required `defaultKID` parameter in the `<ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"></ContentProtection>` node. See https://github.com/google/ExoPlayer/issues/9169#issuecomment-878297192.

**Comment by xxanisxx** [comment]
Thank you for your fast reply

i did understand the first point but the second point and the third i have an issue on them 

### First Point ( Fixed)
```
 val drmKey = "b537b1141cef8d580f7e8a4efba57b65"
        val drmKeyId = "000babeda3f2592ce71f7a976288ef9b"
        val mpdUrl = "https://linear210-de-dash1-prd-ak.cdn12.skycdp.com/345431/index_stereo.mpd"

        val drmKeyBytes = drmKey.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        val encodedDrmKey = Base64.encodeToString(drmKeyBytes,
            Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP)

        val drmKeyIdBytes = drmKeyId.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        val encodedDrmKeyId = Base64.encodeToString(drmKeyIdBytes, Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP)
     
        val drmBody = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"${encodedDrmKey}\",\"kid\":\"${encodedDrmKeyId}\"}],\"type\":\"temporary\"}"
```

### Second Point ( Not Fixed)
issues: 
-the build work but the ide is all on read cause 
```
This declaration is opt-in and its usage should be marked with `@androidx.media3.common.util.UnstableApi` or `@OptIn(markerClass = androidx.media3.common.util.UnstableApi.class)`
```
-i did follow the code in the example but there is onw thing i cant import or use which is ( DownloadUtil )
```
val dashMediaItem = MediaItem.Builder()
            .setUri(mpdUrl)
            .setMimeType(MimeTypes.APPLICATION_MPD)
            .setMediaMetadata(MediaMetadata.Builder().setTitle("test").build())
            .build()

        val trackSelector = DefaultTrackSelector(this)
        val loadControl = DefaultLoadControl()

        val drmCallback = LocalMediaDrmCallback(drmBody.toByteArray())
        val drmSessionManager = DefaultDrmSessionManager.Builder()
            .setPlayClearSamplesWithoutKeys(true)
            .setMultiSession(false)
            .setKeyRequestParameters(HashMap())
            .setUuidAndExoMediaDrmProvider(C.CLEARKEY_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
            .build(drmCallback)
        val mediaSource = DashMediaSource.Factory(DownloadUtil.getHttpDataSourceFactory(this))
            .setDrmSessionManagerProvider { drmSessionManager }
            .createMediaSource(dashMediaItem)

        exoPlayer = ExoPlayer.Builder(this)
            .setTrackSelector(trackSelector)
            .setLoadControl(loadControl)
            .setSeekForwardIncrementMs(10000L)
            .setSeekBackIncrementMs(10000L)
            .build()

        playerView.player = exoPlayer;


        exoPlayer.setMediaSource(mediaSource, true)
        exoPlayer.prepare();
        exoPlayer.play();
```

### Third Point ( Not Fixed)

am sorry but i didnt understand this point DASH manifest where i can find this file and where i put this tag  ContentProtection

### Thank you

**Comment by icbaker** [comment]
You will need to handle the opt-in error as described here: https://developer.android.com/media/media3/exoplayer/migration-guide#unstableapi

You don't need to create the `DashMediaSource` manually. You can customize just the `DrmSessionManager` instance as described here: https://developer.android.com/media/media3/exoplayer/drm#using-a-custom-drmsessionmanager

And your `DefaultMediaSourceFactory` can then be passed when building the player: https://developer.android.com/media/media3/exoplayer/media-sources#customizing-media-source-creation

---

You DASH manifest is the media link you provided in the original comment: https://linear210-de-dash1-prd-ak.cdn12.skycdp.com/345431/index_stereo.mpd

**Comment by xxanisxx** [comment]
### Thank you i get it now 

Full working code if some one need it 

```
@OptIn(UnstableApi::class)
    fun clearkeyPlayer(){
        val drmKey = "000babeda3f2592ce71f7a976288ef9b"
        val drmKeyId = "b537b1141cef8d580f7e8a4efba57b65"
        val mpdUrl = "https://linear210-de-dash1-prd-ak.cdn12.skycdp.com/345431/index_stereo.mpd"
        val drmKeyBytes = drmKey.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        val encodedDrmKey = Base64.encodeToString(drmKeyBytes,
            Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP)

        val drmKeyIdBytes = drmKeyId.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        val encodedDrmKeyId = Base64.encodeToString(drmKeyIdBytes, Base64.URL_SAFE or Base64.NO_PADDING or Base64.NO_WRAP)

        val drmBody = "{\"keys\":[{\"kty\":\"oct\",\"k\":\"${encodedDrmKey}\",\"kid\":\"${encodedDrmKeyId}\"}],\"type\":\"temporary\"}"


        val dashMediaItem = MediaItem.Builder()
            .setUri(mpdUrl)
            .setMimeType(MimeTypes.APPLICATION_MPD)
            .setMediaMetadata(MediaMetadata.Builder().setTitle("test").build())
            .build()

        val trackSelector = DefaultTrackSelector(this)
        val loadControl = DefaultLoadControl()

        val drmCallback = LocalMediaDrmCallback(drmBody.toByteArray())
        val drmSessionManager = DefaultDrmSessionManager.Builder()
            .setPlayClearSamplesWithoutKeys(true)
            .setMultiSession(false)
            .setKeyRequestParameters(HashMap())
            .setUuidAndExoMediaDrmProvider(C.CLEARKEY_UUID, FrameworkMediaDrm.DEFAULT_PROVIDER)
            .build(drmCallback)

        val customDrmSessionManager: DrmSessionManager = drmSessionManager
        val mediaSourceFactory = DefaultMediaSourceFactory(this)
            .setDrmSessionManagerProvider { customDrmSessionManager }
            .createMediaSource(dashMediaItem)
        exoPlayer = ExoPlayer.Builder(this)
            .setTrackSelector(trackSelector)
            .setLoadControl(loadControl)
            .setSeekForwardIncrementMs(10000L)
            .setSeekBackIncrementMs(10000L)
            .build()

        playerView.player = exoPlayer;


        exoPlayer.setMediaSource(mediaSourceFactory, true)
        exoPlayer.prepare();
        exoPlayer.play();
    }
```
