### ISSUE TITLE
Encrypted media not playing in exoplayer

### ISSUE THREAD

**Issue by WeMakeBest** [androidx/media#1259]
Hello, i am trying to play encrypted mp4 file in exoplayer v1.3.0 but I am getting this error:

```Playback error

androidx.media3.exoplayer.ExoPlaybackException: Source error
  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713)
  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:683)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loopOnce(Looper.java:223)
  at android.os.Looper.loop(Looper.java:324)
  at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FragmentedMp4Extractor, Mp4Extractor, FlvExtractor, FlacExtractor, WavExtractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor, PngExtractor, WebpExtractor, BmpExtractor, HeifExtractor) could read the stream.{contentIsMalformed=false, dataType=1}
  at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:94)
  at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1044)
  at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
  at java.lang.Thread.run(Thread.java:1012)
                                                                                                      
```

When I try to decrypt the file into file manager it works perfectly fine but it does not work in exoplayer. Here is the code I am using to play media in exoplayer:

https://github.com/WeMakeBest/Encrypted-Video-Player-Code/tree/main

**Comment by icbaker** [comment]
Does your `FileEncryptedDataSource` pass the tests defined by [`DataSourceContractTest`](https://developer.android.com/reference/androidx/media3/test/utils/DataSourceContractTest) once you've set up some encrypted sample files (they don't have to be MP4)? More info: https://medium.com/google-exoplayer/standardising-datasource-implementations-through-testing-b7a8ab04f8d1

That would help identify whether the issue is with ExoPlayer or with your `DataSource` implementation.

**Comment by WeMakeBest** [comment]
Hey,
Can you tell me more about how I can implement DataSourceContractTest?

**Comment by icbaker** [comment]
You can see lots of examples in our code base: https://github.com/search?q=repo%3Aandroidx%2Fmedia%20extends%20DataSourceContractTest&type=code

**Comment by WeMakeBest** [comment]
I did subclass DataSourceContractTest but don't know how to use it.

**Comment by WeMakeBest** [comment]
@icbaker  Thanks for your help! I managed to solve the issue.
