### ISSUE TITLE
Offline download fails after started with HttpDataSourceException

### ISSUE THREAD

**Issue by sureshsivalingam01** [androidx/media#1327]
### Version

Media3 1.3.1

### Devices that reproduce the issue

Samsung M12 Running Android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

Start download task with download manager with hls feed link

### Expected result

Should download the entire stream

### Actual result

Task failed: application/x-mpegURL:https://d2ezdd2dtb7fe2.cloudfront.net/2024movies/301ashke/master.m3u8, false
                                                                                                      androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                                                          at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:436)
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:799)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:612)
                                                                                                          at androidx.media3.datasource.cache.CacheWriter.readBlockToCache(CacheWriter.java:174)
                                                                                                          at androidx.media3.datasource.cache.CacheWriter.cache(CacheWriter.java:136)
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader$SegmentDownloadRunnable.doWork(SegmentDownloader.java:507)
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader$SegmentDownloadRunnable.doWork(SegmentDownloader.java:484)
                                                                                                          at androidx.media3.common.util.RunnableFutureTask.run(RunnableFutureTask.java:126)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)

### Media

https://d2ezdd2dtb7fe2.cloudfront.net/2024movies/301ashke/master.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
The stream downloads perfectly fine for me in the demo app. Given the 403 response code, it might have been some temporary issue or similar? In case, this sounds more like a network/server issue where it shouldn't reply with 403 when requesting media segments.

**Comment by sureshsivalingam01** [comment]
thank you, I'll check it again

**Comment by tonihei** [comment]
Closing due to lack of further information.
