### ISSUE TITLE
Exception: Malformed URL (RTSP)

### ISSUE THREAD

**Issue by 1280103995** [androidx/media#1427]
### Version

Media3 1.3.1

### More version details

The same problem also occurs on version 1.1.1

### Devices that reproduce the issue

Samsung A51, android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

Actually, I'm using ```react-native-video``` and I also added:
```
media3Version = "1.3.1"
useExoplayerRtsp = true
```
But I guess this problem has nothing to do with what you use to build the App.

### Expected result

Hopefully it will work fine like VLC.

### Actual result

```
Playback error
     androidx.media3.exoplayer.ExoPlaybackException: Source error
         at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:717)
         at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:689)
         at android.os.Handler.dispatchMessage(Handler.java:102)
         at android.os.Looper.loopOnce(Looper.java:226)
         at android.os.Looper.loop(Looper.java:313)
         at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
         at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:418)
         at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:311)
         at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
         at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
         at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029)
         at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
         at java.lang.Thread.run(Thread.java:1012)
```
<img width="1303" alt="3aecc0f-6cfe-4bab-b3f7-fc04e3330ced" src="https://github.com/androidx/media/assets/17424486/5d5c86eb-a968-4199-8059-95fa026ecd8e">

### Media

The link I used for testing is as follows (the token is hidden by me).The same problem occurs when removing the parameter.

rtsp://192.168.43.1:1338?auth=************

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by 1280103995** [comment]
<img width="1048" alt="d08ef6c-38fc-4f81-9a69-b9e09f5c9813" src="https://github.com/androidx/media/assets/17424486/819cf3bd-3b04-47cf-8d3d-1f130c9c3407">

**Comment by icbaker** [comment]
The error looks like your `MediaSource.Factory` implementation hasn't delegated to `RtspMediaSource.Factory` (I can see `ProgressiveMediaPeriod` in your call stack in the debugger screenshot, which means you're using `ProgressiveMediaSource`). `DefaultMediaSourceFactory` should do this delegation automatically, and fail if `RtspMediaSource.Factory` is not available at run-time, so it seems that you must have a custom `MediaSource.Factory` (or be incorrectly creating `MediaSource` instances directly).

It's hard to offer more precise help without more information, but this hopefully gives you an idea of where to look to fix things - it's not a problem with the URI, or the selection of `DataSource`, it's a problem with the selection of `MediaSource`.

`useExoplayerRtsp = true` is not a setting I recognize, I dobn't think it's directly affecting the behaviour of the media3 library, it must be consumed by something else.

**Comment by 1280103995** [comment]
> The error looks like your `MediaSource.Factory` implementation hasn't delegated to `RtspMediaSource.Factory` (I can see `ProgressiveMediaPeriod` in your call stack in the debugger screenshot, which means you're using `ProgressiveMediaSource`). `DefaultMediaSourceFactory` should do this delegation automatically, and fail if `RtspMediaSource.Factory` is not available at run-time, so it seems that you must have a custom `MediaSource.Factory` (or be incorrectly creating `MediaSource` instances directly).
> 
> It's hard to offer more precise help without more information, but this hopefully gives you an idea of where to look to fix things - it's not a problem with the URI, or the selection of `DataSource`, it's a problem with the selection of `MediaSource`.
> 
> `useExoplayerRtsp = true` is not a setting I recognize, I dobn't think it's directly affecting the behaviour of the media3 library, it must be consumed by something else.

Thanks, this is useful information, I will forward the question to the attribution repository.
