### ISSUE TITLE
Tell me please why the error androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer occurs

### ISSUE THREAD

**Issue by udfvirus** [androidx/media#1502]
```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=2, format=Format(1/4, null, null, audio/mpeg-L2, null, -1, null, [-1, -1, -1.0, null], [2, 48000]), format_supported=NO_UNSUPPORTED_TYPE
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(1/4, null, null, audio/mpeg-L2, null, -1, null, [-1, -1, -1.0, null], [2, 48000])
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1079)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:551)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1560)
	at androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:517)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:994)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
	at android.os.Handler.dispatchMessage(Handler.java:102) 
	at android.os.Looper.loop(Looper.java:223) 
	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by icbaker** [comment]
`format_supported=NO_UNSUPPORTED_TYPE`

The logs indicate that your device doesn't support the audio you're playing. Note that the `audio/mpeg-L2` audio sample format is not required to be supported by any Android devices (though some devices may of course support it): https://developer.android.com/media/platform/supported-formats#audio-formats
