### ISSUE TITLE
Exoplayer constantly requesting for the same segment in dash live stream

### ISSUE THREAD

**Issue by Vinni0834** [androidx/media#1534]
HI,
My exoplayer application is constantly requesting the same segment number ,so I dwelled down a little 
I added a breakpoint at timeus calculation then I found out that all the values that I am getting are some random values.this is the call stack 
`"ExoPlayer: Playback@22667" prio=5 tid=0x46 nid=NA runnable

java.lang.Thread.State: RUNNABLE

 at androidx.media3.exoplayer.dash.manifest.SegmentBase$MultiSe gmentBase.getSegmentNum (Segme ntBase.java:190)

at androidx.media3.exoplayer.dash.manifest.Representation$MultiSegment Representation.getSegmentN um(Representation.java:358)

at androidx.media3.exoplayer.d ash.DefaultDashChunk Source$Repre sentation Holder.getSegmentNum(Def aultDashChunk Source.java:1151)

at androidx.media3.exoplayer.dash.DefaultDashChunkSource.getSeg mentNum(DefaultDashChunk Source.j ava:685)

at androidx.media3.exoplayer.dash.DefaultDashChunkSource.getNextChunk(DefaultDashChunkSource.java:401)

at androidx.media3.exoplayer.source.chunk.ChunkSampleStream.continueLoading(ChunkSampleStream.java:588)

at androidx.media3.exoplayer.source.Composite SequenceableLoade r$SequenceableLoaderWith Track Types.continueLoading (CompositeSequeceableLoader.java:131)

at androidx.media3.exoplayer.dash. DashMediaPeriod.continueLoading(DashMediaPeriod.java:328)

at androidx.media3.exoplayer.source.M asking Media Period.continueLoading( Masking MediaPeriod.java:229)

at androidx.media3.exoplayer.M ediaPeriod Holder.continueLoading(MediaPeriod Holder.java:234)

at androidx.media3.exoplayer. ExoPlayer ImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:2521)

at androidx.media3.exoplayer. ExoPlayer ImplInternal.handlePeriod Prepared(ExoPlayerImplInternal.java:2473)

at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:563)

at android.os.Handler.dispatch Message(Handler.java:102)

at android.os.Looper.loopOnce( Looper.java:201)

at android.os.Looper.loop(Looper.java:288) 
at android.os.HandlerThread.run(HandlerThread.java:67)`

I can see that in Android.os.looper.looponce there is  an maskingmedia object and based on those values segment number is calculated .when I had checked the network logs it's actually requesting future segments.the segments that are not available in the livestream .

**Comment by simpleearn** [comment]
> HI,
> My exoplayer application is constantly requesting the same segment number ,so I dwelled down a little 
> I added a breakpoint at timeus calculation then I found out that all the values that I am getting are some random values.this is the call stack 
> `"ExoPlayer: Playback@22667" prio=5 tid=0x46 nid=NA runnable
> 
> java.lang.Thread.State: RUNNABLE
> 
>  at androidx.media3.exoplayer.dash.manifest.SegmentBase$MultiSe gmentBase.getSegmentNum (Segme ntBase.java:190)
> 
> at androidx.media3.exoplayer.dash.manifest.Representation$MultiSegment Representation.getSegmentN um(Representation.java:358)
> 
> at androidx.media3.exoplayer.d ash.DefaultDashChunk Source$Repre sentation Holder.getSegmentNum(Def aultDashChunk Source.java:1151)
> 
> at androidx.media3.exoplayer.dash.DefaultDashChunkSource.getSeg mentNum(DefaultDashChunk Source.j ava:685)
> 
> at androidx.media3.exoplayer.dash.DefaultDashChunkSource.getNextChunk(DefaultDashChunkSource.java:401)
> 
> at androidx.media3.exoplayer.source.chunk.ChunkSampleStream.continueLoading(ChunkSampleStream.java:588)
> 
> at androidx.media3.exoplayer.source.Composite SequenceableLoade r$SequenceableLoaderWith Track Types.continueLoading (CompositeSequeceableLoader.java:131)
> 
> at androidx.media3.exoplayer.dash. DashMediaPeriod.continueLoading(DashMediaPeriod.java:328)
> 
> at androidx.media3.exoplayer.source.M asking Media Period.continueLoading( Masking MediaPeriod.java:229)
> 
> at androidx.media3.exoplayer.M ediaPeriod Holder.continueLoading(MediaPeriod Holder.java:234)
> 
> at androidx.media3.exoplayer. ExoPlayer ImplInternal.maybeContinueLoading(ExoPlayerImplInternal.java:2521)
> 
> at androidx.media3.exoplayer. ExoPlayer ImplInternal.handlePeriod Prepared(ExoPlayerImplInternal.java:2473)
> 
> at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage (ExoPlayerImplInternal.java:563)
> 
> at android.os.Handler.dispatch Message(Handler.java:102)
> 
> at android.os.Looper.loopOnce( Looper.java:201)
> 
> at android.os.Looper.loop(Looper.java:288) 
> at android.os.HandlerThread.run(HandlerThread.java:67)`
> 
> I can see that in Android.os.looper.looponce there is  an maskingmedia object and based on those values segment number is calculated .when I had checked the network logs it's actually requesting future segments.the segments that are not available in the livestr

**Comment by Vinni0834** [comment]
@simpleearn what was your comment
Didn't get you
