### ISSUE TITLE
Allow changing SNTP client timeout

### ISSUE THREAD

**Issue by jrocharodrigues** [androidx/media#1540]
### [REQUIRED] Use case description
We started seeing some high video start times (~10 seconds) in our live stream app. After some investigation we found out the problem was that due to some problem in their network, the request to the SNTP server to resolve the time offset was timing out, and this exception was thrown:
```
Failed to resolve time offset.
  java.net.SocketTimeoutException: Poll timed out
      at libcore.io.IoBridge.poll(IoBridge.java:682)
      at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:150)
      at java.net.PlainDatagramSocketImpl.receive0(PlainDatagramSocketImpl.java:141)
      at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:164)
      at java.net.DatagramSocket.receive(DatagramSocket.java:847)
      at androidx.media3.exoplayer.util.SntpClient.loadNtpTimeOffsetMs(SntpClient.java:185)
      at androidx.media3.exoplayer.util.SntpClient.access$400(SntpClient.java:41)
      at androidx.media3.exoplayer.util.SntpClient$NtpTimeLoadable.load(SntpClient.java:300)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      at java.lang.Thread.run(Thread.java:919)
```

After some digging, we found out the problem was due to the client could not reach the sntp server (time.android.com) with IPv6. 
Changing the server to one without IPv6, or disabling IPv6 on the client network would solve the problem.

### Proposed solution
It would be great if exoplayer allowed to change the timeout of the sntp request, because the default, 10 seconds, seems to high for a non critical request.

It would also be nice if the exoplayer SNTP client would follow the protocol and attempt the alternative ipAddresses in case of failure, which would also solve the problem we we're having due to IPv6 connectivity problems.

Thanks in advance for your support
Best regards

**Comment by rohitjoins** [comment]
Hi @jrocharodrigues,

We have added changes to [allow changing SNTP client timeout](https://github.com/androidx/media/commit/c60baabb1c0b6b2f700ec605cb309d5704b30b66) and [retrying alternative addresses](https://github.com/androidx/media/commit/ded66debc32a51c273be1dbd96c34e01f6607fac). Thank you for reporting this issue and feel free to reopen this issue in case you have any more questions / suggestions.

**Comment by jose-a-rodrigues-alb** [comment]
Hi @rohitjoins,

Thanks for the fast response and solution.

Best regards

**Comment by jrocharodrigues** [comment]
Hi @rohitjoins ,

Thanks for the fast response and fix.

Best regards
