### ISSUE TITLE
Unable to play an online stream

### ISSUE THREAD

**Issue by ashishb** [androidx/media#1567]
### Version

Media3 main branch

### More version details

Exoplayer (media3) cannot play this online stream
http://radio3.citrus3.com:8584/listen.pls?sid=1

### Devices that reproduce the issue

Multiple devices including emulator

### Reproducible in the demo app?

Yes

### Reproduction steps

Try to play this stream in Exoplayer

### Expected result

The stream should play

### Actual result

The play fails with

```
java.lang.Exception: Failed to play http://radio3.citrus3.com:8584/listen.pls?sid=1 -> ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED
at androidx.media3.exoplayer.ExoPlayerImpl.lambda$updatePlaybackInfo$16(ExoPlayerImpl.java:2119)
at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda26.invoke(D8$$SyntheticClass:0)
at androidx.media3.common.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:339)
at androidx.media3.common.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:223)
at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
at androidx.media3.common.util.ListenerSet.flushEvents(ListenerSet.java:245)
at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:2182)
at androidx.media3.exoplayer.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:2016)
at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$1$androidx-media3-exoplayer-ExoPlayerImpl(ExoPlayerImpl.java:351)
at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
...
```

### Media

http://radio3.citrus3.com:8584/listen.pls?sid=1

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @ashishb,

The media link you provided indicates that it was a `.pls` playlist file, however, we currently don't support parsing and extracting the media URLs from this kind of file. Similar to the suggestion in https://github.com/google/ExoPlayer/issues/2051#issuecomment-259368308 and https://github.com/google/ExoPlayer/issues/1947#issuecomment-253755064, you can parse the playlists in your app code, then pass the contained media URLs to ExoPlayer.

Hope the answer helps!

**Comment by ashishb** [comment]
Thanks @tianyif
