### ISSUE TITLE
Exoplayer not working for Android 6.0

### ISSUE THREAD

**Issue by ajithrshivan** [androidx/media#1579]
### Version

Media3 main branch

### More version details

I am using Exoplayer to play videos from a URL. It works like a charm for Android 7.0 and above but the player freezes and gives error 400 while playing in Android 6.0. Please help. 

Playback error
  androidx.media3.exoplayer.ExoPlaybackException: Source error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
      at android.os.Handler.dispatchMessage(Handler.java:98)
      at android.os.Looper.loop(Looper.java:148)
      at android.os.HandlerThread.run(HandlerThread.java:61)
  Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:366)
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64)
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
      at java.lang.Thread.run(Thread.java:818)
  Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
      at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212)
      at com.android.okhttp.Connection.connect(Connection.java:1322)
      at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
      at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:485)
      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:372)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:362)
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64) 
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182) 
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
      at java.lang.Thread.run(Thread.java:818) 
  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337)
      at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231)
      at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
      at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643)
      at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353)
      at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
      at com.android.okhttp.Connection.connect(Connection.java:1322) 
      at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
      at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:485) 
      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466) 
      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:372) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540) 
      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java) 
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:362) 
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64) 
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182) 
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
      at java.lang.Thread.run(Thread.java:818) 
  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337) 
      at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231) 
      at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115) 
      at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643) 
      at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353) 
      at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
      at com.android.okhttp.Connection.connect(Connection.java:1322) 
      at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
      at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:485) 
      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466) 
      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:372) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540) 
      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java) 
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:362) 
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64) 
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182) 
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
      at java.lang.Thread.run(Thread.java:818) 

### Devices that reproduce the issue

Samsung Galaxy J2 Pro running android 6.0.1

### Devices that do not reproduce the issue

Redmi Note 7 running android 10

### Reproducible in the demo app?

Not tested

### Reproduction steps

Just play video using this url

### Expected result

The media play successfully

### Actual result

Playback error
  androidx.media3.exoplayer.ExoPlaybackException: Source error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
      at android.os.Handler.dispatchMessage(Handler.java:98)
      at android.os.Looper.loop(Looper.java:148)
      at android.os.HandlerThread.run(HandlerThread.java:61)
  Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:366)
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64)
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
      at java.lang.Thread.run(Thread.java:818)
  Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
      at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212)
      at com.android.okhttp.Connection.connect(Connection.java:1322)
      at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
      at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:485)
      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:372)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:362)
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64) 
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182) 
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
      at java.lang.Thread.run(Thread.java:818) 
  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337)
      at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231)
      at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
      at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643)
      at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353)
      at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
      at com.android.okhttp.Connection.connect(Connection.java:1322) 
      at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
      at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:485) 
      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466) 
      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:372) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540) 
      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java) 
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:362) 
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64) 
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182) 
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
      at java.lang.Thread.run(Thread.java:818) 
  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337) 
      at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231) 
      at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115) 
      at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643) 
      at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353) 
      at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212) 
      at com.android.okhttp.Connection.connect(Connection.java:1322) 
      at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410) 
      at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131) 
      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:485) 
      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466) 
      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:372) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418) 
      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540) 
      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java) 
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:362) 
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86) 
      at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
      at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64) 
      at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:182) 
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
      at java.lang.Thread.run(Thread.java:818) 

### Media

https://player.vimeo.com/external/449791591.m3u8?s=a9b3328543a5647b86b2af747d539fc732e487fb&oauth2_token_id=1202211572

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @ajithrshivan,

According to [this guide](https://developer.android.com/media/media3/exoplayer/troubleshooting#fixing-sslhandshakeexception-certpathvalidatorexception-and-err_cert_authority_invalid-errors), this error is not an ExoPlayer issue I'm afraid, please find the documentation contained in the above link for further troubleshooting. Thanks!
