### ISSUE TITLE
Chromebook + Media Notification Click = :boom: 

### ISSUE THREAD

**Issue by DavidEdwardsBL** [androidx/media#1584]
### Version

Media3 main branch

### Devices that reproduce the issue

Chromebook running version 103.0.5060.132

### Devices that do not reproduce the issue

Chromebook running version 125.0.6422.197

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Start app
2. Play media
3. Notification icon shows in toolbar
4. Click on icon
5. Notification list opens up
6. Click on demo app media notification
7. :boom: Notification dies (App is still alive)

Notification also does not ever reappear, until the App is killed.

### Expected result

Notification uses the session activity pending intent to take the user to the app.

### Actual result

Notification dies.

---

It also crashes for the Spotify App. It does not crash for web apps, such as Youtube Music.

In case it is helpful, this appears in the log when clicking the notification.

```
15:07:57.785  I  close
15:07:57.786  E  onConnectionError
                 MojoResult(0): OK
                 	at org.chromium.mojo.bindings.Connector.readOutstandingMessages(Connector.java:179)
                 	at org.chromium.mojo.bindings.Connector.onWatcherResult(Connector.java:152)
                 	at org.chromium.mojo.bindings.Connector.access$100(Connector.java:25)
                 	at org.chromium.mojo.bindings.Connector$WatcherCallback.onResult(Connector.java:142)
                 	at org.chromium.mojo.system.impl.WatcherImpl.onHandleReady(WatcherImpl.java:53)
15:07:57.787  I  stopDucking
15:07:57.788  E  onConnectionError
                 MojoResult(9): FAILED_PRECONDITION
                 	at org.chromium.mojo.bindings.Connector.onWatcherResult(Connector.java:154)
                 	at org.chromium.mojo.bindings.Connector.access$100(Connector.java:25)
                 	at org.chromium.mojo.bindings.Connector$WatcherCallback.onResult(Connector.java:142)
                 	at org.chromium.mojo.system.impl.WatcherImpl.onHandleReady(WatcherImpl.java:53)
```

From `ArcMediaSession` and `ArcMediaController`.

### Media

n/a

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @DavidEdwardsBL,

My understanding is that `ArcMediaSession` and `ArcMediaController` are in the package of `org.chromium.arc.media_session`, where we can hardly help with. [Chromium project](https://www.chromium.org/chromium-projects/) is probably a better party to firstly consult with.
