### ISSUE TITLE
MediaDrmStateException in FrameworkMediaDrm.getKeyRequest during OfflineLicenseHelper.renewLicense call of ExoPlayer

### ISSUE THREAD

**Issue by rdutta2020** [androidx/media#1604]
We are calling "offlineLicenseHelper.renewLicense" and passing "offlineLicenseKeySetId" same as we got during "downloadLicense" response.
Getting the below error: (HLS content)::
`android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
                                                                                                          at android.media.MediaDrm.getKeyRequest(Native Method)
                                                                                                          at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:199)
                                                                                                          at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:468)
                                                                                                          at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:433)
                                                                                                          at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:303)
                                                                                                          at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:785)
                                                                                                          at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:686)
                                                                                                          at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:565)
                                                                                                          at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:511)
                                                                                                          at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:284)
                                                                                                          at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:267)
                                                                                                          at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207)`

Please help.

**Comment by icbaker** [comment]
Please take an `adb bugreport` shortly after seeing this error and send it to android-media-github@google.com with the subject `Issue #1604`. Please also update this issue to indicate you’ve done this.

**Comment by rdutta2020** [comment]
email sent with bugreport, same error as mentioned above 

`08-09 13:00:12.134 10398 32724 32724 E MediaDrm-JNI: Illegal state exception: Failed to get key request: General DRM error (-2000)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession: DRM session error
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:   android.media.MediaDrm$MediaDrmStateException: Failed to get key request: General DRM error
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at android.media.MediaDrm.getKeyRequest(Native Method)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.FrameworkMediaDrm.getKeyRequest(FrameworkMediaDrm.java:199)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.DefaultDrmSession.postKeyRequest(DefaultDrmSession.java:468)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.DefaultDrmSession.doLicense(DefaultDrmSession.java:433)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.DefaultDrmSession.acquire(DefaultDrmSession.java:303)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSession(DefaultDrmSessionManager.java:785)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.createAndAcquireSessionWithRetry(DefaultDrmSessionManager.java:686)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:565)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.DefaultDrmSessionManager.acquireSession(DefaultDrmSessionManager.java:511)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.OfflineLicenseHelper.openBlockingKeyRequest(OfflineLicenseHelper.java:284)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.OfflineLicenseHelper.blockingKeyRequest(OfflineLicenseHelper.java:267)
08-09 13:00:12.137 10398 32724 32724 E DefaultDrmSession:       at com.google.android.exoplayer2.drm.OfflineLicenseHelper.renewLicense(OfflineLicenseHelper.java:207)`

**Comment by rrfrias** [comment]
The license policy has a flag set that disallows renewal. If you or your license provider is a widevine licensee you might want to reach out for support to make sure your licenses are correctly configured: https://widevine.com/contact
