### ISSUE TITLE
VTT subtitles not working

### ISSUE THREAD

**Issue by SuNNjek** [androidx/media#1606]
Hello,

I'm trying to add subtitles to a player by using a `MergingMediaSource`. The code for this looks like this:

```kotlin
val subtitleConfiguration = SubtitleConfiguration.Builder(Uri.parse(video.captionUrl))
    .setMimeType(MimeTypes.TEXT_VTT)
    .setSelectionFlags(C.SELECTION_FLAG_DEFAULT)
    .build()

MergingMediaSource(videoSource, captionFactory.createMediaSource(subtitleConfiguration, C.TIME_UNSET))
```

Now, when I try to play the video in the app, I only get this in the logcat output:
```
Playback error
  androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)
      at android.os.Handler.dispatchMessage(Handler.java:103)
      at android.os.Looper.loopOnce(Looper.java:232)
      at android.os.Looper.loop(Looper.java:317)
      at android.os.HandlerThread.run(HandlerThread.java:85)
  Caused by: java.lang.IllegalStateException: Legacy decoding is disabled, can't handle text/vtt samples (expected application/x-media3-cues).
      at androidx.media3.common.util.Assertions.checkState(Assertions.java:100)
      at androidx.media3.exoplayer.text.TextRenderer.assertLegacyDecodingEnabledIfRequired(TextRenderer.java:589)
      at androidx.media3.exoplayer.text.TextRenderer.onStreamChanged(TextRenderer.java:212)
      at androidx.media3.exoplayer.BaseRenderer.replaceStream(BaseRenderer.java:151)
      at androidx.media3.exoplayer.BaseRenderer.enable(BaseRenderer.java:125)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderer(ExoPlayerImplInternal.java:2770)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:2744)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:2725)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2525)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
      at android.os.Handler.dispatchMessage(Handler.java:103) 
      at android.os.Looper.loopOnce(Looper.java:232) 
      at android.os.Looper.loop(Looper.java:317) 
      at android.os.HandlerThread.run(HandlerThread.java:85) 
```

The error message "Legacy decoding is disabled" implies that it can somehow be enabled. I could however not find anything about this.
So, if I need to enable this nebulous "legacy decoding", how do I do it? Or is there another way of getting VTT subtitles to work?

**Comment by SuNNjek** [comment]
Ok, I managed to find this on my own. You can apparently set a property to the `TextRenderer` to enable it:

```kotlin
val renderersFactory = object : DefaultRenderersFactory(context) {
    override fun buildTextRenderers(
        context: Context,
        output: TextOutput,
        outputLooper: Looper,
        extensionRendererMode: Int,
        out: ArrayList<Renderer>
    ) {
        val textRenderer = TextRenderer(output, outputLooper)
        textRenderer.experimentalSetLegacyDecodingEnabled(true)
        out.add(textRenderer)
    }
}
ExoPlayer.Builder(context, renderersFactory)
    .setSeekBackIncrementMs(skipBackwardsDuration.inWholeMilliseconds)
    .setSeekForwardIncrementMs(skipForwardsDuration.inWholeMilliseconds)
    .setSeekParameters(SeekParameters.EXACT)
    .build()
    .apply { playWhenReady = true }
```

It is, in true Google fashion, deprecated though, so I assume this will not work forever.

**Comment by icbaker** [comment]
Can you use `DefaultMediaSourceFactory` and `Player.setMediaItem` instead of manually creating your `MediaSource` instance(s) yourself? This should enable the non-legacy handling of subtitles automatically, and save you needing to rely on the deprecated backwards compatibility in `TextRenderer`.

It's not shown in your code snippet, but I assume `captionFactory.createMediaSource(...)` creates a `SingleSampleMediaSource`, and it's this that is causing you issues (not `MergingMediaSource`). If you need to create your `MediaSource` instances manually, you will need to switch to using `ProgressiveMediaSource` here in order to use non-legacy subtitle handling, in the same way that `DefaultMediaSourceFactory` does.

See also https://github.com/androidx/media/issues/1569#issuecomment-2255506625

**Comment by SuNNjek** [comment]
@icbaker Thanks a lot for your answer, I'll look into that. You're correct, the `captionFactory` in my example is indeed a `SingleSampleMediaSource.Factory`
