### ISSUE TITLE
androidx.media3.exoplayer.hls.SampleQueueMappingException on DRM Content specific on HiSense HiSmart 2K TV

### ISSUE THREAD

**Issue by JosephSanjaya** [androidx/media#1614]
### Version

Media3 1.3.1

### Devices that reproduce the issue

HiSense HiSmart 2K TV

### Devices that do not reproduce the issue

On Other android TV

### Reproducible in the demo app?

No

### Reproduction steps

1. Has HiSense Smart TV
2. Play DRM Content

### Expected result

The media play successfully

### Actual result

Playback crashes with stacktraces:
```
Exception: androidx.media3.exoplayer.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with MIME type video/avc.
       at androidx.media3.exoplayer.hls.SampleQueueMappingException.<init>(SampleQueueMappingException.java:32)
       at androidx.media3.exoplayer.hls.HlsSampleStream.maybeThrowError(HlsSampleStream.java:62)
       at androidx.media3.exoplayer.BaseRenderer.maybeThrowStreamError(BaseRenderer.java:182)
       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1125)
       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:223)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
I can't find a `SampleQueueMappingException` in the provided BR. The only ExoPlayer error I can see happened when the player was already being released:

```
08-13 16:35:04.333 10029 19897 19897 E EventLogger: playerFailed [eventTime=2498.55, mediaPos=734.01, window=0, period=0, errorCode=ERROR_CODE_TIMEOUT
08-13 16:35:04.333 10029 19897 19897 E EventLogger:   androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.exoplayer.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:1070)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda9.invoke(D8$$SyntheticClass:0)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.common.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:339)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.common.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:223)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.common.util.ListenerSet.flushEvents(ListenerSet.java:245)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.common.util.ListenerSet.sendEvent(ListenerSet.java:260)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.exoplayer.ExoPlayerImpl.release(ExoPlayerImpl.java:1066)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.demo.main.PlayerActivity.releasePlayer(PlayerActivity.java:390)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.demo.main.PlayerActivity.onStop(PlayerActivity.java:182)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1476)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.Activity.performStop(Activity.java:8215)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4850)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4829)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4903)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.os.Handler.dispatchMessage(Handler.java:106)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.os.Looper.loop(Looper.java:223)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at android.app.ActivityThread.main(ActivityThread.java:7656)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at java.lang.reflect.Method.invoke(Native Method)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:   Caused by: androidx.media3.exoplayer.ExoTimeoutException: Player release timed out.
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       at androidx.media3.exoplayer.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:1069)
08-13 16:35:04.333 10029 19897 19897 E EventLogger:       ... 24 more
08-13 16:35:04.333 10029 19897 19897 E EventLogger: ]
```

Please provide a BR that contains the described exception.

**Comment by JosephSanjaya** [comment]
that's weird. okay let me resend the BR later. 

Thanks for response

**Comment by JosephSanjaya** [comment]
I'm already resend the bug report, sorry for the inconveniences.

Thanks

**Comment by JosephSanjaya** [comment]
is there any update regarding this issue?

**Comment by JonWatson** [comment]
We are having a similar issue.  Our Video provider can produce both DASH and HLS.  Dash play without issue but the HLS (also DRMed) content receives this same error.  On both 1.3.0 and 1.4.0.

**Comment by tianyif** [comment]
Hi @JosephSanjaya,

Could you please provide the stream that has this issue? Not sure it is similar to https://github.com/androidx/media/issues/1675 as you said there are devices that cannot reproduce this, so might be due to some other reasons.

**Comment by JosephSanjaya** [comment]
Hello @tianyif, thanks for response
already send the video and token thorugh email

**Comment by JosephSanjaya** [comment]
Just today I just realized i think there's some problem with the mapping function, when i check on other devices the video that played is actually .mpd which dash. but specific on HiSense somehow it detect as HLS, so it make sense the mapping will be failed, but why is this only happened on Hisense TV?

**Comment by JosephSanjaya** [comment]
We have resolved the issue internally. The root cause was identified as the TV’s inability to load video streams using HLS with PlayFair.

To address this, we have transitioned the streaming feed to utilize DASH with Widevine, ensuring compatibility.
