### ISSUE TITLE
BehindLiveWindowException

### ISSUE THREAD

**Issue by FongMi** [androidx/media#1629]
### Version

Media3 1.4.0

### Devices that reproduce the issue

Xiaomi 13

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Add play url to media.exolist.json
2. Add android:usesCleartextTraffic="true" to AndroidManifest.xml
3. Run demo app
4. Play the test url

### Expected result

Like mpv player can play well.

### Actual result

Show error
![image](https://github.com/user-attachments/assets/dd64e44c-6998-4bb6-8199-d2807a73ed07)

### Media

http://171.108.239.128:8181/tsfile/live/1010_1.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by FongMi** [comment]
@kientux Can you help this like https://github.com/google/ExoPlayer/issues/1074

**Comment by oceanjules** [comment]
If I use the URL you provided, I run into "Cleartext HTTP traffic not permitted", because of

https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/common/src/main/java/androidx/media3/common/util/Util.java#L435-L454

If I change it to https, I get:

```
2024-08-19 15:56:39.071 13122-13145 chromium                androidx.media3.demo.main            E  [0819/155639.071530:ERROR:ssl_client_socket_impl.cc(974)] handshake failed; returned -1, SSL error code 1, net_error -107
2024-08-19 15:56:39.074 13122-13122 EventLogger             androidx.media3.demo.main            E  internalError [eventTime=7.95, mediaPos=0.00, window=0, loadError
                                                                                                      androidx.media3.datasource.HttpEngineDataSource$OpenException: android.net.http.NetworkExceptionWrapper: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at androidx.media3.datasource.HttpEngineDataSource.open(HttpEngineDataSource.java:472)
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:801)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:614)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                                                                                                          at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
                                                                                                          at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64)
                                                                                                          at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:180)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:437)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                      Caused by: android.net.http.NetworkExceptionWrapper: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at android.net.http.CronetExceptionTranslationUtils.translateException(CronetExceptionTranslationUtils.java:45)
                                                                                                          at android.net.http.UrlRequestCallbackWrapper.onFailed(UrlRequestCallbackWrapper.java:78)
                                                                                                          at android.net.connectivity.org.chromium.net.impl.VersionSafeCallbacks$UrlRequestCallback.onFailed(VersionSafeCallbacks.java:65)
                                                                                                          at android.net.connectivity.org.chromium.net.impl.CronetUrlRequest$8.run(CronetUrlRequest.java:1005)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                          at java.lang.Thread.run(Thread.java:1012) 
                                                                                                      Caused by: android.net.connectivity.org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at android.net.connectivity.org.chromium.net.impl.CronetUrlRequest.onError(CronetUrlRequest.java:884)
                                                                                                    ]
2024-08-19 15:56:39.081 13122-13178 ExoPlayerImplInternal   androidx.media3.demo.main            E  Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                          at android.os.Looper.loop(Looper.java:317)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                      Caused by: androidx.media3.datasource.HttpEngineDataSource$OpenException: android.net.http.NetworkExceptionWrapper: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at androidx.media3.datasource.HttpEngineDataSource.open(HttpEngineDataSource.java:472)
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:801)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:614)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                                                                                                          at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
                                                                                                          at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64)
                                                                                                          at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:180)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:437)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                      Caused by: android.net.http.NetworkExceptionWrapper: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at android.net.http.CronetExceptionTranslationUtils.translateException(CronetExceptionTranslationUtils.java:45)
                                                                                                          at android.net.http.UrlRequestCallbackWrapper.onFailed(UrlRequestCallbackWrapper.java:78)
                                                                                                          at android.net.connectivity.org.chromium.net.impl.VersionSafeCallbacks$UrlRequestCallback.onFailed(VersionSafeCallbacks.java:65)
                                                                                                          at android.net.connectivity.org.chromium.net.impl.CronetUrlRequest$8.run(CronetUrlRequest.java:1005)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                          at java.lang.Thread.run(Thread.java:1012) 
                                                                                                      Caused by: android.net.connectivity.org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at android.net.connectivity.org.chromium.net.impl.CronetUrlRequest.onError(CronetUrlRequest.java:884)
2024-08-19 15:56:39.082 13122-13122 EventLogger             androidx.media3.demo.main            E  playerFailed [eventTime=7.95, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                          at android.os.Looper.loop(Looper.java:317)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                      Caused by: androidx.media3.datasource.HttpEngineDataSource$OpenException: android.net.http.NetworkExceptionWrapper: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at androidx.media3.datasource.HttpEngineDataSource.open(HttpEngineDataSource.java:472)
                                                                                                          at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:801)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:614)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                                                                                                          at androidx.media3.datasource.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
                                                                                                          at androidx.media3.datasource.DataSourceInputStream.open(DataSourceInputStream.java:64)
                                                                                                          at androidx.media3.exoplayer.upstream.ParsingLoadable.load(ParsingLoadable.java:180)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:437)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                      Caused by: android.net.http.NetworkExceptionWrapper: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at android.net.http.CronetExceptionTranslationUtils.translateException(CronetExceptionTranslationUtils.java:45)
                                                                                                          at android.net.http.UrlRequestCallbackWrapper.onFailed(UrlRequestCallbackWrapper.java:78)
                                                                                                          at android.net.connectivity.org.chromium.net.impl.VersionSafeCallbacks$UrlRequestCallback.onFailed(VersionSafeCallbacks.java:65)
                                                                                                          at android.net.connectivity.org.chromium.net.impl.CronetUrlRequest$8.run(CronetUrlRequest.java:1005)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                          at java.lang.Thread.run(Thread.java:1012) 
                                                                                                      Caused by: android.net.connectivity.org.chromium.net.impl.NetworkExceptionImpl: Exception in CronetUrlRequest: net::ERR_SSL_PROTOCOL_ERROR, ErrorCode=11, InternalErrorCode=-107, Retryable=false
                                                                                                          at android.net.connectivity.org.chromium.net.impl.CronetUrlRequest.onError(CronetUrlRequest.java:884)
                                                                                                    ]



Could you please provide a working URL and any additional steps for reproduction?
```

**Comment by FongMi** [comment]
You can add this line to XML
**usesCleartextTraffic**
![Screenshot_2024-08-19-23-01-33-977_com.android.chrome.jpg](https://github.com/user-attachments/assets/9b738695-bb27-4a3e-99c5-699a5eb99c0f)

**Comment by oceanjules** [comment]
Thanks! I've been able to reproduce. Have you taken a look at:

https://github.com/androidx/media/issues/519
https://github.com/androidx/media/issues/596#issuecomment-1687749330
https://github.com/androidx/media/issues/607

Maybe any of those discussions would be useful?

Also, I'm assuming that as per https://developer.android.com/media/media3/exoplayer/live-streaming#behindlivewindowexception-and, the current handling of the error in the demo app is not enough for your media:

https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/demos/main/src/main/java/androidx/media3/demo/main/PlayerActivity.java#L477-L486

I also noticed the seeking keeps going back in 5-10sec decrements 

https://github.com/user-attachments/assets/6a5a0c37-8277-497c-970e-155332bde8a6
