### ISSUE TITLE
Exoplayer 2 Crashing when used with media3 dependency.

### ISSUE THREAD

**Issue by ShivamGoyal1899** [androidx/media#1691]
### Version

Media3 1.4.1

### Devices that reproduce the issue

- Pixel 7 Pro running Android 13

### Reproducible in the demo app?

Not tested

### Reproduction steps

- Add both media3 and exoplayer2 dependency in the project.
- Implement Separate Players for both dependencies.

### Expected result

Both Videos should play separately.

### Actual result

Media3 Player works but Exoplayer 2 crashes w/ below log.

```kotlin
15:16:22.925 AndroidRuntime           E  FATAL EXCEPTION: main
                                         Process: com.example.app, PID: 20460
                                         android.view.InflateException: Binary XML file line #116 in com.example.app:layout/video_player_widget_layout: Binary XML file line #116 in com.example.app:layout/video_player_widget_layout: Error inflating class com.google.android.exoplayer2.ui.PlayerView
                                         Caused by: android.view.InflateException: Binary XML file line #116 in com.example.app:layout/video_player_widget_layout: Error inflating class com.google.android.exoplayer2.ui.PlayerView
                                         Caused by: java.lang.reflect.InvocationTargetException
                                         	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                         	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                         	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
                                         	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
                                         	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
                                         	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
                                         	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                         	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
                                         	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
                                         	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
                                         	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
                                         	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
                                         	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
                                         	at com.example.app.adapters.BaseRVAdapter.onCreateViewHolder(BaseRVAdapter.kt:34)
                                         	at com.example.app.adapters.BaseRVAdapter.onCreateViewHolder(BaseRVAdapter.kt:26)
                                         	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7719)
                                         	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6804)
                                         	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
                                         	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
                                         	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
                                         	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
                                         	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                         	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                         	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
                                         	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4307)
                                         	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
                                         	at android.view.View.layout(View.java:23693)
                                         	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                         	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
                                         	at android.view.View.layout(View.java:23693)
                                         	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                         	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                         	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                         	at android.view.View.layout(View.java:23693)
                                         	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                         	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                         	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                         	at android.view.View.layout(View.java:23693)
                                         	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                         	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                         	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                         	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                         	at android.view.View.layout(View.java:23693)
                                         	at android.view.ViewGroup.layout(ViewGroup.java:6413)
                                         	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                         	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                         	at android.view.View.layout(View.java:23693)
                                         	at android.view.ViewGroup.layout(ViewGroup.java:6413)
``` 

### Media

Not applicable.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for your report.

It's not a supported configuration to have the same library with different package names in the same project/app.

Code that is using the old package names needs to be [migrated](https://developer.android.com/media/media3/exoplayer/migration-guide) when depending to the new package name.

**Comment by ShivamGoyal1899** [comment]
@marcbaechinger aren't they both treated as separate dependencies?

**Comment by ShivamGoyal1899** [comment]
understood.

on another note, i tried migrating the old implementation to media3 using the doc you provided but it migrates to 1.1.1 while latest is 1.4.1. any plan to update migration script to migrate to 1.4.1?

**Comment by marcbaechinger** [comment]
We don't update the migration script. The migration path is to update to the latest exoplayer2 version, then migrate to 1.1.1. After this is achieved, upgrading the dependency from 1.1.1 to 1.4.1 should be simple.

**Comment by ShivamGoyal1899** [comment]
i was able to migrate everything to media3. thanks!
