### ISSUE TITLE
Media 3 v1.4.1 streaming video crashes in Amazon Fire HD 10 Plus(11th generation) Tablet 

### ISSUE THREAD

**Issue by ajayhack** [androidx/media#1718]
### Version

Media3 1.4.1

### More version details

main

### Devices that reproduce the issue

1.Amazon Fire HD 10 Plus(11th generation) Tablet

### Reproducible in the demo app?

Yes

### Reproduction steps

1.Play any type video in Media 3 v1.4.1 in Amazon Fire HD 10 Tablet

Crash Logs:-
Process: com.tvod.combo696, PID: 27093
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'androidx.media3.datasource.DataSource androidx.media3.datasource.DataSource$Factory.createDataSource()' on a null object reference
                                                                                                    	at androidx.media3.datasource.DefaultDataSource$Factory.createDataSource(DefaultDataSource.java:114)
                                                                                                    	at androidx.media3.datasource.DefaultDataSource$Factory.createDataSource(DefaultDataSource.java:63)
                                                                                                    	at androidx.media3.datasource.cache.CacheDataSource$Factory.createDataSource(CacheDataSource.java:258)
                                                                                                    	at androidx.media3.datasource.cache.CacheDataSource$Factory.createDataSource(CacheDataSource.java:66)
                                                                                                    	at androidx.media3.exoplayer.source.ProgressiveMediaSource.createPeriod(ProgressiveMediaSource.java:298)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:131)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:214)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:154)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:49)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource.lambda$prepareChildSource$0$androidx-media3-exoplayer-source-CompositeMediaSource(CompositeMediaSource.java:117)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(D8$$SyntheticClass:0)
                                                                                                    	at androidx.media3.exoplayer.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:90)
                                                                                                    	at androidx.media3.exoplayer.source.ProgressiveMediaSource.notifySourceInfoRefreshed(ProgressiveMediaSource.java:386)
                                                                                                    	at androidx.media3.exoplayer.source.ProgressiveMediaSource.prepareSourceInternal(ProgressiveMediaSource.java:288)
                                                                                                    	at androidx.media3.exoplayer.source.BaseMediaSource.prepareSource(BaseMediaSource.java:255)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:122)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.prepareChildSource(WrappingMediaSource.java:240)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:127)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:38)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:131)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.createPeriod(AdsMediaSource.java:246)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:131)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:214)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:154)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:49)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource.lambda$prepareChildSource$0$androidx-media3-exoplayer-source-CompositeMediaSource(CompositeMediaSource.java:117)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(D8$$SyntheticClass:0)
                                                                                                    	at androidx.media3.exoplayer.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:90)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.maybeUpdateSourceInfo(AdsMediaSource.java:359)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.onAdPlaybackState(AdsMediaSource.java:314)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.access$100(AdsMediaSource.java:64)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource$ComponentListener.lambda$onAdPlaybackState$0$androidx-media3-exoplayer-source-ads-AdsMediaSource$ComponentListener(AdsMediaSource.java:414)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource$ComponentListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
---------------------------- PROCESS ENDED (27093) for package com.tvod.combo696 ----------------------------
---------------------------- PROCESS STARTED (27341) for package com.tvod.combo696 ----------------------------

### Expected result

Video should play fine without any crash in Media3v1.4.1 on Amazon Fire HD Tablet

### Actual result

Media3v1.4.1 crashes when streaming video in Amazon Fire HD Tablet.

### Media

Process: com.tvod.combo696, PID: 27093
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'androidx.media3.datasource.DataSource androidx.media3.datasource.DataSource$Factory.createDataSource()' on a null object reference
                                                                                                    	at androidx.media3.datasource.DefaultDataSource$Factory.createDataSource(DefaultDataSource.java:114)
                                                                                                    	at androidx.media3.datasource.DefaultDataSource$Factory.createDataSource(DefaultDataSource.java:63)
                                                                                                    	at androidx.media3.datasource.cache.CacheDataSource$Factory.createDataSource(CacheDataSource.java:258)
                                                                                                    	at androidx.media3.datasource.cache.CacheDataSource$Factory.createDataSource(CacheDataSource.java:66)
                                                                                                    	at androidx.media3.exoplayer.source.ProgressiveMediaSource.createPeriod(ProgressiveMediaSource.java:298)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:131)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:214)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:154)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:49)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource.lambda$prepareChildSource$0$androidx-media3-exoplayer-source-CompositeMediaSource(CompositeMediaSource.java:117)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(D8$$SyntheticClass:0)
                                                                                                    	at androidx.media3.exoplayer.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:90)
                                                                                                    	at androidx.media3.exoplayer.source.ProgressiveMediaSource.notifySourceInfoRefreshed(ProgressiveMediaSource.java:386)
                                                                                                    	at androidx.media3.exoplayer.source.ProgressiveMediaSource.prepareSourceInternal(ProgressiveMediaSource.java:288)
                                                                                                    	at androidx.media3.exoplayer.source.BaseMediaSource.prepareSource(BaseMediaSource.java:255)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:122)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.prepareChildSource(WrappingMediaSource.java:240)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:127)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.createPeriod(MaskingMediaSource.java:38)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:131)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.createPeriod(AdsMediaSource.java:246)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:131)
                                                                                                    	at androidx.media3.exoplayer.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:214)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:154)
                                                                                                    	at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:49)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource.lambda$prepareChildSource$0$androidx-media3-exoplayer-source-CompositeMediaSource(CompositeMediaSource.java:117)
                                                                                                    	at androidx.media3.exoplayer.source.CompositeMediaSource$$ExternalSyntheticLambda0.onSourceInfoRefreshed(D8$$SyntheticClass:0)
                                                                                                    	at androidx.media3.exoplayer.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:90)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.maybeUpdateSourceInfo(AdsMediaSource.java:359)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.onAdPlaybackState(AdsMediaSource.java:314)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource.access$100(AdsMediaSource.java:64)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource$ComponentListener.lambda$onAdPlaybackState$0$androidx-media3-exoplayer-source-ads-AdsMediaSource$ComponentListener(AdsMediaSource.java:414)
                                                                                                    	at androidx.media3.exoplayer.source.ads.AdsMediaSource$ComponentListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
---------------------------- PROCESS ENDED (27093) for package com.tvod.combo696 ----------------------------
---------------------------- PROCESS STARTED (27341) for package com.tvod.combo696 ----------------------------

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Your stack trace indicates that `baseDataSourceFactory` is null here:
https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/datasource/src/main/java/androidx/media3/datasource/DefaultDataSource.java#L112-L114

This can only happen if you pass `null` as the second parameter into the `DefaultDataSource.Factory(Context, DataSource.Factory)` constructor, which is not permitted (since it's not annotated `@Nullable`). Does this look possible/likely from looking at your app code?

**Comment by ajayhack** [comment]
@icbaker The same code is working fine on Android Mobile / Android TV.
The code we are using to create second parameter of **DataSourceFactory.Factory** is:-
`@OptIn(markerClass = UnstableApi.class)
    public static synchronized HttpDataSource.Factory getHttpDataSourceFactory(Context context) {
        if (httpDataSourceFactory == null && context != null) {
            context = context.getApplicationContext();
            if (AppConstants.isAmazon) {
                CronetEngineWrapper cronetEngineWrapper = new CronetEngineWrapper(context);
                httpDataSourceFactory = new CronetDataSourceFactory(cronetEngineWrapper, Executors.newSingleThreadExecutor(), DEFAULT_CONNECT_TIMEOUT_MILLIS, DEFAULT_READ_TIMEOUT_MILLIS, true, Util.getUserAgent(context , AppConfig.kAppName));
            } else {
                CronetEngine cronetEngine = CronetUtil.buildCronetEngine(context);
                if (cronetEngine != null) {
                    httpDataSourceFactory = new CronetDataSource.Factory(cronetEngine, Executors.newSingleThreadExecutor());
                }
            }
        }
        return httpDataSourceFactory;
    }`
    
    So as you can see for Amazon "**CronetEngineWrapper**" is used and for Android "**CronetUtil**" is used to make CronetEngine.
    In previous Media 3 v1.3.0 it's working fine for both Amazon/Android Platforms but when we upgrade Media 3 v1.4.1 then "**CronetEngineWrapper**" this is depricated , So we used same  "**CronetUtil**" for both Amazon/Android Platform and then we faced this crash on Amazon Platform , Although it's working fine for Android Platforms.

**Comment by icbaker** [comment]
Your `CronetUtil` code results in your `getHttpDataSourceFactory` method returning `null` when Cronet is not available on the device (which I assume is the case on Amazon devices, but also may occur on other devices too). This is because `CronetUtil.buildCronetEngine` returns `null` in this case, [as documented](https://github.com/androidx/media/blob/1.4.1/libraries/datasource_cronet/src/main/java/androidx/media3/datasource/cronet/CronetUtil.java#L62):

> `Neither are fallback providers [considered], since it's more efficient to use {@link DefaultHttpDataSource} than it is to use {@link CronetDataSource} with a fallback {@link CronetEngine}.`

The difference with the `CronetEngineWrapper` code is that it **does** trigger the fallback behaviour in `CronetDataSource` when Cronet isn't available, resulting in the less efficient behaviour mentioned by the `CronetUtil` docs.

The solution is to fix your `getHttpDataSourceFactory` method to either **never** return `null` (return a `DefaultHttpDataSource.Factory` instead), or allow it to return `null` and when it does you use the single-arg variant of `DefaultDataSource.Factory` (which will use `DefaultHttpDataSource.Factory` internally).
