### ISSUE TITLE
On remote subtitle load error player errors out as well

### ISSUE THREAD

**Issue by TheBeastLT** [androidx/media#1722]
When a media item defines a remote url subtitles and when loading such a subtitle and error occurs it crashes the whole player, even tho you could argue that subtitles are not the most important part of the video and it could fail silently continuing to play the video, since potentially you could selected some other subtitle which would not fail.
Is this intentional behaviour or maybe there's some way to circumvent this to not crash the player?

**Comment by oceanjules** [comment]
Hi @TheBeastLT, thanks for reporting the issue! Could you provide the error stack trace and/or media that causes the crash?

**Comment by TheBeastLT** [comment]
```
Playback error
      androidx.media3.exoplayer.ExoPlaybackException: Source error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:211)
      at android.os.HandlerThread.run(HandlerThread.java:65)
    Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 500
      at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:397)
      at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
      at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
      at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      at java.lang.Thread.run(Thread.java:764)
```

This error code is from subtitles url, you can potentially replicate this by adding a subtitle configuration with url pointing to some non-existing file which would result in a 404. Ie:

```
SubtitleConfiguration.Builder("https://example.com/subtitle.srt".toUri())
                            .setId("my-id")
                            .setMimeType(MimeTypes.APPLICATION_SUBRIP)
                            .setLanguage("en")
                            .setLabel("English")
                            .build()
```

**Comment by oceanjules** [comment]
Thanks! I could repro and do a bit of debugging

* Given that we don't have a loadErrorHandlingPolicy, we rely on `DefaultLoadErrorHandlingPolicy`

https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/DefaultMediaSourceFactory.java#L531-L538

* We end up with loadErrorAction = RETRY

https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/ProgressiveMediaPeriod.java#L669-L679

* Forcefully setting it to DONT_RETRY and cancelling the load results in a timeout. Even though the Loader should handle it gracefully for `ACTION_TYPE_DONT_RETRY`

https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/upstream/Loader.java#L494-L510

Assigning it to @icbaker who might know more on the issue

**Comment by icbaker** [comment]
The changes linked above mean that errors from both loading and parsing subtitle (and metadata) are suppressed, allowing the rest of the playback to continue. This should work with both sideloaded subtitles (via `MediaItem.SubtitleConfiguration`) and in-stream subtitles (whether that's a track in an MP4 file, or configured through a DASH or HLS playlist).

These errors are logged when they're suppressed, and also propagated out via `onLoadError` callbacks on `AnalyticsListener` and `MediaSourceEventListener`.
