### ISSUE TITLE
DRM & ClearKey 1.4.X Unexpected runtime error on FireTV Stick 4K

### ISSUE THREAD

**Issue by KingLucius** [androidx/media#1732]
### Version

Media3 1.4.0

### More version details

From 1.4.0 and up has this issue, downgrading to 1.3.1 fixes it

### Devices that reproduce the issue

Amazon FireTV Stick 4K (Mantis)

### Reproducible in the demo app?

Not tested

### Reproduction steps

I can provide sample ClearKey link in private to test

### Expected result

Media working like in 1.3.1

### Actual result

```
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal: Playback error
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:98)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:154)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:61)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:   Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2584)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:108)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1994)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:873)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
09-13 07:39:36.096 18108 18297 E ExoPlayerImplInternal:       ... 3 more
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal: Disable failed.
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:   android.media.MediaCodec$CryptoException: Operation not supported in this configuration
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2068)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:168)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1566)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1523)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:722)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:98)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:154)
09-13 07:39:36.097 18108 18297 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:61)
```

### Media

Will send to [android-media-github@google.com](mailto:android-media-github@google.com)

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
> * You will email the zip file produced by `adb bugreport` to [android-media-github@google.com](mailto:android-media-github@google.com) after filing this issue.

We didn't receive this. Please re-send it with subject `Issue #1732`. Thanks!

**Comment by KingLucius** [comment]
> > * You will email the zip file produced by `adb bugreport` to [android-media-github@google.com](mailto:android-media-github@google.com) after filing this issue.
> 
> We didn't receive this. Please re-send it with subject `Issue #1732`. Thanks!

Done

**Comment by icbaker** [comment]
The email contains a logcat snippet, not the zip file produced by `adb bugreport`. The full bugreport often contains additional info which can help to understand issues. Please run `adb bugreport` after reproducing the issue, and email us the resulting zip file, then update this issue.

**Comment by KingLucius** [comment]
> The email contains a logcat snippet, not the zip file produced by `adb bugreport`. The full bugreport often contains additional info which can help to understand issues. Please run `adb bugreport` after reproducing the issue, and email us the resulting zip file, then update this issue.

Updated the email with `adb bugreport` zip file result

**Comment by icbaker** [comment]
Thanks - please can you add an `EventLogger` (https://developer.android.com/media/media3/exoplayer/debug-logging) and reproduce and take a new BR.

Please can you also provide a BR of a successful playback using 1.3.1, so we can understand what might be behaving differently.

**Comment by KingLucius** [comment]
> Thanks - please can you add an `EventLogger` (https://developer.android.com/media/media3/exoplayer/debug-logging) and reproduce and take a new BR.
> 
> Please can you also provide a BR of a successful playback using 1.3.1, so we can understand what might be behaving differently.

Updated, please check

**Comment by icbaker** [comment]
Thanks - I can't see any `EventLogger` output in the BR, so I'm not sure if you added it correctly (you need to add a line like `player.addAnalyticsListener(new EventLogger())`).

However I can see a difference between the two BRs without this, that I suspect is responsible for the error you're seeing.

At 1.3.1 we are instantiating an "insecure" (i.e. not HW-secure) video decoder:

```
OMXMaster: makeComponentInstance(OMX.MTK.VIDEO.DECODER.AVC) in mediacodec process
```

At 1.4.0 we are instantiating a HW-secure one (note the `.secure` suffix):

```
OMXMaster: makeComponentInstance(OMX.MTK.VIDEO.DECODER.AVC.secure) in mediacodec process
```

ClearKey doesn't support HW-secure playback. 

At a guess, I suspect the change in behaviour might have been introduced by https://github.com/androidx/media/commit/c872af4bc00608be70b74a2f61078e5d65ed8322 where we switched from using [`MediaCrypto.requiresSecureDecoderComponent(String)`](https://developer.android.com/reference/android/media/MediaCrypto#requiresSecureDecoderComponent(java.lang.String)) to [`MediaDrm.requiresSecureDecoder(String)`](https://developer.android.com/reference/android/media/MediaDrm#requiresSecureDecoder(java.lang.String)).

We made a related follow-up fix/workaround that was included in 1.4.1 where `MediaDrm.requiresSecureDecoder(String)` was returning `false` when it should have been returning `true` (and `MediaCrypto.requiresSecureDecoderComponent(String)` was returning `true`): https://github.com/androidx/media/commit/b184677b7b50652ea9a97d1504c80f171143d7d9 (and then a follow-up fix to **this** for an edge-case that will be in 1.5.0-beta01: https://github.com/androidx/media/commit/0b86f8949865ed685ff1aad89962867b5629ee8d).

In your case, my hypothesis would suggest that `MediaDrm.requiresSecureDecoder(String)` is incorrectly returning `true` while `MediaCrypto.requiresSecureDecoderComponent(String)` is returning `false`. Would you be able to test this hypothesis?

If you have a [local dependency on ExoPlayer](https://github.com/androidx/media/blob/release/README.md#locally) this is quite easy, because you can just add some logging here in `MediaCodecRenderer`:

https://github.com/androidx/media/blob/be4d31ba87d240e76f7a34458073a124d61bfeff/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/MediaCodecRenderer.java#L579-L584

Something like:

```java
if (codecDrmSession != null 
    && (codecDrmSession.getState() == DrmSession.STATE_OPENED
        || codecDrmSession.getState() == DrmSession.STATE_OPENED_WITH_KEYS)) {
  Log.w(
    "issue-1732",
    "drmSession.requiresSecureDecoder()="
        + codecDrmSession.requiresSecureDecoder(checkStateNotNull(inputFormat.sampleMimeType));
}
if (mediaCrypto != null) {
  Log.w(
    "issue-1732",
    "mediaCrypto.requiresSecureDecoderComponent()="
        + mediaCrypto.requiresSecureDecoderComponent(checkStateNotNull(mimeType));
}
```

**Comment by KingLucius** [comment]
with 1.5.0 the error changed to "ERROR_CODE_DRM_SYSTEM_ERROR (6006)"

```
Playback error
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.640028, 2528997, null, [1920, 1080, 25.0, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:641)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                      Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
                                                                                                          at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                          at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2584)
                                                                                                          at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:112)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1990)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1094)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1138)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by efkann** [comment]
> I couldn't build locally so I can't test the above and with 1.5.0 the error changed to "ERROR_CODE_DRM_SYSTEM_ERROR (6006)"
> 
> ```
> Playback error
> androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/avc, avc1.640028, 2528997, null, [1920, 1080, 25.0, ColorInfo(Unset color space, Unset color range, Unset color transfer, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
>                                                                                                           at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:641)
>                                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
>                                                                                                           at android.os.Looper.loop(Looper.java:154)
>                                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
>                                                                                                       Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration
>                                                                                                           at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
>                                                                                                           at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2584)
>                                                                                                           at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:112)
>                                                                                                           at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1990)
>                                                                                                           at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:875)
>                                                                                                           at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1094)
>                                                                                                           at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1138)
>                                                                                                           at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
>                                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98) 
>                                                                                                           at android.os.Looper.loop(Looper.java:154) 
>                                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61) 
> ```


I just noticed that I also received a similar error for a HLS + ClearKey stream. 


```
Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, avc1.64001F, -1, null, [848, 480, -1.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:641)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                          at android.os.Looper.loop(Looper.java:313)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: android.media.MediaCodec$CryptoException: Operation not supported in this configuration: 6 (Unknown error -6)
                                                                                                      ============================== Beginning of DRM Plugin Log ==============================
                                                                                                        12-13 05:49:00.712 I found instance=clearkey version=android.hardware.drm@1.4::IDrmFactory
                                                                                                        12-13 05:49:00.712 I found instance=widevine version=android.hardware.drm@1.4::IDrmFactory
                                                                                                        12-13 06:17:01.117 E Not implemented
                                                                                                      ============================== End of DRM Plugin Log ==============================                                                                                                      
```
@icbaker, I'd really appreciate if you could reopen the issue.

**Comment by KingLucius** [comment]
Downgrading solved it for me

**Comment by icbaker** [comment]
@KingLucius 

> with 1.5.0 the error changed to "ERROR_CODE_DRM_SYSTEM_ERROR (6006)"

This is likely due to this change in the [release notes](https://github.com/androidx/media/blob/release/RELEASENOTES.md):
> Fix `MediaCodec.CryptoException` sometimes being reported as an "unexpected runtime error" when `MediaCodec` is operated in asynchronous mode (default behaviour on API 31+).

> appreciate your help building the lib so I can try it directly with the needed log modifications

The instructions for depending on ExoPlayer locally from your project are here: https://github.com/androidx/media/blob/release/README.md#locally

Or just modify a local copy of our demo app if it's easier.

----

@efkann 

> Interesting enough, downgrading to 1.3.1 doesn't fix anything for me. Still same error:

Given this issue is specifically about a behaviour that changed between 1.3.1 and 1.4.0, I think you're probably experiencing something different. I see you already filed https://github.com/androidx/media/issues/1964 and as you've seen from https://github.com/androidx/media/issues/1045 ClearKey in HLS is, as far as I understand, undocumented and currently unsupported by ExoPlayer. I suggest you either keep discussion of your issue in https://github.com/androidx/media/issues/1964 or file a new issue if it's separate to that.

**Comment by KingLucius** [comment]
I will check the demo app
Thanks

**Comment by KingLucius** [comment]
Google Android TV API 25 Results (Media works without any issue):
```
drmSession.requiresSecureDecoder()=true
drmSession.requiresSecureDecoder()=true
```

Amazon Android TV API 25 Results (Media doesn't work):
```
drmSession.requiresSecureDecoder()=true
drmSession.requiresSecureDecoder()=true
```

**Comment by KingLucius** [comment]
Last working commit: d833d59124d795afc146322fe488b2c0d4b9af6a
First commit doesn't work: 2a5b9afb88965dba7b7138e7c721672360149dbd
(Really strange it's the same as d833d59124d795afc146322fe488b2c0d4b9af6a)

**Comment by icbaker** [comment]
> Last working commit on A FireTV Stick : [d833d59](https://github.com/androidx/media/commit/d833d59124d795afc146322fe488b2c0d4b9af6a)
> First commit doesn't work: [2a5b9af](https://github.com/androidx/media/commit/2a5b9afb88965dba7b7138e7c721672360149dbd)
> (Really strange it's the same as [d833d59](https://github.com/androidx/media/commit/d833d59124d795afc146322fe488b2c0d4b9af6a))

These commits are on different branches, so it's not very meaningful to compare the code state between them.

If you are bisecting I suggest you stick to commits on a single branch, either `main` or `release`.

----


> Google Android TV API 25 Emulator Results (Media works without any issue):
> 
> ```
> drmSession.requiresSecureDecoder()=true
> drmSession.requiresSecureDecoder()=true
> ```
> 
> Amazon Android TV API 25 Results (Media doesn't work):
> 
> ```
> drmSession.requiresSecureDecoder()=true
> drmSession.requiresSecureDecoder()=true
> ```


And what does `MediaCrypto.requiresSecureDecoderComponent(String)`  return in each case? See https://github.com/androidx/media/issues/1732#issuecomment-2367927781.

**Comment by KingLucius** [comment]
> And what does MediaCrypto.requiresSecureDecoderComponent(String) return in each case? See https://github.com/androidx/media/issues/1732#issuecomment-2367927781.

drmSession.requiresSecureDecoder()=true for both emulator (media works) & real Amazon stick (media doesn't work)

**Comment by icbaker** [comment]
> > And what does MediaCrypto.requiresSecureDecoderComponent(String) return in each case? See [#1732 (comment)](https://github.com/androidx/media/issues/1732#issuecomment-2367927781).
> 
> drmSession.requiresSecureDecoder()=true for both emulator (media works) & real Amazon stick (media doesn't work)

OK - but that's only half of what I asked, in either my original comment and my follow-up. The other half is: **`MediaCrypto.requiresSecureDecoderComponent`** (**not** `drmSession.requiresSecureDecoder`)

**Comment by KingLucius** [comment]
Ah sorry missed those part

for `MediaCrypto.requiresSecureDecoderComponent` there was no logging at all

**Comment by KingLucius** [comment]
mediaCrypto is always null, please find the below full logcat from the device
[Amazon-AFTMM-Android-7.1.2_2024-12-16_195057.zip](https://github.com/user-attachments/files/18154784/Amazon-AFTMM-Android-7.1.2_2024-12-16_195057.zip)

**Comment by icbaker** [comment]
> mediaCrypto is always null even on the emulator though the media is working with no issue, please find the below full logcat from the device

Thanks for clarifying - it looks like I asked you to add the `MediaCrypto` part of the logging in the wrong place. Can you try putting it back closer to where it was before https://github.com/androidx/media/commit/c872af4bc00608be70b74a2f61078e5d65ed8322 - concretely here, at the bottom of (but **inside**) this `else if`:

https://github.com/androidx/media/blob/df887a942222914836081f868067960eb0149547/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/MediaCodecRenderer.java#L1088-L1096

So it looks like:

```
  } else if (cryptoConfig instanceof FrameworkCryptoConfig) {
    FrameworkCryptoConfig frameworkCryptoConfig = (FrameworkCryptoConfig) cryptoConfig;
    try {
      mediaCrypto = new MediaCrypto(frameworkCryptoConfig.uuid, frameworkCryptoConfig.sessionId);
    } catch (MediaCryptoException e) {
      throw createRendererException(
          e, inputFormat, PlaybackException.ERROR_CODE_DRM_SYSTEM_ERROR);
    }
    Log.w(
        "issue-1732",
        "mime="
            + inputFormat.sampleMimeType
            + ", mediaCrypto.requiresSecureDecoderComponent()="
            + mediaCrypto.requiresSecureDecoderComponent(
                checkStateNotNull(inputFormat.sampleMimeType)));
  }
  return true;
}
```

---

When testing I also realised the duplicate logging is due to one for audio and one for video, so it might be clearer to log the MIME type in each case too (as I've added to the code snippet above).

**Comment by KingLucius** [comment]
API 25 on Emulator
```
drmSession.requiresSecureDecoder()=true
mime=video/avc, mediaCrypto.requiresSecureDecoderComponent()=false
drmSession.requiresSecureDecoder()=true
mime=video/avc, mediaCrypto.requiresSecureDecoderComponent()=false
drmSession.requiresSecureDecoder()=true
mime=audio/mp4a-latm, mediaCrypto.requiresSecureDecoderComponent()=false
```

API 25 on Fire Stick
```
drmSession.requiresSecureDecoder()=true
mime=video/avc, mediaCrypto.requiresSecureDecoderComponent()=false
drmSession.requiresSecureDecoder()=true
mime=video/avc, mediaCrypto.requiresSecureDecoderComponent()=false
```

**Comment by icbaker** [comment]
Thanks, those logs seem to confirm my hypothesis from above in https://github.com/androidx/media/issues/1732#issuecomment-2367927781:

> In your case, my hypothesis would suggest that `MediaDrm.requiresSecureDecoder(String)` is incorrectly returning `true` while `MediaCrypto.requiresSecureDecoderComponent(String)` is returning `false`.

**Comment by KingLucius** [comment]
Have you noticed that the log repeated 3 times for the emulator (2 video / 1 audio), while on Fire stick no audio mime logging

**Comment by icbaker** [comment]
> Have you noticed that the log repeated 3 times for the emulator (2 video / 1 audio), while on Fire stick no audio mime logging

I'm not sure if this is relevant? Given your exception in https://github.com/androidx/media/issues/1732#issuecomment-2539719220 is from the **video** decoder.


> Please notice that media is working on emulator while not working on real fire stick

This may be because the emulator isn't able to provide a secure decoder, so we never end up incorrectly playing content on a secure decoder.

**Comment by KingLucius** [comment]
> I'm not sure if this is relevant? Given your exception in https://github.com/androidx/media/issues/1732#issuecomment-2539719220 is from the video decoder.

I think you're right, I have tried the same build on Android 14 smart phone and the result is media is working and the log as the below:

```
drmSession.requiresSecureDecoder()=false
mime=video/avc, mediaCrypto.requiresSecureDecoderComponent()=false
drmSession.requiresSecureDecoder()=false
mime=audio/mp4a-latm, mediaCrypto.requiresSecureDecoderComponent()=false
```

**Comment by KingLucius** [comment]
Any ETA when this issue can be resolved ?

**Comment by KingLucius** [comment]
Any update?

**Comment by icbaker** [comment]
Looking into this again - my hypothesis from https://github.com/androidx/media/issues/1732#issuecomment-2548521587 can't be correct because in the FireTV BR provided by @KingLucius the device reports its API level as 25 (`[ro.build.version.sdk]: [25]`) and the Xiaomi TV looks like it's API 23 (based on the screenshot provided in https://github.com/androidx/media/issues/2088). Both of these are lower than 31, which is when the framework `MediaDrm.requiresSecureDecoder` method was added. So this bug can't be about a discrepancy between the return values of the framework `MediaCrypto` and `MediaDrm` methods.

New, related, hypothesis: We're entering this `catch` block:

https://github.com/androidx/media/blob/76088cd6af7f263aba238b7a48d64bd4f060cb8b/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/drm/FrameworkMediaDrm.java#L299-L305

@KingLucius Would you be able to add a bit of logging to confirm that?

**Comment by KingLucius** [comment]
![Image](https://github.com/user-attachments/assets/f42d9cfe-d167-4264-a267-2073008b23dc)

![Image](https://github.com/user-attachments/assets/6f457296-12bb-406d-a304-ea041644fe3f)

`
FrameworkMediaDrm.requiresSecureDecoder() Exception
Exception Details =>android.media.MediaCryptoException: Failed to instantiate crypto object.
drmSession.requiresSecureDecoder()=true
FrameworkMediaDrm.requiresSecureDecoder() Exception
Exception Details =>android.media.MediaCryptoException: Failed to instantiate crypto object.
`

**Comment by FongMi** [comment]
Finally, I make result = fasle when catch expection, it's works.

**Comment by icbaker** [comment]
While looking to make the change to set `result = false` for ClearKey in that `catch` block I spotted the probable cause for the exception in the first place - and fixed that too. The fix is in the commit linked above.
