### ISSUE TITLE
 android.media.MediaCodec$CodecException: Error 0xfffffc0e

### ISSUE THREAD

**Issue by yzm123-yzm** [androidx/media#1739]
### Version

Media3 main branch

### More version details

I encountered this exception while playing HDR video, which caused me to be unable to play it

Log is :
`getErrorMessage:
                                                                                                    androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/hevc, hvc1.2.4.H153.90, -1, null, [3840, 2160, 59.940308, ColorInfo(BT2020, Limited range, ST2084 PQ, false, 10bit Luma, 10bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.hevc.decoder.awesome2, Format(3, null, null, video/hevc, hvc1.2.4.H153.90, -1, null, [3840, 2160, 59.940308, ColorInfo(BT2020, Limited range, ST2084 PQ, false, 10bit Luma, 10bit Chroma)], [-1, -1])
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1144)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602)
                                                                                                    	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
                                                                                                    	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                                                                    	at android.media.MediaCodec.native_configure(Native Method)
                                                                                                    	at android.media.MediaCodec.configure(MediaCodec.java:2215)
                                                                                                    	at android.media.MediaCodec.configure(MediaCodec.java:2131)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:173)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:54)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:119)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1225)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588) 
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602) 
                                                                                                    	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182) 
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042) 
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860) 
                                                                                                    	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018) 
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136) 
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) `

### Devices that reproduce the issue

Android13

### Reproducible in the demo app?

Yes

### Reproduction steps

Unable to instantiate decoder 

### Expected result

play fail  /Unable to instantiate decoder 

### Actual result

Unable to instantiate decoder 

### Media

Unable to instantiate decoder 

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @yzm123-yzm, the provided log 
```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/hevc, hvc1.2.4.H153.90, -1, null, [3840, 2160, 59.940308, ColorInfo(BT2020, Limited range, ST2084 PQ, false, 10bit Luma, 10bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
```
suggests that your doesn't support the content, but we should look at why this is not detected at the track selection stage. Could you please send the media URL to android-media-github@google.com so that we can take a closer look? And could you please also specify the device that can reproduce this issue?

**Comment by tianyif** [comment]
Hi @yzm123-yzm,

Could you please send your media to android-media-github@google.com so that we can take a closer look? And could you please also specify the device that can reproduce this issue?

**Comment by yzm123-yzm** [comment]
Hi@tianyif the device is Android Tv

**Comment by yzm123-yzm** [comment]
@tianyif the device is Android Tv

**Comment by yzm123-yzm** [comment]
I have sent the video and am looking forward to your feedback.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "androidx/media"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 凌晨1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [androidx/media]  android.media.MediaCodec$CodecException: Error 0xfffffc0e (Issue #1739)





 
Hi @yzm123-yzm,
 
Could you please send your media to ***@***.*** so that we can take a closer look? And could you please also specify the device that can reproduce this issue?

**Comment by susanti16** [comment]
hi.. is there any update for this issue?
I got the same issue using media3 v1.8.0

here's my log:
error.trace: androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, video/mp4, video/avc, avc1.640032, 6552411, und, [1920, 1920, 30.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
	at androidx.media3.exoplayer.BaseRenderer.createRendererException(:545)
	at androidx.media3.exoplayer.BaseRenderer.createRendererException(:514)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(:599)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(:1671)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(:1530)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(:1120)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(:883)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(:1314)
	at androidx.media3.exoplayer.RendererHolder.render(:391)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(:1367)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(:697)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc.secure, Format(1, null, video/mp4, video/avc, avc1.640032, 6552411, und, [1920, 1920, 30.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(:1226)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(:597)
	... 12 more
Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2176)
	at android.media.MediaCodec.configure(MediaCodec.java:2092)
	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(:195)
	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(:54)
	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(:135)
	at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(:164)
	at axis.android.sdk.client.exo.RetryCapableCodecAdapterFactory.createAdapter(:22)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(:1307)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(:1219)
	... 13 more

codecInfo: OMX.qcom.video.decoder.avc.secure

diagnosticInfo: android.media.MediaCodec.error_neg_1010

mimeType: video/avc

secureDecoderRequired: true
