### ISSUE TITLE
Video codec error when there is 2 or more player instances

### ISSUE THREAD

**Issue by dianaludovice** [androidx/media#1825]
### Version

Media3 main branch

### More version details

exoplayer demo app from main , cloned from https://github.com/androidx/media.git

### Devices that reproduce the issue

Our OEM device running on Android 13 (LineageOS20)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the demo-shortform app 
2. Set players to 2 or more 
3. Drag mouse to switch to different players 

### Expected result

The media should play successfully 

### Actual result

Playback stops and the crashes with the following logs 

```
10-23 09:23:15.925  5283  6688 D MediaCodec: flushMediametrics
10-23 09:23:15.925  5283  6682 I gralloc : ddebug, free share_fd=325, user_hnd=0x1f, ion client=90
10-23 09:23:15.925  5283  5283 D player-1: timeline [eventTime=254.08, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
10-23 09:23:15.925  5283  6688 D MediaCodec: flushMediametrics
10-23 09:23:15.926  5283  5283 D player-1:   period [17.24]
10-23 09:23:15.926  5283  6682 I gralloc : ddebug, free share_fd=327, user_hnd=0x20, ion client=90
10-23 09:23:15.927  5283  6682 I gralloc : ddebug, free share_fd=329, user_hnd=0x21, ion client=90
10-23 09:23:15.927  5283  5283 D player-1:   window [17.24, seekable=true, dynamic=false]
10-23 09:23:15.928  5283  5283 D player-1: ]
10-23 09:23:15.930  5283  5283 E player-1: playerFailed [eventTime=254.09, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_RESOURCES_RECLAIMED
10-23 09:23:15.930  5283  5283 E player-1:   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/hevc, hvc1.1.6.L153, -1, null, [1920, 1080, 29.98927, ColorInfo(BT709, Full range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
10-23 09:23:15.930  5283  5283 E player-1:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
10-23 09:23:15.930  5283  5283 E player-1:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 09:23:15.930  5283  5283 E player-1:       at android.os.Looper.loopOnce(Looper.java:201)
10-23 09:23:15.930  5283  5283 E player-1:       at android.os.Looper.loop(Looper.java:288)
10-23 09:23:15.930  5283  5283 E player-1:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-23 09:23:15.930  5283  5283 E player-1:   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.amlogic.hevc.decoder.awesome
10-23 09:23:15.930  5283  5283 E player-1:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
10-23 09:23:15.930  5283  5283 E player-1:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
10-23 09:23:15.930  5283  5283 E player-1:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
10-23 09:23:15.930  5283  5283 E player-1:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
10-23 09:23:15.930  5283  5283 E player-1:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
10-23 09:23:15.930  5283  5283 E player-1:       ... 4 more
10-23 09:23:15.930  5283  5283 E player-1:   Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
10-23 09:23:15.930  5283  5283 E player-1: ]
10-23 09:23:15.931  5283  5283 D player-1: state [eventTime=254.09, mediaPos=0.00, window=0, period=0, IDLE]
10-23 09:23:15.932  3761  5150 D MediaMetricsManagerService: failed to get player_metrics_app_blocklist from DeviceConfig
10-23 09:23:15.932  3761  5150 V MediaMetricsManagerService: Logging level blocked: Failed to get PLAYER_METRICS_APP_BLOCKLIST.
10-23 09:23:15.932  3761  5150 D MediaMetricsManagerService: failed to get player_metrics_app_blocklist from DeviceConfig
10-23 09:23:15.932  3761  5150 V MediaMetricsManagerService: Logging level blocked: Failed to get PLAYER_METRICS_APP_BLOCKLIST.
10-23 09:23:15.933  5283  5283 D player-1: audioTrackReleased [eventTime=254.09, mediaPos=0.00, window=0, period=0, 2,12,48000,false,false,48000]
10-23 09:23:16.067  5283  6541 E MediaCodecVideoRenderer: Video codec error
10-23 09:23:16.067  5283  6541 E MediaCodecVideoRenderer:   android.media.MediaCodec$CodecException: Error 0xffffffe0
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal: Playback error
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/hevc, hvc1.1.6.L153, -1, null, [1920, 1080, 29.989359, ColorInfo(BT709, Full range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.amlogic.hevc.decoder.awesome
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:       ... 4 more
10-23 09:23:16.070  5283  6541 E ExoPlayerImplInternal:   Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal: Disable failed.
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:   java.lang.IllegalStateException
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2387)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:247)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1566)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1523)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:686)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
10-23 09:23:16.073  5283  6541 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
10-23 09:23:16.073  5283  5283 D player-3: videoDisabled [eventTime=242.27, mediaPos=1.51, window=0, period=0]
10-23 09:23:16.073  5283  5283 D player-3: videoSize [eventTime=242.27, mediaPos=1.51, window=0, period=0, 0, 0]
10-23 09:23:16.076  5283  6626 D CCodecBuffers: [c2.android.aac.decoder#555:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
10-23 09:23:16.076  5283  6626 D CCodecBuffers: [c2.android.aac.decoder#555:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
```

### Media

Device is reproducible with the default media from the demo-shortform app 

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for your report!

I don't think this is a bug in ExoPlayer. 

You may have consulted the error code [`ERROR_CODE_DECODING_RESOURCES_RECLAIMED`](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/PlaybackException.java#L277) that shows up in your stack trace already. So sorry if I'm going to repeat the obvious.

The error code says `Caused by higher priority task reclaiming resources needed for decoding.` I'd translate that to that this device is only having a single decoder for HEVC so you can't create more that one player instance for that codec on that devices. As the error message says, multiple players would compete to claim decoder resources and one of them will loose as expressed by the playback error.

I don't think we can't do more from the player side than telling you that you can't do on lower end devices what you can do with a high-end device that has multiple codecs.

Do I understand that correctly? Or are you saying that you know that your OEM device has multiple codecs available and it should support multiple players?

**Comment by dianaludovice** [comment]
Hi Marc, thanks for the feedback. 
The device supports multiple video decoders.
Support multi-video decoder up to 4Kx2K@60fps+1x1080P@60fps
Supports multiple “secured” video decoding sessions and simultaneous decoding and encoding

I have an ongoing test with the same device with Android 9 and OS running for an hour with 4 player instances and it doesn't exhibit the same error so far.

**Comment by marcbaechinger** [comment]
What do people from `LineageOS20` say about it? Or are you `LineageOS20`? :)

**Comment by leenickcode** [comment]
@marcbaechinger   have encountered a similar problem where it is not possible to play more than two ExoPlayer instances on certain devices. Moreover, when I check using MediaCodecInfo, it shows that the maximum number of supported instances is only one.

[log.txt](https://github.com/user-attachments/files/18055504/log.txt)

`12-09 10:21:41.979  3899  4003 I DeviceStateService: app: cn.ac.caict.iguard pid: 32757 stop mediacodec.
12-09 10:21:41.980 32757  6503 I MediaCodec: MediaCodec releaseAsync
12-09 10:21:41.980 32757  6544 I ACodec  : ACodec initiateShutdown
12-09 10:21:41.982  3899  4003 I DeviceStateService: event is too short, not process app: cn.ac.caict.iguard mediacodec action.
12-09 10:21:41.982 32757  6544 I MediaCodec: kWhatRelease or kWhatStop processing is complete.
12-09 10:21:41.983  1662 14584 I OMX-VDEC-1080P: omx_vdec::component_deinit() complete
12-09 10:21:41.984  1662 14584 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=66
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:   java.lang.IllegalStateException
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at android.media.MediaCodec.native_stop(Native Method)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at android.media.MediaCodec.stop(MediaCodec.java:2300)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.release(AsynchronousMediaCodecAdapter.java:268)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:124)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1225)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at android.os.Handler.dispatchMessage(Handler.java:113)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at android.os.Looper.loopOnce(Looper.java:205)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at android.os.Looper.loop(Looper.java:293)
12-09 10:21:41.988 32757  6503 W MediaCodecRenderer:       at android.os.HandlerThread.run(HandlerThread.java:110)
12-09 10:21:41.990 32757  6544 D MediaCodec: flushMediametrics
12-09 10:21:41.990 32757  6544 I MediaCodec: mediacodec kWhatReleaseCompleted end
12-09 10:21:41.990 32757  6544 D MediaCodec: flushMediametrics
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer: Video codec error
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:   androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.4D401F, -1, null, [992, 1220, 59.99601, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1144)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:113)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at android.os.Looper.loopOnce(Looper.java:205)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:293)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:110)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:   Caused by: java.lang.IllegalStateException
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at android.media.MediaCodec.native_stop(Native Method)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at android.media.MediaCodec.stop(MediaCodec.java:2300)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.release(AsynchronousMediaCodecAdapter.java:268)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:124)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1225)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
12-09 10:21:41.993 32757  6503 E MediaCodecVideoRenderer:       ... 12 more
12-09 10:21:41.994 32757  6503 D MediaCodecInfo: NoSupport [sizeAndRate.cover, 992x1220@59.996009826660156] [OMX.qcom.video.decoder.avc, video/avc] [HWBNE-Q, BON-AL00, HUAWEI, 31]
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal: Playback error
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D401F, -1, null, [992, 1220, 59.99601, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:113)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:205)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:293)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:110)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.4D401F, -1, null, [992, 1220, 59.99601, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1144)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:588)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1602)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1182)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:1042)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:860)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       ... 4 more
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_stop(Native Method)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at android.media.MediaCodec.stop(MediaCodec.java:2300)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.release(AsynchronousMediaCodecAdapter.java:268)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:124)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1225)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1137)
12-09 10:21:42.001 32757  6503 E ExoPlayerImplInternal:       ... 12 more
12-09 10:21:42.005 32757  6303 D OpenGLRenderer: gpu complete is not signaled
12-09 10:21:42.016  2441  2751 D MediaMetricsManagerService: failed to get player_metrics_app_blocklist from DeviceConfig
12-09 10:21:42.017  2441  2751 D MediaMetricsManagerService: failed to get player_metrics_app_blocklist from DeviceConfig
12-09 10:21:42.038 32757  6303 D OpenGLRenderer: gpu complete is not signaled
12-09 10:21:42.090  4390 25086 D HwCommBoosterService: reportBoosterPara enter
12-09 10:21:42.091  4390 25086 D HwCommBoosterManager: reportBoosterPara enter
12-09 10:21:42.091  4390 25086 D HwCommBoosterManager: pluginId: 2
12-09 10:21:42.091  1692 17502 I sensors-hal: handle_sns_std_sensor_event:577, ambient_light_event: ts=1498595221011404 lux = 96 ir = 45 ch0=2972 raw_clear=45 atime=99 again=128 noise = [904.530640, 7.747164, 0.000000, 0.000000]
12-09 10:21:42.092  4390  4564 D HwCommBoosterManager: handleBoosterMessageSendModuleDataToPlugin enter
12-09 10:21:42.098  2441  2441 I DE J DES: [effect] dynamicFpsState=1,lux=96
12-09 10:21:42.101  3899 10418 I ApsAGPAdapter: APS: APK: setScreenFactorModeToAgp mode=1`

**Comment by marcbaechinger** [comment]
Thanks for the logs

> Moreover, when I check using MediaCodecInfo, it shows that the maximum number of supported instances is only one.

I don't think we can help with that I'm afraid. If there is only one codec instance, you can only use one codec at the same time.
