### ISSUE TITLE
Video Codec Error on Google TV while playing certain Ads

### ISSUE THREAD

**Issue by nishantkp** [androidx/media#1827]
On GoogleTV, I sometimes get the following codec error when an Ad is playing. Can you explain this error a little bit? Is is like certain Ad format is not supported? 

```
09-25 18:50:22.206  4005  4589 I DMCodecAdapterFactory: Creating an asynchronous MediaCodec adapter for track type video
09-25 18:50:22.229  4005  4610 I OMXClient: IOmx service obtained
09-25 18:50:22.238  4005  4609 I MediaCodec: MediaCodec will operate in async mode
09-25 18:50:22.240  4005  4609 D MediaCodec: flushMediametrics
09-25 18:50:22.240  4005  4609 D SurfaceUtils: connecting to surface 0xe9b21108, reason connectToSurface
09-25 18:50:22.240  4005  4609 I MediaCodec: [OMX.amlogic.avc.decoder.awesome2] setting surface generation to 4101127
09-25 18:50:22.240  4005  4609 D SurfaceUtils: disconnecting from surface 0xe9b21108, reason connectToSurface(reconnect)
09-25 18:50:22.240  4005  4609 D SurfaceUtils: connecting to surface 0xe9b21108, reason connectToSurface(reconnect)
09-25 18:50:22.244  4005  4610 E ACodec  : [OMX.amlogic.avc.decoder.awesome2] configureCodec returning error -1010
09-25 18:50:22.244  4005  4610 E ACodec  : signalError(omxError 0x80001001, internalError -1010)
09-25 18:50:22.244  4005  4609 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3/CONFIGURING
09-25 18:50:22.244  4005  4609 D MediaCodec: flushMediametrics
09-25 18:50:22.244  4005  4609 D SurfaceUtils: disconnecting from surface 0xe9b21108, reason disconnectFromSurface
09-25 18:50:22.244  4005  4589 E MediaCodec: configure failed with err 0xfffffc0e, resetting...
09-25 18:50:22.267  4005  4610 I OMXClient: IOmx service obtained
09-25 18:50:22.283  4005  4609 I MediaCodec: MediaCodec will operate in async mode
09-25 18:50:22.286  4005  4589 W MediaCodecRenderer: Preferred decoder instantiation failed. Sleeping for 50ms then retrying.
09-25 18:50:22.291  4005  4609 D MediaCodec: flushMediametrics
09-25 18:50:22.293  4005  4609 D MediaCodec: flushMediametrics
09-25 18:50:22.293  4005  4609 I BpBinder: onLastStrongRef automatically unlinking death recipients: android.media.IResourceManagerService
09-25 18:50:22.337  4005  4589 I DMCodecAdapterFactory: Creating an asynchronous MediaCodec adapter for track type video
09-25 18:50:22.382  4005  4616 I MediaCodec: MediaCodec will operate in async mode
09-25 18:50:22.384  4005  4616 D MediaCodec: flushMediametrics
09-25 18:50:22.384  4005  4616 D SurfaceUtils: connecting to surface 0xe9b25c98, reason connectToSurface
09-25 18:50:22.384  4005  4616 I MediaCodec: [OMX.amlogic.avc.decoder.awesome2] setting surface generation to 4101128
09-25 18:50:22.384  4005  4616 D SurfaceUtils: disconnecting from surface 0xe9b25c98, reason connectToSurface(reconnect)
09-25 18:50:22.384  4005  4616 D SurfaceUtils: connecting to surface 0xe9b25c98, reason connectToSurface(reconnect)
09-25 18:50:22.389  4005  4617 E ACodec  : [OMX.amlogic.avc.decoder.awesome2] configureCodec returning error -1010
09-25 18:50:22.389  4005  4617 E ACodec  : signalError(omxError 0x80001001, internalError -1010)
09-25 18:50:22.389  4005  4616 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3/CONFIGURING
09-25 18:50:22.389  4005  4616 D MediaCodec: flushMediametrics
09-25 18:50:22.390  4005  4616 D SurfaceUtils: disconnecting from surface 0xe9b25c98, reason disconnectFromSurface
09-25 18:50:22.390  4005  4589 E MediaCodec: configure failed with err 0xfffffc0e, resetting...
09-25 18:50:22.400  4005  4617 I OMXClient: IOmx service obtained
09-25 18:50:22.416  4005  4616 I MediaCodec: MediaCodec will operate in async mode
09-25 18:50:22.425  4005  4616 D MediaCodec: flushMediametrics
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer: Failed to initialize decoder: OMX.amlogic.avc.decoder.awesome2
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:   android.media.MediaCodec$CodecException: Error 0xfffffc0e
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at android.media.MediaCodec.native_configure(Native Method)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2176)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2092)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:174)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:54)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:119)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1195)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1103)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:551)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1560)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1150)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:994)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at android.os.Looper.loopOnce(Looper.java:201)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at android.os.Looper.loop(Looper.java:288)
09-25 18:50:22.426  4005  4589 W MediaCodecRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
09-25 18:50:22.426  4005  4616 D MediaCodec: flushMediametrics
09-25 18:50:22.426  4005  4616 I BpBinder: onLastStrongRef automatically unlinking death recipients: android.media.IResourceManagerService
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer: Video codec error
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:   androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome2, Format(1, null, null, video/avc, avc1.4D4032, -1, null, [2048, 1152, 23.975225, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1114)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:551)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1560)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1150)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:994)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at android.os.Looper.loopOnce(Looper.java:201)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:288)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at android.media.MediaCodec.native_configure(Native Method)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2176)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2092)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:174)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:54)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:119)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1195)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1103)
09-25 18:50:22.437  4005  4589 E MediaCodecVideoRenderer:       ... 12 more
09-25 18:50:22.439  4005  4589 D MediaCodecInfo: NoSupport [codec.profileLevel, avc1.4D4032, video/avc] [OMX.amlogic.avc.decoder.awesome2, video/avc] [boreal, Chromecast HD, Google, 31]
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal: Playback error
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4032, -1, null, [2048, 1152, 23.975225, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome2, Format(1, null, null, video/avc, avc1.4D4032, -1, null, [2048, 1152, 23.975225, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1114)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:551)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1560)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1150)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:994)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:814)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       ... 4 more
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_configure(Native Method)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at android.media.MediaCodec.configure(MediaCodec.java:2176)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at android.media.MediaCodec.configure(MediaCodec.java:2092)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:174)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:54)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:119)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:137)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1195)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1103)
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:       ... 12 more
```

**Comment by marcbaechinger** [comment]
yeah, looks like in this case:

```
09-25 18:50:22.452  4005  4589 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4032, -1, null, [2048, 1152, 23.975225, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
```

The video track exeeds the capabilities of the device and it's reported like this. If there is no alternative track, then ExoPlayer still tries to play it. The stack trace above seems to be the result of it.

Is this an HD version of Google TV? The video track is of 2048, 1152, so more than 1080 that the HD version of the dongle supports according to [1]: https://support.google.com/chromecast/answer/12578818?hl=en

**Comment by nishantkp** [comment]
@marcbaechinger Yes, it is HD version of it. We need to control the Ad resolution in this case.

**Comment by marcbaechinger** [comment]
Hmmm, not sure if the ad is an adaptive source. If properly configured, ExoPlayer wouldn't select an unsupported track if there was one that is a supported alternative in the manifest.

I would see that the creatives that are delivered by the SDK do not exceed the capabilities. It's surprising this isn't the case.

**Comment by nishantkp** [comment]
yeah makes sense.
I will adjust the rule in the creative profile parameter (`pp`) in GAM for the max height and width to be `1920 x 1080`. That way, no high-resolution creative will get by. I will also add the DefaultTrackSelector from the code.

**Comment by Senne021** [comment]
I've got the same error player an HLS video on a chromecast:
`Decoder init failed: OMX.amlogic.avc.decoder.awesome2, Format(0, null, null, video/avc, avc1.640028, 9337088, null, [1920, 1080, 25.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1])`

**Comment by nishantkp** [comment]
@Senne021 can you share the entire log?

My issue was that the player was playing a high-resolution Ad that the platform could not handle. HD GoogleTV can only play ads with a max resolution of 1080p, but the ad was 1152p.

I was able to fix it by correcting the creative. The VAST response showed that an Ad was 1080p but the actual creative was 1152p upon downloading the mp4.
