### ISSUE TITLE
demo-shortform: When opening ViewPagerActivity multiple times, OOM occurs

### ISSUE THREAD

**Issue by bang919** [androidx/media#1839]
### Version

Media3 main branch

### More version details

Media3 1.4.1

### Devices that reproduce the issue

Google Pixel 4a running Android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

1) Click "OPEN VIEW PAGER ACTIVITY" on [demo-shortform](https://github.com/androidx/media/tree/release/demos/shortform) app
2) Exit ViewPagerActivity
3) Repeat the above steps

### Expected result

No OOM and No crash

### Actual result

Memory usage is increasing and then:

`FATAL EXCEPTION: main
Process: androidx.media3.demo.shortform, PID: 27397
java.lang.OutOfMemoryError: Failed to allocate a 120 byte allocation with 98000 free bytes and 95KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
at android.content.res.AssetManager.nativeGetSizeConfigurations(Native Method)
at android.content.res.AssetManager.getSizeConfigurations(AssetManager.java:1451)
at android.content.res.ResourcesImpl.getSizeConfigurations(ResourcesImpl.java:203)
at android.content.res.Resources.getSizeConfigurations(Resources.java:2207)
at android.app.ActivityThread.reportSizeConfigurations(ActivityThread.java:3837)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3817)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

### Media

No

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @bang919, 

Thanks for reporting! I used the same device model, OS and library version (1.4.1), and repeated the provided steps for several times, but still couldn't reproduce. Did you change any configurations in `DefaultLoadControl` before seeing the issue?

**Comment by tianyif** [comment]
Thanks @bang919 for the useful information! 

I saw that the corresponding `ViewHolder`s are still alive even when the `ViewPagerActivity` is stopped and GC is executed. I will provide a fix to this.
