### ISSUE TITLE
Decoder Issues Vorbis & VP9

### ISSUE THREAD

**Issue by MrBoe** [androidx/media#1847]
### Version

Media3 1.4.1

### Devices that reproduce the issue

Pixel 4 Running Android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play attached media in the demo app

### Expected result

The media plays succesfully

### Actual result

Playback crashes with following stacktraces...
1112_Audio_74_mp4-vorbis.mp4:
		playerFailed [eventTime=0.09, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
		  androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=4, format=Format(1, null, null, audio/vorbis, null, 112000, und, [-1, -1, -1.0, null], [2, 44100]), format_supported=YES
			  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
			  at android.os.Handler.dispatchMessage(Handler.java:102)
			  at android.os.Looper.loopOnce(Looper.java:201)
			  at android.os.Looper.loop(Looper.java:288)
			  at android.os.HandlerThread.run(HandlerThread.java:67)
		  Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.vorbis.decoder
			  at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:976)
			  at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:848)
			  at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
			  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
			  at android.os.Handler.dispatchMessage(Handler.java:102) 
			  at android.os.Looper.loopOnce(Looper.java:201) 
			  at android.os.Looper.loop(Looper.java:288) 
			  at android.os.HandlerThread.run(HandlerThread.java:67) 
		  Caused by: java.lang.IllegalStateException
			  at android.media.MediaCodec.native_queueInputBuffer(Native Method)
			  at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2671)
			  at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doQueueInputBuffer(AsynchronousMediaCodecBufferEnqueuer.java:220)
			  at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doHandleMessage(AsynchronousMediaCodecBufferEnqueuer.java:189)
			  at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.access$000(AsynchronousMediaCodecBufferEnqueuer.java:45)
			  at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer$1.handleMessage(AsynchronousMediaCodecBufferEnqueuer.java:91)
			  at android.os.Handler.dispatchMessage(Handler.java:106)
			  at android.os.Looper.loopOnce(Looper.java:201) 
			  at android.os.Looper.loop(Looper.java:288) 
			  at android.os.HandlerThread.run(HandlerThread.java:67) 
		]

1121_Audio codec_OPUS_48kHz.WEBM:
		Playback error
		  androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/x-vnd.on2.vp9, null, -1, und, [576, 432, -1.0, null], [-1, -1]), format_supported=YES
			  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
			  at android.os.Handler.dispatchMessage(Handler.java:102)
			  at android.os.Looper.loopOnce(Looper.java:201)
			  at android.os.Looper.loop(Looper.java:288)
			  at android.os.HandlerThread.run(HandlerThread.java:67)
		  Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.exynos.vp9.decoder
			  at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1915)
			  at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:848)
			  at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
			  at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
			  at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
			  at android.os.Handler.dispatchMessage(Handler.java:102) 
			  at android.os.Looper.loopOnce(Looper.java:201) 
			  at android.os.Looper.loop(Looper.java:288) 
			  at android.os.HandlerThread.run(HandlerThread.java:67) 

### Media

[1112_Audio_74_mp4-vorbis.mp4](https://github.com/user-attachments/assets/b9252d38-3ee4-4b61-8d4e-560cad89521c)

[1121_Audio codec_OPUS_48kHz.WEBM](https://github.com/user-attachments/assets/b2c6c678-1d86-4078-81d2-651d5f144fc6)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by MrBoe** [comment]
Hi @microkatz, is there there some news on your side? I cross-tested with other media files (from CTS 1.4) with same container/codec combination and they are playing well in media3. In reverse, our appended test files are playing well in different other players. Here 2 Diffs for the regarding files - Maybe you have an idea on this:
![grafik](https://github.com/user-attachments/assets/30abe103-5edb-40a8-9f88-4812e7810101)
![grafik](https://github.com/user-attachments/assets/48ecca72-4c38-49d4-bd80-c3f9a1b867a7)
