### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by Arman3092** [androidx/media#1974]
Hello, Who can help with this?

FATAL EXCEPTION: main
                                                                                                    Process: com.ptv.mytest, PID: 30726
                                                                                                    java.lang.ArithmeticException: divide by zero
                                                                                                    	at androidx.leanback.app.VideoSupportFragment.onVideoSizeChanged(VideoSupportFragment.java:102)
                                                                                                    	at androidx.leanback.app.PlaybackSupportFragmentGlueHost$2.onVideoSizeChanged(PlaybackSupportFragmentGlueHost.java:130)
                                                                                                    	at androidx.leanback.media.PlaybackBaseControlGlue$1.onVideoSizeChanged(PlaybackBaseControlGlue.java:178)
                                                                                                    	at androidx.leanback.media.MediaPlayerAdapter$5.onVideoSizeChanged(MediaPlayerAdapter.java:84)
                                                                                                    	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3543)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by icbaker** [comment]
From the stack trace:

> `at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3543)`

It looks like this issue doesn't refer to `androidx.media3` at all and is instead about combining `androidx.leanback` with `MediaPlayer`? In that case, this is not in scope for this issue tracker.
