### ISSUE TITLE
Media 3 return 403 for exoplayer media3 

### ISSUE THREAD

**Issue by ThreeMinutesFix** [androidx/media#1977]
I tried to play a url. I have already mailed the m3u8 url to the android-media-github@google.co. please check for recreate issue.
Hls link i shared plays well in mxplayer or any other place even in nsplayer. but not in media3 nor exoplayer i use .
Information
Device Android 11
Exoplayer Laterst :1.5.0
I checked other bug replies but there was no solution.
Error log from exoplayer 
```
Playback error
androidx.media3.exoplayer.ExoPlaybackException: Source error
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:737)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:709)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:223)
    at android.os.Looper.loop(Looper.java:317)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 403
    at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:401)
    at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:87)
    at androidx.media3.exoplayer.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:525)
    at androidx.media3.exoplayer.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:498)
    at androidx.media3.exoplayer.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:467)
    at androidx.media3.exoplayer.hls.HlsMediaChunk.load(HlsMediaChunk.java:424)
    at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:450)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)
```
Error In action video attached "https://www.youtube.com/shorts/K0xqIXUavC0"
please provide a solution 
thankyou team

**Comment by ThreeMinutesFix** [comment]
I have sent the email with sub :issue 1977

**Comment by marcbaechinger** [comment]
Thanks for your question. I couldn't find the email I'm afraid.

However, I'm not sure we can help with a HTTP response 403 reports forbidden  access. That's something you need to figure out with the folks that operates the server, so you can make sure your app has access. If you think that some kind of authentication is required, let us know why you think this isn't working. We can probably assist you with that. 

In case you need to set some kind of special HTTP headers you can look into [`ResolvingDataSource`](https://github.com/androidx/media/blob/release/libraries/datasource/src/main/java/androidx/media3/datasource/ResolvingDataSource.java) that would allow you to for instance add HTTP headers to a request.

**Comment by ThreeMinutesFix** [comment]
thankyou its weird google replies mail cannot be deliver any how here is the mail 

https://icdnflare.com/istream.m3u8  
like it plays for some second and the the video stops playing no matter how much you click on play and pause but in other exoplayer based application like NS Player or other apps based on exoplayer are running the same m3u8 flawlessly without any problem, 
regards

i think there is no need of header because it play well in vlc or in browser or any where else except my exoplayer or media 3 
yes , I tried both exoplayer  2.19 or final version code as well as this media 3 1.15 v code 
both play video for min and stop and if i skip it play well for few min and stop.

**Comment by marcbaechinger** [comment]
Thanks for the email. Yeah, sorry I can not help with 403 I'm afraid.

That stream plays in the ExoPlayer main demo app without problems. I doubt that if you get a 403 this would be different with another player than ExoPlayer, but of course I do not question your observation.

For this issue I think I can't help. The stream you sent now play for about 5 minutes on my phone (it's quite a violent scene going on right now at 15:24).

Sorry, I can't help with this. You need to figure this out with the server operator as mentioned above.

You can try adding the URI to the ExoPlayer main demo app and see if you have the same issues there. For the 403 in general  I can't help you some further I'm afraid.

**Comment by ThreeMinutesFix** [comment]
Actually solution was, just changing user agent. thanks for your help :) You can close  the issue ,if needed.

**Comment by ThreeMinutesFix** [comment]
Closed as fixed
