### ISSUE TITLE
AbstractMethodError : java.lang.AbstractMethodError: abstract method "void androidx.media3.common.Player$Listener.onSurfaceSizeChanged(int, int)

### ISSUE THREAD

**Issue by Anush-Shand** [androidx/media#1981]
### Version

Media3 1.1.1 / ExoPlayer 2.19.1

### Devices that reproduce the issue

Example - Pixel 6 running API 33

(Reproducible irrespective of the device)

### Reproducible in the demo app?

Not tested

### Reproduction steps

Haven't tried on the sample app

### Expected result

The video is shown without running into the `AbstractMethodError`

### Actual result

The video runs into `AbstractMethodError`

### Media

`java.lang.AbstractMethodError: abstract method "void androidx.media3.common.Player$Listener.onSurfaceSizeChanged(int, int)"
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$maybeNotifySurfaceSizeChanged$27(ExoPlayerImpl.java:2718)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda18.invoke(Unknown Source:6)
                                                                                                    	at androidx.media3.common.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:339)
                                                                                                    	at androidx.media3.common.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:223)
                                                                                                    	at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                                                                    	at androidx.media3.common.util.ListenerSet.flushEvents(ListenerSet.java:245)
                                                                                                    	at androidx.media3.common.util.ListenerSet.sendEvent(ListenerSet.java:260)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImpl.maybeNotifySurfaceSizeChanged(ExoPlayerImpl.java:2717)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImpl.setVideoSurfaceHolder(ExoPlayerImpl.java:1352)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImpl.setVideoSurfaceView(ExoPlayerImpl.java:1383)
                                                                                                    	at androidx.media3.ui.PlayerView.setPlayer(PlayerView.java:585)
                                                                                                    	at com.clevertap.android.sdk.video.inbox.Media3Handle.initPlayerView(Media3Handle.kt:113)`

https://github.com/CleverTap/clevertap-android-sdk/blob/5124bed0076badad5aec22ac0e61065ee3a4b17e/clevertap-core/src/main/java/com/clevertap/android/sdk/video/inbox/Media3Handle.kt#L27

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by Anush-Shand** [comment]
More details here https://github.com/CleverTap/clevertap-android-sdk/issues/671

**Comment by icbaker** [comment]
This looks the same as:
* https://github.com/google/ExoPlayer/issues/10741
* https://github.com/google/ExoPlayer/issues/8254
* https://github.com/google/ExoPlayer/issues/8224
* https://github.com/google/ExoPlayer/issues/7927
* https://github.com/google/ExoPlayer/issues/7349

See a summary here: https://github.com/google/ExoPlayer/issues/7349
