### ISSUE TITLE
Required assistance for using CompositionPlayer in my project

### ISSUE THREAD

**Issue by muhammad-najam-cmp** [androidx/media#1983]
For my case scenario I found Composition player from the demo app, but it has required some bug fixings, specially it is crashing on inputs. I'm using it in Compose project.

`@Composable
fun MultipleCompositionVideosPlayer(
    selectionModels: List<FileSelectionModel>,
    frameType: String = "FILL",
    audioUri: String? = null,
    isActive: Boolean = true
) {
    val context = LocalContext.current
    val compositionPlayer = remember { CompositionPlayer.Builder(context).build() }
    val lifecycleOwner = LocalLifecycleOwner.current

    // Filter selection models
    val filteredSelectionModels = selectionModels.filter { it.uriString.isNotEmpty() }
    val currentMediaItems = remember { mutableStateOf(filteredSelectionModels) }
    var videoSequenceDurationUs = 0L

    // Only update if the filtered models are different
    if (currentMediaItems.value != filteredSelectionModels && filteredSelectionModels.isNotEmpty()) {
        currentMediaItems.value = filteredSelectionModels

        val videoEffects = arrayListOf<Effect>().apply {
            add(Presentation.createForWidthAndHeight(1080, 1920, Presentation.LAYOUT_SCALE_TO_FIT))
        }

        val mediaItemsList = mutableListOf<EditedMediaItem>()

        val pitchChanger = SonicAudioProcessor()
        pitchChanger.setPitch(if (filteredSelectionModels.size % 2 == 0) 2f else 0.2f)
        // Iterate through each selection model
        filteredSelectionModels.forEach { selectedFile ->
            log("Composition_LOG", "${selectedFile.fileType}, audio=${selectedFile.enableOriginalAudio}, " +
                    "w:h=${selectedFile.videoWidth}:${selectedFile.videoHeight}")

            val editedMediaItem = when (selectedFile.fileType) {
                "Video" -> {
                    val startTime = (selectedFile.uriStartTime * 1000L).toLong()
                    val clipDuration = (selectedFile.clip.duration?.times(1000) ?: 1000)

                    EditedMediaItem.Builder(
                        MediaItem.Builder().setUri(selectedFile.uriString)
                            .setClippingConfiguration(
                                ClippingConfiguration.Builder()
                                    .setStartPositionMs(startTime)
                                    .setEndPositionMs(startTime + clipDuration.toLong())
                                    .build()
                            ).build()
                    ).apply {
                        setRemoveAudio(true)  // Disable sound from video
                        setFrameRate(30)
                        setDurationUs(clipDuration.toLong() * 1000)
                        setEffects(Effects(listOf(pitchChanger), videoEffects))
                    }.build()
                }

                else -> {
                    val imageDurationUs = (selectedFile.uriDuration * 1000 * 1000).toLong()
                    EditedMediaItem.Builder(
                        MediaItem.Builder().setUri(selectedFile.uriString).build()
                    ).apply {
                        setRemoveAudio(true)  // Disable sound for images
                        setDurationUs(imageDurationUs)
                        setFrameRate(30)
                        setEffects(Effects(listOf(), videoEffects))
                    }.build()
                }
            }

            videoSequenceDurationUs += (selectedFile.clip.duration?.times(1000L) ?: 1).toLong()
            mediaItemsList.add(editedMediaItem)
        }

        // Add the custom audio if provided
        val audioSequence: EditedMediaItemSequence? = if (audioUri != null) {
            log("audioUri_LOG", "$audioUri duration $videoSequenceDurationUs")

            val backgroundAudio = EditedMediaItem.Builder(
                MediaItem.Builder().setUri(audioUri)
                    .setClippingConfiguration(
                        ClippingConfiguration.Builder().setStartPositionMs(0)
                            .setEndPositionMs(videoSequenceDurationUs).build()
                    ).build()
            ).apply {
                setFrameRate(30)
                setDurationUs(videoSequenceDurationUs * 1000)
                setEffects(Effects(listOf(), videoEffects))
            }.build()

            EditedMediaItemSequence(ImmutableList.of(backgroundAudio), false)
        } else {
            null
        }

        // Add video/image sequences to the composition
        val videoImageSequences = mutableListOf(EditedMediaItemSequence(mediaItemsList))
        if (audioSequence != null) {
            videoImageSequences.add(audioSequence)
        }

        // Use SonicAudioProcessor to adjust sample rate (optional, depending on audio)
        val sampleRateChanger = SonicAudioProcessor()
        sampleRateChanger.setOutputSampleRateHz(8000)

        // Create the composition
        val composition = remember {
            Composition.Builder(videoImageSequences)
                .setVideoCompositorSettings(VideoCompositorSettings.DEFAULT)
                .setEffects(Effects(listOf(sampleRateChanger), listOf()))
                .setHdrMode(Composition.HDR_MODE_KEEP_HDR)
                .build()
        }

        // Set up the player
        compositionPlayer.repeatMode = Player.REPEAT_MODE_ALL
        compositionPlayer.volume = 1f
        compositionPlayer.playWhenReady = isActive
        compositionPlayer.setComposition(composition)
        compositionPlayer.prepare()
    }

    // Setup UI for the player view
    val allowController = BuildConfig.ALLOW_CONTROL
    DisposableEffect(
        AndroidView(factory = {
            PlayerView(context).apply {
                useController = allowController
                resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM
                player = compositionPlayer
                layoutParams = FrameLayout.LayoutParams(MATCH_PARENT, MATCH_PARENT)
            }
        })
    ) {
        val observer = object : DefaultLifecycleObserver {
            override fun onPause(owner: LifecycleOwner) {
                log("_LOG", "Activity-onPause.....")
                compositionPlayer.pause()
            }

            override fun onResume(owner: LifecycleOwner) {
                log("_LOG", "Activity-onResume.....")
                compositionPlayer.play()
            }
        }

        lifecycleOwner.lifecycle.addObserver(observer)

        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
            compositionPlayer.release()
        }
    }
}`

Hurdles I'm finding right now:
1- I'm fixing the height and width of edited media item using presentation, but after composing it is as *input video not what I'm fixing.
2- I'm setting sound remove for all inputs but it is playing sound of input videos
3- I'm finding this crash for some input videos Caused by: androidx.media3.common.audio.AudioProcessor$UnhandledAudioFormatException: Audio can not be modified to match downstream format AudioFormat[sampleRate=44100, channelCount=2, encoding=2]
4- Repeat_MODE_ALL is not working as aspeted, once player stops it is not playing again, 

Note: when I'm transforming video it is as I'm expeting.

**Comment by droid-girl** [comment]
Hi @muhammad-najam-cmp!
Thank you for testing `CompositionPlayer`. Are you testing with 1.5.0 version?

**Comment by muhammad-najam-cmp** [comment]
Hi Welcome, I started with 1.4.1 but latterly I updated that fixes of above mentioned issues.
yes I'm doing it with 1.5.0.
It's all going good, but there's a problem I'm facing in Compose that it is not providing me PlayerView on **re submission.** (Re submission means updating my uri list with in same screen)
and also not providing the desired out put Presentation frame of 1080*1920. Other issue were handled laterally. 

The main issue is if I update composition then its not generating preview, I'm getting problem in Composable re-drawn(re-compose). I tried hard but fails. 

More over its working some awesome.

How I'm doing it:

```
            Box(
                modifier = Modifier
                    .aspectRatio(outputFrameDiv)
                    .fillMaxSize()
                    .background(color = colorBg),
                contentAlignment = Alignment.Center,
            ) {
                Card(
                    modifier = Modifier
                        .aspectRatio(outputFrameDiv)
                        .align(Alignment.Center)
                        .wrapContentSize(),
                    colors = CardDefaults.cardColors(containerColor = Color.Gray),
                    shape = RoundedCornerShape(8.sdp),
                ) {

                    MultipleCompositionVideosPlayer(  selectionModels = selectedFiles, frameType = frameType,
                        audioUri = filesSelectionViewModel.selectedAudioUrl.value
                    )
           }
```

Main Code base, working fine with composition creation and play for first time. 


```
@UnstableApi
@Composable
fun MultipleCompositionVideosPlayer(
    selectionModels: List<FileSelectionModel>,
    frameType: String = "FILL",
    audioUri: String? = null,
    isActive: Boolean = true
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current

    val filteredSelectionModels = selectionModels.filter { it.uriString.isNotEmpty() }
    var videoSequenceDurationUs = 0L

    val compositionPlayer = remember { CompositionPlayer.Builder(context).build() }
    // Force recomposition when the filteredSelectionModels changes
    if (filteredSelectionModels.isNotEmpty()) {
        LaunchedEffect(filteredSelectionModels) {
            val videoEffectsBuilder = ImmutableList.Builder<Effect>()
            videoEffectsBuilder.add(Presentation.createForHeight(1920))

            val videoEffects = videoEffectsBuilder.build()

            val editedMediaItemsList = mutableListOf<EditedMediaItem>()
            val pitchChanger = SonicAudioProcessor()
            pitchChanger.setPitch(if (filteredSelectionModels.size % 2 == 0) 2f else 0.2f)

            // Iterate through each selection model
            filteredSelectionModels.forEach { selectedFile ->
                log("Composition_LOG", "${selectedFile.fileType}, audio=${selectedFile.enableOriginalAudio}, " +
                            "w:h=${selectedFile.videoWidth}:${selectedFile.videoHeight}")

                val editedMediaItem = when (selectedFile.fileType) {
                    "Video" -> {
                        val startTime = (selectedFile.uriStartTime * 1000L).toLong()
                        val clipDuration = (selectedFile.clip.duration?.times(1000) ?: 1000)

                        EditedMediaItem.Builder(
                            MediaItem.Builder().setUri(selectedFile.uriString)
                                .setClippingConfiguration(
                                    ClippingConfiguration.Builder()
                                        .setStartPositionMs(startTime)
                                        .setEndPositionMs(startTime + clipDuration.toLong())
                                        .build()
                                ).build()
                        ).apply {
                            setRemoveAudio(true)  // Disable sound from video
                            setFrameRate(30)
                            setDurationUs(clipDuration.toLong() * 1000)
                            setEffects(Effects(listOf(pitchChanger), videoEffects))
                        }.build()
                    }

                    else -> {
                        val imageDurationUs = (selectedFile.uriDuration * 1000 * 1000).toLong()
                        EditedMediaItem.Builder(
                            MediaItem.Builder().setUri(selectedFile.uriString).build()
                        ).apply {
                            setDurationUs(imageDurationUs)
                            setFrameRate(30)
                            setEffects(Effects(listOf(), videoEffects))
                        }.build()
                    }
                }
                videoSequenceDurationUs += (selectedFile.clip.duration?.times(1000L) ?: 1).toLong()
                editedMediaItemsList.add(editedMediaItem)
            }

            // Add the custom audio if provided
            val audioSequence: EditedMediaItemSequence? = if (audioUri != null) {
                log("audioUri_LOG", "$audioUri duration $videoSequenceDurationUs")

                val backgroundAudio = EditedMediaItem.Builder(
                    MediaItem.Builder().setUri(audioUri)
                        .setClippingConfiguration(
                            ClippingConfiguration.Builder().setStartPositionMs(0)
                                .setEndPositionMs(videoSequenceDurationUs).build()
                        ).build()
                ).apply {
                    setFrameRate(30)
                    setDurationUs(videoSequenceDurationUs * 1000)
                    setEffects(Effects(listOf(), videoEffects))
                }.build()

                EditedMediaItemSequence.Builder().addItem(backgroundAudio).build()
            } else {
                null
            }

            val videoImageSequences =
                mutableListOf(EditedMediaItemSequence.Builder().addItems(editedMediaItemsList).build())
            if (audioSequence != null) {
                videoImageSequences.add(audioSequence)
            }

            // Creating the composition
            val composition = Composition.Builder(videoImageSequences)
                .setEffects(Effects(listOf(), listOf()))
                .build()

            // Pause and update composition if needed, if below compositionPlayer.release() 
            // is called it returns blank screen
            
//          compositionPlayer.release()
            
            
            compositionPlayer.pause()
            compositionPlayer.setComposition(composition)
            compositionPlayer.prepare()
            compositionPlayer.repeatMode = CompositionPlayer.REPEAT_MODE_ALL
            compositionPlayer.playWhenReady = isActive

            compositionPlayer.addListener(object : Player.Listener {
                override fun onPlayerError(error: PlaybackException) {
                    log("ExoPlayerError_LOG", "Error code: ${error.errorCode}")
                    log("ExoPlayerError_LOG", "Error message: ${error.message}")
                    log("ExoPlayerError_LOG", "Error details: ${error.stackTrace}")
                }
            })
        }
    }

    // Setup UI for the player view
    val allowController = BuildConfig.ALLOW_CONTROL
    DisposableEffect(
        AndroidView(factory = {
            PlayerView(context).apply {
                useController = allowController
                resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM
                player = compositionPlayer
                layoutParams = FrameLayout.LayoutParams(MATCH_PARENT, MATCH_PARENT)
            }
        })
    ) {
        val observer = object : DefaultLifecycleObserver {
            override fun onPause(owner: LifecycleOwner) {
                log("_LOG", "Activity-onPause.....")
                compositionPlayer.pause()
            }

            override fun onResume(owner: LifecycleOwner) {
                log("_LOG", "Activity-onResume.....")
                compositionPlayer.play()
            }
        }

        lifecycleOwner.lifecycle.addObserver(observer)

        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
            compositionPlayer.release()

        }
    }

}
```



**Currently I'm facing following crash in Jetpack Compose.**

```
AndroidRuntime           E  FATAL EXCEPTION: main
                            Process: com.leapixel.reelstemplix, PID: 32530
                            java.lang.IllegalStateException
                            	at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
                            	at androidx.media3.transformer.CompositionPlayer.setComposition(CompositionPlayer.java:341)
                            	at com.leapixel.reelstemplix.root.composable.VideoPlayerKt$MultipleCompositionVideosPlayer$2$1.invokeSuspend(VideoPlayer.kt:941)
                            	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                            	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                            	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                            	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                            	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                            	at android.os.Handler.handleCallback(Handler.java:883)
                            	at android.os.Handler.dispatchMessage(Handler.java:100)
                            	at android.os.Looper.loop(Looper.java:214)
                            	at android.app.ActivityThread.main(ActivityThread.java:7453)
```

**Comment by muhammadzubair906** [comment]
I'm also having same issue. An example Playing Media 3 Composition (Different media files with different clippings and a background audio) on Media 3 Composition player on Jetpack compose layout would help alot.

**Comment by muhammad-najam-cmp** [comment]
@shahdDaghash could you please assit me as soon as possible, as I'm holding my running project.

**Comment by shahdDaghash** [comment]
Hi,

Thanks for providing the code and highlighting this issue! There is a current limitation on CompositionPlayer that requires recreating both the `CompositionPlayer` and `Composition` with every recomposition. This is due to `CompositionPlayer` being an in-progress API, and we're actively working on improvements.

Looking at the code, it appears your `composition` is only being recreated when `filteredSelectionModels.isNotEmpty()`. Also, because `compositionPlayer` is remembered, it won't be recreated on recomposition. To address this, ensure both `composition` and `compositionPlayer` are recreated with every recomposition.

Please let us know if you have other questions or run into further issues.

**Comment by muhammad-najam-cmp** [comment]
``Hi, 
You're welcome, @shahdDaghash I tried what you asked in your response, but in compose **It is not updating Playerview** when I update number of inputs. Though I test debug and check thoroughly that my Compose is updating Everytime with its sound but fails in preview. 

I'm providing you my implementations and a Video file to describe it in details. 


My initials:

`@SuppressLint("RestrictedApi")
@OptIn(UnstableApi::class)
@Composable
fun VideoPlayerLayout(
    context: Context,
    selectedFiles: List<FileSelectionModel>,
    selectedFrame: FrameSizeModel,
) {
    val filesSelectionViewModel: FileSelectionViewModel = koinViewModel()

    val coroutineScope = rememberCoroutineScope()
    
    Box(
        modifier = Modifier
            .aspectRatio(outputFrameDiv)
            .fillMaxSize()
            .background(color = colorBg),
        contentAlignment = Alignment.Center,
    ) {
        Card(
            modifier = Modifier
                .aspectRatio(outputFrameDiv)
                .align(Alignment.Center)
                .wrapContentSize(),
            colors = CardDefaults.cardColors(containerColor = Color.Gray),
            shape = RoundedCornerShape(8.sdp),
        ) {
            val playVideo = uiStateViewModel.isMusicPlaying.value

            var composition by remember { mutableStateOf<Composition?>(null) }

            LaunchedEffect(selectedFiles) {
                log("Into-Scope-LOG", "Into-LaunchEffect")
                coroutineScope.launch {
                    composition = null
                    composition = createComposition(
                        context, selectedFiles,
                        frameType, outputFrameDiv,
                        filesSelectionViewModel.selectedAudioUrl.value
                    )
                }
            }

            composition?.let {
                MultipleCompositionVideosPlayer(context, it)
            } ?: run {
                log("Dispose_LOG", "into-null")
            }
        }
    }`
    
    
    My Video Playing Compose Widget:
    
    @RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)
@SuppressLint("OpaqueUnitKey", "RestrictedApi")
@UnstableApi
@Composable
fun MultipleCompositionVideosPlayer(
    context: Context,
    composition: Composition,
) {
    val lifecycleOwner = LocalLifecycleOwner.current

    log("Dispose_LOG", "Into Multiple")

    val playerView = PlayerView(context).apply {
        useController = BuildConfig.ALLOW_CONTROL
        resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM
        layoutParams = FrameLayout.LayoutParams(MATCH_PARENT, MATCH_PARENT)
    }

    val compositionPlayer = CompositionPlayer.Builder(context).build()

    LaunchedEffect(composition) {
        compositionPlayer.setComposition(composition)
        compositionPlayer.prepare()
        compositionPlayer.repeatMode = CompositionPlayer.REPEAT_MODE_ALL
        compositionPlayer.playWhenReady = true
        playerView.player = compositionPlayer
    }

    compositionPlayer.addListener(object : Player.Listener {
        override fun onPlayerError(error: PlaybackException) {
            error.printStackTrace()
            log("ExoPlayerError_LOG", "Error code: ${error.errorCode}")
            log("ExoPlayerError_LOG", "Error message: ${error.message}")
            log("ExoPlayerError_LOG", "Error details: ${error.stackTrace}")
        }

    })

    AndroidView(factory = {
        playerView
    })

    val observer = object : DefaultLifecycleObserver {
        override fun onPause(owner: LifecycleOwner) {
            log("_LOG", "Activity-onPause.....")
            compositionPlayer.pause()
        }

        override fun onResume(owner: LifecycleOwner) {
            log("_LOG", "Activity-onResume.....")
            compositionPlayer.play()
        }

        override fun onDestroy(owner: LifecycleOwner) {
            super.onDestroy(owner)
            log("_LOG", "Activity-onDestroy.....")
            compositionPlayer.release()
            playerView.player = null
        }
    }

    lifecycleOwner.lifecycle.addObserver(observer)

    DisposableEffect(key1 = composition, key2 = lifecycleOwner) {

        onDispose {
            compositionPlayer.release()
            playerView.player = null
            log("onDispose_LOG", "Disposing from disposable $compositionPlayer, $composition")
        }
    }

}


I'm using **DisposeEffect on composition to completely destroy my Playerview** and all its holding.

**Outputs Logs:

1- When Blackout**
`
FinalShaderWrapper       W  Output surface and size not set, dropping frame.
FinalShaderWrapper       W  Output surface and size not set, dropping frame.
chatty                   I  uid=10316(com.leapixel.reelstemplix) Effect:DefaultV identical 3 lines
FinalShaderWrapper       W  Output surface and size not set, dropping frame.
ACodec                   E  dequeueBuffer failed: WOULD_BLOCK(-11).
FinalShaderWrapper       W  Output surface and size not set, dropping frame.
FinalShaderWrapper       W  Output surface and size not set, dropping frame.
FinalShaderWrapper       W  Output surface and size not set, dropping frame.`

**2- When displays very first frame**
`SurfaceUtils             D  disconnecting from surface 0x7a49fe2010, reason connectToSurface(reconnect)
SurfaceUtils             D  connecting to surface 0x7a49fe2010, reason connectToSurface(reconnect)
SurfaceUtils             D  legacy buffer drop disabled: target sdk (35)
ExtendedACodec           I  setupVideoDecoder()
ExtendedACodec           I  Decoder will be in frame by frame mode
SurfaceUtils             D  set up nativeWindow 0x7a49fe2010 for 720x1488, color 0x7fa30c06, rotation 0, usage 0x20002900
MapperHal                W  buffer descriptor with invalid usage bits 0x2000mimeType=video/avc, codecs=avc1.64002A, res=720x1488, color=BT601/Limited range/SDR SMPTE 170M/8/8, fps=21.310106]
MapperHal                W  buffer descriptor with invalid usage bits 0x2000
MapperHal                W  buffer descriptor with invalid usage bits 0x2000
EventLogger              D  rendererReady [eventTime=196.53, mediaPos=0.00, window=0, period=0, rendererIndex=0, audio, true]
EventLogger              D  loading [eventTime=196.56, mediaPos=0.00, window=0, period=0, false]
SurfaceUtils             D  set up nativeWindow 0x7a49fe2010 for 720x1488, color 0x7fa30c06, rotation 0, usage 0x20002900
EventLogger              D  state [eventTime=196.58, mediaPos=0.00, window=0, period=0, READY]
MapperHal                W  buffer descriptor with invalid usage bits 0x2000
MapperHal                W  buffer descriptor with invalid usage bits 0x2000
EventLogger              D  loading [eventTime=196.60, mediaPos=0.00, window=0, period=0, true]
MapperHal                W  buffer descriptor with invalid usage bits 0x2000
EventLogger              D  loading [eventTime=196.63, mediaPos=0.00, window=0, period=0, true]
EventLogger              D  loading [eventTime=196.64, mediaPos=0.00, window=0, period=0, false]
FinalShaderWrapper       W  Output surface and size not set, dropping frame.
EventLogger              D  rendererReady [eventTime=196.66, mediaPos=0.00, window=0, period=0, rendererIndex=1, video, true]
EventLogger              D  loading [eventTime=196.66, mediaPos=0.00, window=0, period=0, true]`

Note: It play the composition if I RE-create the activity.

**Comment by droid-girl** [comment]
Hi @muhammad-najam-cmp, it looks like there is a problem in your setup of `CompositionPlayer` and compose. 
Please make sure to:

1. Create a new `Composition` when you need to update any effects or media items
2. Create a new `CompositionPlayer` every time you update your composition

Please note that `CompositionPlayer` is still under active development and may contain some limitations, for example re-creating `CompositionPlayer` every time.

**Comment by muhammad-najam-cmp** [comment]
Perhaps, I've to utilise PlayerView via xml, It's working with that.

**Comment by muhammad-najam-cmp** [comment]
Hi, @droid-girl , @shahdDaghash 

I'm getting one more problem, when I'm composing video with any of my MediaItem Contained By EditedMediaItem with clipping time not starting from 0MS it is causing audio syncing issue. 

Note I'm creating video sequences separately while audio in separate. As provided implementations above.

```
            val startTime = ((selectedFile.uriStartTime * 1000L)).toLong()
            val clipDuration = (selectedFile.clip.duration?.times(1000) ?: 1000)
            val endTime = startTime + clipDuration.toLong()
            
            EditedMediaItem.Builder(
                        MediaItem.Builder().setUri(selectedFile.uriString)
                            .setClippingConfiguration(
                                ClippingConfiguration.Builder()
                                    .setStartPositionMs(startTime)
                                    .setEndPositionMs(endTime)
                                    .build()
                            ).build()
                    ).apply {
                        setRemoveAudio(selectedFile.containsAudio)
                        setFrameRate(30)
                        setDurationUs(endTime * 1000)
                        setEffects(Effects(listOf(pitchChanger), videoEffects))
                    }.build()
```

when ever any of inputvideo startTimeis greater the 0MS it is causing audio syncing issue or disruptive audio. for example
val startTime = ((selectedFile.uriStartTime * 1000L+400L)).toLong().
I also tried to set audio in US.

**Comment by shahdDaghash** [comment]
Hi @muhammad-najam-cmp,

Thanks for explaining the problem you're experiencing. I attempted to reproduce the issue in the Composition demo by creating a sequence of videos with audio, each configured with different start position clipping. However, I was unable to observe any syncing issues or audio disruptions.

To help us investigate further, could you please provide us with more details about the issue you're seeing? A demo recording of the problem would be especially helpful. Please also include any other information you think might be relevant, such as your setup and configuration. Thanks!
