### ISSUE TITLE
ExoPlaybackException starting 1.4.0-beta01

### ISSUE THREAD

**Issue by KingLucius** [androidx/media#1991]
### Version

Media3 main branch

### Devices that reproduce the issue

Android 14

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play the attached media

### Expected result

Media plays without issue

### Actual result

```
androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:737)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:707)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:113)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                          at android.os.Looper.loop(Looper.java:302)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor, PngExtractor, WebpExtractor, BmpExtractor, HeifExtractor, AvifExtractor) could read the stream. {contentIsMalformed=false, dataType=1}
                                                                                                          at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:108)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1100)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:450)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
```

### Media

Email

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by KingLucius** [comment]
c002ff6a6f074426c919f5850a3128d50251676d is the first bad commit
commit c002ff6a6f074426c919f5850a3128d50251676d
Author: Tofunmi Adigun-Hameed <tofunmi@google.com>
Date:   Thu Jun 22 15:33:06 2023 +0000

Merge pull request #419 from v-novaltd:vnova-104

**Comment by KingLucius** [comment]
You have to use the same referer I sent in the email, it's in html ext but it's direct video link.

**Comment by icbaker** [comment]
I tried:

```
curl --referer $PROVIDED_REFERER $PROVIDED_URL -O
```

The downloaded file is an HTML 403 error.

**Comment by KingLucius** [comment]
Updated the link
Thanks

**Comment by icbaker** [comment]
New link gives me the same 403 HTML page when using the `curl --referer` command described above.

**Comment by Datj0000** [comment]
@icbaker you can use this m3u8 file

[test.txt](https://github.com/user-attachments/files/19256317/test.txt)
