### ISSUE TITLE
Changing BitRate of a Video does not compress it

### ISSUE THREAD

**Issue by BraveEvidence** [androidx/media#1992]
### Version

Media3 main branch

### More version details

Media3 Version 1.5.0

### Devices that reproduce the issue

Samsung Galaxy M01 running Android 12

### Reproducible in the demo app?

Not tested

### Reproduction steps

I am trying to change the Bitrate of a video to compress it but instead of reducing the size of the video , it increases the size

here is the sample code 

  ```
transformer = with(Transformer.Builder(this)) {
            setEncoderFactory(DefaultEncoderFactory.Builder(this@MainActivity)
                .setRequestedVideoEncoderSettings(VideoEncoderSettings.Builder()
                    .setBitrate(20)
                    .build())
                .build())
            addListener(this@MainActivity)
            build()
        }

        val inputMediaItem = MediaItem.Builder().apply {
            setUri(videoUrl)
        }.build()

        val editedMediaItem = EditedMediaItem.Builder(inputMediaItem).apply {
            setEffects(Effects(mutableListOf(), mutableListOf()))
        }.build()

        filePath = createExternalFile()
        transformer!!.start(editedMediaItem, filePath?.absolutePath!!)

```

I have tried using different values for bitrate like 20,40,60 still the size of the video does not decrease. I followed [this](https://github.com/androidx/media/issues/1154#issuecomment-1986591491) suggestion

### Expected result

Should reduce the video size

### Actual result

Increases the video size

### Media

https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by droid-girl** [comment]
The same issue was discussed in [this comment](https://github.com/androidx/media/issues/1304#issuecomment-2124324237). 
Could you try switching to Constant Bitrate (CBR) mode as recommended there.

**Comment by BraveEvidence** [comment]
@droid-girl  Thanks, I tried your suggestion for multiple videos but I get following error

```
Export error after export ended
                                                                                                    androidx.media3.transformer.ExportException: Codec exception: CodecInfo{type=VideoDecoder, configurationFormat={exo-pixel-width-height-ratio-float=1.0, sar-width=1, is-forced-subtitle=0, allow-frame-drop=0, level=512, mime=video/avc, profile=8, codecs-string=avc1.64001F, csd-1=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], encoder-delay=0, sar-height=1, width=1280, is-autoselect=0, is-default=0, encoder-padding=0, frame-rate=24.000002, max-input-size=97468, rotation-degrees=0, height=720, csd-0=java.nio.HeapByteBuffer[pos=0 lim=27 cap=27]}, name=OMX.qcom.video.decoder.avc}
                                                                                                    	at androidx.media3.transformer.DefaultCodec.createExportException(DefaultCodec.java:465)
                                                                                                    	at androidx.media3.transformer.DefaultCodec.createExportException(DefaultCodec.java:443)
                                                                                                    	at androidx.media3.transformer.DefaultCodec.queueInputBuffer(DefaultCodec.java:246)
                                                                                                    	at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.feedDecoderFromInput(ExoAssetLoaderBaseRenderer.java:301)
                                                                                                    	at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.render(ExoAssetLoaderBaseRenderer.java:112)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1138)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.IllegalStateException
                                                                                                    	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
                                                                                                    	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2634)
                                                                                                    	at androidx.media3.transformer.DefaultCodec.queueInputBuffer(DefaultCodec.java:243)
                                                                                                    	at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.feedDecoderFromInput(ExoAssetLoaderBaseRenderer.java:301) 
                                                                                                    	at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.render(ExoAssetLoaderBaseRenderer.java:112) 
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1138) 
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
2024-12-23 08:55:46.137 11048-11048 Progress is             com.codingwithnobody.myandroidapp    I  0 0
```

Here is the updated code

  ```
transformer = with(Transformer.Builder(this)) {
            setEncoderFactory(DefaultEncoderFactory.Builder(this@MainActivity)
                .setRequestedVideoEncoderSettings(VideoEncoderSettings.Builder()
                    .setBitrate(40)
                    .setBitrateMode(MediaCodecInfo.EncoderCapabilities.BITRATE_MODE_CBR)
                    .build())
                .build())
            addListener(this@MainActivity)
            build()
        }
```

**Comment by tipa** [comment]
@droid-girl I'm also seeing exceptions (on some, older devices) after switching from the default (VBR) to CBR in order to force a lower bitrate. I'm using Media 1.7.1 and want to encode to H265/HEVC. Is this a hardware-limitation and if so, how can I check if CBR is supported before using it?

```
androidx.media3.transformer.ExportException: Codec exception: CodecInfo{type=VideoEncoder, configurationFormat=Format(null, null, null, video/hevc, hvc1.1.6.H120, -1, null, [360, 203, 29.998276, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), name=null}
	at androidx.media3.transformer.DefaultEncoderFactory.createExportException(DefaultEncoderFactory.java:843)
	at androidx.media3.transformer.DefaultEncoderFactory.createForVideoEncoding(DefaultEncoderFactory.java:277)
	at androidx.media3.transformer.DefaultEncoderFactory.createForVideoEncoding(DefaultEncoderFactory.java:53)
	at androidx.media3.transformer.CapturingEncoderFactory.createForVideoEncoding(CapturingEncoderFactory.java:41)
	at androidx.media3.transformer.VideoSampleExporter$EncoderWrapper.getSurfaceInfo(VideoSampleExporter.java:331)
	at androidx.media3.transformer.VideoSampleExporter$VideoGraphWrapper.onOutputSizeChanged(VideoSampleExporter.java:514)
	at androidx.media3.effect.SingleInputVideoGraph$1.lambda$onOutputSizeChanged$0$androidx-media3-effect-SingleInputVideoGraph$1(SingleInputVideoGraph.java:114)
	at androidx.media3.effect.SingleInputVideoGraph$1$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:0)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at androidx.media3.effect.SingleInputVideoGraph$1.onOutputSizeChanged(SingleInputVideoGraph.java:114)
	at androidx.media3.effect.FinalShaderProgramWrapper.lambda$ensureConfigured$6$androidx-media3-effect-FinalShaderProgramWrapper(FinalShaderProgramWrapper.java:487)
	at androidx.media3.effect.FinalShaderProgramWrapper$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at androidx.media3.effect.FinalShaderProgramWrapper.ensureConfigured(FinalShaderProgramWrapper.java:485)
	at androidx.media3.effect.FinalShaderProgramWrapper.renderFrame(FinalShaderProgramWrapper.java:399)
	at androidx.media3.effect.FinalShaderProgramWrapper.queueInputFrame(FinalShaderProgramWrapper.java:218)
	at androidx.media3.effect.FrameConsumptionManager.lambda$queueInputFrame$1$androidx-media3-effect-FrameConsumptionManager(FrameConsumptionManager.java:96)
	at androidx.media3.effect.FrameConsumptionManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at androidx.media3.effect.VideoFrameProcessingTaskExecutor.lambda$wrapTaskAndSubmitToExecutorService$3$androidx-media3-effect-VideoFrameProcessingTaskExecutor(VideoFrameProcessingTaskExecutor.java:290)
	at androidx.media3.effect.VideoFrameProcessingTaskExecutor$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalArgumentException: The requested video encoding format is not supported.
	... 25 more
```

**Comment by waheedkhan-dev** [comment]
@tipa  i am facing the same issue. did you manage to fix this?

**Comment by droid-girl** [comment]
@waheedkhan-dev could you share a code snippet and the params of the input video or a link to the input video to be able to debug this?
