### ISSUE TITLE
Crash while reordering media with cast connected

### ISSUE THREAD

**Issue by lstonussi** [androidx/media#2002]
### Version

Media3 1.4.1

### Devices that reproduce the issue

Galaxy S10

### Reproducible in the demo app?

Not tested

### Reproduction steps
 Enqueue some medias in exoplayer
 play one of them
 starts cast
 Reorder medias with cast connected

### Expected result

list of medias reordened

### Actual result

Crash 
```
E/AndroidRuntime( 9179): java.lang.NullPointerException
E/AndroidRuntime( 9179): 	at androidx.media3.common.util.Assertions.checkNotNull(Assertions.java:155)
E/AndroidRuntime( 9179): 	at androidx.media3.cast.DefaultMediaItemConverter.toMediaItem(DefaultMediaItemConverter.java:53)
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by lstonussi** [comment]
In some point, mediaInfo comes as null in this check:
`Assertions.checkNotNull(mediaInfo);`

**Comment by marcbaechinger** [comment]
The plan is that `CastPlayer` is being reworked by the cast team. Thanks for your patience. I don't have a timeline I'm afraid.

**Comment by lstonussi** [comment]
Thanks, Is there any alternative that can be used while the CastPlayer is being reworked?

**Comment by lstonussi** [comment]
@marcbaechinger 
Thanks, Is there any alternative that can be used while the CastPlayer is being reworked?

**Comment by marcbaechinger** [comment]
I think an app can always use the Cast SDK directly as an alternative if this is what you mean.
