### ISSUE TITLE
MediaController notifyAccepted fails assertion

### ISSUE THREAD

**Issue by entibaldi** [androidx/media#206]
### Media3 Version

1.0.0-beta02
androidx.media 1.6.0

### Devices that reproduce the issue

Reproduces across all devices and Android versions. This currently affects 35% of our Beta users, and for that reason we have to revert media2->media3 migration for our music control feature.

### Devices that do not reproduce the issue

Did not identify one

### Reproducible in the demo app?

Not tested

### Reproduction steps

We have not been able to reproduce the problem, that happens on the background.
Our app is listening to active MediaSessions (from any other music/media app) while in the background and is able to control music (play/pause etc.).

### Expected result

Doesn't crash

### Actual result

Crashes with 
```
Fatal Exception: java.lang.IllegalStateException:
       at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
       at androidx.media3.session.MediaController.notifyAccepted(MediaController.java:1792)
       at androidx.media3.session.MediaControllerImplLegacy.updateControllerInfo(MediaControllerImplLegacy.java:1407)
       at androidx.media3.session.MediaControllerImplLegacy.handleNewLegacyParameters(MediaControllerImplLegacy.java:1368)
       at androidx.media3.session.MediaControllerImplLegacy.access$500(MediaControllerImplLegacy.java:102)
       at androidx.media3.session.MediaControllerImplLegacy$ControllerCompatCallback.onSessionReady(MediaControllerImplLegacy.java:1609)
       at android.support.v4.media.session.MediaControllerCompat$Callback$MessageHandler.handleMessage(MediaControllerCompat.java:1121)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8212)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Media

We have not been able to reproduce yet. This might be the same issue as this stale report  https://github.com/androidx/media/issues/49

### Bug Report

- [] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue. - **we are unable to reproduce and create a bug report**

**Comment by tonihei** [comment]
Let's keep #49 for tracking. It looks like we falsely try to re-notify that the connection succeeded if we receive an extra binder call from the session after the initial connection.
