### ISSUE TITLE
MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder

### ISSUE THREAD

**Issue by vanniktech** [androidx/media#214]
### Media3 Version

1.0.0-beta03

### Devices that reproduce the issue

Pixel 6 XL running Android 13:

```
W  [c2.android.mp3.decoder] previous call to queue exceeded timeout
E  Codec reported err 0x80000000/UNKNOWN_ERROR, actionCode 0, while in state 6/STARTED
D  [c2.android.mp3.decoder#576] MediaCodec discarded an unknown buffer
D  [c2.android.mp3.decoder#576] MediaCodec discarded an unknown buffer
D  [c2.android.mp3.decoder#576] MediaCodec discarded an unknown buffer
D  [c2.android.mp3.decoder#576] MediaCodec discarded an unknown buffer
I  onLastStrongRef automatically unlinking death recipients
E  Audio codec error
android.media.MediaCodec$CodecException: Error 0x80000000
E  Playback error
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.mp3.decoder
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:947)
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:815)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1002)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:503)
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loopOnce(Looper.java:201) 
    at android.os.Looper.loop(Looper.java:288) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
E  Disable failed.
java.lang.IllegalStateException
    at android.media.MediaCodec.native_flush(Native Method)
    at android.media.MediaCodec.flush(MediaCodec.java:2388)
    at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:228)
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:879)
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:872)
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:712)
    at androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:611)
    at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:190)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1663)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1404)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1367)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:595)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play the attached file using.

### Expected result

Should play the audio file.

### Actual result

Crashes.

### Media

https://adbackstage.libsyn.com/episode-192-the-path-forward

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment]
@vanniktech I tried playing the mp3 file in the demo app after downloading it from the link provided above and was able to play this file successfully on Pixel 6a and Pixel 6. Unfortunately I don't have a Pixel 6 XL. 

Can you try to replicate this issue on our demo app and patch the player to behave in a similar manner as your application? You can then send us the git patch and we can investigate this further.

**Comment by vanniktech** [comment]
So I tried the exact same thing again in my app and now it worked flawlessly. Hence closing.
