### ISSUE TITLE
MediaCodecAudioRenderer: Audio codec error (API 31)

### ISSUE THREAD

**Issue by kevinguitar** [androidx/media#23]
Hello there 👋  
I ran into this audio codec error by seeking the media item rapidly, seems the codec can't be started after flushing, and it's only happened on API 31 for me.

```
2021-12-21 17:32:27.065 10626-11013/com.bandlab.bandlab.test E/MediaCodecAudioRenderer: Audio codec error
      java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2284)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.$r8$lambda$eDpY_fTfY9aVkUSlR57RZPPXgr0(Unknown Source:0)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback.onFlushCompletedSynchronized(AsynchronousMediaCodecCallback.java:267)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback.onFlushCompleted(AsynchronousMediaCodecCallback.java:246)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback.lambda$flushAsync$0$androidx-media3-exoplayer-mediacodec-AsynchronousMediaCodecCallback(AsynchronousMediaCodecCallback.java:203)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-12-21 17:32:27.068 10626-11013/com.bandlab.bandlab.test E/ExoPlayerImplInternal: Playback error
      androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(1, null, null, audio/mp4a-latm, mp4a.40.2, -1, und, [-1, -1, -1.0], [2, 44100]), format_supported=YES
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:570)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecDecoderException: Decoder failed: c2.android.aac.decoder
        at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.createDecoderException(MediaCodecRenderer.java:920)
        at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:801)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:990)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:494)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2284)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.$r8$lambda$eDpY_fTfY9aVkUSlR57RZPPXgr0(Unknown Source:0)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback.onFlushCompletedSynchronized(AsynchronousMediaCodecCallback.java:267)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback.onFlushCompleted(AsynchronousMediaCodecCallback.java:246)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback.lambda$flushAsync$0$androidx-media3-exoplayer-mediacodec-AsynchronousMediaCodecCallback(AsynchronousMediaCodecCallback.java:203)
        at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecCallback$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

I've found the exact same error in ExoPlayer's repo, and the reporter said it was fixed in `2.16.1`, may I know if it's a known issue and what's the current ExoPlayer version that media3 is using? Thanks!
https://github.com/google/ExoPlayer/issues/9716

**Comment by christosts** [comment]
Thanks for reporting.

The commit that fixes this issue is pushed in the main dev branch (see 5721208) and will be included in the next release.

**Comment by kevinguitar** [comment]
@christosts  Awesome! Thanks for replying 👍
