### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by lucamtudor** [androidx/media#239]
### Media3 Version

1.0.0-beta03

### Devices that reproduce the issue

Device Brand:sky
Model:Elite R55
Orientation: Portrait
RAM free: 514.99 MB
Disk free: 6.07 GB
Operating System
Version:Android 11
Orientation: Portrait
Rooted:No

### Reproducible in the demo app?

Not tested

### Reproduction steps

Unfortunately, I don't have any data points besides the Crashlytics report saying 100% Devices in Background running Android 11.

### Expected result

irelevant

### Actual result

> Fatal Exception: java.lang.IllegalArgumentException: Service not registered: s6.q0$m@89c5d3
>        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1775)
>        at android.app.ContextImpl.unbindService(ContextImpl.java:1887)
>        at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
>        at androidx.media3.session.MediaControllerImplBase.lambda$release$3(MediaControllerImplBase.java:386)
>        at androidx.activity.ComponentActivity$$InternalSyntheticLambda$1$f7979a7b7286ed37b664e8d41a94ec65e3d54774ca037fa175dd9df0faa673c4$0.run$bridge(ComponentActivity.java:386)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:223)
>        at android.app.ActivityThread.main(ActivityThread.java:7703)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

### Media

![CleanShot 2023-01-04 at 14 15 27](https://user-images.githubusercontent.com/3036785/210553303-c1e5b4be-5245-46c2-8c4c-6017a888a2eb.png)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
It's a bit unclear to me how this can happen. It looks like the controller is released after the service has (been) terminated (and unregistered). That's confusing, because as long as a client is bound to a service, the service should actually not be stopped as [per documentation](https://developer.android.com/guide/components/bound-services) and experience.

Can you provide a bit more context around when you release the controller in your app? Also, do you have some logic that stops the service via calling `stopSelf` or `stopService` and is the media session properly released in `onDestroy()` in such a case? Is the player paused (meaning the service is not in the foreground), when you try to stop the service? Any indication of service crashes?

I'm asking because if the service is not properly stopped, it may be crashed by the system and restarted. In such a case `onDestroy` is not called where I'd expect a call to `mediaSession.release()`. So if you somehow stop the service with your code, I'd watch out for some log statements of the `ActivityManager` telling to restart the service. See [this comment](https://github.com/androidx/media/issues/175#issuecomment-1262025281) for more details.

To be clear, these are all long shots as  I'm just guessing here.

Either way,

**Comment by sampengilly** [comment]
I've had this issue appear in some early work on a new project. It's occurring when I forcibly close the app from the recent apps screen.

I'm obtaining a MediaController through the use of a Compose state producer (which AFAIK should ensure that the controller is built, and is released when the producer is removed from the composition): 

```
@Composable
fun rememberMediaController(
    context: Context = LocalContext.current,
) = produceState<MediaController?>(initialValue = null, context) {
    val token = SessionToken(context, ComponentName(context, PlaybackService::class.java))
    value = MediaController.Builder(context, token).buildAsync().await()
    awaitDispose {
        value?.release()
        value = null
    }
}.value
```

I assume that it's a case where if the app is forcibly closed, the service is shut down before the activity/UI has a chance to unload?

**Comment by sampengilly** [comment]
Another stacktrace is also showing up alongside this one, stating that the Activity has leaked the ServiceConnection, though that stacktrace seems to point more towards where the service was bound.

```
Activity [package].MainActivity has leaked ServiceConnection androidx.media3.session.MediaControllerImplBase$SessionServiceConnection@4eb76b0 that was originally bound here
android.app.ServiceConnectionLeaked: Activity [package].MainActivity has leaked ServiceConnection androidx.media3.session.MediaControllerImplBase$SessionServiceConnection@4eb76b0 that was originally bound here
  at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:2045)
  at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1917)
  at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1896)
  at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2021)
  at android.app.ContextImpl.bindService(ContextImpl.java:1951)
  at android.content.ContextWrapper.bindService(ContextWrapper.java:853)
  at androidx.media3.session.MediaControllerImplBase.requestConnectToService(MediaControllerImplBase.java:2143)
  at androidx.media3.session.MediaControllerImplBase.connect(MediaControllerImplBase.java:192)
  at androidx.media3.session.MediaController.<init>(MediaController.java:421)
  at androidx.media3.session.MediaController$Builder.buildAsync(MediaController.java:293)
  at [package].MediaControllerKt$rememberPlaybackMediaController$1.invokeSuspend(MediaController.kt:24)
```

**Comment by marcbaechinger** [comment]
Thanks for the reports. 

I'm not an expert in Compose, but are you sure that the controller is correctly released when the activity goes down. Because I would say the case you a mentioning should not happen when everything is in places.

- The controller is created in `onResume/onStart` of the activity
- The controller is release in `onPause/onStop` of the activivty
- The service is stopped in `onTaskRemoved()` of the service
- The session is release in `onDestroy()` of the service

This gives me this log statements:

```
2023-02-02 16:07:35.026 10862-10862 sess-life               androidx.media3.demo.session         D  service onCreate
2023-02-02 16:08:04.329 10862-10862 sess-life               androidx.media3.demo.session         D  onStart
2023-02-02 16:08:04.331 10862-10862 sess-life               androidx.media3.demo.session         D  onResume
2023-02-02 16:08:04.366 10862-10862 sess-life               androidx.media3.demo.session         D  controller connected
2023-02-02 16:08:16.128 10862-10862 sess-life               androidx.media3.demo.session         D  onPause
2023-02-02 16:08:16.162 10862-10862 sess-life               androidx.media3.demo.session         D  onStop
2023-02-02 16:08:16.178 10862-10862 sess-life               androidx.media3.demo.session         D  onDisconnected
2023-02-02 16:08:16.255 10862-10862 sess-life               androidx.media3.demo.session         D  onTaskRemoved
2023-02-02 16:08:16.257 10862-10862 sess-life               androidx.media3.demo.session         D  service onDestroy
```

> the Activity has leaked the ServiceConnection,

This sounds then that the activitvy didn't correctly release the controller?

The logs show that the service's `onDestry()` is called after the `onDisconnect` of the controller. The service connection is released when the controller is disconnected I think. So this seems to me a setup issue then?

Can you confirm the controller is disconnected when the activity is stopped?

**Comment by sampengilly** [comment]
I've done some breakpoint debugging and when I force quit the app the `awaitDispose` block is called resulting in `release()` getting called. I don't know at what point in the Activity lifecycle that occurs.

the `produceState` composable runs its lambda parameter in a coroutine scope that is launched when `produceState` is added to the composition, and is cancelled when `produceState` is removed from the composition. `awaitDispose` just blocks the suspending lambda from completing and waits for it to be cancelled before running.

The entire composition is wrapped up in a call to `setContent(@Composable () -> Unit)` in the MainActivity. According to docs this is roughly analogous to:
```
setContentView(
    ComposeView(this).apply {
        setContent { /* Composable content */ }
    }
)
```

So under the hood I imagine that the entire composition follows the same lifecycle as a regular Activity View. Since this occurs in `onCreate()` I imagine it's destroyed in `onDestroy()`.

I could attempt to maintain the MediaController in the activity and pass it into Compose instead, but I'm not sure that's the most ideal solution, particularly for transitional apps that are migrating slowly over to Compose which might have difficulty sharing something from the activity down to a particular composable.

**Comment by sampengilly** [comment]
I've confirmed that extracting the MediaController instance up to the Activity level and providing it to compose by containing it in a `mutableStateOf()` and passing it to the composable content works, upon force-quitting the app the media session service no longer gets destroyed and continues playing, which is more expected behaviour. The crash log also disappeared.

This begs the question though of why obtaining the MediaController in a different way caused the Service itself to be destroyed when force-quitting the activity

**Comment by naory159** [comment]
Any update with this issue?
How can we avoid this crash?

**Comment by marcbaechinger** [comment]
@naory159 Please note that [this comment](https://github.com/androidx/media/issues/239#issuecomment-1414497268) above said that refactoring the Compose setup solved the problem.

From above comments:

> under the hood I imagine that the entire composition follows the same lifecycle as a regular Activity [...]
>  [...] I don't know at what point in the Activity lifecycle that occurs.

It needs a bit of an involvement from developer side as Compose isn't taking care of your app being correct. Compose makes it easy to create a reactive UI but it still needs to be  integrated into an Android app correctly.

I'm closing this issue. If you think you have a similar issue. Please take the time to explain your problem in a bit more detail to make it actionable and post that with a new issue.
