### ISSUE TITLE
 SecurityException with ListenableFuture<MediaController>.Get()

### ISSUE THREAD

**Issue by Kayri** [androidx/media#277]
Hello, 
Currently working on a video feature supporting multiple session for a compose app. 

For our example I have 1 video who appear in a middle of a list which contain other items. 
The feature is fully working when scrolling normally.
The video isn't composed yet and when user scroll down the list, when the video appear on view, it create the component which get connected to the mediaSessionService to retrieve or Add a new session. 
If user continue to scroll down and video is out of the view, we release the component. 

The code is simple, I have a Composable containing an `AndroidView` for the player view and a `DisposableEffect` which call `MediaController.releaseFuture(controllerFuture)` when the component is unload. 
```
DisposableEffect(Unit) {
   onDispose { state.onDispose() }
}
AndroidView(
   factory = { _ -> state.view // return the view },
   update = {}
)
```

The logic is made in a VideoPlayerState: 
```
class VideoPlayerState(...) {
    private val controllerBundle: Bundle = Bundle().apply {...}
    private val controllerFuture: ListenableFuture<MediaController> = MediaController.Builder(
        context,
        SessionToken(context, ComponentName(context, ApolloMediaSessionService::class.java))
    )
        .setConnectionHints(controllerBundle)
        .buildAsync()


    // Todo crash: when scroll fast down and up.
    val controller: MediaController?
        get() = if (controllerFuture.isDone) controllerFuture.get() else null


    init {
        controllerFuture.addListener({ setController() }, MoreExecutors.directExecutor())
    }

    private fun setController() {
        val controller: MediaController = this.controller ?: return
        ....
    }

```

When a user Scroll fast to the bottom the `MediaController.releaseFuture(controllerFuture)` is called and `Future.get()` will throw a `CancellationException: "Task was cancelled"` which is the normal behaviour. 

But if a user scroll up to reload the component video I see in `AbstractFuture.Get()` that `localValue = javax.net.ssl.SSLHandshakeException: Connection closed by peer`.

I couldn't go any further in my investigation as limited knowledge on Future. But I understand the issue is coming from `MediaSessionService` who reject the connection. 

````
FATAL EXCEPTION: main
Process: android.AbcApplication, PID: 5170
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
Caused by: java.util.concurrent.ExecutionException: java.lang.SecurityException: Session rejected the connection request.
    at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
    at au.net.abc.apollo.media3.VideoPlayerState.getController(TeaserVideoPlayer.kt:257)
    at au.net.abc.apollo.media3.VideoPlayerState.setController(TeaserVideoPlayer.kt:293)
    at au.net.abc.apollo.media3.VideoPlayerState._init_$lambda$1(TeaserVideoPlayer.kt:288)
    at au.net.abc.apollo.media3.VideoPlayerState.$r8$lambda$j26VTzzHmtGX48tuw1ld6HqiIsc(Unknown Source:0)
    at au.net.abc.apollo.media3.VideoPlayerState$$ExternalSyntheticLambda0.run(Unknown Source:2)
    at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
    at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
    at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
    at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
    at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67)
    at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57)
    at androidx.media3.session.MediaController.release(MediaController.java:512)
    at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda63.run(Unknown Source:2)
    at androidx.media3.common.util.Util.postOrRun(Util.java:607)
    at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1837)
    at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:94)
    at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda3.run(Unknown Source:0)
    at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$11(MediaControllerStub.java:301)
    at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda11.run(Unknown Source:4)
    at androidx.media3.common.util.Util.postOrRun(Util.java:607)
    at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:293)
    at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:92)
    at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0$androidx-media3-session-MediaSessionService$MediaSessionServiceStub(MediaSessionService.java:712)
    at androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(Unknown Source:14)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
Caused by: java.lang.SecurityException: Session rejected the connection request.
    at androidx.media3.session.MediaControllerHolder.maybeSetException(MediaControllerHolder.java:67) 
    at androidx.media3.session.MediaControllerHolder.onRejected(MediaControllerHolder.java:57) 
    at androidx.media3.session.MediaController.release(MediaController.java:512) 
    at androidx.media3.session.MediaControllerImplBase$$ExternalSyntheticLambda63.run(Unknown Source:2) 
    at androidx.media3.common.util.Util.postOrRun(Util.java:607) 
    at androidx.media3.session.MediaController.runOnApplicationLooper(MediaController.java:1837) 
    at androidx.media3.session.MediaControllerStub.lambda$onDisconnected$1(MediaControllerStub.java:94) 
    at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda3.run(Unknown Source:0) 
    at androidx.media3.session.MediaControllerStub.lambda$dispatchControllerTaskOnHandler$11(MediaControllerStub.java:301) 
    at androidx.media3.session.MediaControllerStub$$ExternalSyntheticLambda11.run(Unknown Source:4) 
    at androidx.media3.common.util.Util.postOrRun(Util.java:607) 
    at androidx.media3.session.MediaControllerStub.dispatchControllerTaskOnHandler(MediaControllerStub.java:293) 
    at androidx.media3.session.MediaControllerStub.onDisconnected(MediaControllerStub.java:92) 
    at androidx.media3.session.MediaSessionService$MediaSessionServiceStub.lambda$connect$0$androidx-media3-session-MediaSessionService$MediaSessionServiceStub(MediaSessionService.java:712) 
    at androidx.media3.session.MediaSessionService$MediaSessionServiceStub$$ExternalSyntheticLambda0.run(Unknown Source:14) 
    at android.os.Handler.handleCallback(Handler.java:942) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loopOnce(Looper.java:201) 
    at android.os.Looper.loop(Looper.java:288) 
    at android.app.ActivityThread.main(ActivityThread.java:7872) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
````

My question is, If I had to understand why the connection is rejected on service side, where should I look? 

Thank you

**Comment by marcbaechinger** [comment]
It looks to me like as if you would release the controller before it actually has connected. Can you confimr this could be the case?

You can verify this by not calling release before `buildAsync` has completed for a given controller.

I think the code snippet you included doesn't show how you release, but the logic when you release can probably take care of the fact, that the controller potentially isn't yet connected when your code runs in the context of a recycler view. 

What I can think of would work is that you put the controller that you build in an async way in a list like `pendingControllers` and then when the controller has actually arrived in `setController` remove it from that list. Then if you release, you should wait with releasing before a given controller is not in the `pendingController` list anymore. If it is still there you need a way to defer releasing until it is actually connected, then release.

You may find better ways to do the above than my suggestion, but I think its clear what I mean.

You could also measure how fast the user is scrolling and at a given speed, stop creating controllers I think. Because you are wasting resources which makes you app not faster that way. 

Can you verify if this helps. If this is the root cause you can fix this quickly. We should probably also think about how we can avoid this from the library side but in general you should wait until the controller is returned by `buildAsync` before actually start using them. 

Can you verify whether this helps?

**Comment by Kayri** [comment]
Thank you for your quick reply. 

Yes I thought that could have been another way to solve that issue. I change the code for test purposes to have something like: 

```
init{
    Futures.addCallback(controllerFuture, object : FutureCallback<MediaController>{
            override fun onSuccess(result: MediaController?) {
                Log.d("MEDIA DEBUG", "Init Success")
                controller = result
                setController()
            }

            override fun onFailure(t: Throwable) {
                Log.d("MEDIA DEBUG", "Init FAIL: ${t.message}")
            }

        },MoreExecutors.directExecutor())
}

fun onDispose() {
        Futures.addCallback(controllerFuture, object : FutureCallback<MediaController>{
            override fun onSuccess(result: MediaController?) {
                Log.d("MEDIA DEBUG", "Release Success")
                MediaController.releaseFuture(controllerFuture)
            }

            override fun onFailure(t: Throwable) {
                Log.d("MEDIA DEBUG", " Release FAIL: ${t.message}")
            }

        },MoreExecutors.directExecutor())
}
```

So there is no crash anymore because I catch the `Throwable` but I keep getting the same error `java.lang.SecurityException: Session rejected the connection request.` and that's because the Init Callback and the Release Callback get Success at the same time. 
My `setController()` contain different things like `addMediaItem` which can take time.  Therefore a solution would be to also wait the service being completed before releasing the `controllerFuture`. But that seems not very efficient. 

If only I could understand how the connection is working on service side I should be able to see why it reject the connection.

**Comment by Kayri** [comment]
UPDATE: 

For reminder, _currently pushing media 3 in a compose environment. I'm having a java.lang.SecurityException: Session rejected the connection request.
The app has a feed where you scroll and the goal is to have playable videos sometimes (LazyColumn).
I have MediaController.releaseFuture(controllerFuture) inside a DisposableEffect when the item disappear..
When the controller future is not done, it cancels the future.
The issue was when I try reconnecting to the session, the controller gets rejected._

I was able to determine where the issue was coming from: 
`MediaSession get()` -> `Throws: IllegalStateException – if a MediaSession with the same ID already exists in the package.`
A session is saved inside `HashMap SESSION_ID_TO_SESSION_MAP` to look at if ID is unique.
Therefore, if we cancel the future and the service has had time to build the `MediaSession` without passing `addSession`, the ID will be saved internally but will not appear in the list of `sessions`


Not sure if we should report it as a bug. I'm still looking at how I can avoid or rewrite it even if the item has the same ID.

**Comment by marcbaechinger** [comment]
Short answer: I recommend to create the session instance in `YourService.onCreate` and release is in `YourService.release()`. 

Long answer:

> Throws: IllegalStateException – if a MediaSession with the same ID already exists in the package.

If the error message is `Session ID must be unique. ID=` and this is the reason for the problem, I think you can fix this because the library never creates a session, it's the app that creates the session. The app needs to make sure to never create more than one instance with the same session ID. This is not related to controller or service it just when a session with the same ID is created before another instance with the same ID is not yet released. When creation of session and releasing the same happens is the responsibility of the app.

> A session is saved inside HashMap SESSION_ID_TO_SESSION_MAP to look at if ID is unique.

Correct. That's happening in the constructor of the `MediaSession`. It's your service implementation that creates this session. Given I understand correctly and you only want one session instance to live at the same time, I recommend creating this session in `YourService.onCreate()` once. Create it in `onCreate`, return always the very same instance in `onGetSession(controller)` and finally release it in `onDestroy()` of your service. 

If you ever only create a single instance of the session with a given ID you never receive `IllegalStateException – Session ID must be unique. ID=`.

Generally, the life-cycle of the session has nothing to do with a controller being connected to it or not.

> Therefore, if we cancel the future and the service has had time to build the MediaSession without passing
> addSession, the ID will be saved internally but will not appear in the list of sessions

I'm not sure I understand what you mean with this I'm afraid.

When the controller bind to the service, the service interface binder sent from the session to the controller. When received, the controller calls `connect()` and send the `IMediaController` to the session with which the session can talk back to the controller. Here in [`connect`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L653) the service calls your `MyService.onGetSession()` and adds the session to the list of sessions maintained by the service.

When looking into connect, I don't see that the session ever would not be put into the list of the services:

When [inspecting this code](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L689-L737), I can't see how calling `controller.release` to early would not result into putting the service into the list of sessions maintained by the service. Even if that would happen, if your service creates only a single session instance then even if this would be the case, the result wouldn't be a `Session ID must be unique. ID=`.

**Comment by Kayri** [comment]
My apologies, I should have give you more details I suppose. I'm using the service to support multiple session. 
Therefore the flow for the service is: 
```
- onGetSession() -> { 
controllerInfo.connectionHints contain a sessionID 
Check if sessions list contain session with this ID ( if yes return session) 
if not, create new mediaSession. MediaSession.Builder(..)... .setId(sessionID).. .build()
return it. 
```

If a user scroll fast enough the `controllerFuture.cancel()` is called instead of `controller.release()`. It's when cancel is called something happen somewhere that avoid the saving of the session. 

I agree with what you're saying, I followed the flow in Debug and I can see `sessions.put()` is being called and I can see my sessions when `isSessionAdded` is being called. 
What I found was that `onDestroy()` is also being called at the end of it. Which I guess is the one responsible to remove the sessions list. (I have looked at `removeSession` or `release` but couldn't see how the sessions were remove/released)

So when `controllerFuture.get()` again, `onGetSession` is called and inside `sessions` list is empty. Something here dump the sessions list, but don't dump the `SESSION_ID_TO_SESSION_MAP` hash-map. 

I hope this issue is clearer.

**Comment by guibirk** [comment]
> Can you try if this helps?

I forgot `stopSelf()` inside `onTaskRemoved `. After adding, as you mentioned,  the issue was fixed. I originally thought the service would stop after `onTaskRemoved`, but I was wrong.

Thanks!

**Comment by toasterofbread** [comment]
This issue was solved in my case by using `context.applicationContext` instead of using `context` directly when creating the MediaController.

https://stackoverflow.com/a/8317874/13979722

**Comment by BejanCorneliu** [comment]
Hello. Regarding original post i have "Session rejected the connection request." crash

In my code in mController.addListener(...) i use some customCommand.
On some phones, inside listener probably mController.get() is not ready
From demo code i notice the line :  val controller = this.controller ?: return

In my code i do not make this check because I supposed mController.get() ( inside addListener will be ready to go)

My question is : 
If i put this check line i will get off this crash but what will happend with the user? A new call will be made on that listener when it will be ready ?

Thanks

**Comment by daniello-fillthegapp** [comment]
@marcbaechinger Hi, I'm having the same problem with:
`override fun onDestroy() {
        mediaSession?.run {
            release()
            player.release()
            mediaSession = null
        }
        super.onDestroy()
    }

    override fun onTaskRemoved(rootIntent: Intent?) {
        mediaSession?.run {
            release()
            if (!player.playWhenReady) {
                player.release()
            }
            stopSelf()
        }
    }`
    
    I tried your solution but cannot find method used here: "mediaLibrarySession.isRelease()"
