### ISSUE TITLE
[Exoplayer] DownloadHelper.createMediaSource not supporting MP4 file

### ISSUE THREAD

**Issue by yoobi** [androidx/media#289]
### Media3 Version

ExoPlayer 2.18.4

### Devices that reproduce the issue

Pixel 6

### Reproducible in the demo app?

No

### Reproduction steps

You can find my module here https://github.com/yoobi/exoplayer-kotlin/tree/master/downloadvideo

1. Download the MP4 file (latest one in the list)
2. Click on the floating button once download is complete
3. Click on the downloaded video
4. Get the error in logs

This issue only appears when trying to play downloaded MP4 video, if you download an M3U8 video and then do the same steps above it does play.
To create the mediaSource of the downloaded video I use:
`DownloadHelper.createMediaSource(downloadRequest, DownloadUtil.getReadOnlyDataSourceFactory(this))` which I thought was the standard way of playing downloaded video.

### Expected result

Downloaded video to play.

### Actual result

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors () could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

### Media

https://storage.googleapis.com/exoplayer-test-media-0/BigBuckBunny_320x180.mp4

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by yoobi** [comment]
Any updates ?
