### ISSUE TITLE
AAC audio playback artifacts

### ISSUE THREAD

**Issue by personshelldon** [androidx/media#311]
### Media3 Version

ExoPlayer 2.18.5

### Devices that reproduce the issue

OnePlus 10 Pro - Android 13
OnePlus 8T - Android 13
MAG425 - Android 9
MAG500 - Android 10
Android Emulator - API 23-33
Android TV Emulator - API 23-33

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Download the video from the attachment below 
2. Play 01.ts in ExoPlayer Demo App
3. The audio is playing incorrectly

### Expected result

The AAC audio from the TS container is playing correctly

### Actual result

The AAC audio from the TS container is playing jerky and with artifacts. 
In the logcat there are errors in a loop:
```
023-04-10 21:56:26.338  2725-32206 C2SoftAacDec            media.swcodec                        W  AAC decoder returned error 0x4004, substituting silence
2023-04-10 21:56:26.339  2725-32206 C2SoftAacDec            media.swcodec                        W  aacDecoder_DecodeFrame decoderErr = 0x4004
2023-04-10 21:56:26.339  2725-32206 C2SoftAacDec            media.swcodec                        W  AAC decoder returned error 0x4004, substituting silence
2023-04-10 21:56:26.350  2725-32206 C2SoftAacDec            media.swcodec                        W  aacDecoder_DecodeFrame decoderErr = 0x4004
2023-04-10 21:56:26.350  2725-32206 C2SoftAacDec            media.swcodec                        W  AAC decoder returned error 0x4004, substituting silence
2023-04-10 21:56:26.361 18146-32200 MediaCodecAudioRenderer com.google.android.exoplayer2.demo   E  Audio sink error
                                                                                                      com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 1000001279997, got 1000001066664
                                                                                                          at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:999)
                                                                                                          at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:706)
                                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1881)
                                                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:774)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                          at android.os.Looper.loop(Looper.java:351)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Media

Download link: https://drive.google.com/file/d/1ZWJJgTtble4CG16wQzlwjqCc_H7oP_cI/view?usp=share_link

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @andrewlewis,

Sorry for the delay! Could you please add a sample media again if you are still seeing this issue? I saw the notice "Sorry, the file you have requested does not exist" when I opened the current link.

Thanks in advance!
