### ISSUE TITLE
onPlayerError not being called after getting SocketTimeout 

### ISSUE THREAD

**Issue by javaboboApp** [androidx/media#361]
### Media3 Version

ExoPlayer 2.18.4

### Devices that reproduce the issue

I have used an emulator to reproduce issue.

### Reproducible in the demo app?

Yes

### Reproduction steps

Description:

When there is an error (SocketTimeout) Using even logger I can see that onLoadError is called but onPlayerError is not called at all.

Step to reproduce issue:

Open playback and observer that playback is working
Using Charles proxy create a rule to force a timeout error
Observe that EventLogger is reporting the timeout but onPlayerError callback function is not being called.

Exoplayer version: 2.18.4
Using drm license: yes
Protocl use: DASH
Content: Live

### Expected result

onPlayerError should be called

### Actual result

onPlayerError is not called after getting SocketTimeoutExeotion. 

### Media

Not applicable

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @javaboboApp,

Thank you for sharing the bug report. 

Quoting from Javadoc:
[onLoadError](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/analytics/AnalyticsListener.java#L812-L827) : `Called when a media source loading error occurred. This method being called does not indicate that playback has failed, or that it will fail.`
[onPlayerError](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/analytics/AnalyticsListener.java#L714-L722): `Called when a fatal player error occurred.`

So `onLoadError` getting triggered should not necessarily mean `onPlayerError` will be triggered. We retry loading the media source a few times before triggering a player error. The [default](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/upstream/DefaultLoadErrorHandlingPolicy.java#L36) behaviour is to retry it 3 times before triggering a player error.  You can customise this behaviour by defining a custom [`LoadErrorHandlingPolicy`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/upstream/LoadErrorHandlingPolicy.java).

Coming back to the issue, the bug report shared only logs the `loadError` once, so it might be possible that it was able to load media source in its second attempt. My question to you is: Does the playback stop when you get `onLoadError` or it continues to play the media? If not, I think this is working as expected.

**Comment by javaboboApp** [comment]
Hi I have done several test and when I block the cdn we get retries and after a fatal error but when I reduce dramatically backwithd we get a lot of retries but never a fatal error: 

So we get this error many times: 

```
internalError [eventTime=10.04, mediaPos=13.31, window=0, loadError
                                                                                                      com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:382)
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:262)
                                                                                                          at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
                                                                                                          at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
                                                                                                          at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
                                                                                                          at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                      Caused by: java.net.SocketTimeoutException: timeout
                                                                                                          at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
                                                                                                          at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
                                                                                                          at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                                                          at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
                                                                                                          at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
                                                                                                          at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
                                                                                                          at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
                                                                                                          at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
                                                                                                          at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
                                                                                                          at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
                                                                                                          at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
                                                                                                          at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
                                                                                                          at com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.getResponseCode(HttpsURLConnectionExtension.java:249)
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:378)
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:262) 
                                                                                                          at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
                                                                                                          at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99) 
                                                                                                          at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62) 
                                                                                                          at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174) 
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                          at java.lang.Thread.run(Thread.java:1012) 
                                                                                                      Caused by: java.net.SocketException: Socket closed
                                                                                                          at java.net.SocketInputStream.read(SocketInputStream.java:188)
                                                                                                          at java.net.SocketInputStream.read(SocketInputStream.java:143)
                                                                                                          at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
                                                                                                          at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
                                                                                                          at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
                                                                                                          at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
                                                                                                          at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
                                                                                                          at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
                                                                                                          at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307) 
                                                                                                          at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301) 
                                                                                                          at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197) 
                                                                                                          at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188) 
                                                                                                          at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129) 
                                                                                                          at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750) 
                                                                                                          at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622) 
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475) 
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411) 
                                                                                                          at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542) 
                                                                                                          at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106) 
                                                                                                          at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30) 
                                                                                                          at com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.getResponseCode(HttpsURLConnectionExtension.java:249) 
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:378) 
                                                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:262) 
                                                                                                          at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
                                                                                                          at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99) 
                                                                                                          at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62) 
                                                                                                          at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174) 
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                          at java.lang.Thread.run(Thread.java:1012) 
                                                                                                    ]


```
I send you bug report. I have tried with differents cnd .. always got same behavier. 

[bugreport-sdk_google_atv64_amati_arm64-TRB2.220506.002-2023-04-28-00-13-18.zip](https://github.com/androidx/media/files/11406925/bugreport-sdk_google_atv64_amati_arm64-TRB2.220506.002-2023-04-28-00-13-18.zip)

**Comment by javaboboApp** [comment]
@rohitjoins  any update on it?

**Comment by javaboboApp** [comment]
> Hi @javaboboApp,
> 
> Thank you for sharing the bug report.
> 
> Quoting from Javadoc: [onLoadError](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/analytics/AnalyticsListener.java#L812-L827) : `Called when a media source loading error occurred. This method being called does not indicate that playback has failed, or that it will fail.` [onPlayerError](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/analytics/AnalyticsListener.java#L714-L722): `Called when a fatal player error occurred.`
> 
> So `onLoadError` getting triggered should not necessarily mean `onPlayerError` will be triggered. We retry loading the media source a few times before triggering a player error. The [default](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/upstream/DefaultLoadErrorHandlingPolicy.java#L36) behaviour is to retry it 3 times before triggering a player error. You can customise this behaviour by defining a custom [`LoadErrorHandlingPolicy`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/upstream/LoadErrorHandlingPolicy.java).
> 
> Coming back to the issue, the bug report shared only logs the `loadError` once, so it might be possible that it was able to load media source in its second attempt. My question to you is: Does the playback stop when you get `onLoadError` or it continues to play the media? If not, I think this is working as expected.

**Comment by javaboboApp** [comment]
> Hi @javaboboApp,
> 
> Thank you for sharing the bug report.
> 
> Quoting from Javadoc: [onLoadError](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/analytics/AnalyticsListener.java#L812-L827) : `Called when a media source loading error occurred. This method being called does not indicate that playback has failed, or that it will fail.` [onPlayerError](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/analytics/AnalyticsListener.java#L714-L722): `Called when a fatal player error occurred.`
> 
> So `onLoadError` getting triggered should not necessarily mean `onPlayerError` will be triggered. We retry loading the media source a few times before triggering a player error. The [default](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/upstream/DefaultLoadErrorHandlingPolicy.java#L36) behaviour is to retry it 3 times before triggering a player error. You can customise this behaviour by defining a custom [`LoadErrorHandlingPolicy`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/upstream/LoadErrorHandlingPolicy.java).
> 
> Coming back to the issue, the bug report shared only logs the `loadError` once, so it might be possible that it was able to load media source in its second attempt. My question to you is: Does the playback stop when you get `onLoadError` or it continues to play the media? If not, I think this is working as expected.


@rohitjoins any update on it?

**Comment by icbaker** [comment]
Hey @javaboboApp, please can you host some media on a server that behaves in the way you're describing here, so that we're able to reproduce the problem you're seeing by playing a URL you provide? That way we can be sure we're looking at exactly the same situation you are (rather than us trying to set up a proxy like Charles in exactly the same way you've got, which honestly we don't really have the time to do).
