### ISSUE TITLE
 ActivityThread.generateForegroundServiceDidNotStartInTimeException on Android 13

### ISSUE THREAD

**Issue by VolodymyrYeletskyi** [androidx/media#393]
### Media3 Version

Media3 1.0.0-rc02

### Devices that reproduce the issue

- Samsung running Android 13(99% of crashes happens with Samsung running Android 13;
- Pixel 7 Pro running Android 13;
- Pixel 6 running Android 13;
-  Oppo A74 5G running Android 13

### Devices that do not reproduce the issue

All devices running Android 12 and below

### Reproducible in the demo app?

Not tested

### Reproduction steps

Some of our users get this exception randomly when use our app. This is very strange because users can get this crash even if they close player activity. We use MediaSessionService and after user closes player activity we call stopService methos inside onDestroy() in our activity:

override fun onDestroy() {
        stopService(Intent(this, MoviePlayerService::class.java))
        super.onDestroy()
}
After user exits player activity sometimes app could crash with ActivityThread.generateForegroundServiceDidNotStartInTimeException, which is strange because our service is already stopped. This crash happens only on devices running Android 13(mainly on Samsung). So my question is: is it a bug with Media3, or problems with several devices, or we just incorrectly stop MediaSessionService? Crash happens randomly and we don't know concrete steps to reproduce it.

### Expected result

App shouldn't crash and media should work successfully

### Actual result

After closing player screen users could get the crash in random moment

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @VolodymyrYeletskyi,

Before the `stopService(Intent(this, MoviePlayerService::class.java))` is called upon the player activity is being destroyed, is it possible that your service is bounded to some clients by `bindService()` already? In this case, `stopService()` or `stopSelf()` doesn't actually stop the service until all of the clients unbind. Please reference to https://developer.android.com/guide/components/services#Lifecycle. 

In terms of `ForegroundServiceDidNotStartInTimeException`, this error indicates that [Context.startForegroundService()](https://developer.android.com/reference/android/content/Context#startForegroundService(android.content.Intent)) was called but [Service.startForeground()](https://developer.android.com/reference/android/app/Service#startForeground(int,%20android.app.Notification)) was not called soon enough ([in 5 seconds](https://developer.android.com/guide/components/services#StartingAService)). But currently I don't have a concrete idea on where this can happen in your app, would it be possible for you to share the code of your app?

**Comment by cuongdq88** [comment]
Hello. 
I have same problem. Please help me check where and why.

Here code my service. [https://github.com/cuongdq88/cuongdq88.github.io/blob/master/PlaybackService.kt](url)

Here ANR and Crash in my app.
<img width="993" alt="Screen Shot 2023-05-17 at 07 18 21" src="https://github.com/androidx/media/assets/1912918/60681fcc-81a4-49aa-bcaf-9890487fdb12">

Thanks & Best Regards.

**Comment by VolodymyrYeletskyi** [comment]
Hi @tianyif,
We release our media controller inside onStop() method before we call stopService(Intent(this, MoviePlayerService::class.java)), so there isn't any connected controllers

**Comment by tianyif** [comment]
Also, I'm wondering if your app is using a `androidx.media.session.MediaButtonReceiver`? Because if your app is using a `MediaButtonReceiver`, when the user presses on the physical playback button (eg. the button on the BT headset), the `MediaButtonReceiver` will [start your service](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:media/media/src/main/java/androidx/media/session/MediaButtonReceiver.java;l=120?q=file:androidx%2Fmedia%2Fsession%2FMediaButtonReceiver.java%20class:androidx.media.session.MediaButtonReceiver) and then sends an Intent with action `android.intent.action.MEDIA_BUTTON`. Then if your service is not started in foreground soon enough, then the exception can be thrown. In the default case, the service will be started in the foreground when the player is in the playing state. So in other words, if the `MediaButtonReceiver` receives the event and starts the service, and if the playback doesn't play immediately, `ForegroundServiceDidNotStartInTimeException` is very likely to happen.

**Comment by cuongdq88** [comment]
https://github.com/androidx/media/assets/1912918/3a31102a-ead9-420a-9eaf-de60ddeb27d2

Hello. I tried on your demo & I found bug. I tried add simple code links #167 but only hand PAUSE_PLAY button. If I input key event like NEXT, PREVIOUS will crash. I tried hand NEXT, PREVIOUS but not success app still crash.

Please watch video. (Emulator run API 33).

**Comment by tianyif** [comment]
@cuongdq88 Yes, the snippet in https://github.com/androidx/media/issues/167#issuecomment-1500241226 is just an example on how to workaround with `onStartCommand()` with PAUSE and PLAY buttons. However, I agree with what my colleague said [here](https://github.com/androidx/media/issues/167#issuecomment-1500569001) that we should be careful with selecting other events than play. Do you see in the real case that the system delivers key events other than PLAY when the service is inactivated? If yes, could you please upload a bug report of it?

**Comment by cuongdq88** [comment]
Hello Tianyif. Below is code my service and report bug from user when i added code #167 . In report bug it do not show key event code. I do not know why I still receive bugs.

<img width="995" alt="Screen Shot 2023-05-18 at 18 28 31" src="https://github.com/androidx/media/assets/1912918/1bb13861-1c12-4932-a256-952b48720aa0">
<img width="1012" alt="Screen Shot 2023-05-18 at 18 29 10" src="https://github.com/androidx/media/assets/1912918/76123175-c546-4661-8aa6-49a0191a1609">
<img width="921" alt="Screen Shot 2023-05-18 at 18 29 33" src="https://github.com/androidx/media/assets/1912918/58c92e50-0dc8-4abb-bb8b-4718cb97cbeb">
<img width="921" alt="Screen Shot 2023-05-18 at 18 29 48" src="https://github.com/androidx/media/assets/1912918/439f5515-6004-4953-9dd9-6ba556d3a863">

Here my service.
[https://github.com/cuongdq88/cuongdq88.github.io/blob/master/PlaybackService.kt](url)

Thanks & Regards.

**Comment by tianyif** [comment]
@cuongdq88 could you please file a new issue and send your whole bug report produced by `adb bugreport` to [dev.exoplayer@gmail.com](mailto:dev.exoplayer@gmail.com) for the new issue?

**Comment by VolodymyrYeletskyi** [comment]
Hello @tianyif,
No, we don't use MediaButtonReceiver, we just set AudioAttributes when create ExoPlayer instance

**Comment by vitaliygerasymchuk** [comment]
@tianyif in my case onGetSession is called 2 times and after that the crash happens. Is this related?

**Comment by pmatsinopoulos** [comment]
> In terms of `ForegroundServiceDidNotStartInTimeException`, this error indicates that [Context.startForegroundService()](https://developer.android.com/reference/android/content/Context#startForegroundService(android.content.Intent)) was called but [Service.startForeground()](https://developer.android.com/reference/android/app/Service#startForeground(int,%20android.app.Notification)) was not called soon enough ([in 5 seconds](https://developer.android.com/guide/components/services#StartingAService)). But currently I don't have a concrete idea on where this can happen in your app, would it be possible for you to share the code of your app?

Hello @tianyif 

In our case the Activity does not call the method `Context.startForegroundService()` because we interact with the Foreground Service via a `MediaBrowser` like this:

```
val browserFuture = MediaBrowser.Builder(
            context,
            SessionToken(context, ComponentName(context, MyMediaLibraryService::class.java))
        ).buildAsync()
        browserFuture.addListener(
            {
                mediaBrowser = browserFuture.get()
                mediaBrowser?.let { md ->
                     playerListener = MyPlayerListener()
                     md.addListener(playerListener)
                }
            },
            MoreExecutors.directExecutor()
        )
```
Also, inside the `MyMediaLibraryService` we never call `Service.startForeground()` because this was not required / documented in the Media3 documentation [here](https://developer.android.com/guide/topics/media/session/mediasessionservice). Also, the demo implementation app [here](https://github.com/androidx/media/blob/release/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt) does not call the `startForeground()`. 
Also, in the same demo application the `PlaybackActivity` does not call `Context.startForegroundService()` [here](https://github.com/androidx/media/blob/release/demos/session/src/main/java/androidx/media3/demo/session/PlayerActivity.kt).

We still get the error, mostly on Samsung phones, Android 13.

```
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d28f17d u0 com.mixlr.android/.playback.MixlrMusicSessionService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067
```

**Comment by kelmer44** [comment]
I am able to consistently repro this using my Google Pixel 2XL device (Android 11) with the demo-session sample app with the following steps:

1. Launch app with a bluetooth device connected
2. Play any audio, Jazz album for instance
3. pause audio
4. force stop app
5. hit play on the bluetooth device

We consistently get:

```
FATAL EXCEPTION: main
                                                                      Process: androidx.media3.demo.session, PID: 19236
                                                                      android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{30029e7 u0 androidx.media3.demo.session/.PlaybackService}
                                                                      	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
                                                                      	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                      	at android.os.Looper.loop(Looper.java:223)
                                                                      	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                      	at java.lang.reflect.Method.invoke(Native Method)
                                                                      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
