### ISSUE TITLE
[Android ExoPlayer] Live Streams Buffering a lot issue

### ISSUE THREAD

**Issue by ajayhack** [androidx/media#427]
### Media3 Version

ExoPlayer 2.18.5

### Devices that reproduce the issue

Issue Reproduce on:-
1.Samsung Galaxy F62 (Android Version 12)

### Reproducible in the demo app?

Yes

### Reproduction steps

Reproduction Stream is mailed to : dev.exoplayer@gmail.com
Need to play above stream and you can observe in exoplayer that it's buffering a lot , we checked with other HLS Live streams and work fine without buffering smoothly working.

### Expected result

ExoPlayer should not show lot of buffering when playing HLS Live Stream. 

### Actual result

ExoPlayer is showing a lot of buffering when playing HLS Live Stream:- https://178475.gvideo.io/cmaf/178475_695019/master.m3u8

### Media

Reproduction Stream is mailed to : dev.exoplayer@gmail.com
and also mailed bug logs report.
We also see some exception error logs ss attached:-
<img width="1341" alt="Screenshot 2023-05-30 at 5 09 01 PM" src="https://github.com/androidx/media/assets/25945277/84daa945-fb3f-4567-ab30-69ac2b3c1dbf">

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by ajayhack** [comment]
@icbaker Can you play stream for more time atleast 10-15 minutes to observe buffering STATE , because it sometimes happen on quickly and sometimes happend after 10-15 minutes of stream play.

**Comment by ajayhack** [comment]
@icbaker , I can see you are checking this on Media 3 Library but we are currently on ExoPlayer Version 2.18.5 , we haven't migrated to Media 3 yet , Can you confirm it might be the chance that this issue is in ExoPlayer Version 2.18.5 and not in Media 3?.

**Comment by icbaker** [comment]
> Can you confirm it might be the chance that this issue is in ExoPlayer Version 2.18.5 and not in Media 3?

In the screenshot you posted in the original comment I can see you're using the media3 demo app (since it has the package `androidx.media3.demo.main`) - so it looks like you've already reproduced the problem in media3? Hence it's not an exoplayer2-specific issue.

Both media3 and exoplayer2 have the same underlying code (we just rename all the symbols when publishing to this GitHub repo), so the logic is identical - it's **very** unlikely that an issue like this would only manifest in exoplayer2 and not media3.

**Comment by ajayhack** [comment]
@icbaker Can we have any solution for this as buffering is  replicable always on our end it's just sometimes it replicable within 5 minutes and sometimes 10-15 minutes of video playback.

**Comment by VIkash2601** [comment]
> I played the example stream for about 2 minutes and didn't notice any rebuffering, playback seemed to work fine.
> 
> I did see some 404s in logcat, which suggest that maybe some chunks are not actually available on the server when the player requests them? This shouldn't happen in a correctly configured HLS stream.
> 
> ```
> internalError [eventTime=82.15, mediaPos=25.03, window=0, period=0, loadError
>   androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 404
>       at androidx.media3.datasource.cronet.CronetDataSource.open(CronetDataSource.java:628)
>       at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272)
>       at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:798)
>       at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:611)
>       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
>       at androidx.media3.exoplayer.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:495)
>       at androidx.media3.exoplayer.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:468)
>       at androidx.media3.exoplayer.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
>       at androidx.media3.exoplayer.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
>       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
>       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
>       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
>       at java.lang.Thread.run(Thread.java:1012)
> ]
> ```
> 
> I didn't see any `Unexpected audio track timestamp discontinuity` errors in logcat, but these are generally due to problems with the media.
> 
> In summary: I wasn't able to reproduce a problem, but the two problematic pieces of logcat (discontinuities, and 404s) both point to issues with the media and how it's being served rather than issues with ExoPlayer.
> 
> I will leave this issue open for a couple of weeks, but this doesn't look like an ExoPlayer problem.

![image](https://github.com/androidx/media/assets/38423769/facb7630-d6e3-41d4-97b0-fa35c79a0602)


@icbaker Sometimes I see 404, 412, and 416 for the same video File. I'm using media3 and while playing the video from cache I see the buffering/discontinuity while rendering the video.

**Comment by ajayhack** [comment]
@VIkash2601 , We have tried this Same Stream on other Player(THEOPlayer) and there it's working fine without any buffering issue even if we played it for 30 minutes straight and not buffering issue at all but on ExoPlayer if we play for 15-20 minutes straight we are observing buffering issue.

**Comment by VIkash2601** [comment]
@ajayhack Thanks for your reply. Can You help me with it how can I use THEOPlayer in my Android app and What changes do I need to make in my Existing Androix.media3.exoplayer to work it as since last couple of days I'm scratching my head to resolve this.

**Comment by icbaker** [comment]
Closing due to inactivity
