### ISSUE TITLE
ERROR_CODE_AUDIO_TRACK_WRITE_FAILED when turning off bluetooth headset during playback

### ISSUE THREAD

**Issue by jdtremblay** [androidx/media#431]
### Media3 Version

ExoPlayer `dev-v2` branch

### Devices that reproduce the issue

[vip7802](https://www.commscope.com/product-type/broadband-video-devices/video-devices/set-tops/video-devices-for-android-tv/vip7802/) running on Android 11

### Devices that do not reproduce the issue

Nvidia Shield on Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

1. In the Demo App, enable Tunneling. You can replace the current PlayerActivity.java with this one.  [PlayerActivity.zip](https://github.com/androidx/media/files/11625683/PlayerActivity.zip)
2. Pair a Bluetooth headset on the device and ensure the device audio output in the headset
3. Build and install the demo app with Tunneling enabled
4. Start the Windevine DASH (MP4,H264) HD (cenc) video
5. The playback and audio output should start in the Bluetooth headset.
6. During the playback, turn off the Bluetooth headset.

ref: https://partnerissuetracker.corp.google.com/u/3/issues/190643538

### Expected result

The audio should output on the TV

### Actual result

The error "Playback failed" is displayed.

stacktrace:

```
playerFailed [eventTime=8.95, mediaPos=6.25, window=0, period=0, errorCode=ERROR_CODE_AUDIO_TRACK_WRITE_FAILED
  com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(0, null, null, audio/mp4a-latm, mp4a.40.2, 134359, en, [-1, -1, -1.0, null], [2, 44100]), format_supported=YES
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:593)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:223)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
      at com.google.android.exoplayer2.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:1146)
      at com.google.android.exoplayer2.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:1038)
      at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:960)
      at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:758)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1928)
      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:804)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1039)
      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:514)
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:223) 
      at android.os.HandlerThread.run(HandlerThread.java:67) 
      Suppressed: com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
          ... 11 more
]
```

### Media

Windevine DASH (MP4,H264) HD (cenc) in the demo App.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by jdtremblay** [comment]
I'm on d7f4fea0b9d1be3f5d0211dc50b0f1fbaec05564

**Comment by jdtremblay** [comment]
I'm on https://github.com/google/ExoPlayer/commit/d7f4fea0b9d1be3f5d0211dc50b0f1fbaec05564

**Comment by tianyif** [comment]
Hi @jdtremblay,

Thanks for reporting! Looks like this is due to the `AudioTrack` throws an [`ERROR_DEAD_OBJECT`](https://developer.android.com/reference/android/media/AudioTrack#ERROR_DEAD_OBJECT) during the `AudioTrack.write()`:

```
06-01 08:56:10.429 10074  9722  9863 E MediaCodecAudioRenderer:   com.google.android.exoplayer2.audio.AudioSink$WriteException: AudioTrack write failed: -6
```
When the tunneling is turned on, the `AudioTrack` is set the flag `AUDIO_OUTPUT_FLAG_HW_AV_SYNC`, and further because of this flag, it is forced the flag [`AUDIO_OUTPUT_FLAG_DIRECT`](https://android.googlesource.com/platform/frameworks/av/+/master/media/libaudioclient/AudioTrack.cpp#502). When the bluetooth headset is disconnected, the platform invalidates the `AudioTrack`, but since it has a forced `AUDIO_OUTPUT_FLAG_DIRECT` (even though it plays PCM on bluetooth headset originally), the `AudioTrack` [won't be restored](https://android.googlesource.com/platform/frameworks/av/+/master/media/libaudioclient/AudioTrack.cpp#2825) by the platform, and `ERROR_DEAD_OBJECT` is thrown.

Per instructed by the [document](https://developer.android.com/reference/android/media/AudioTrack#ERROR_DEAD_OBJECT), `AudioTrack` needs to be recreated when `ERROR_DEAD_OBJECT` is out. In `DefaultAudioSink`, we do have [a recovery mechanism](https://github.com/google/ExoPlayer/blob/dev-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/DefaultAudioSink.java#L1144) for `ERROR_DEAD_OBJECT` to recreate `AudioTrack`, but it looks like just under the situation when the encoded stream is played originally (non PCM). So in this case, the error won't be handled onto that recovery path.

Let me check with my team if there is a previous intention that we don't do the error handling for this case, or we need to add it. I'll get back to you with the answer.

**Comment by tianyif** [comment]
We will be working on a fix for this.

**Comment by lyswhut** [comment]
any news?
