### ISSUE TITLE
UnsatisfiedLinkError Permission denied fatal crash while accessing libCronet.so

### ISSUE THREAD

**Issue by Amud** [androidx/media#447]
### Media3 Version

ExoPlayer 2.16.1

### Devices that reproduce the issue

Redmi 10 Redmi 10 prime, Redmi Note 9 Pro, Xiaomi 11 Lite NE:

### Reproducible in the demo app?

No

### Reproduction steps

My live streaming SDK, which uses Http3 via CronetDataSource for HLS streaming, works with most clients, but one client's APK raises a security exception when Cronet tries to access play services. I suspect this may be due to the client's security settings during APK creation. However, without access to the APK codebase, I'm limited in addressing this issue.

Reproduce steps : 
1. Create an instance of CronetEngine using CronetEngine.Builder
   with CronetEngine.Builder.enableQUIC(true)
2. Send a request

### Expected result

no crash

### Actual result

native crash 

### Media

Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/0000006f/CronetDynamite.apk!/lib/arm64-v8a/libcronet.111.0.5563.55.so" segment 1: Permission denied
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at org.chromium.net.impl.CronetLibraryLoader.a(:com.google.android.gms.dynamite_cronetdynamite@231656044@23.16.56 (190400-0):4)
       at org.chromium.net.impl.CronetUrlRequestContext.<init>(:com.google.android.gms.dynamite_cronetdynamite@231656044@23.16.56 (190400-0):8)
       at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(:com.google.android.gms.dynamite_cronetdynamite@231656044@23.16.56 (190400-0):2)
       at org.chromium.net.CronetEngine$Builder.build(CronetEngine.java:313)
       at HlsLiveModule.provideCronetEngine(HlsLiveModule.kt:40)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @Amud,

Could you please check if native Cronet binaries are bundled into your app?  Also, we have a util method `CronetUtil.buildCronetEngine` which will [catch the `UnsatisfiedLinkError`](https://github.com/google/ExoPlayer/blob/r2.16.1/extensions/cronet/src/main/java/com/google/android/exoplayer2/ext/cronet/CronetUtil.java#L108) and avoid the crash.

Hope this answer can help!
