### ISSUE TITLE
Duplicate MediaSession

### ISSUE THREAD

**Issue by TheBeastLT** [androidx/media#451]
After migrating to `media3` from `ExoPlayer` and new `MediaSession` api, we've started getting some rare crash reports on duplicate media sessions:

```
Fatal Exception: java.lang.IllegalStateException: Session ID must be unique. ID=.MySession
       at androidx.media3.session.MediaSession.<init>(MediaSession.java:553)
       at androidx.media3.session.MediaSession$Builder.build(MediaSession.java:360)
```

Session is correctly cleaned up on fragment stop/destroy lifecycles, but I guess there can be conditions where you're not able to release it (due to some timeout or fragment crash) and the reference to it escapes your scope. So I think it would be convenient to have some static method to retrieve a `MediaSession` by it's `id`, or have some flag in the builder to force release previous session if it exists?

**Comment by oceanjules** [comment]
I think we actually have a map you are talking about here:

https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L235

...which is how the uniqueness is checked in the first place, although it's private.


Could you provide a bit more information about how you initialise and release your session? Have you compared your implementation to what we have in: https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/demos/session/src/main/java/androidx/media3/demo/session/PlaybackService.kt#L85-L89

**Comment by marcbaechinger** [comment]
Yeah, I also think we need a bit more information about how you create/release sessions.

> Session is correctly cleaned up on fragment stop/destroy lifecycles,

Are you using a session without a service in your UI or are you connecting a `MediaController`/`MediaBrowser` to a service? 

> where you're not able to release it (due to some timeout or fragment crash) and the reference to it escapes your scope. 

I think you'd find a way to handle such cases. If the app crashes, fine, then the process will go away and you don't have much of a chance other then fixing the root problem that crashed the app. But I'm not sure I understand what you mean with `the fragment crashes`. Because if the app is still alive you should be able to detect this and gracefully release the session.

However, please shed some light on how you initialize and release your session and add some more details what you intent to do. Specifically if you want to create and destroy your session in accordance to the life-cycle of a fragment or another UI components I'd be interested to hear what your use case is.

Perhaps, we can give you some guidance in how to do that best, or we find that there is a use case that we currently don't support well.

**Comment by TheBeastLT** [comment]
This happens on some rarer cases for which we see crash reports, but it's not very clear on the conditions how it happens.
This is how we init and destroy the session:
```kotlin
...
    override fun onStart() {
        super.onStart()
        createMediaSession()
    }

    override fun onStop() {
        player?.stop()
        super.onStop()
        releaseMediaSession()
    }

    override fun onDestroy() {
        super.onDestroy()
        releasePlayer()
    }
...
    private fun createMediaSession() {
        mediaSession = MediaSession.Builder(requireContext(), player)
            .setId(MEDIA_SESSION_TAG)
            .build()
    }

    private fun releasePlayer() {
        releaseMediaSession()
        playerTransportGlue?.host = null
        playerTransportGlue = null
        playerAdapter = null
        player?.release()
        player = null
    }

    private fun releaseMediaSession() {
        mediaSession?.release()
        mediaSession = null
    }
```

**Comment by achampagne-ensemble** [comment]
I am also running into this issue, how I handle creating and releasing the mediaSession is similar to @TheBeastLT's code.  I can repro if I close the video player activity and quickly try to re-open the activity.  My guess is that there is some kind of race condition where the activity is destroyed before the mediaSession is released, and re-starting the activity stops the mediaSession from being released before it's re-created.  It would be nice if there was a static method that allows developers to find all active mediaSessions, so we could prevent re-creating one that is not yet released.

**Comment by RKaySilverorange** [comment]
Just wanted to note that our team is experience an issue with this as well. Couple key points:
- We create and manage the MediaSession via a Foreground Service, not an Activity
- We never have multiple sessions running by design (only ever one set of Media Items get played at a time), so this is either a bug in our code or within media 3 which causes more than one session to be created per Service instance (or perhaps bind/unbind is going on, discussed later)
- Our Service, as well as our MediaController (which is not an Activity either) are within a Singleton scoped Dagger component
- We do have Android Auto available as another Controller, but we never unbind the initial MediaController during playback

The crash affects about 2% of our userbase and only ever happens when the app is in background state. 

Given that we create the MediaSession within a Singleton scoped foreground Android `Service`, I suspect the situation is that the MediaController gets GCed in rare situations but the Service does not. From research, that sounds like the only case where we could expect a single instance of a Service to call onCreate more than once (which is where we create the MediaSession). Apparently if everything unbinds from a service then something rebinds that might re-trigger the lifecycle methods in question. If anyone is aware of other cases let me know. 

We were not previously calling mediaSession.release() in that Service's `onDestroy()` as it wasn't apparent we might need to do that. However, after digging into the source code, I noted that this function specifically removes the ID and MediaSession object from the HashMap which ultimately is used to check for duplicates:
```
  public final void release() {
    try {
      synchronized (STATIC_LOCK) {
        SESSION_ID_TO_SESSION_MAP.remove(impl.getId());
      }
      impl.release();
    } catch (Exception e) {
      // Should not be here.
    }
  }
```

At the moment our only option is to roll out a new release with this added and hope that it fixes these rare crashes. If it they do go to 0, I will report back if I remember.

**Comment by jfisher-naim** [comment]
We're also seeing this, it's pulling our crash-free rate below 98%. We have a MediaLibraryService used by Android Auto, we don't create any instances ourselves and the implementation just follows the guide (so the note added to the docs about duplicate media IDs isn't relevant, see: https://github.com/androidx/media/issues/1115). 

Android Auto use isn't needed to force the crash. Play audio in-app via a MediaSessionService, stop, when the app has been in the background for 30+ minutes and the user brings it to the foreground and tries to play media in-app again via a MediaSessionService and we get this exception.
