### ISSUE TITLE
IllegalStateException when setting shuffle with custom order before adding media items. 

### ISSUE THREAD

**Issue by tzugen** [androidx/media#480]
### Media3 Version

Media3 1.0.2

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Yes

### Reproduction steps

```
fun crash (val shuffle: Boolean) {
            val list = IntArray(0) { 0 }
            val seed = System.currentTimeMillis()
            exo.shuffleModeEnabled = true
            exo.setShuffleOrder(ShuffleOrder.DefaultShuffleOrder(list, seed))
            exo.addMediaItems(insertAt, mediaItems)
 }
```

### Expected result

No crash

### Actual result

```
FATAL EXCEPTION: main
                                                                      Process: org.moire.ultrasonic.debug, PID: 15276
                                                                      java.lang.IllegalStateException
                                                                      	at androidx.media3.exoplayer.ExoPlayerImpl.evaluateMediaItemTransitionReason(ExoPlayerImpl.java:2165)
                                                                      	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1890)
                                                                      	at androidx.media3.exoplayer.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1856)
                                                                      	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$1$androidx-media3-exoplayer-ExoPlayerImpl(ExoPlayerImpl.java:324)
                                                                      	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda27.run(Unknown Source:4)
                                                                      	at android.os.Handler.handleCallback(Handler.java:942)
                                                                      	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      	at android.os.Looper.loopOnce(Looper.java:201)
                                                                      	at android.os.Looper.loop(Looper.java:288)
                                                                      	at android.app.ActivityThread.main(ActivityThread.java:7937)
                                                                      	at java.lang.reflect.Method.invoke(Native Method)
                                                                      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

### Media

All

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tianyif** [comment]
Hi @tzugen,

I used your reproducing code, and I got a different exception:
```
                 Process: androidx.media3.demo.main, PID: 13147
                 java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                 	at androidx.media3.exoplayer.PlaylistTimeline.getTimelineByChildIndex(PlaylistTimeline.java:88)
                 	at androidx.media3.exoplayer.AbstractConcatenatedTimeline.getFirstWindowIndex(AbstractConcatenatedTimeline.java:185)
                 	at androidx.media3.common.Timeline.equals(Timeline.java:1338)
                 	at androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1888)
                 	at androidx.media3.exoplayer.ExoPlayerImpl.setShuffleOrder(ExoPlayerImpl.java:745)
                 	at androidx.media3.demo.main.PlayerActivity.initializePlayer(PlayerActivity.java:298)
```

I'm not sure how you got the exception on `evaluateMediaItemTransitionReason`, but in fact, the `ShuffleOrder` must have the same number of elements as the current playlist. So you need to add the `MediaItem`s first and then set the shuffle order. 

We will also add a fail-fast check and improve the documentation for this issue. Thanks for the reporting!
