### ISSUE TITLE
The Media3 part of the app Xtra for Twitch crashes with bluetooth connected

### ISSUE THREAD

**Issue by thinkpad4** [androidx/media#489]
### Media3 Version

ExoPlayer 2.18.0

### Devices that reproduce the issue

Samsung J3(2016)  Android 6.0.1

### Reproducible in the demo app?

Not tested

### Reproduction steps

Loading the app Xtra for Twitch it crashes when loading a stream with Bluetooth connected

### Expected result

To work with bluetooth connected

### Actual result

```
[06-20 19:17:56.221 24903:24903 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.github.andreyasadchy.xtra.debug, PID: 24903
java.lang.IllegalStateException: onLoadChildren sent null list for id androidx.media3.session.MediaLibraryService
at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:473)
at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:469)
at android.service.media.MediaBrowserService$Result.sendResult(MediaBrowserService.java:131)
at androidx.media.MediaBrowserServiceCompat$ResultWrapper.sendResult(MediaBrowserServiceCompat.java:1279)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:418)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:406)
at androidx.media.MediaBrowserServiceCompat$Result.sendResult(MediaBrowserServiceCompat.java:860)
at androidx.media3.session.MediaSessionServiceLegacyStub.onLoadChildren(MediaSessionServiceLegacyStub.java:93)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onLoadChildren(MediaBrowserServiceCompat.java:427)
at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onLoadChildren(MediaBrowserServiceCompat.java:518)
at android.service.media.MediaBrowserService.performLoadChildren(MediaBrowserService.java:495)
at android.service.media.MediaBrowserService.addSubscription(MediaBrowserService.java:459)
at android.service.media.MediaBrowserService.access$400(MediaBrowserService.java:68)
at android.service.media.MediaBrowserService$ServiceBinder$3.run(MediaBrowserService.java:247)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7230)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

### Media

Use the Xtra for Twitch app on Android 6.0.1 and have bluetooth connect and try to watch a stream, you have to be logged into twitch through the app first.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by thinkpad4** [comment]
Any update?

**Comment by marcbaechinger** [comment]
Please try again after this commit: https://github.com/androidx/media/commit/17ee5277d5daf3285e10f5a9bffd1ca027ae51aa

If this does not help, please contact the Xtra for Twitch app developers directly. It would require their support to investigate some further. Happy to assist them when they contact us.

**Comment by threema-maurus** [comment]
Same problem with the Threema app when playing voice messages on a Samsung J5 (2016) SM-J5108.

@marcbaechinger feel free to contact me if you need more information.

```
java.lang.IllegalStateException: onLoadChildren sent null list for id androidx.media3.session.MediaLibraryService
	at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:473)
	at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:469)
	at android.service.media.MediaBrowserService$Result.sendResult(MediaBrowserService.java:131)
	at androidx.media.MediaBrowserServiceCompat$ResultWrapper.sendResult(MediaBrowserServiceCompat.java:1279)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:418)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:406)
	at androidx.media.MediaBrowserServiceCompat$Result.sendResult(MediaBrowserServiceCompat.java:860)
	at androidx.media3.session.MediaSessionServiceLegacyStub.e(MediaSessionServiceLegacyStub.java)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onLoadChildren(MediaBrowserServiceCompat.java:427)
	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onLoadChildren(MediaBrowserServiceCompat.java:518)
	at android.service.media.MediaBrowserService.performLoadChildren(MediaBrowserService.java:495)
	at android.service.media.MediaBrowserService.addSubscription(MediaBrowserService.java:459)
	at android.service.media.MediaBrowserService.access$400(MediaBrowserService.java:68)
	at android.service.media.MediaBrowserService$ServiceBinder$3.run(MediaBrowserService.java:247)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7410)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by crackededed** [comment]
apparently sending empty list instead of null here fixes the issue:
https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/session/src/main/java/androidx/media3/session/MediaSessionServiceLegacyStub.java#L92-L94

found from this post:
https://stackoverflow.com/a/52322357

**Comment by nicholas-signal** [comment]
We are also experiencing this in the Signal application on Android 6 devices:

```
java.lang.IllegalStateException: onLoadChildren sent null list for id androidx.media3.session.MediaLibraryService
 	at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:473)
 	at android.service.media.MediaBrowserService$3.onResultSent(MediaBrowserService.java:469)
 	at android.service.media.MediaBrowserService$Result.sendResult(MediaBrowserService.java:131)
 	at androidx.media.MediaBrowserServiceCompat$ResultWrapper.sendResult(MediaBrowserServiceCompat.java:1279)
 	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:418)
 	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$2.onResultSent(MediaBrowserServiceCompat.java:406)
 	at androidx.media.MediaBrowserServiceCompat$Result.sendResult(MediaBrowserServiceCompat.java:860)
 	at androidx.media3.session.MediaSessionServiceLegacyStub.onLoadChildren(MediaSessionServiceLegacyStub.java:93)
 	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onLoadChildren(MediaBrowserServiceCompat.java:427)
 	at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onLoadChildren(MediaBrowserServiceCompat.java:518)
 	at android.service.media.MediaBrowserService.performLoadChildren(MediaBrowserService.java:495)
 	at android.service.media.MediaBrowserService.addSubscription(MediaBrowserService.java:459)
 	at android.service.media.MediaBrowserService.access$400(MediaBrowserService.java:68)
 	at android.service.media.MediaBrowserService$ServiceBinder$3.run(MediaBrowserService.java:247)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:158)
 	at android.app.ActivityThread.main(ActivityThread.java:7224)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
 ```
 
 Similar to @threema-maurus, the entire stacktrace is within the android.* and androidx.* namespaces.
 
 Feel free to reach out to me if you need any further information, and you can browse our usage of `androidx.media3` in this and adjacent files: https://github.com/signalapp/Signal-Android/blob/v6.35.5/app/src/main/java/org/thoughtcrime/securesms/components/voice/VoiceNotePlaybackService.java

**Comment by icbaker** [comment]
I had a look into this. The code pointed to above in https://github.com/androidx/media/issues/489#issuecomment-1722214046 is within the contract of `MediaBrowserServiceCompat.onLoadChildren` which says:
> When the given parentId is invalid, implementations must call `result.sendResult` with `null`, which will invoke `onError`.

This null value is also permitted by the current documented contract of the framework [`MediaBrowserService`](https://developer.android.com/reference/android/service/media/MediaBrowserService#onLoadChildren(java.lang.String,%20android.service.media.MediaBrowserService.Result%3Cjava.util.List%3Candroid.media.browse.MediaBrowser.MediaItem%3E%3E,%20android.os.Bundle)).

Both the current versions of `androidx.media` and the framework handle this null value and transform it into a call to `onError` as documented:
* AndroidX does it on the controller/browser side: 
   * In [`androidx.media.MediaBrowserCompat.MediaBrowser.MediaBrowserImplBase`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:media/media/src/main/java/android/support/v4/media/MediaBrowserCompat.java;l=1456;drc=187e9a2088c3f281cfb617b9bedd94b9a3546d8b) ([used](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:media/media/src/main/java/android/support/v4/media/MediaBrowserCompat.java;l=214;drc=187e9a2088c3f281cfb617b9bedd94b9a3546d8b) on API 14 to 20)
   * Also, equivalently, in [`androidx.media.MediaBrowserCompat.MediaBrowser.MediaBrowserImplApi21`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:media/media/src/main/java/android/support/v4/media/MediaBrowserCompat.java;l=1996;drc=187e9a2088c3f281cfb617b9bedd94b9a3546d8b) ([used](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:media/media/src/main/java/android/support/v4/media/MediaBrowserCompat.java;l=212;drc=187e9a2088c3f281cfb617b9bedd94b9a3546d8b) on API 21 and 22)
* In the framework also on the controller side in [`MediaBrowser`](https://source.corp.google.com/h/googleplex-android/platform/superproject/main/+/main:frameworks/base/media/java/android/media/browse/MediaBrowser.java;l=679;drc=6128432078ca50bda7c543f0e22ae40e6a7273dd).

The mention of Android 6 (Marshmallow, API 23) above made me dig back into previous versions of the framework session code. I found the exception message and a clear cause of the exception in [`MediaBrowserService`](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/marshmallow-release/media/java/android/service/media/MediaBrowserService.java#473).

It looks like this was always a bug, because even on Marshmallow [null was documented as permitted](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/marshmallow-release/media/java/android/service/media/MediaBrowserService.java#341).

It seems the same bug is present on Lollipop (API 21) too (which is the first release to contain the framework `MediaBrowserService`):
* [`onLoadChildren` docs](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/lollipop-release/media/java/android/service/media/MediaBrowserService.java#315)
* [Null check](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/lollipop-release/media/java/android/service/media/MediaBrowserService.java#410)

The problematic null check was [removed before the Nougat release](https://android.googlesource.com/platform/frameworks/base/+/2189f58ec5a4fa35b7e06d9d28abcef5d67f9c7f). With [further changes made](https://android.googlesource.com/platform/frameworks/base/+/64f16f1dc1a6bdc1e16c7017a057da1620fac88b) to introduce the `onError` calling behaviour.

I think the optimum way to resolve this (given we can't change the framework code running on old Android devices) is modify the behavior of `androidx.media.MediaBrowserServiceCompat` to avoid passing null on OS versions with this bug. I'm not yet sure what value we should pass instead.

**Comment by icbaker** [comment]
This should be resolved by http://r.android.com/2794937 - once that's submitted we will ensure it's included in a future `androidx.media` release, then bump media3's dependencies to transitively pull in the fix (though [apps will be able to bump their `androidx.media` dependency](https://docs.gradle.org/current/userguide/dependency_constraints.html) before media3 releases a new version with this bumped dependency).

**Comment by nicholas-signal** [comment]
@icbaker thank you for the quick response! I must admit I'm not entirely up to speed on the branching structure; can we expect it in the very next `androidx.media` release (patch version?) or will it be held back for a minor (or major) release?

**Comment by icbaker** [comment]
The plan is to include this fix in`androidx.media` 1.7.0, which will go to `beta01`on 1st November.
