### ISSUE TITLE
Playback resumption not triggered with `KEY_EVENT_PLAY_PAUSE`

### ISSUE THREAD

**Issue by marcbaechinger** [androidx/media#493]
### Media3 Version

Media3 1.1.0-alpha01

### Devices that reproduce the issue

Devices on which playback resumption results in a `KEY_EVENT_PLAY_PAUSE` (or devices with a BT device that sends this?).

### Reproducible in the demo app?

Yes

### Reproduction steps

Enable playback resumption, start playback and terminate the app.

Then trigger playback resumption that results in a `KEY_EVENT_PLAY_PAUSE`. 

### Expected result

Playback resumption is triggered (`Callback.onPlaybackResumption()`).

### Actual result

Only player.prepare/play is called instead

See stack trace screenshot in [27](https://github.com/androidx/media/issues/27#issuecomment-1614938728)

### Media

All media

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by WSteverink** [comment]
Hi there @marcbaechinger! 

Is this still an issue?

I am trying to fix a bug for MediaResumption that occurs on some devices. 
My problem occurs in the following scenario :

1. Play something
2. Pause it
3. Swipe app away from recents.
4. See a dead/stale notification that does not trigger `onPlaybackResumption`


Thanks to some other comments/issues i found out that our Service seems to restart due to a crash.
I managed to fix that with the latest version `1.4.0-rc01` that contains:

`pauseAllPlayersAndStopSelf()`

My `MediaLibraryService` does this now:

```kotlin
    override fun onTaskRemoved(rootIntent: Intent?) {
        super.onTaskRemoved(rootIntent)
        logDebug("onTaskRemoved()")

        pauseAllPlayersAndStopSelf()
        cleanUp()
    }

    override fun onDestroy() {
        super.onDestroy()
        logDebug("onDestroy()")
        cleanUp()
    }

```

Now that i use the new function `pauseAllPlayerAndStopSelf` the service does not seem to restart due to a crash anymore.
I do still have a stale notification though and i see this happening in the logs:

```
 E  Remote failure in play.
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:584)
                                                                                                    	at android.media.session.ISessionCallback$Stub$Proxy.onPlay(ISessionCallback.java:729)
                                                                                                    	at com.android.server.media.MediaSessionRecord$SessionCb.play(MediaSessionRecord.java:1408)
                                                                                                    	at com.android.server.media.MediaSessionRecord$ControllerStub.play(MediaSessionRecord.java:1743)
                                                                                                    	at android.media.session.ISessionController$Stub.onTransact(ISessionController.java:523)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1339)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1275)

```

I found this issue while doing some digging, so i am just wondering if this is the same problem. Thanks in advance!

**Comment by WSteverink** [comment]
After i did some extra digging i decided to create an [issue](https://github.com/androidx/media/issues/1557) for the above.

**Comment by WSteverink** [comment]
Any news on this one?

**Comment by marcbaechinger** [comment]
Do you have a BT device that still repos this problem?

From what I know and the source code I'd say this has been fixed but not closed here. Please let me know if you can repro this with a BT device and what devices this is.

EVENT_PLAY_PAUSE is IMO handled correctly

- in [`MediaButtonReceiver.receive`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaButtonReceiver.java#L126)
- in [`MediaSessionService.onStartCommand()` ](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L440)to where the MBR from above fires an `Intent`
- and eventually in [`MediaSessionImpl.applyMediaButtonEvent`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionImpl.java#L1271) where the key event is resolved to an actual player call 'play()` or 'pause()`

If you can repro this please let me know. Else I'm going to close this. I'm aware there is  #1557, which is something else than this issue. I don't have news for that other issue right now I'm afraid. There are a bunch of similar issues also related to OS bugs, that I need to sort out. Will updated when there.

Sorry for not having a better answer.

**Comment by WSteverink** [comment]
> I'm aware there is #1557, which is something else than this issue

Ah sorry, i was somehow convinced both issues where related. Good to hear that 1557 is on the radar, i was a bit afraid it got lost out of sight. Thanks for the response 👍
