### ISSUE TITLE
How do I use setVideoEffects?

### ISSUE THREAD

**Issue by hyoromo** [androidx/media#510]
I am the person who previously told you how to flip the screen left and right.
https://github.com/androidx/media/issues/285

I tried using setVideoEffects as you taught us in media3 v1.1.0, but the video itself does not play.

I am using it in front of player.prepare() , am I using it wrong?
Errors that occur when videos do not play are as follows.

```
E/EventLogger: playerFailed [eventTime=2.15, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_VIDEO_FRAME_PROCESSING_FAILED
      androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1440, 1080, 59.93995, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: androidx.media3.common.VideoFrameProcessingException: java.lang.IllegalArgumentException: width -1 must be positive
        at androidx.media3.effect.VideoFrameProcessingTaskExecutor.handleException(VideoFrameProcessingTaskExecutor.java:200)
        at androidx.media3.effect.VideoFrameProcessingTaskExecutor.lambda$wrapTaskAndSubmitToExecutorService$2$androidx-media3-effect-VideoFrameProcessingTaskExecutor(VideoFrameProcessingTaskExecutor.java:186)
        at androidx.media3.effect.VideoFrameProcessingTaskExecutor$$ExternalSyntheticLambda2.run(Unknown Source:6)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalArgumentException: width -1 must be positive
        at androidx.media3.common.util.Assertions.checkArgument(Assertions.java:55)
        at androidx.media3.effect.Presentation.createForWidthAndHeight(Presentation.java:153)
        at androidx.media3.effect.FinalShaderProgramWrapper.createDefaultShaderProgram(FinalShaderProgramWrapper.java:488)
        at androidx.media3.effect.FinalShaderProgramWrapper.ensureConfigured(FinalShaderProgramWrapper.java:467)
        at androidx.media3.effect.FinalShaderProgramWrapper.renderFrame(FinalShaderProgramWrapper.java:320)
        at androidx.media3.effect.FinalShaderProgramWrapper.renderOutputFrame(FinalShaderProgramWrapper.java:275)
        at androidx.media3.effect.DefaultVideoFrameProcessor.lambda$renderOutputFrame$2$androidx-media3-effect-DefaultVideoFrameProcessor(DefaultVideoFrameProcessor.java:472)
        at androidx.media3.effect.DefaultVideoFrameProcessor$$ExternalSyntheticLambda3.run(Unknown Source:4)
        at androidx.media3.effect.VideoFrameProcessingTaskExecutor.lambda$wrapTaskAndSubmitToExecutorService$2$androidx-media3-effect-VideoFrameProcessingTaskExecutor(VideoFrameProcessingTaskExecutor.java:182)
        at androidx.media3.effect.VideoFrameProcessingTaskExecutor$$ExternalSyntheticLambda2.run(Unknown Source:6) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

I have one more question.
Is it possible to flip the video left and right after prepare?
I would like to add a left-right flip button to the video player so that I can switch between left and right while the video is playing.

That is all. I would be happy to receive your answer.

**Comment by andrewlewis** [comment]
@claincly Please take a look. Thanks.

**Comment by hyoromo** [comment]
@claincly 
The code before and after the Effects is written as follows: If setVideoEffects is not present, the video plays without problems.

```
ExoPlayer.Builder playerBuilder = new ExoPlayer.Builder(this);
		
RenderersFactory renderersFactory = DemoUtil.buildRenderersFactory(this, false);
playerBuilder.setRenderersFactory(renderersFactory);

ExoPlayer player = playerBuilder.build();
player.addListener(new PlayerEventListener());
player.addAnalyticsListener(new EventLogger());
player.setAudioAttributes(AudioAttributes.DEFAULT, true);
player.setPlayWhenReady(false);

_videoPlayer.setBackgroundColor(ContextCompat.getColor(this, R.color.player_background)); // SurfaceView _videoPlayer

player.setRepeatMode(Player.REPEAT_MODE_ONE);
_videoController.setPlayer(_player); // PlayerControlView _videoController
        
player.setVideoEffects(ImmutableList.of((MatrixTransformation) presentationTimeUs -> {
    android.graphics.Matrix transformationMatrix = new android.graphics.Matrix();
    transformationMatrix.postScale(/* sx= */ -1, /* sy= */ 1);
    return transformationMatrix;
}));

MediaItem mediaItem = MediaItem.fromUri(videoUri);
player.setMediaItem(mediaItem, _playRangeStart);
player.prepare();
```

> No not at the moment, but we are working on this! Sorry I wouldn't be able to give you an ETA just yet.

That is the feature I want. I look forward to seeing it implemented.

**Comment by claincly** [comment]
What type of view do you use in `PlayerControllerView`? We currently supports only `SurfaceView` and `SurfaceHolder`, but the code otherwise looks good.

**Comment by hyoromo** [comment]
Sorry, the problem was that I was using [ZoomSurfaceView](https://github.com/natario1/ZoomLayout) instead of SurfaceView.

The reason for using ZoomSurfaceView is that we wanted to zoom in and out and move the video after it was loaded.
Are there any plans to allow "zooming in/out" and "moving" even after the video has been loaded?

**Comment by claincly** [comment]
The `MatrixTransformation` interface allows you define a transformation matrix based on timestamps. You can reference  `ScaleAndRotateTransformation.java`, specifically lines 

```
public Matrix getMatrix(long presentationTimeUs) {
    return checkStateNotNull(adjustedTransformationMatrix, "configure must be called first");
}
```

If you have further questions to using the `MatrixTransformations`, please open another issue as it's out of scope of this one. I'll close this issue for now.
