### ISSUE TITLE
Dual video player issue with AC3 

### ISSUE THREAD

**Issue by techker** [androidx/media#533]
Hey, we have an app for TV that has an epg guide that in that guide we have a preview player and in the background have the current channel still streaming.

The issue is when we hit a channel that has AC3 Audio, when the preview starts we get an error status -20 error when initializing Audio track.
createTrack returned -38...
But in our case we do not want audio in the preview..

is there a way to avoid this error?

Error:

androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(tracks-a1, null, null, audio/ac3, ac-3, 384000, en, [-1, -1, -1.0, null], [6, 48000]), format_supported=YES
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                          at android.os.Looper.loop(Looper.java:214)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.exoplayer.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 24000) Format(tracks-a1, null, null, audio/ac3, ac-3, 384000, en, [-1, -1, -1.0, null], [6, 48000])
                                                                                                          at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2109)
                                                                                                          at androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1019)
                                                                                                          at androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:997)
                                                                                                          at androidx.media3.exoplayer.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:789)
                                                                                                          at androidx.media3.exoplayer.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:875)
                                                                                                          at androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:712)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1940)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:816)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                                                          at android.os.Looper.loop(Looper.java:214) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                          Suppressed: androidx.media3.exoplayer.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 252, 24000) Format(tracks-a1, null, null, audio/ac3, ac-3, 384000, en, [-1, -1, -1.0, null], [6, 48000])
                                                                                                              ... 13 more
                                                                                                          Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
                                                                                                              at android.media.AudioTrack$Builder.build(AudioTrack.java:1018)
                                                                                                              at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2158)
                                                                                                              at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2136)
                                                                                                              at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2101)

-------------------------

**Comment by techker** [comment]
i have seen in some case to disable passthrough?

**Comment by icbaker** [comment]
> But in our case we do not want audio in the preview..

You can disable the audio in a couple of different ways:
1. Construct `ExoPlayer` with a custom `RenderersFactory` that doesn't instantiate an audio `Renderer`. The easiest way to do this while keeping everything else the same is probably to subclass `DefaultRenderersFactory` and override [`buildAudioRenderers`](https://developer.android.com/reference/androidx/media3/exoplayer/DefaultRenderersFactory#buildAudioRenderers(android.content.Context,int,androidx.media3.exoplayer.mediacodec.MediaCodecSelector,boolean,androidx.media3.exoplayer.audio.AudioSink,android.os.Handler,androidx.media3.exoplayer.audio.AudioRendererEventListener,java.util.ArrayList%3Candroidx.media3.exoplayer.Renderer%3E)) to be a no-op. See an example of customising the `RenderersFactory` here: https://developer.android.com/guide/topics/media/exoplayer/customization#enabling-asynchronous-buffer-queueing
2. Disable the `AudioRenderer` using track selection: https://developer.android.com/guide/topics/media/exoplayer/track-selection#disabling_track_types_or_groups   

(1) should definitely prevent a `AudioTrack` from being created. I'm less sure about (2) - but I think it will also work.

**Comment by techker** [comment]
cool, il take a look, cause seems like the first player trigger the error.
playerFailed [0.96] : androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(tracks-a1, null, null, audio/ac3, ac-3, 384000, fr, [-1, -1, -1.0, null], [6, 48000]), format_supported=YES

**Comment by techker** [comment]
Ok got that part working 
 mPlayer!!.trackSelectionParameters =
                    mPlayer!!.trackSelectionParameters
                        .buildUpon()
                        .setTrackTypeDisabled(C.TRACK_TYPE_AUDIO, /* disabled= */ true)
                        .build()
But when we click on the channel for Full view player the audio is muted. Is there a way to enable it without reseting the player?

**Comment by icbaker** [comment]
> But when we click on the channel for Full view player the audio is muted. Is there a way to enable it without reseting the player?

You should be able to change the track selection parameters again, but with `.setTrackTypeDisabled(C.TRACK_TYPE_AUDIO, /* disabled= */ false)` to re-enable the audio track - does that work?

**Comment by techker** [comment]
i need to re init the player do?since it is already muted..

**Comment by icbaker** [comment]
I'm not sure what you mean by 're init the player'. You can change track selection parameters during playback. I just tried this in the demo app (inside `PlayerActivity.initializePlayer`) and it enables & disables audio throughout playback:

```java
Handler handler = new Handler();
Runnable r =
    new Runnable() {
      boolean audioEnabled = false;

      @Override
      public void run() {
        player.setTrackSelectionParameters(
            player
                .getTrackSelectionParameters()
                .buildUpon()
                .setTrackTypeDisabled(C.TRACK_TYPE_AUDIO, audioEnabled)
                .build());
        audioEnabled = !audioEnabled;
        handler.postDelayed(this, 2000L);
      }
    };
handler.postDelayed(r, 2000L);
```

**Comment by techker** [comment]
ok great, i was thinking you need to re initialize the player to apply the parameters.il give it a go.

can you do that for bitrate also or that requires a re initialization?

**Comment by icbaker** [comment]
Any changes to `TrackSelectionParameters` can be made during playback. 

Given your problem statement of playing the video in a small window, you may not want to directly constrain bitrate but instead inform the track selector of the viewport size and let it pick tracks based on that (but ofc that's up to you): https://developer.android.com/reference/androidx/media3/common/TrackSelectionParameters.Builder#setViewportSize(int,int,boolean)

**Comment by techker** [comment]
perfect thx for the help!👍
