### ISSUE TITLE
.rmvb not supported ?

### ISSUE THREAD

**Issue by litianjun05090** [androidx/media#552]
### Version

Media3 1.1.0

### More version details

I know .rmvb is an outdated container but there are still great demands about it. Can you illustrate how to implement it ? 

### Devices that reproduce the issue

Huawei P40 ++ Android 10
Oneplus Ace pro Android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

Open a local .rmvb video 

### Expected result

Play successfully

### Actual result

2023-07-29 15:10:21.575 19876-19876 EventLogger             com.ltj.myplayer                     D  surfaceSize [eventTime=0.00, mediaPos=0.00, window=0, 0, 0]
2023-07-29 15:10:21.578 19876-19876 EventLogger             com.ltj.myplayer                     D  timeline [eventTime=0.00, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
2023-07-29 15:10:21.578 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.578 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.578 19876-19876 EventLogger             com.ltj.myplayer                     D  ]
2023-07-29 15:10:21.578 19876-19876 EventLogger             com.ltj.myplayer                     D  mediaItem [eventTime=0.00, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
2023-07-29 15:10:21.579 19876-19876 EventLogger             com.ltj.myplayer                     D  timeline [eventTime=0.00, mediaPos=0.00, window=0, periodCount=2, windowCount=2, reason=PLAYLIST_CHANGED
2023-07-29 15:10:21.579 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.579 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.579 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.579 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.579 19876-19876 EventLogger             com.ltj.myplayer                     D  ]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D  timeline [eventTime=0.00, mediaPos=0.00, window=0, periodCount=3, windowCount=3, reason=PLAYLIST_CHANGED
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D  ]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D  positionDiscontinuity [eventTime=0.01, mediaPos=0.00, window=1, reason=SEEK, PositionInfo:old [mediaItem=0, period=0, pos=0], PositionInfo:new [mediaItem=1, period=1, pos=0]]
2023-07-29 15:10:21.580 19876-19876 EventLogger             com.ltj.myplayer                     D  mediaItem [eventTime=0.01, mediaPos=0.00, window=1, reason=SEEK]
2023-07-29 15:10:21.594 19876-19876 EventLogger             com.ltj.myplayer                     D  state [eventTime=0.02, mediaPos=0.00, window=1, BUFFERING]
2023-07-29 15:10:21.595 19876-19876 EventLogger             com.ltj.myplayer                     D  playWhenReady [eventTime=0.02, mediaPos=0.00, window=1, true, USER_REQUEST]
2023-07-29 15:10:21.604 19876-19876 InputEventReceiver      com.ltj.myplayer                     D  Input log is disabled
2023-07-29 15:10:21.605 19876-19876 VRI[VideoFilesActivity] com.ltj.myplayer                     D  onFocusEvent false
2023-07-29 15:10:21.605 19876-19876 VRI[VideoFilesActivity] com.ltj.myplayer                     D  send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8416 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
2023-07-29 15:10:21.637 19876-19876 EventLogger             com.ltj.myplayer                     D  surfaceSize [eventTime=0.06, mediaPos=0.00, window=1, 1080, 2412]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D  loading [eventTime=0.09, mediaPos=0.00, window=1, period=1, true]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D  timeline [eventTime=0.09, mediaPos=0.00, window=1, period=1, periodCount=3, windowCount=3, reason=SOURCE_UPDATE
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D    period [?]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=false]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D    window [?, seekable=false, dynamic=true]
2023-07-29 15:10:21.670 19876-19876 EventLogger             com.ltj.myplayer                     D  ]
2023-07-29 15:10:21.746 19876-19876 EventLogger             com.ltj.myplayer                     E  internalError [eventTime=0.17, mediaPos=0.00, window=1, period=1, loadError
                                                                                                      androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, AviExtractor, Mp3Extractor, JpegExtractor) could read the stream.
                                                                                                          at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:94)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1018)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                    ]
2023-07-29 15:10:21.750 19876-19876 VRI[VideoP...rActivity] com.ltj.myplayer                     D  onFocusEvent true
2023-07-29 15:10:21.750 19876-19876 VRI[VideoP...rActivity] com.ltj.myplayer                     D  send msg MSG_WINDOW_FOCUS_CHANGED with caller android.view.ViewRootImplExtImpl.markAndDumpWindowFocusChangeMsg:956 android.view.ViewRootImpl.windowFocusChanged:9837 android.view.ViewRootImpl$WindowInputEventReceiver.onFocusEvent:9550 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:349 android.os.Looper.loopOnce:186 android.os.Looper.loop:351 android.app.ActivityThread.main:8416 java.lang.reflect.Method.invoke:-2 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:584 com.android.internal.os.ZygoteInit.main:1013 <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> <bottom of call stack> 
2023-07-29 15:10:21.760 19876-19876 EventLogger             com.ltj.myplayer                     E  playerFailed [eventTime=0.19, mediaPos=0.00, window=1, period=1, errorCode=ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:652)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:622)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                          at android.os.Looper.loop(Looper.java:351)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, AviExtractor, Mp3Extractor, JpegExtractor) could read the stream.
                                                                                                          at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:94)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1018)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                    ]
2023-07-29 15:10:21.764 19876-19876 EventLogger             com.ltj.myplayer                     D  loading [eventTime=0.19, mediaPos=0.00, window=1, period=1, false]
2023-07-29 15:10:21.765 19876-19876 EventLogger             com.ltj.myplayer                     D  state [eventTime=0.19, mediaPos=0.00, window=1, period=1, IDLE]

### Media

no 

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @litianjun05090,

You can find formats supported by media3 [here](https://developer.android.com/guide/topics/media/exoplayer/supported-formats).

Unfortunately how you do that in your own custom `Extractor` implementation is beyond the scope of this issue tracker. 

Similar to https://github.com/google/ExoPlayer/issues/5309.
