### ISSUE TITLE
Is it possible to add looping audio over a video using Transformer?

### ISSUE THREAD

**Issue by jordond** [androidx/media#557]
Say I have a video file that is 30 seconds long. Using Transformer, is there a way to loop a 10 second audio file over the video. Such that the overlayed audio will loop the total duration of the video?

**Comment by kim-vde** [comment]
It depends if your video file has an audio track or not, and if you want to include it in the output.

**If your video file doesn't have any audio track**

You should create a `Composition `with 2 `EditedMediaItemSequences`, where
- The first sequence contains the video file;
- The second sequence contains the background audio file and has [`isLooping`](https://github.com/androidx/media/blob/5328d6464acb077a7e8cba61b8cac1973c4943d7/libraries/transformer/src/main/java/androidx/media3/transformer/EditedMediaItemSequence.java#L65) set to true.

**If your video file contains an audio track but you want to ignore it**

You should create the `Composition` as in the first case, and set [`removeAudio`](https://github.com/androidx/media/blob/5328d6464acb077a7e8cba61b8cac1973c4943d7/libraries/transformer/src/main/java/androidx/media3/transformer/EditedMediaItem.java#L72) to true on the `EditedMediaItem` representing your video file. 

**If your video file contains an audio track and you want to mix it with the background audio track**

This is currently not supported but will be in the next release. It will work by creating the same `Composition` as in the first case. The 2 audio tracks will automatically be mixed, but you might have to adapt their volume .

**Comment by jordond** [comment]
In my case I want to mix the two audio tracks, I'll check out the main branch, thanks 👍

**Comment by kim-vde** [comment]
Just adding some info about volume:

If you want to adapt the volume of the input audio streams, you will need to create a `ChannelMixingAudioProcessor` for each `EditedMediaItem` for which you want to change the volume, and include it in the corresponding `Effects`. The volume is adapted by setting the coefficients of the `ChannelMixingMatrices` passed to the `ChannelMixingAudioProcessor`.

**Comment by jordond** [comment]
I'm getting the following error when attempt to overlay audio over a sample video (while keeping the video's audio)

```
androidx.media3.transformer.ExportException: Audio error: existingInputs=1, audioFormat=AudioFormat[sampleRate=44100, channelCount=1, encoding=2]
    at androidx.media3.transformer.AudioGraph.registerInput(AudioGraph.java:61)
    at androidx.media3.transformer.AudioSampleExporter.getInput(AudioSampleExporter.java:105)
    at androidx.media3.transformer.AudioSampleExporter.getInput(AudioSampleExporter.java:34)
    at androidx.media3.transformer.TransformerInternal$SequenceAssetLoaderListener.onOutputFormat(TransformerInternal.java:536)
    at androidx.media3.transformer.SequenceAssetLoader.onOutputFormat(SequenceAssetLoader.java:249)
    at androidx.media3.transformer.SequenceAssetLoader.onOutputFormat(SequenceAssetLoader.java:50)
    at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.ensureSampleConsumerInitialized(ExoAssetLoaderBaseRenderer.java:265)
    at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.render(ExoAssetLoaderBaseRenderer.java:109)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1077)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:534)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.common.audio.AudioProcessor$UnhandledAudioFormatException: Can not add source. MixerFormat=AudioFormat[sampleRate=48000, channelCount=2, encoding=2] AudioFormat[sampleRate=44100, channelCount=1, encoding=2]
    at androidx.media3.transformer.AudioMixerImpl.addSource(AudioMixerImpl.java:134)
    at androidx.media3.transformer.AudioGraph.registerInput(AudioGraph.java:57)
    at androidx.media3.transformer.AudioSampleExporter.getInput(AudioSampleExporter.java:105) 
    at androidx.media3.transformer.AudioSampleExporter.getInput(AudioSampleExporter.java:34) 
    at androidx.media3.transformer.TransformerInternal$SequenceAssetLoaderListener.onOutputFormat(TransformerInternal.java:536) 
    at androidx.media3.transformer.SequenceAssetLoader.onOutputFormat(SequenceAssetLoader.java:249) 
    at androidx.media3.transformer.SequenceAssetLoader.onOutputFormat(SequenceAssetLoader.java:50) 
    at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.ensureSampleConsumerInitialized(ExoAssetLoaderBaseRenderer.java:265) 
    at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.render(ExoAssetLoaderBaseRenderer.java:109) 
    at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1077) 
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:534) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loopOnce(Looper.java:201) 
    at android.os.Looper.loop(Looper.java:288) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
 ```
    
  I've uploaded the Video and music file to [Google Drive](https://drive.google.com/drive/folders/1BukOMZSsHAUbuzT95triNGHBxJBj6GSM?usp=sharing).
  
  I am using commit 670658f3a on the `main` branch

**Comment by kim-vde** [comment]
Ah yes, we currently require all sequences to have the same audio sample rate. You can work around this setting the frame rate of each sequence with a `SonicAudioProcessor`. Here is a code example of how to build the `Composition`:

```java
SonicAudioProcessor sonicAudioProcessor = new SonicAudioProcessor();
sonicAudioProcessor.setOutputSampleRateHz(44100);
Effects effects =
    new Effects(ImmutableList.of(sonicAudioProcessor), /* videoEffects= */ ImmutableList.of());
EditedMediaItem videoEditedMediaItem =
    new EditedMediaItem.Builder(MediaItem.fromUri(videoUri)).setEffects(effects).build();
EditedMediaItemSequence videoSequence =
    new EditedMediaItemSequence(ImmutableList.of(videoEditedMediaItem));
EditedMediaItem audioEditedMediaItem =
    new EditedMediaItem.Builder(MediaItem.fromUri(audioUri)).setEffects(effects).build();
EditedMediaItemSequence audioSequence =
    new EditedMediaItemSequence(ImmutableList.of(audioEditedMediaItem), /* isLooping= */ true);
Composition composition = new Composition.Builder(ImmutableList.of(videoSequence, audioSequence)).build();
```

We are planning to remove this limitation soon.

**Comment by jordond** [comment]
Ah can't believe I missed that 😄

Thanks, using the SonicAudioProcessor fixed it 👍
