### ISSUE TITLE
Live DASH content always playing at the trailing edge

### ISSUE THREAD

**Issue by darrentaft** [androidx/media#607]
### Version

Media3 1.1.1

### Devices that reproduce the issue

Any device, but developing on:
Pixel 7 Pro running Android 14

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play a DASH live stream using an app that has specified a target offset in the LiveConfiguration.
Observe playback position (either on screen, or via additional logging).

### Expected result

By default, the target offset position should be honoured (only being overridden if conditions demanded otherwise)

### Actual result

Playback always occurs at the tail end of the manifest - i.e. the oldest segment.

By implementing a proxy for DefaultLivePlaybackSpeedControl I can see that on stream start, the live offset override in the speed control is immediately forcing it to maximum:

```
com.my.app.CustomSpeedControl.setTargetLiveOffsetOverrideUs(CustomSpeedControl.kt:22)
at androidx.media3.exoplayer.ExoPlayerImplInternal.updatePlaybackSpeedSettingsForNewPeriod(ExoPlayerImplInternal.java:2040)
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMediaSourceListInfoRefreshed(ExoPlayerImplInternal.java:1972)
at androidx.media3.exoplayer.ExoPlayerImplInternal.mediaSourceListUpdateRequestedInternal(ExoPlayerImplInternal.java:818)
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:588)
```

This means player.currentLiveOffset is always at/over the maximum (42 seconds), even though I requested a lower value (24000 ms).

### Media

Live stream available on request (geo-restricted, so a VPN can be provided or specific IP whitelisted).
Manifest attached: 
[livestream.mpd.txt](https://github.com/androidx/media/files/12429114/livestream.mpd.txt)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by darrentaft** [comment]
Further to this, I've just realised that this is why we're seeing so many users experiencing player failure.  As it's always following the trailing edge of the manifest, it only takes a single buffering event for the player to fall into a BehindLiveWindowException and quit playback (already discussed in #596)

**Comment by tonihei** [comment]
Based on your last post it sounds like everything is working as intended. Passing zero to `startPositionMs` means that the player attempts to start at position zero in the live window (= at the trailing edge), see also https://developer.android.com/guide/topics/media/exoplayer/live-streaming#detecting-and for the various position reference points for live streams.

If you want a common value for on-demand and live streams, then you should probably use `C.TIME_UNSET` which means "start at the default position". The default for on-demand is usually zero and the default for live is the configured target offset. But then you don't need to specify a start position at all because `player.setMediaItem(mediaItem)` will already assume `C.TIME_UNSET` for the start position.

**Comment by darrentaft** [comment]
Thanks - that makes sense.  The hardest part was finding the documentation on how it was supposed to behave - a comment/pointer in the documentation for startPositionMs would be very useful.
