### ISSUE TITLE
Audio sink error when setPreferredAudioDevice with offload mode enable

### ISSUE THREAD

**Issue by zling123** [androidx/media#611]
### Version

Media3 1.1.1

### Devices that reproduce the issue

Android SDK33

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Connect the Bluetooth headset to the device.
2. Enable offload mode in app.
3. start playback opus media 5 seconds, then pause 1s, then use setPreferredAudioDevice(AudioDeviceInfo.TYPE_BUILTIN_SPEAKER) to switch device, then resume playback 5s, then stop.

### Expected result

the media play 5s using bt-headset, pause 1s, then play 5s using speaker, then stop.

### Actual result

the media play 5s using bt-headset, pause 1s, then no voice can be heard in both bt-headset and speaker for 6s(1s for pause), then stop.
**When disable Offload mode, the result is as expected.**
And I confirm OPUS offload playback is supported on my device.
The logcat shows _Audio sink error_.
_08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer: Audio sink error
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:   androidx.media3.exoplayer.audio.AudioSink$WriteException: AudioTrack write failed: -6
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.writeBuffer(DefaultAudioSink.java:1164)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.processBuffers(DefaultAudioSink.java:1056)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:978)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:712)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.bypassRender(MediaCodecRenderer.java:2246)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:811)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at android.os.Looper.loopOnce(Looper.java:205)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at android.os.Looper.loop(Looper.java:294)
08-21 18:40:26.352  7502  7547 E MediaCodecAudioRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)_

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
@microkatz Could you take a look?

**Comment by zling123** [comment]
Any update here?

**Comment by zling123** [comment]
I found a similar issue [627](https://github.com/androidx/media/issues/627). So, I tried the latest version [1.2.0-rc01](https://github.com/androidx/media/releases/tag/1.2.0-rc01), but still _AudioTrack write failed_ and no audio can be heard after [setPreferredAudioDevice](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/SimpleExoPlayer.java#L645). The issue still exists.
Then I tried another way. 
I added the code [3742f6b](https://github.com/androidx/media/commit/3742f6b1f50df69f171846912f04b6e77b98a1fe) to the [release](https://github.com/androidx/media/tree/release) branch. The log still shows  _AudioTrack write failed_, but **audio can be heard after _setPreferredAudioDevice_**. The log shows it is using deep-buffer-playback rather than compress-offload-playback after _setPreferredAudioDevice_.

@microkatz I hope this can provide you with some useful information.
