### ISSUE TITLE
ConcurrentModificationException in SlidingPercentile

### ISSUE THREAD

**Issue by ojoNetgem** [androidx/media#612]
### Version

Media3 1.1.1

### Devices that reproduce the issue

AndroidTV box

### Reproducible in the demo app?

Not tested

### Reproduction steps

Looking for the different methods to compute bandwidth, I'm using in this case the ExperimentalBandwidthMeter without any changes in Builder.

```
val bandwidthMeter = ExperimentalBandwidthMeter.Builder(context)
    .build()
val player = Exoplayer.Builder(context)
    .setBandwidthMeter(bandwidthMeter)
    .build()
```

### Expected result

No crash

### Actual result

Sometimes the app crashes with this call stack:

```
androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1472)
	at java.util.Collections.sort(Collections.java:206)
	at androidx.media3.exoplayer.upstream.SlidingPercentile.ensureSortedByValue(SlidingPercentile.java:147)
	at androidx.media3.exoplayer.upstream.SlidingPercentile.getPercentile(SlidingPercentile.java:122)
	at androidx.media3.exoplayer.upstream.experimental.PercentileTimeToFirstByteEstimator.getTimeToFirstByteEstimateUs(PercentileTimeToFirstByteEstimator.java:92)
	at androidx.media3.exoplayer.upstream.experimental.ExperimentalBandwidthMeter.getTimeToFirstByteEstimateUs(ExperimentalBandwidthMeter.java:322)
	at androidx.media3.exoplayer.trackselection.AdaptiveTrackSelection.getTotalAllocatableBandwidth(AdaptiveTrackSelection.java:693)
	at androidx.media3.exoplayer.trackselection.AdaptiveTrackSelection.getAllocatedBandwidth(AdaptiveTrackSelection.java:671)
	at androidx.media3.exoplayer.trackselection.AdaptiveTrackSelection.determineIdealSelectedIndex(AdaptiveTrackSelection.java:600)
	at androidx.media3.exoplayer.trackselection.AdaptiveTrackSelection.evaluateQueueSize(AdaptiveTrackSelection.java:524)
	at androidx.media3.exoplayer.source.MergingMediaPeriod$ForwardingTrackSelection.evaluateQueueSize(MergingMediaPeriod.java:589)
	at androidx.media3.exoplayer.dash.DefaultDashChunkSource.getPreferredQueueSize(DefaultDashChunkSource.java:304)
	at androidx.media3.exoplayer.source.chunk.ChunkSampleStream.reevaluateBuffer(ChunkSampleStream.java:666)
	at androidx.media3.exoplayer.source.CompositeSequenceableLoader.reevaluateBuffer(CompositeSequenceableLoader.java:60)
	at androidx.media3.exoplayer.dash.DashMediaPeriod.reevaluateBuffer(DashMediaPeriod.java:315)
	at androidx.media3.exoplayer.source.CompositeSequenceableLoader.reevaluateBuffer(CompositeSequenceableLoader.java:60)
	at androidx.media3.exoplayer.source.MergingMediaPeriod.reevaluateBuffer(MergingMediaPeriod.java:192)
	at androidx.media3.exoplayer.source.MaskingMediaPeriod.reevaluateBuffer(MaskingMediaPeriod.java:223)
	at androidx.media3.exoplayer.MediaPeriodHolder.reevaluateBuffer(MediaPeriodHolder.java:211)
	at androidx.media3.exoplayer.MediaPeriodQueue.reevaluateBuffer(MediaPeriodQueue.java:140)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleContinueLoadingRequested(ExoPlayerImplInternal.java:2354)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Media

Any dash stream should retroduce the issue

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by ojoNetgem** [comment]
Good news, thanks
