### ISSUE TITLE
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer errorCode=ERROR_CODE_DECODING_FAILED

### ISSUE THREAD

**Issue by androidlukas** [androidx/media#635]
### Version

Media3 1.1.1

### More version details

```
playerFailed [eventTime=1.83, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODING_FAILED
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D403C, -1, null, [820, 3552, 24.000002, null], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
at android.os.HandlerThread.run(HandlerThread.java:67)
                Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.mtk.avc.decoder
 at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)
at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)
 at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)
at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loopOnce(Looper.java:226) 
at android.os.Looper.loop(Looper.java:313) 
at android.os.HandlerThread.run(HandlerThread.java:67) 
Caused by: android.media.MediaCodec$CodecException: Error 0x80000000
```

Dump I sent at mail 

### Devices that reproduce the issue

Samsung A22 5G android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play video that I sent on mail(It work at demo app)

### Expected result

Video should play

### Actual result

Video doesn't play and show error 4003

### Media

I sent on mail

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
The codec declares it doesn't support the content you're playing (`NO_EXCEEDS_CAPABILITIES`), so crashing is one of the expected outcomes. We still try and play in this case, because sometimes codecs declare this when they actually **can** play the content.

To resolve this, you should encode your content in a way that's supported by your device. You can see the video encodings that are guaranteed to be supported on different versions of Android here: https://developer.android.com/guide/topics/media/platform/supported-formats#video-formats

**Comment by androidlukas** [comment]
We check video, it is H.264, should support this format
![image (15)](https://github.com/androidx/media/assets/99200686/7a197827-d9a6-45b6-9201-2f46e68632a5)

**Comment by androidlukas** [comment]
We have the same error with h264 but new video ratio MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [498, 2160, 29.970037], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES

**Comment by androidlukas** [comment]
MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [498, 2160, 24.000002], [-1, -1]), format_supported=YES

**Comment by androidlukas** [comment]
@icbaker Why it can be?
You very fast close issue)
