### ISSUE TITLE
How to fault-tolerantly play potentially corrupted videos

### ISSUE THREAD

**Issue by simman** [androidx/media#649]
### Version

ExoPlayer 2.19.1

### More version details

main

### Devices that reproduce the issue

Galaxy Nexus API 31

### Reproducible in the demo app?

Yes

### Reproduction steps

1. use https://github.com/google/ExoPlayer/tree/release-v2/demos/main
2. choose local file (https://gofile.io/d/0nc7tD)
3. export

First of all, there may be a problem with this video. Use ffmpeg to verify it. The results are as follows:

```
➜  Downloads ffmpeg -i SH_017.mp4
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x142604290] stream 0, missing mandatory atoms, broken header
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'SH_017.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    creation_time   : 2023-09-11T08:16:57.000000Z
  Duration: 00:00:06.07, start: 0.000000, bitrate: 361 kb/s
  Stream #0:0[0x1](und): Audio: aac (mp4a / 0x6134706D), 16000 Hz, mono, fltp (default)
    Metadata:
      creation_time   : 2023-09-11T08:16:57.000000Z
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 358 kb/s, 30 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2023-09-11T08:16:58.000000Z
      vendor_id       : [0][0][0][0]
      encoder         : JVT/AVC Coding
At least one output file must be specified
```

Is it possible to play the content of this video like vlc?

### Expected result

the media plays successfully

### Actual result

```
2023-09-13 19:00:13.630 21067-21185 EGL_emulation           com...id.exoplayer2.transformerdemo  D  app_time_stats: avg=579.20ms min=14.60ms max=4499.22ms count=8
2023-09-13 19:00:13.743 21067-21067 ExoPlayerImpl           com...id.exoplayer2.transformerdemo  I  Init 79d09b6 [ExoPlayerLib/2.19.1] [emulator64_arm64, sdk_gphone64_arm64, Google, 31]
2023-09-13 19:00:13.764 21067-21756 LoadTask                com...id.exoplayer2.transformerdemo  E  Unexpected exception loading stream
                                                                                                      java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
                                                                                                          at com.google.android.exoplayer2.util.ParsableByteArray.readInt(ParsableByteArray.java:334)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers$ChunkIterator.<init>(AtomParsers.java:2020)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:484)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:193)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:526)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:481)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:463)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:261)
                                                                                                          at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:133)
                                                                                                          at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:920)
2023-09-13 19:00:13.777 21067-21755 ExoPlayerImplInternal   com...id.exoplayer2.transformerdemo  E  Playback error
                                                                                                      com.google.android.exoplayer2.ExoPlaybackException: Source error
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:660)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                          at android.os.Looper.loop(Looper.java:288)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=16; index=16
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:441)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:920)
                                                                                                      Caused by: java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
                                                                                                          at com.google.android.exoplayer2.util.ParsableByteArray.readInt(ParsableByteArray.java:334)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers$ChunkIterator.<init>(AtomParsers.java:2020)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:484)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:193)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:526)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:481)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:463)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:261)
                                                                                                          at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:133)
                                                                                                          at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                          at java.lang.Thread.run(Thread.java:920) 
2023-09-13 19:00:13.779 21067-21754 ExoPlayerImpl           com...id.exoplayer2.transformerdemo  I  Release 79d09b6 [ExoPlayerLib/2.19.1] [emulator64_arm64, sdk_gphone64_arm64, Google, 31] [goog.exo.core, goog.exo.ui, goog.exo.transformer, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
2023-09-13 19:00:13.801 21067-21067 TransformerActivity     com...id.exoplayer2.transformerdemo  E  Export error
                                                                                                      com.google.android.exoplayer2.transformer.ExportException: Asset loader error
                                                                                                          at com.google.android.exoplayer2.transformer.ExoPlayerAssetLoader$PlayerListener.onPlayerError(ExoPlayerAssetLoader.java:369)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$16(ExoPlayerImpl.java:2052)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda2.invoke(Unknown Source:4)
                                                                                                          at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:342)
                                                                                                          at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:226)
                                                                                                          at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
                                                                                                          at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:248)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:2113)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1946)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1$com-google-android-exoplayer2-ExoPlayerImpl(ExoPlayerImpl.java:328)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda19.run(Unknown Source:4)
                                                                                                          at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                          at android.os.Looper.loop(Looper.java:288)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: com.google.android.exoplayer2.ExoPlaybackException: Source error
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
                                                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:660)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                          at android.os.Looper.loop(Looper.java:288) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                      Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=16; index=16
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:441)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                          at java.lang.Thread.run(Thread.java:920)
                                                                                                      Caused by: java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
                                                                                                          at com.google.android.exoplayer2.util.ParsableByteArray.readInt(ParsableByteArray.java:334)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers$ChunkIterator.<init>(AtomParsers.java:2020)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:484)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:193)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:526)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:481)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:463)
                                                                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:261)
                                                                                                          at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:133)
                                                                                                          at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
                                                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                          at java.lang.Thread.run(Thread.java:920) 
2023-09-13 19:00:14.213 21067-21185 OpenGLRenderer          com...id.exoplayer2.transformerdemo  D  endAllActiveAnimators on 0xb4000074540ca740 (RippleDrawable) with handle 0xb40000736409b140

```

### Media

https://gofile.io/d/0nc7tD

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by oceanjules** [comment]
The `com.google.android.exoplayer2` project is now deprecated. Could you please reproduce it using: https://github.com/androidx/media/tree/release/demos/main ?
