### ISSUE TITLE
DASH UHD HEVC playback failure on Amazon FireTV Stick UHD (AFTMM)

### ISSUE THREAD

**Issue by vkoehler** [androidx/media#654]
### Version

Media3 1.1.1

### Devices that reproduce the issue

Amazon FireTV Stick UHD (AFTMM)
Fire OS 6.2.9.8 (NS6298/4758)

### Devices that do not reproduce the issue

Amazon FireTV Stick UHD Max

### Reproducible in the demo app?

Yes

### Reproduction steps

Play DASH UHD HEVC stream with Widevine DRM. 

### Expected result

Stream can be played successfully.

### Actual result

Playback crashes with the following error:
```
2023-09-14 08:13:10.172   245-276   BufferQueueProducer     pid-245                              E  [SurfaceView - androidx.media3.demo.main/androidx.media3.demo.main.PlayerActivity] dequeueBuffer: createGraphicBuffer failed
2023-09-14 08:13:10.172   748-1024  ACodec                  androidx.media3.demo.main            E  dequeueBuffer failed: Out of memory (12)
2023-09-14 08:13:10.172   748-1024  ACodec                  androidx.media3.demo.main            E  Failed to allocate output port buffers after port reconfiguration: (-12)
2023-09-14 08:13:10.172   748-1024  ACodec                  androidx.media3.demo.main            E  signalError(omxError 0x80001001, internalError -12)
2023-09-14 08:13:10.172   748-1022  MediaCodec              androidx.media3.demo.main            E  Codec reported err 0xfffffff4, actionCode 0, while in state 6
2023-09-14 08:13:10.173   748-1022  MediaCodecLogger        androidx.media3.demo.main            I  xxx.4K.secure.HW.video.hevc.DecoderErrorFatal = 1
2023-09-14 08:13:10.173   748-1022  MediaCodecLogger        androidx.media3.demo.main            I  xxx.4K.secure.HW.video.hevc.ASAP-P2Ms = 16
2023-09-14 08:13:10.173   748-1022  MediaCodecLogger        androidx.media3.demo.main            I  xxx.4K.secure.HW.video.hevc.ASAP-P3Ms = 29
2023-09-14 08:13:10.173   748-1022  MediaCodecLogger        androidx.media3.demo.main            I  xxx.4K.secure.HW.video.hevc.FirstFrameReadyMs = -234915546
2023-09-14 08:13:10.180   748-993   MediaCodecVideoRenderer androidx.media3.demo.main            E  Video codec error
                                                                                                      java.lang.IllegalStateException
                                                                                                          at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                          at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2584)
                                                                                                          at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:108)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1865)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:816)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
2023-09-14 08:13:10.183   748-993   ExoPlayerImplInternal   androidx.media3.demo.main            E  Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(video_deu=2212041, null, null, video/hevc, hvc1.2.4.L93.90, 2212041, null, [1280, 720, 25.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                                      Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.HEVC.secure
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                                      Caused by: java.lang.IllegalStateException
                                                                                                          at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                                                          at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2584)
                                                                                                          at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:108)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1865)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:816)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852) 
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047) 
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522) 
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                                          at android.os.Looper.loop(Looper.java:154) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61) 
2023-09-14 08:13:10.185   748-993   ExoPlayerImplInternal   androidx.media3.demo.main            E  Disable failed.
                                                                                                      java.lang.IllegalStateException
                                                                                                          at android.media.MediaCodec.native_flush(Native Method)
                                                                                                          at android.media.MediaCodec.flush(MediaCodec.java:2068)
                                                                                                          at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:168)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:901)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:894)
                                                                                                          at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:733)
                                                                                                          at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:634)
                                                                                                          at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:197)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1731)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1453)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1413)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:634)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
```

### Media

Will be emailed.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by vkoehler** [comment]
last working ExoPlayer version is 2.18.1.
In 2.18.2 the calculation of codecMaxInputSize for HEVC has been changed, that leads to the playback crash on AFTMM: https://github.com/androidx/media/commit/d3d5ffce91452ebf1edf51a0c0c9d80ad29fe0b6

**Comment by christosts** [comment]
Thank you for the report. I'll take a look as soon as possible. I saw you've shared content with us (thanks again) but with a 24hr token. Can you make the token can last longer, say 1 week, or even better share a non-encrypted version of the content with us? If the issue is with the commit you spotted, then having access to the non-encrypted version of the content should be enough.

**Comment by christosts** [comment]
I tried the content on a device (not FireTV) with media3 1.1.0 and ExoPlayer 2.18.1. Btw, the content doesn't play (the DRM server returns 500 - the token expired?) but the player can parse the manifest and calculate the HEVC max input buffers.

On your log, the error is thrown when playing the 720p resolution for which
- media3 1.1.1 calculates the max input size to around 2MB
- ExoPlayer 2.18.1 calculates the max input size to around 350 KB

While I see the difference in the calculations between the library versions, the specific content can reach 4K resolution, in which the max input size calculated by ExoPlayer 2.18.1 is ~3MB.  What is the maximum resolution the FireTV can reach? If the codec max value is the problem, and if the 4K resolution is playable, then the FireTV would maybe throw on ExoPlayer 2.18.1 too?

I wonder if the problem comes from elsewhere. Unfortunately the bug report does not contain the logs from the demo app. Can you please reproduce again on the FireTV and then obtain a bug report immediately?

Also, as mentioned in the above comment, can you please share a content with a longer expiration token, or non encryption at all?

**Comment by christosts** [comment]
aside: @tonihei when MediaCodecVideoRenderer is calculating the codec max input size and the content is adaptive, shouldn't it be using a max input size based on the max possible resolution? While debugging, I noticed that the player sets the max input size based on the currently played resolution.

**Comment by christosts** [comment]
Please disregard my previous comment (I have now hidden it), I was debugging on a device with resolution up to 1080p and the player was excluding resolutions over 1080p, I need to debug on a 4K screen.

**Comment by vkoehler** [comment]
The max input size in ExoPlayer 2.18.1 is ~3MB and in media3 1.1.0 ~6MB, because minCompressionRatio changed from 4 to 2 for HEVC. It seems to be too much for FireTV AFTMM. 

4K resolution is playable on FireTV AFTMM with ExoPlayer 2.18.1. However, the same stream fails on FireTV AFTMM with media3 1.1.0. I tried to change minCompressionRatio from 2 back to 4 in media 3 1.1.0, then the same stream can be played in 4K.

DRM 500 is indeed an expired token. Unfortunatelly, we don't have an unencrypted stream and can't change the token life time.  I can send you an updated license URL, if you tell me, when exactly you would like to run your tests. Btw, FireTV AFTMM runs into an exception, that I reported, before requesting a license. So you would see this exception, even if the token has expired.

**Comment by christosts** [comment]
The change in ExoPlayer was made after we found HEVC content with access units larger than the previous calculations. The current calculations in ExoPlayer assume a min compression of 2 in alignment with the the HEVC software decoder [in the platform](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/av/media/codec2/components/hevc/C2SoftHevcDec.cpp;l=224;drc=05575b11d336e40ba9bf8406347df1bdc5e673ab). 

This seems to be a FireTV specific issue. However, I'm not aware of another report coming from FireTV users, so I'm hesitating to make a change in the code specifically for FireTV (at least not yet). Also, I wonder what would happen if you try to play HEVC content on the FireTV with access units are larger than the previously calculated max input size, which we know was too optimistic on the assumed min compression rate. 

In the short term, you can customize the behavior on your app, the value is calculated at `MediaCodecVideoRenderer.getCodecMaxValues()` which is `protected` and you can override it. If you're not customizing the renderers at the moment, then the fastest path to customize `MediaCodecVideoRenderer` is to build a `DefaulRenderersFactory` and pass it to the player, here's an example

```java
RenderersFactory renderersFactory = new DefaultRenderersFactory(context){
    @Override
    protected void buildVideoRenderers(Context context,
        @ExtensionRendererMode int extensionRendererMode, MediaCodecSelector mediaCodecSelector,
        boolean enableDecoderFallback, Handler eventHandler,
        VideoRendererEventListener eventListener, long allowedVideoJoiningTimeMs,
        ArrayList<Renderer> out) {
      out.add(new MediaCodecVideoRenderer(
          context,
          getCodecAdapterFactory(),
          mediaCodecSelector,
          allowedVideoJoiningTimeMs,
          enableDecoderFallback,
          eventHandler,
          eventListener,
          MAX_DROPPED_VIDEO_FRAME_COUNT_TO_NOTIFY){
        @Override
        protected CodecMaxValues getCodecMaxValues(MediaCodecInfo codecInfo, Format format,
            Format[] streamFormats) {
          CodecMaxValues codecMaxValues = super.getCodecMaxValues(codecInfo, format,
              streamFormats);
          if (codecMaxValues.inputSize > XXX) {
            codecMaxValues = new CodecMaxValues(codecMaxValues.height, codecMaxValues.width, YYY);
          }
          return codecMaxValues;
        }
      });
    }
  };
  ExoPlayer exoPlayer = new ExoPlayer.Builder(context, renderersFactory).build();
}
```

where `XXX` and `YYY` are the FireTV specific values for the max input size. Can you try this and let us know if that works on your app?

**Comment by vkoehler** [comment]
Customizing MediaCodecVideoRenderer helps. I did it for FireTV AFTMM and set maxInputSize to 3,110,400 (as it was calculated by ExoPlayer 2.18.1)

```java
if ("Amazon".equals(Util.MANUFACTURER) && "AFTMM".equals(Util.MODEL) && codecMaxValues.inputSize > 3110400) {
   codecMaxValues = new CodecMaxValues(codecMaxValues.height, codecMaxValues.width, 3110400);
}
``` 
The limit for maxInputSize on AFTMM seems to be somewhere between 5,900,000 and 6,000,000, but 3,110,400 works for our content.

You mentioned, that you found HEVC content with access units larger than the previous calculations. I could try playing it on AFTMM, if you can give me the url.

**Comment by vkoehler** [comment]
Wouldn't you consider adding this exception to the getCodecMaxInputSize function? I see, that you did it in a similar way for H264:
```java
case MimeTypes.VIDEO_H264:
        if ("BRAVIA 4K 2015".equals(Util.MODEL) // Sony Bravia 4K
            || ("Amazon".equals(Util.MANUFACTURER)
                && ("KFSOWI".equals(Util.MODEL) // Kindle Soho
                    || ("AFTS".equals(Util.MODEL) && codecInfo.secure)))) { // Fire TV Gen 2
          // Use the default value for cases where platform limitations may prevent buffers of the
          // calculated maximum input size from being allocated.
          return Format.NO_VALUE;
        }
```

**Comment by christosts** [comment]
I tried playing UHD content on a FireTV 4K TV stick (identified as AFTMM) and did not see the issue. I wonder if this error is specific to your app and/or content. I'm inclined not to change the library and add an exception for FireTV until we get more reports that this is happening on other FireTV devices (I have not seen such reports yet). Adding the exception you mention above  has some risk too. For example if we add the same logic as it is for H264, that method will not return a specific value letting MediaCodec decide on its own, and I'm not sure that this will not impact devices even more.
