### ISSUE TITLE
evaluateMediaItemTransitionReason - IllegalStateException

### ISSUE THREAD

**Issue by captain81** [androidx/media#713]
### Version

ExoPlayer 2.14.0

### More version details

java.lang.IllegalStateException at com.oplus.tbl.exoplayer2.ExoPlayerImpl.evaluateMediaItemTransitionReason(ExoPlayerImpl.java:18) at com.oplus.tbl.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:5) at com.oplus.tbl.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:19) at com.oplus.tbl.exoplayer2.ExoPlayerImpl.lambda$null$1(ExoPlayerImpl.java:1) at com.oplus.tbl.exoplayer2.ExoPlayerImpl.s(Unknown Source:0) at com.oplus.tbl.exoplayer2.s.run(Unknown Source:4) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:240) at android.os.Looper.loop(Looper.java:351) at android.app.ActivityThread.main(ActivityThread.java:8422) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### Devices that reproduce the issue

All

### Devices that do not reproduce the issue

NO

### Reproducible in the demo app?

Yes

### Reproduction steps

Play video, I have seen many people asking this question before, but there has been no clear solution

### Expected result

No crash

### Actual result

crash

### Media

No

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by captain81** [comment]
https://github.com/google/ExoPlayer/issues/10244

**Comment by tianyif** [comment]
Hi @captain81,

Are you able to reliably reproduce this in some specific scenario? I've seen one issue (https://github.com/androidx/media/issues/480) on this question where the reporter said they saw this by setting the shuffle order, but I could just reproduce another exception with their steps at that time.

**Comment by tonihei** [comment]
I assume this is just the same issue as #480? The fix is only in release 1.1.1 (or ExoPlayer 2.19.1), so the 2.14.0 you are using won't have it yet. Will close the issue under this assumption. If you can reproduce after updating to the latest version, please file a new issue with the stack trace observed there.
