### ISSUE TITLE
androidx.media3.transformer.ExportException: Asset loader error

### ISSUE THREAD

**Issue by pawaom** [androidx/media#736]
I am trying to Add audio over video using following code

the video has its own audio and we are trying to keep the original audio(of the video) and overlay new audio also

```
public void TransformVideo() {
        try {
            outputPath = createOutputFile().getAbsolutePath();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        MediaItem inputMediaItem = new MediaItem.Builder().setUri(VideoUri).setClippingConfiguration(
                new MediaItem.ClippingConfiguration.Builder()
                        .setStartPositionMs(1000)
                        .setEndPositionMs(25000)
                        .build()).build();

        MediaItem inputMediaItem2 = new MediaItem.Builder().setUri(AudioUri).setClippingConfiguration(
                new MediaItem.ClippingConfiguration.Builder()
                        .setStartPositionMs(30000)
                        .setEndPositionMs(50000)
                        .build()).build();


        Transformer transformer =
                new Transformer.Builder(Own_Media_Transform.this)
                        .setTransformationRequest(
                                new TransformationRequest.Builder().build())
                        .addListener(transformerListener)
                        .build();

        EditedMediaItem.Builder editedMediaItemBuilder = new EditedMediaItem.Builder(inputMediaItem);
        EditedMediaItem.Builder editedMediaItemBuilder2 = new EditedMediaItem.Builder(inputMediaItem2);

        List<EditedMediaItem> editedMediaItems = new ArrayList<>();
        editedMediaItems.add(editedMediaItemBuilder.build());

        editedMediaItems.add(editedMediaItemBuilder2.build());

        List<EditedMediaItemSequence> sequences = new ArrayList<>();
        sequences.add(new EditedMediaItemSequence(editedMediaItems));

        Composition composition = new Composition.Builder(sequences)
                .build();


        transformer.start(composition, outputPath);
        ProgressHolder progressHolder = new ProgressHolder();
        mainHandler = new Handler(Looper.getMainLooper());
        mainHandler.post(
                new Runnable() {
                    @Override
                    public void run() {
                        if (transformer != null
                                && transformer.getProgress(progressHolder) != PROGRESS_STATE_NOT_STARTED) {
                            progressIndicator.setProgress(progressHolder.progress);
                            mainHandler.postDelayed(/* r= */ this, /* delayMillis= */ 500);
                        }
                    }
                });
    }
```

The video is created but without the overlay audio 

this is the error log 

```
androidx.media3.transformer.ExportException: Asset loader error at
androidx.media3.transformer.ExoPlayerAssetLoader$PlayerListener.onPlayerError
(ExoPlayerAssetLoader.java:363) at
androidx.media3.exoplayer.ExoPlayerImpl.lambda$updatePlaybackInfo$16
(ExoPlayerImpl.java:2055) at
androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda2.invoke
(Unknown Source:4) at
androidx.media3.common.util.ListenerSet$ListenerHolder.invoke
(ListenerSet.java:339) at
androidx.media3.common.util.ListenerSet.lambda$queueEvent$0
(ListenerSet.java:223) at
androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda1.run
(Unknown Source:6) at androidx.media3.common.util.ListenerSet.flushEvents
(ListenerSet.java:245) at
androidx.media3.exoplayer.ExoPlayerImpl.updatePlaybackInfo
(ExoPlayerImpl.java:2116) at
androidx.media3.exoplayer.ExoPlayerImpl.handlePlaybackInfo
(ExoPlayerImpl.java:1949) at
androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$1$androidx-media3-exoplayer-ExoPlayerImpl(ExoPlayerImpl.java:331)
at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda15.run
(Unknown Source:4) at android.os.Handler.handleCallback(Handler.java:942) at
android.os.Handler.dispatchMessage(Handler.java:99) at
android.os.Looper.loopOnce(Looper.java:226) at android.os.Looper.loop
(Looper.java:313) at android.os.HandlerThread.run
(HandlerThread.java:67) Caused by:
androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error at
androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage
(ExoPlayerImplInternal.java:668) at android.os.Handler.dispatchMessage
(Handler.java:102) at android.os.Looper.loopOnce(Looper.java:226) at
android.os.Looper.loop(Looper.java:313) at android.os.HandlerThread.run
(HandlerThread.java:67) Caused by: java.lang.IllegalStateException: Inputs
with no video track are not supported when the output contains a video track
at androidx.media3.common.util.Assertions.checkState(Assertions.java:100) at
androidx.media3.transformer.SequenceAssetLoader.onOutputFormat
(SequenceAssetLoader.java:271) at
androidx.media3.transformer.ExoAssetLoaderBaseRenderer.ensureSampleConsumerInitialized(ExoAssetLoaderBaseRenderer.java:265)
at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.render
(ExoAssetLoaderBaseRenderer.java:109) at
androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork
(ExoPlayerImplInternal.java:1047) at
androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage
(ExoPlayerImplInternal.java:522) at android.os.Handler.dispatchMessage
(Handler.java:102) at android.os.Looper.loopOnce(Looper.java:226) at
android.os.Looper.loop(Looper.java:313) at android.os.HandlerThread.run
(HandlerThread.java:67) 
```

We even tried to add audio by removing the original audio of the video and add new video but it gives the error `unexpected runtime error `

**Comment by droid-girl** [comment]
Hi @pawaom,
To be able to add audio over video you need to create 2 `EditedMediaItemSequence`: one that will contain video and another one for audio, something like this:
``` 
EditedMediaItemSequence videoSequence = new EditedMediaItemSequence(
    editedMediaItemBuilder.build());
EditedMediaItemSequence audioSequence = new EditedMediaItemSequence(
    Collections.singletonList(backgroundAudioFile), /* isLooping= */ true);
Composition c = new Composition.Builder(
    ImmutableList.of(videoSequence, audioSequence)).build();
``` 
Could you try this and let me know if you have any follow up questions?

**Comment by pawaom** [comment]
I tried your suggestion 
this is the modified code

 ```
public void TransformVideo() {
        ImmutableList.Builder<Effect> effects = new ImmutableList.Builder<>();
        try {
            effects.add(createOverlayEffect());
        } catch (PackageManager.NameNotFoundException e) {
            throw new RuntimeException(e);
        }
        try {
            outputPath = createOutputFile().getAbsolutePath();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        MediaItem inputMediaItem = new MediaItem.Builder().setUri(VideoUri).setClippingConfiguration(
                new MediaItem.ClippingConfiguration.Builder()
                        .setStartPositionMs(1000)
                        .setEndPositionMs(25000)

                        .build()).build();

        MediaItem audioMediaItem2 = new MediaItem.Builder().setUri(AudioUri).setClippingConfiguration(
                new MediaItem.ClippingConfiguration.Builder()
                        .setStartPositionMs(1000)
                        .setEndPositionMs(25000)
                        .build()).build();


        Transformer transformer =
                new Transformer.Builder(Own_Media_Transform.this)
                        .setTransformationRequest(
                                new TransformationRequest.Builder().build())
                        .addListener(transformerListener)
                        .build();

        EditedMediaItem.Builder editedMediaItemBuilder = new EditedMediaItem.Builder(inputMediaItem);
        EditedMediaItem.Builder editedMediaItemBuilder2 = new EditedMediaItem.Builder(audioMediaItem2);
        editedMediaItemBuilder.setEffects(new Effects(createAudioProcessorsFromBundle(), effects.build()));
        List<EditedMediaItem> editedMediaItems = new ArrayList<>();
        editedMediaItems.add(editedMediaItemBuilder.build());

        //  editedMediaItems.add(editedMediaItemBuilder2.build());

        List<EditedMediaItem> editedAudioMediaItems = new ArrayList<>();
        editedAudioMediaItems.add(editedMediaItemBuilder2.build());

        EditedMediaItemSequence VideoSequence = new EditedMediaItemSequence(editedMediaItems);
        EditedMediaItemSequence audioSequence = new EditedMediaItemSequence(
                editedAudioMediaItems, /* isLooping= */ false);


        Composition composition = new Composition.Builder(ImmutableList.of(VideoSequence, audioSequence))
                .build();


        transformer.start(composition, outputPath);
        ProgressHolder progressHolder = new ProgressHolder();
        mainHandler = new Handler(Looper.getMainLooper());
        mainHandler.post(
                new Runnable() {
                    @Override
                    public void run() {
                        if (transformer != null
                                && transformer.getProgress(progressHolder) != PROGRESS_STATE_NOT_STARTED) {
                            progressIndicator.setProgress(progressHolder.progress);
                            mainHandler.postDelayed(/* r= */ this, /* delayMillis= */ 500);
                        }
                    }
                });
    }
```

but it gives me a new error ` Caused by: java.lang.IllegalStateException: There is already a track of type 1`

```
Export error
                                                                                                      androidx.media3.transformer.ExportException: Unexpected runtime error
                                                                                                          at androidx.media3.transformer.TransformerInternal.handleMessage(TransformerInternal.java:305)
                                                                                                          at androidx.media3.transformer.TransformerInternal.$r8$lambda$0Eq5y0bhoOvqh9wEU99UtqZE5oc(Unknown Source:0)
                                                                                                          at androidx.media3.transformer.TransformerInternal$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                          at android.os.Looper.loop(Looper.java:313)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: java.lang.IllegalStateException: There is already a track of type 1
                                                                                                          at androidx.media3.common.util.Assertions.checkState(Assertions.java:100)
                                                                                                          at androidx.media3.transformer.MuxerWrapper.addTrackFormat(MuxerWrapper.java:178)
                                                                                                          at androidx.media3.transformer.SamplePipeline.feedMuxer(SamplePipeline.java:101)
                                                                                                          at androidx.media3.transformer.SamplePipeline.processData(SamplePipeline.java:67)
                                                                                                          at androidx.media3.transformer.TransformerInternal.drainPipelinesInternal(TransformerInternal.java:326)
                                                                                                          at androidx.media3.transformer.TransformerInternal.handleMessage(TransformerInternal.java:291)
                                                                                                          at androidx.media3.transformer.TransformerInternal.$r8$lambda$0Eq5y0bhoOvqh9wEU99UtqZE5oc(Unknown Source:0) 
                                                                                                          at androidx.media3.transformer.TransformerInternal$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2) 
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                          at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                          at android.os.Looper.loop(Looper.java:313) 
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67) 
```
