### ISSUE TITLE
AdPlaybackState.getAdGroup ArrayIndexOutOfBoundsException length=0; index=0

### ISSUE THREAD

**Issue by ldd386** [androidx/media#743]
### Version

ExoPlayer 2.19.1

### More version details

After upgrading the exoplayer to the latest version (2.19.1) we started to see these errors in the production app:

java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at com.google.android.exoplayer2.source.ads.AdPlaybackState.getAdGroup(AdPlaybackState.java:625)
at com.google.android.exoplayer2.Timeline$Period.getAdGroupTimeUs(Timeline.java:735)
at com.google.android.exoplayer2.analytics.PlaybackStatsListener.findBestEventTime(PlaybackStatsListener.java:328)
at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onEvents(PlaybackStatsListener.java:253)
at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector.lambda$setPlayer$1$com-google-android-exoplayer2-analytics-DefaultAnalyticsCollector(DefaultAnalyticsCollector.java:140)
at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector$$ExternalSyntheticLambda19.invoke
at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:353)
at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java:297)
at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$eEvjP-IE0x3J2lRvKfFbbjRFRvc
at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.handleMessage
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

I reported the issue on the ExoPlayer github page and I was told I have to create a bug report here and there is another ticket open with the same issue https://github.com/google/ExoPlayer/issues/10817 and a open PR (https://github.com/google/ExoPlayer/pull/10819).
 

### Devices that reproduce the issue

- 4K Google TV Box (Android 11)
- Bravia TL  (Android 11)
- Philips AndroidTV  (Android 11)
- SHIELD TV Pro  (Android 11)
- AI PONT (Android 10)
- Philips UHD Android TV (Android 11)
- Bravia 4K (Android 10)
- .....

### Reproducible in the demo app?

No

### Reproduction steps

It happens (sometimes) while playing ads.
The ads seem to work with the VAST web player.

### Expected result

Playback of the ad and streaming.

### Actual result

App crashes

### Media

I send it via email.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
The same question I just asked on the linked issue still applies: What exactly do you have to do to reproduce it? What kind of ads (ideally with example ad tag), how is the `PlaybackStatsListener` added, any interactions with the player that are relevant (seeking etc), which ad (preroll, midroll, postroll),...

**Comment by ldd386** [comment]
this is the code related to playbackStatsListener, nothing special:

```
val playbackStatsListener = PlaybackStatsListener(false, null)
...
player.addAnalyticsListener(playbackStatsListener)
```
we receive ads dynamically, It is difficult to know what the content of the VAST was.
We are still trying to reproduce the problem, we will probably add more logs.
It's not a common issue, but it happens to 5 or 6 users every day.
