### ISSUE TITLE
MEDIA_BUTTON action checkStateNotNull exception

### ISSUE THREAD

**Issue by ohoos** [androidx/media#75]
Hi, when I pause a track, kill the application, and click on the play button on my headphones, when the application crash (for example code is the same ).

```
Fatal Exception: java.lang.RuntimeException
Unable to start service ....audioplayer.player.MediaPlayerService@2552659 with Intent { act=android.intent.action.MEDIA_BUTTON dat=androidx.media3.session.p6:/48035136 flg=0x10000000 cmp=….player.MediaPlayerService (has extras) }: java.lang.IllegalStateException

Caused by java.lang.IllegalStateException
       at androidx.media3.common.util.Assertions.checkStateNotNull(Assertions.java:117)
       at androidx.media3.session.MediaSessionService.onStartCommand(MediaSessionService.java:326)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4534)
       at android.app.ActivityThread.access$2100(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by marcbaechinger** [comment]
Thanks for reporting. This is fixed with [this commit](https://github.com/androidx/media/commit/88cedf010c3ed6b66bbb011a8c3727f91f5b6b87) already and will land in the next release.
