### ISSUE TITLE
demo-session crashing when connected from "Media Controller Tester"

### ISSUE THREAD

**Issue by loki666** [androidx/media#78]
Demo session sample app is crashing when conneced from https://github.com/googlesamples/android-media-controller

Tested against both release and main branches

Crash with Android API 24
On API 26 & 28 it doesn’t crash, but returns no results when browsing
Works with Android API 29 & 30

Step to reproduce
deploy both apps on device
launch media controller test app
click "control" on Media3 Session Demo in the list 

`2022-05-20 11:50:09.972 9872-9872/androidx.media3.demo.session E/AndroidRuntime: FATAL EXCEPTION: main
    Process: androidx.media3.demo.session, PID: 9872
    java.lang.UnsupportedOperationException: It is not supported to send an error for [rootID]
        at androidx.media.MediaBrowserServiceCompat$Result.onErrorSent(MediaBrowserServiceCompat.java:944)
        at androidx.media.MediaBrowserServiceCompat$Result.sendError(MediaBrowserServiceCompat.java:889)
        at androidx.media3.session.MediaLibraryServiceLegacyStub.onLoadChildren(MediaLibraryServiceLegacyStub.java:178)
        at androidx.media3.session.MediaLibraryServiceLegacyStub.onLoadChildren(MediaLibraryServiceLegacyStub.java:168)
        at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21.onLoadChildren(MediaBrowserServiceCompat.java:427)
        at androidx.media.MediaBrowserServiceCompat$MediaBrowserServiceImplApi21$MediaBrowserServiceApi21.onLoadChildren(MediaBrowserServiceCompat.java:518)
        at android.service.media.MediaBrowserService.performLoadChildren(MediaBrowserService.java:662)
        at android.service.media.MediaBrowserService.addSubscription(MediaBrowserService.java:600)
        at android.service.media.MediaBrowserService.-wrap3(MediaBrowserService.java)
        at android.service.media.MediaBrowserService$ServiceBinder$3.run(MediaBrowserService.java:272)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)`

**Comment by marcbaechinger** [comment]
Thanks for reporting!

I think this is because the `PlaybackService` of the session demo does advertises `COMMAND_CODE_LIBRARY_SUBSCRIBE` but actually doesn't override `MediaLibrarySessionCallback.subscribe()`.  We already have implemented `subscribe` in the meanwhile and this will be fixed in the main branch soon and part of the next release.

**Comment by loki666** [comment]
Ok thanks.
I'll give it a try and let you know

**Comment by loki666** [comment]
mmmh, still crashing the same way.

I think the issue is because `controller` is null
https://github.com/androidx/media/blob/72a4fb082d9e68ecd7db3ff87b19f4232a5991d2/libraries/session/src/main/java/androidx/media3/session/MediaLibraryServiceLegacyStub.java#L178

**Comment by iTaysonLab** [comment]
Can confirm that this issue is reproducible on all Samsungs with Samsung Experience ROM (pre-One UI, also SDK 24), and it directly happens if you try to connect a `MediaController` directly to your application's `MediaLibraryService`.

Is there any workaround of it at the moment? Production users are reporting about the issues on such devices, and there is no possible way to override `onSubscribe` without disabling `MediaLibraryService` features (like losing Android Auto support)

**Comment by bubenheimer** [comment]
At the time of media3 1.0 release, the release announcement said that android-media-controller app would be updated within weeks for media3 support. Is that still on the radar? I really would like to poke at my controller pretty hard one of these days, including the media3-specific parts.

https://android-developers.googleblog.com/2023/03/media3-is-ready-to-play.html#:~:text=our%20testing%20tool%2C%20the%20Media%20Controller%20Test%20app%2C%20will%20also%20be%20updated%20to%20Media3%20on%20their%20main%20branches%20in%20the%20coming%20weeks

**Comment by tonihei** [comment]
@bubenheimer Thanks for the reminder! That's still on our radar and planned for the upcoming 1.4.0 release, sorry we didn't get around to publish the test app earlier.

**Comment by icbaker** [comment]
@bubenheimer The app is now published in https://github.com/androidx/media/commit/f54991eea103ae7ee30e9e217ca22bddfd6cd8da
