### ISSUE TITLE
video not playing

### ISSUE THREAD

**Issue by maven08** [androidx/media#794]
### Version

ExoPlayer 2.19.1

### More version details

releaseVersion = '2.19.1'
releaseVersionCode = 2_019_001

### Devices that reproduce the issue

1. vivo v23e 5G Android OS 11

2. Samsung M33 5G Android OS 13

3. One Plus 8T Android OS 13

4. Samsung Tab 3 Android OS 11

### Reproducible in the demo app?

Yes

### Reproduction steps

Try playing the stream in the demo application.

### Expected result

Media should play proerly 

### Actual result

Frames skipping

### Media

https://customer-592a255a0tcjq2h1.cloudflarestream.com/c4001bd24ade448f8fb0b2265e651d7f/manifest/video.m3u8

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by maven08** [comment]
@rohitjoins this one

**Comment by maven08** [comment]
@rohitjoins

**Comment by maven08** [comment]
I have created on both repo https://github.com/google/ExoPlayer/issues/11333

**Comment by FongMi** [comment]
It's looks perfect.

https://github.com/androidx/media/assets/3471963/facb5dfb-b387-4194-b71c-2f38512deedb

**Comment by maven08** [comment]
10 seconds of playback won't show you issue switch to time lapse of 9.34 and play for 5 more mins you will see video frames skipping also if you have access to android-media-github@google.com you can find my email where I have shared complete log report 

Audio sink error
                com.google.android.exoplayer2.audio.AudioSink$UnexpectedDiscontinuityException: Unexpected audio track timestamp discontinuity: expected 1000946541400, got 1000956562734
                    at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:999)
                    at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:709)
                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1889)
                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:782)
                    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
                    at android.os.Handler.dispatchMessage(Handler.java:102)
                    at android.os.Looper.loopOnce(Looper.java:226)
                    at android.os.Looper.loop(Looper.java:313)
                    at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by FongMi** [comment]
I think the exo team will says it's your video problem.

**Comment by maven08** [comment]
> I think the exo team will says it's your video problem. Because i have experience.

But it's working fine on VLC Player so I don't think media is having issue.

**Comment by maven08** [comment]
@rohitjoins have you checked this yet?

**Comment by rohitjoins** [comment]
Hi @maven08,

I haven't checked the media yet. 

> But it's working fine on VLC Player so I don't think media is having issue.

This is not necessarily true, we try and adhere to the spec when playing media. Other media players may have chosen other ways to fail or play media when it doesn't adhere to the spec which may not apply to ExoPlayer.
