### ISSUE TITLE
[IMA SDK] Crash when no WebView is installed

### ISSUE THREAD

**Issue by cdongieux** [androidx/media#795]
### Version

ExoPlayer 2.19.0

### Devices that reproduce the issue

Sony TV: Bravia 4K GB ATV3, Android 8

### Devices that do not reproduce the issue

Other Android or AndroidTV devices having WebView installed.

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play a media with VAST ads

### Expected result

The media plays successfully

### Actual result

The app crashes with the following stacktrace:

```
Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:438)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:211)
       at android.webkit.WebView.getFactory(WebView.java:2467)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2462)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2527)
       at android.view.View.<init>(View.java:4536)
       at android.view.View.<init>(View.java:4668)
       at android.view.ViewGroup.<init>(ViewGroup.java:597)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:636)
       at android.webkit.WebView.<init>(WebView.java:581)
       at android.webkit.WebView.<init>(WebView.java:564)
       at android.webkit.WebView.<init>(WebView.java:551)
       at android.webkit.WebView.<init>(WebView.java:541)
       at com.google.ads.interactivemedia.v3.internal.aiq.<init>(IMASDK:1)
       at com.google.ads.interactivemedia.v3.api.ImaSdkFactory.createAdsLoader(IMASDK:6)
       at com.google.ads.interactivemedia.v3.api.ImaSdkFactory.createAdsLoader(IMASDK:4)
       at com.google.android.exoplayer2.ext.ima.ImaAdsLoader$DefaultImaFactory.createAdsLoader(ImaAdsLoader.java:784)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.requestAds(AdTagLoader.java:545)
       at com.google.android.exoplayer2.ext.ima.AdTagLoader.<init>(AdTagLoader.java:281)
       at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.requestAds(ImaAdsLoader.java:478)
       at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.start(ImaAdsLoader.java:566)
       at com.google.android.exoplayer2.source.ads.AdsMediaSource.lambda$prepareSourceInternal$0(AdsMediaSource.java:201)
```

### Media

This crash is reported by Firebase Crashlytics for my app on production, I don't have the associated media but I guess any media having VAST ads will make the app crash on devices having no WebView installed.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment]
Thanks for reporting.

The Android CDD [`2.3.3. Software`](https://source.android.com/docs/compatibility/8.0/android-8.0-cdd#2_3_3_software) for Android 8 (and following versions), states that TV devices need to provide web compatibility as defined in [`3.4 Web Compatibility`](https://source.android.com/docs/compatibility/8.0/android-8.0-cdd#3_4_web_compatibility). This for instance means the device needs to report `android.software.webview` through the package manager and provide a web view accordingly:

```
context.getPackageManager.hasSystemFeature("android.software.webview")
```

For client side ads it looks fairly easy to avoid this by testing for the feature and then create a conventional  content media source instead of an `AdMediaSource`. The library could/should probably do this in the `DefaultMediaSourceFactory`. I doubt the factory should do this silently though but report this to the app somehow to give a chance to have this in analytics. We should look into this and think about sanitizing such cases.

For a quick fix. I don't know how you exactly create you `AdsMediaSource`.  Generally, check for the feature with the snippet above and don't add the adTag URI to the `MediaItem`. The `DefaultMediaSourceFactory` will then create a source without ad support.
