### ISSUE TITLE
unable to download video link with m3u8 file for android version less than 10 using media3 transformation

### ISSUE THREAD

**Issue by Kaleb09** [androidx/media#813]
### Version

Media3 1.1.1

### Devices that reproduce the issue

All android devices with android version less than 10

### Devices that do not reproduce the issue

All android devices with android version greater than or equal to10

### Reproducible in the demo app?

Yes

### Reproduction steps

add  m3u8 video link to the PRESET_FILE_URIS in the configuration activity of the demo app then run the app 
from the first activity choose the preset file that we added previously and export the video then you will get fatal error 

for the video link you can use this https://video.twimg.com/ext_tw_video/1724277349913694208/pu/pl/avc1/480x852/OIzk0NvR1pHHmatT.m3u8?container=fmp4

### Expected result

we expect to make the transformation successful  which works for android versions greater than or equal to 10

### Actual result

the actual result is the transformation fails with error fatal error

the error occur only for android version less than 10

the error log is
at com.google.android.exoplayer2.transformer.TransformerInternal.handleMessage(TransformerInternal.java:306)
at com.google.android.exoplayer2.transformer.TransformerInternal.$r8$lambda$wLcb-t1rNJBtxPBz3q3mAtv5x5M(TransformerInternal.java)
at com.google.android.exoplayer2.transformer.TransformerInternal$$ExternalSyntheticLambda3.handleMessage(D8$$SyntheticClass)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalStateException: Samples not in presentation order (133333 < 166666) unsupported on this API version
at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:107)
at com.google.android.exoplayer2.transformer.FrameworkMuxer.writeSampleData(FrameworkMuxer.java:176)
at com.google.android.exoplayer2.transformer.DefaultMuxer.writeSampleData(DefaultMuxer.java:97)
at com.google.android.exoplayer2.transformer.MuxerWrapper.writeSample(MuxerWrapper.java:243)
at com.google.android.exoplayer2.transformer.SamplePipeline.feedMuxer(SamplePipeline.java:125)
at com.google.android.exoplayer2.transformer.SamplePipeline.processData(SamplePipeline.java:73)
at com.google.android.exoplayer2.transformer.TransformerInternal.drainPipelinesInternal(TransformerInternal.java:327)
at com.google.android.exoplayer2.transformer.TransformerInternal.handaleMessage(TransformerInternal.java:292)
at com.google.android.exoplayer2.transformer.TransformerInternal.$r8$lambda$wLcb-t1rNJBtxPBz3q3mAtv5x5M(TransformerInternal.java) 
at com.google.android.exoplayer2.transformer.TransformerInternal$$ExternalSyntheticLambda3.handleMessage(D8$$SyntheticClass) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:154) 
at android.os.HandlerThread.run(HandlerThread.java:61) 

### Media

i got the following error log when i try to make media transformation with m3u8 video link i used the demo app and added my own m3u8 video link and try to make the transformation but it failed the app works perfectly with android versions greater than 9 but it doesn't work for versions equalto and less than 9 i got the following error logs

Export error

at com.google.android.exoplayer2.transformer.TransformerInternal.handleMessage(TransformerInternal.java:306)
at com.google.android.exoplayer2.transformer.TransformerInternal.$r8$lambda$wLcb-t1rNJBtxPBz3q3mAtv5x5M(TransformerInternal.java)
at com.google.android.exoplayer2.transformer.TransformerInternal$$ExternalSyntheticLambda3.handleMessage(D8$$SyntheticClass)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:154)
at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalStateException: Samples not in presentation order (133333 < 166666) unsupported on this API version
at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:107)
at com.google.android.exoplayer2.transformer.FrameworkMuxer.writeSampleData(FrameworkMuxer.java:176)
at com.google.android.exoplayer2.transformer.DefaultMuxer.writeSampleData(DefaultMuxer.java:97)
at com.google.android.exoplayer2.transformer.MuxerWrapper.writeSample(MuxerWrapper.java:243)
at com.google.android.exoplayer2.transformer.SamplePipeline.feedMuxer(SamplePipeline.java:125)
at com.google.android.exoplayer2.transformer.SamplePipeline.processData(SamplePipeline.java:73)
at com.google.android.exoplayer2.transformer.TransformerInternal.drainPipelinesInternal(TransformerInternal.java:327)
at com.google.android.exoplayer2.transformer.TransformerInternal.handaleMessage(TransformerInternal.java:292)
at com.google.android.exoplayer2.transformer.TransformerInternal.$r8$lambda$wLcb-t1rNJBtxPBz3q3mAtv5x5M(TransformerInternal.java) 
at com.google.android.exoplayer2.transformer.TransformerInternal$$ExternalSyntheticLambda3.handleMessage(D8$$SyntheticClass) 
at android.os.Handler.dispatchMessage(Handler.java:98) 
at android.os.Looper.loop(Looper.java:154) 
at android.os.HandlerThread.run(HandlerThread.java:61) 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by SheenaChhabra** [comment]
@Kaleb09 Thanks for reaching out. The support for out of order B-frame is only available after API 24 (platform limitation). In the upcoming releases, the support on API <= 24 will also be added using an InAppMuxer.
I can confirm that it should work fine for android version > 7. Can you please double check whether it fails for all versions < 10 as mentioned in the bug?
Please feel free to reopen the bug if it still reproduces.
