### ISSUE TITLE
Error occured when encode a video with videoEffects(Presentation.createForHeight(any value)) or set video bitrate with VideoEncoderSettings.

### ISSUE THREAD

**Issue by Ktaewon** [androidx/media#830]
### Version

Media3 1.2.0

### Devices that reproduce the issue

* Samsung S23+ running android 14
* Samsung S23 running android 14

### Devices that do not reproduce the issue

* Samsung S21 running android 14
* Samsung S22 running android 13
* Pixel 7 running android 14

### Reproducible in the demo app?

Yes

### Reproduction steps

1. launch demo app and choose preset file `1080P H265 video and AAC audio`
2. set output video resolution lower then original resolution(me set 720). (Some higher resolution is works. In this preset, 1440, 2560 is works)
3. press export and then exception occured.

### Expected result

```
stop() called but track is not started or stopped
2023-11-22 20:32:32.319 25924-10978 TransformerInternal     androidx.media3.demo.transformer     W  Export error after export ended
androidx.media3.transformer.ExportException: VideoEncoder error: mediaFormat={exo-pixel-width-height-ratio-float=1.0, sar-width=1, color-format=2130708361, i-frame-interval=1.0, is-forced-subtitle=0, mime=video/hevc, bitrate=3866761, priority=1, color-standard=1, operating-rate=2147483647, color-transfer=3, encoder-delay=0, sar-height=1, width=1280, bitrate-mode=1, is-autoselect=0, is-default=0, color-range=2, encoder-padding=0, frame-rate=30, rotation-degrees=0, height=720}, mediaCodecName=c2.qti.hevc.encoder
	at androidx.media3.transformer.DefaultCodec.createExportException(DefaultCodec.java:395)
	at androidx.media3.transformer.DefaultCodec.<init>(DefaultCodec.java:151)
	at androidx.media3.transformer.DefaultEncoderFactory.createForVideoEncoding(DefaultEncoderFactory.java:329)
	at androidx.media3.transformer.DefaultEncoderFactory.createForVideoEncoding(DefaultEncoderFactory.java:47)
	at androidx.media3.transformer.CapturingEncoderFactory.createForVideoEncoding(CapturingEncoderFactory.java:41)
	at androidx.media3.transformer.VideoSamplePipeline$EncoderWrapper.getSurfaceInfo(VideoSamplePipeline.java:453)
	at androidx.media3.transformer.VideoSamplePipeline$1.onOutputSizeChanged(VideoSamplePipeline.java:173)
	at androidx.media3.effect.FinalShaderProgramWrapper.lambda$ensureConfigured$4$androidx-media3-effect-FinalShaderProgramWrapper(FinalShaderProgramWrapper.java:407)
	at androidx.media3.effect.FinalShaderProgramWrapper$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at androidx.media3.effect.FinalShaderProgramWrapper.ensureConfigured(FinalShaderProgramWrapper.java:405)
	at androidx.media3.effect.FinalShaderProgramWrapper.renderFrame(FinalShaderProgramWrapper.java:320)
	at androidx.media3.effect.FinalShaderProgramWrapper.queueInputFrame(FinalShaderProgramWrapper.java:212)
	at androidx.media3.effect.FrameConsumptionManager.lambda$queueInputFrame$1$androidx-media3-effect-FrameConsumptionManager(FrameConsumptionManager.java:89)
	at androidx.media3.effect.FrameConsumptionManager$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at androidx.media3.effect.VideoFrameProcessingTaskExecutor.lambda$wrapTaskAndSubmitToExecutorService$2$androidx-media3-effect-VideoFrameProcessingTaskExecutor(VideoFrameProcessingTaskExecutor.java:184)
	at androidx.media3.effect.VideoFrameProcessingTaskExecutor$$ExternalSyntheticLambda2.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.media.MediaCodec$CodecException: 
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2332)
	at android.media.MediaCodec.configure(MediaCodec.java:2248)
	at androidx.media3.transformer.DefaultCodec.configureCodec(DefaultCodec.java:421)
	at androidx.media3.transformer.DefaultCodec.<init>(DefaultCodec.java:114)
	at androidx.media3.transformer.DefaultEncoderFactory.createForVideoEncoding(DefaultEncoderFactory.java:329) 
	at androidx.media3.transformer.DefaultEncoderFactory.createForVideoEncoding(DefaultEncoderFactory.java:47) 
	at androidx.media3.transformer.CapturingEncoderFactory.createForVideoEncoding(CapturingEncoderFactory.java:41) 
	at androidx.media3.transformer.VideoSamplePipeline$EncoderWrapper.getSurfaceInfo(VideoSamplePipeline.java:453) 
	at androidx.media3.transformer.VideoSamplePipeline$1.onOutputSizeChanged(VideoSamplePipeline.java:173) 
	at androidx.media3.effect.FinalShaderProgramWrapper.lambda$ensureConfigured$4$androidx-media3-effect-FinalShaderProgramWrapper(FinalShaderProgramWrapper.java:407) 
	at androidx.media3.effect.FinalShaderProgramWrapper$$ExternalSyntheticLambda6.run(Unknown Source:4) 
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) 
	at androidx.media3.effect.FinalShaderProgramWrapper.ensureConfigured(FinalShaderProgramWrapper.java:405) 
	at androidx.media3.effect.FinalShaderProgramWrapper.renderFrame(FinalShaderProgramWrapper.java:320) 
	at androidx.media3.effect.FinalShaderProgramWrapper.queueInputFrame(FinalShaderProgramWrapper.java:212) 
	at androidx.media3.effect.FrameConsumptionManager.lambda$queueInputFrame$1$androidx-media3-effect-FrameConsumptionManager(FrameConsumptionManager.java:89) 
	at androidx.media3.effect.FrameConsumptionManager$$ExternalSyntheticLambda1.run(Unknown Source:6) 
	at androidx.media3.effect.VideoFrameProcessingTaskExecutor.lambda$wrapTaskAndSubmitToExecutorService$2$androidx-media3-effect-VideoFrameProcessingTaskExecutor(VideoFrameProcessingTaskExecutor.java:184) 
	at androidx.media3.effect.VideoFrameProcessingTaskExecutor$$ExternalSyntheticLambda2.run(Unknown Source:6) 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487) 
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	at java.lang.Thread.run(Thread.java:1012) 
2023-11-22 20:32:32.322 25924-25924 Toast                   androidx.media3.demo.transformer     I  show: caller = androidx.media3.demo.transformer.TransformerActivity.onError:641 
2023-11-22 20:32:32.323 25924-25924 Toast                   androidx.media3.demo.transformer     I  show: isDexDualMode = false
2023-11-22 20:32:32.323 25924-25924 Toast                   androidx.media3.demo.transformer     I  show: contextDispId = 0 mCustomDisplayId = -1 focusedDisplayId = 0 isActivityContext = false
2023-11-22 20:32:32.330 25924-25924 TransformerActivity     androidx.media3.demo.transformer     E  Export error
  androidx.media3.transformer.ExportException: VideoDecoder error: mediaFormat={exo-pixel-width-height-ratio-float=1.0, sar-width=1, is-forced-subtitle=0, allow-frame-drop=0, level=1024, mime=video/hevc, profile=1, codecs-string=hvc1.1.6.L120.90, encoder-delay=0, sar-height=1, width=1920, is-autoselect=0, is-default=0, encoder-padding=0, frame-rate=29.969316, max-input-size=175633, rotation-degrees=0, height=1080, csd-0=java.nio.HeapByteBuffer[pos=0 lim=999 cap=999]}, mediaCodecName=c2.qti.hevc.decoder
      at androidx.media3.transformer.DefaultCodec.createExportException(DefaultCodec.java:395)
      at androidx.media3.transformer.DefaultCodec.createExportException(DefaultCodec.java:379)
      at androidx.media3.transformer.DefaultCodec.maybeDequeueInputBuffer(DefaultCodec.java:186)
      at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.feedDecoderFromInput(ExoAssetLoaderBaseRenderer.java:281)
      at androidx.media3.transformer.ExoAssetLoaderBaseRenderer.render(ExoAssetLoaderBaseRenderer.java:112)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loopOnce(Looper.java:230)
      at android.os.Looper.loop(Looper.java:319)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: java.lang.IllegalStateException: Invalid to call at Released state; only valid in executing state
  
      at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
      at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:3139)
      at androidx.media3.transformer.DefaultCodec.maybeDequeueInputBuffer(DefaultCodec.java:183)
      ... 8 more
```

### Actual result

Transformer exports the video with the set resolution.

### Media

Not working preset files:
* All preset files

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by andrewlewis** [comment]
Thanks for the bug report. The logcat contains this crash, which looks the same as the one in the other bug, so I'll mark this as a duplicate.

```

11-22 20:31:37.526  1046 10294 10510 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : Build fingerprint: 'samsung/dm2qksx/dm2q:14/UP1A.231005.007/S916NKSU2BWK7:user/release-keys'
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : Revision: '13'
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : ABI: 'arm64'
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : Processor: '-1'
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : Timestamp: 2023-11-22 20:31:37.450620127+0900
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : Process uptime: 67s
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : Cmdline: media.hwcodec /vendor.qti.media.c2@1.0-service
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : pid: 10294, tid: 10510, name: HwBinder:10294_  >>> media.hwcodec <<<
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : uid: 1046
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : signal 0 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : Abort message: 'ubsan: mul-overflow'
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x0  0000000000000000  x1  000000000000290e  x2  0000000000000006  x3  00000075eda59e50
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x4  0000000000000010  x5  0000000000000010  x6  0000000000000010  x7  7f7f7f7f7f7f7f7f
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x8  00000000000000f0  x9  00000076866dbf28  x10 0000000000000001  x11 0000007686758344
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x12 00000075f8d6a1fc  x13 00000076866da598  x14 0000000004000000  x15 0000000000000028
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x16 00000076867c3a00  x17 000000768679be60  x18 00000075ecada000  x19 0000000000002836
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x20 000000000000290e  x21 00000000ffffffff  x22 00000075eda59fb0  x23 00000075eda59ff8
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x24 0000000000000000  x25 00000075eda5b000  x26 b4000075d7dc3640  x27 b400007604799c70
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     x28 0000000000000000  x29 00000075eda59ed0
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :     lr  0000007686749084  sp  00000075eda59e30  pc  00000076867490b0  pst 0000000000001000
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : 19 total frames
11-22 20:31:37.526  1046 10294 10510 F DEBUG   : backtrace:
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :       #00 pc 00000000000950b0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 02a91a85343debb2911714273ff2b670)
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :       #01 pc 000000000006c3e0  /vendor/lib64/libqcodec2_v4l2codec.so (__ubsan_handle_mul_overflow_minimal_abort+64) (BuildId: 73c4a5b66eb4b5cd62a6f94229d04e37)
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :       #02 pc 00000000000a4634  /vendor/lib64/libqcodec2_v4l2codec.so (BuildId: 73c4a5b66eb4b5cd62a6f94229d04e37)
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :       #03 pc 00000000000a4980  /vendor/lib64/libqcodec2_v4l2codec.so (BuildId: 73c4a5b66eb4b5cd62a6f94229d04e37)
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :       #04 pc 000000000008c738  /vendor/lib64/libcodec2_vndk.so (C2InterfaceHelper::ParamHelper::Impl::trySet(C2Param const*, bool, bool*, C2InterfaceHelper::Factory&, std::__1::vector<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> >, std::__1::allocator<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> > > >*)+92) (BuildId: 06168e79b848d2f330955e9339b7510e)
11-22 20:31:37.526  1046 10294 10510 F DEBUG   :       #05 pc 000000000008ffb4  /vendor/lib64/libcodec2_vndk.so (C2InterfaceHelper::config(std::__1::vector<C2Param*, std::__1::allocator<C2Param*> > const&, c2_blocking_t, std::__1::vector<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> >, std::__1::allocator<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> > > >*, bool, std::__1::vector<std::__1::shared_ptr<C2Param>, std::__1::allocator<std::__1::shared_ptr<C2Param> > >*)+852) (BuildId: 06168e79b848d2f330955e9339b7510e)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #06 pc 0000000000054fe4  /vendor/lib64/libqcodec2_core.so (qc2::QC2ComponentInterface2::config_locked(std::__1::vector<C2Param*, std::__1::allocator<C2Param*> > const&, c2_blocking_t, std::__1::vector<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> >, std::__1::allocator<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> > > >*)+344) (BuildId: ab8c50b2b11df6cd92160944071e145d)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #07 pc 0000000000053980  /vendor/lib64/libqcodec2_core.so (qc2::QC2ComponentInterface2::config_vb(std::__1::vector<C2Param*, std::__1::allocator<C2Param*> > const&, c2_blocking_t, std::__1::vector<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> >, std::__1::allocator<std::__1::unique_ptr<C2SettingResult, std::__1::default_delete<C2SettingResult> > > >*)+140) (BuildId: ab8c50b2b11df6cd92160944071e145d)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #08 pc 0000000000035728  /vendor/lib64/libcodec2_hidl@1.0.so (android::hardware::media::c2::V1_0::utils::CachedConfigurable::config(android::hardware::hidl_vec<unsigned char> const&, bool, std::__1::function<void (android::hardware::media::c2::V1_0::Status, android::hardware::hidl_vec<android::hardware::media::c2::V1_0::SettingResult> const&, android::hardware::hidl_vec<unsigned char> const&)>)+272) (BuildId: d1574c8b827f8b8c9141fd88a8793ec1)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #09 pc 000000000007c8b0  /vendor/lib64/android.hardware.media.c2@1.0.so (android::hardware::media::c2::V1_0::BnHwConfigurable::_hidl_config(android::hidl::base::V1_0::BnHwBase*, android::hardware::Parcel const&, android::hardware::Parcel*, std::__1::function<void (android::hardware::Parcel&)>) (.cfi)+596) (BuildId: 7a702ab41bc0cc235dbbb287f984839c)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #10 pc 000000000007ba6c  /vendor/lib64/android.hardware.media.c2@1.0.so (android::hardware::media::c2::V1_0::BnHwConfigurable::onTransact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>)+672) (BuildId: 7a702ab41bc0cc235dbbb287f984839c)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #11 pc 0000000000083750  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::BHwBinder::transact(unsigned int, android::hardware::Parcel const&, android::hardware::Parcel*, unsigned int, std::__1::function<void (android::hardware::Parcel&)>)+156) (BuildId: 0b7c7ec657276a97287f4882b617fa4a)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #12 pc 000000000008870c  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::IPCThreadState::executeCommand(int)+2784) (BuildId: 0b7c7ec657276a97287f4882b617fa4a)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #13 pc 0000000000087acc  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::IPCThreadState::getAndExecuteCommand()+224) (BuildId: 0b7c7ec657276a97287f4882b617fa4a)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #14 pc 0000000000088c98  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::IPCThreadState::joinThreadPool(bool)+172) (BuildId: 0b7c7ec657276a97287f4882b617fa4a)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #15 pc 0000000000094220  /apex/com.android.vndk.v33/lib64/libhidlbase.so (android::hardware::PoolThread::threadLoop()+24) (BuildId: 0b7c7ec657276a97287f4882b617fa4a)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #16 pc 0000000000012f18  /apex/com.android.vndk.v33/lib64/libutils.so (android::Thread::_threadLoop(void*)+416) (BuildId: c200e9a85d2415f28f0687a94e6b8643)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #17 pc 00000000000fd0f4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 02a91a85343debb2911714273ff2b670)
11-22 20:31:37.527  1046 10294 10510 F DEBUG   :       #18 pc 0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 02a91a85343debb2911714273ff2b670)
```
