### ISSUE TITLE
Downloads stuck if app is force closed

### ISSUE THREAD

**Issue by kelmer44** [androidx/media#831]
I've managed to repro this with the horologist app, for instance, and it also happens with my own app:

If I start a couple downloads, and force stop the app before they finish (either with adb force stop or in the Android task manager), the downloads wont resume when the app is restarted.

I know this is due to the DownloadService not being started, because once I start another download those pending downloads start downloading again. However if I try to start the service manually with:

        DownloadService.startForeground(context, SxmDownloadService::class.java)

I get the dreaded `android.app.ForegroundServiceStartNotAllowedException` exception. Whats the right approach here?

**Comment by tianyif** [comment]
Hi @kelmer44,

Yes, you can start the service with `DownloadService.start` method that you referred to. As an example, the demo app [starts the download service](https://github.com/androidx/media/blob/release/demos/main/src/main/java/androidx/media3/demo/main/SampleChooserActivity.java#L128) when the `SampleChooserActivity` is created.

The reason being this is, the service is created after `Context.startService` and `onCreate()` is called. The `DownloadService` calls [`DownloadManager.resumeDownloads`](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/offline/DownloadService.java#L602) in `onCreate()`, which resumes any ongoing downloads.

**Comment by kelmer44** [comment]
Thanks @tianyif  I have a follow up question.

My app has a periodic Worker that checks against a backedn service and triggers a few downloads if needed. This can obviously happen in the background. 

My worker will eventually call:

```
  DownloadService.sendAddDownload(
            context,
            MyDownload::class.java,
            downloadRequest,
            false
        )
```

but this errors when the app is in the background with:

failed because it threw an exception/error as starting services is not allowed from the background:

                                                                     ```
 java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Not allowed to start service Intent { act=androidx.media3.exoplayer.downloadService.action.ADD_DOWNLOAD cmp=com.sirius/com.sxmp.downloads.downloader.asset.manager.SxmDownloadService (has extras) }: app is in background uid UidRecord{12c6aa7 u0a641 TRNB bg:+14m9s172ms idle change:uncached procs:1 seq(0,0,0)}
                                                                      	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                                                                      	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                      	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                                                                      	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                      	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                      	at java.lang.Thread.run(Thread.java:923)
```

When I try to set foreground to true like:

        DownloadService.sendAddDownload(
            context,
            SxmDownloadService::class.java,
            downloadRequest,
            true
        )

then I get the dreaded:

                                                                     ```
 java.util.concurrent.ExecutionException: android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.sirius/com.sxmp.downloads.downloader.asset.manager.SxmDownloadService
                                                                      	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
                                                                      	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
                                                                      	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:317)
                                                                      	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                      	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                      	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                      	at java.lang.Thread.run(Thread.java:1012)
```

So im really not sure how to solve this, is it even possible to trigger download starts from the background with media3?

**Comment by kelmer44** [comment]
Ill rephrase my question to:

the DownloadService is technically not needed right? If one creates his own notifications and triggers download actions through the DownloadManager (injecting it for instance) one should not have any need for the Service. Am i correct in this assumption @tianyif ?
