### ISSUE TITLE
Realtime RTSP with realtime OPUS audio problem

### ISSUE THREAD

**Issue by lonewolf73** [androidx/media#838]
After reading issue [Add support for RTSP Opus](https://github.com/androidx/media/pull/53) about Opus support in RTSP streaming, I have a realtime RTSP stream from an IP camera so ID header could be correctly missing because stream is already on play and in fact I obtain always this error: 

```
Unexpected exception loading stream
                            java.lang.IllegalArgumentException: ID Header missing
                                at androidx.media3.common.util.Assertions.checkArgument(Assertions.java:55)
                                at androidx.media3.exoplayer.rtsp.reader.RtpOpusReader.validateOpusIdHeader(RtpOpusReader.java:146)
                                at androidx.media3.exoplayer.rtsp.reader.RtpOpusReader.consume(RtpOpusReader.java:90)
                                at androidx.media3.exoplayer.rtsp.RtpExtractor.read(RtpExtractor.java:178)
                                at androidx.media3.exoplayer.rtsp.RtpDataLoadable.load(RtpDataLoadable.java:177)
                                at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:417)
                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                at java.lang.Thread.run(Thread.java:1012)
```

so since it's a realtime RTSP streaming , is there a way to avoid this ID header check ? Maybe like a parameter to pass to  RtpOpusReader.java's function checkForOpusIdHeader() ?.... 
(Previously I used libvlc and it ignored ID header if being in a network stream but libvlc is pretty huge as library...)

Thanks to all! Cheers!

**Comment by lonewolf73** [comment]
UPDATE : following this page [Opus decoder module](https://github.com/androidx/media/tree/release/libraries/decoder_opus) , I tried to compile inside ubuntu obtaining those libopusV2JNI.so libraries... then I copied those libraries inside jniLibs in my Android Studio project  on Windows and I added in gradle:

```
ndk {
	moduleName "libopusV2JNI"
}
```

and 

```
sourceSets {
	main {
		jniLibs.srcDir 'src/main/jniLibs'
	
	}
}
```

and

`implementation fileTree(dir: 'jniLibs', include: ['*.so'])`

then I settled : 

```
renderersFactory = new DefaultRenderersFactory( popupcamvideoView.getContext() )
		.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER);
```

as explained in that page to give `LibopusAudioRenderer` priority but seems .so library doesn't contain any `LibopusAudioRenderer` class because even trying to declare `LibopusAudioRenderer variable` in my project it doesn't find anything.... maybe did I missed something since explanation in [Using the module with ExoPlayer](https://github.com/androidx/media/tree/release/libraries/decoder_opus#using-the-module-with-exoplayer) is not so clear ?... 

Thanks! Cheers!

**Comment by lonewolf73** [comment]
Solved... had to put androidx .java sources in project then recompile everthing directly via PowerShell and now it works even if my audio stream cannot be decoded because Initialization Data size returns 0... thanks anyway

**Comment by lonewolf73** [comment]
Solved... had to put androidx .java sources in project then recompile everthing directly via PowerShell and now it works even if my audio stream cannot be decoded because Initialization Data size returns 0... thanks anyway
