### ISSUE TITLE
Possibility to wrap RtpOpusReader.java to consider log-session-id in AMessage?

### ISSUE THREAD

**Issue by lonewolf73** [androidx/media#859]
Hello everyone! 

I am trying to play a RTSP audio stream in my Java App which codec is audio/opus using media3 exoplayer 1.2.0
If I try to play , it goes normally with this error: 

```
LoadTask                E  Unexpected exception loading stream
                             java.lang.IllegalArgumentException: ID Header missing
                                 at androidx.media3.common.util.Assertions.checkArgument(Assertions.java:55)
                                 at androidx.media3.exoplayer.rtsp.reader.RtpOpusReader.validateOpusIdHeader(RtpOpusReader.java:146)
                                 at androidx.media3.exoplayer.rtsp.reader.RtpOpusReader.consume(RtpOpusReader.java:90)
                                 at androidx.media3.exoplayer.rtsp.RtpExtractor.read(RtpExtractor.java:178)
                                 at androidx.media3.exoplayer.rtsp.RtpDataLoadable.load(RtpDataLoadable.java:177)
                                 at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:417)
                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                 at java.lang.Thread.run(Thread.java:1012)
ExoPlayerImplInternal   E  Playback error
                             androidx.media3.exoplayer.ExoPlaybackException: Source error
```

but if I look in LogCat about stream analyzing I see : 

```
EventLogger             D  state [eventTime=5.47, mediaPos=0.00, window=0, period=0, BUFFERING]
EventLogger             D  loading [eventTime=6.49, mediaPos=0.00, window=0, period=0, true]
EventLogger             D  timeline [eventTime=6.49, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
EventLogger             D    period [?]
EventLogger             D    window [?, seekable=false, dynamic=false]
EventLogger             D  ]
BufferPoolAccessor2.0   D  evictor expired: 1, evicted: 0
TrafficStats            D  tagSocket(112) with statsTag=0xffffffff, statsUid=-1
TrafficStats            D  tagSocket(138) with statsTag=0xffffffff, statsUid=-1
DMCodecAdapterFactory   I  Creating an asynchronous MediaCodec adapter for track type audio
EventLogger             D  audioEnabled [eventTime=7.11, mediaPos=0.00, window=0, period=0]
MediaCodec              I  (0xb400007977f10fb0) init name(c2.android.opus.decoder)
CCodec                  D  allocate(c2.android.opus.decoder)
EventLogger             D  tracks [eventTime=7.11, mediaPos=0.00, window=0, period=0
EventLogger             D    group [
EventLogger             D      [X] Track:0, id=null, mimeType=audio/opus, channels=2, sample_rate=48000, supported=YES
EventLogger             D    ]
EventLogger             D  ]
CCodec                  I  setting up 'default' as default (vendor) store
CCodec                  I  Created component [c2.android.opus.decoder]
CCodecConfig            D  read media type: audio/opus
ReflectedParamUpdater   D  extent() != 1 for single value type: algo.buffers.max-count.values
ReflectedParamUpdater   D  extent() != 1 for single value type: output.subscribed-indices.values
ReflectedParamUpdater   D  extent() != 1 for single value type: input.buffers.allocator-ids.values
ReflectedParamUpdater   D  extent() != 1 for single value type: output.buffers.allocator-ids.values
ReflectedParamUpdater   D  extent() != 1 for single value type: algo.buffers.allocator-ids.values
ReflectedParamUpdater   D  extent() != 1 for single value type: output.buffers.pool-ids.values
ReflectedParamUpdater   D  extent() != 1 for single value type: algo.buffers.pool-ids.values
CCodecConfig            I  query failed after returning 7 values (BAD_INDEX)
CCodecConfig            D  c2 config diff is Dict {
                             c2::u32 coded.bitrate.value = 6000
                             c2::u32 input.buffers.max-size.value = 5760
                             c2::u32 input.delay.value = 0
                             string input.media-type.value = "audio/opus"
                             string output.media-type.value = "audio/raw"
                             c2::u32 raw.channel-count.value = 1
                             c2::u32 raw.sample-rate.value = 48000
                           }
MediaCodec              I  (0xb400007977f10fb0) Component Allocated (c2.android.opus.decoder)
MediaCodec              I  MediaCodec will operate in async mode
MediaCodec              I  (0xb400007977f10fb0) configure surface(0x0) crypto(0x0) flags(0)
MediaCodec              D  (0xb400007977f10fb0) configure format: AMessage(what = 0x00000000) = {
                                                                      float operating-rate = 48000.000000
                                                                      string log-session-id = "6T6xOhZNtcDfmPN0"
                                                                      int32_t sample-rate = 48000
                                                                      string mime = "audio/opus"
                                                                      int32_t channel-count = 2
                                                                      int32_t priority = 0
                                 int32_t max-output-channel-count = 99
                               }
MediaCodec              D  flushMediametrics
CCodec                  D  [c2.android.opus.decoder] buffers are bound to CCodec for this session
CCodecConfig            D  no c2 equivalents for log-session-id
CCodecConfig            D  no c2 equivalents for flags
CCodecConfig            D  c2 config diff is   c2::u32 raw.channel-count.value = 2
Codec2Client            W  query -- param skipped: index = 1107298332.
CCodec                  D  encoding statistics level = 0
CCodec                  D  setup formats input: AMessage(what = 0x00000000) = {
                             int32_t bitrate = 6000
                             int32_t channel-count = 2
                             int32_t max-input-size = 5760
                             string mime = "audio/opus"
                             int32_t sample-rate = 48000
                           }
CCodec                  D  setup formats output: AMessage(what = 0x00000000) = {
                             int32_t channel-count = 2
                             string mime = "audio/raw"
                             int32_t sample-rate = 48000
                             int32_t android._config-pcm-encoding = 2
                           }
CCodecConfig            I  query failed after returning 7 values (BAD_INDEX)
MediaCodec              I  (0xb400007977f10fb0) start
MediaCodec              D  keep callback message for reclaim
Codec2Client            W  query -- param skipped: index = 1342179345.
Codec2Client            W  query -- param skipped: index = 2415921170.
CCodecBufferChannel     D  [c2.android.opus.decoder#215] Created input block pool with allocatorID 16 => poolID 18 - OK (0)
CCodecBufferChannel     I  [c2.android.opus.decoder#215] Created output block pool with allocatorID 16 => poolID 1428 - OK
CCodecBufferChannel     D  [c2.android.opus.decoder#215] Configured output block pool ids 1428 => OK
CCodecBufferChannel     D  [c2.android.opus.decoder#215] start: updating output delay 0
MediaCodec              I  (0xb400007977f10fb0) kWhatStartCompleted
EventLogger             D  audioDecoderInitialized [eventTime=7.13, mediaPos=0.00, window=0, period=0, c2.android.opus.decoder]
EventLogger             D  audioInputFormat [eventTime=7.13, mediaPos=0.00, window=0, period=0, id=null, mimeType=audio/opus, channels=2, sample_rate=48000]
```

where audioInputFormat returns just in fact `id=null`

`audioInputFormat [eventTime=7.13, mediaPos=0.00, window=0, period=0, id=null, mimeType=audio/opus, channels=2, sample_rate=48000]`

but looking better in the messages of stream I can see in particular this: 

```
MediaCodec              D  (0xb400007977f10fb0) configure format: AMessage(what = 0x00000000) = {
																  float operating-rate = 48000.000000
																  string log-session-id = "6T6xOhZNtcDfmPN0"
																  int32_t sample-rate = 48000
																  string mime = "audio/opus"
																  int32_t channel-count = 2
																  int32_t priority = 0
							 int32_t max-output-channel-count = 99
                               }
```

where id is represented by parameter `log-session-id` .... I suspect maybe `audioInputFormat` doesn't check for `log-session-id` but for ID represented differently .... is that right? 

If yes , is there a way to wrap someway that `audioInputFormat` to force read log-session-id as ID so it passes as not null and plays the stream? Or even better pass the name of ID label from my code so it would accept as parameter and read that parameter as ID because could depends from the source?... 

Thanks in advance!! 
Cheers!!!

**Comment by lonewolf73** [comment]
HI @tonihei  !! Thanks for your answer ... I investigated more and it's pure Opus stream, not contained into OGG... 
So I tried to compile and attach sources of `androidx.media3.decoder.opus` which contains `LibopusAudioRenderer` class, then I tried to run and see if it'd works.
But even if stream is playing , on Logcat it reports error about `androidx.media3.decoder.opus.OpusDecoderException: Invalid initialization data size` even if a stream exists and its playing... Here what Logcat reports: 

```
nativeloader            com.libopus_test                D  Configuring clns-4 for other apk /data/app/~~7Qmy93ASPhVq0GlMtSqicQ==/com.libopus_test-Z2GwjvZYzM3-3xfU9uzr8Q==/base.apk. target_sdk_version=34, uses_libraries=, library_path=/data/app/~~7Qmy93ASPhVq0GlMtSqicQ==/com.libopus_test-Z2GwjvZYzM3-3xfU9uzr8Q==/lib/arm64:/data/app/~~7Qmy93ASPhVq0GlMtSqicQ==/com.libopus_test-Z2GwjvZYzM3-3xfU9uzr8Q==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/com.libopus_test
GraphicsEnvironment     com.libopus_test                V  ANGLE Developer option for 'com.libopus_test' set to: 'default'
GraphicsEnvironment     com.libopus_test                V  ANGLE GameManagerService for com.libopus_test: false
GraphicsEnvironment     com.libopus_test                V  Updatable production driver is not supported on the device.
NetworkSecurityConfig   com.libopus_test                D  No Network Security Config specified, using platform default
NetworkSecurityConfig   com.libopus_test                D  No Network Security Config specified, using platform default
Typeface                com.libopus_test                I  updateThemeFont new=Rookery-Regular;old=sans-serif;new=Rookery-Stacked;old=
AppCompatDelegate       com.libopus_test                D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
ea.libopus_test         com.libopus_test                W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
ea.libopus_test         com.libopus_test                W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
Compatibil...geReporter com.libopus_test                D  Compat change id reported: 210923482; UID 10404; state: ENABLED
Compatibil...geReporter com.libopus_test                D  Compat change id reported: 171228096; UID 10404; state: ENABLED
ExoPlayerImpl           com.libopus_test                I  Init fff1640 [AndroidXMedia3/1.2.0] [berlin, motorola edge 20, motorola, 33]
ea.libopus_test         com.libopus_test                W  Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (unsupported, reflection, allowed)
DefaultRenderersFactory com.libopus_test                I  Loaded LibopusAudioRenderer.
EventLogger             com.libopus_test                D  timeline [eventTime=0.00, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
EventLogger             com.libopus_test                D    period [?]
EventLogger             com.libopus_test                D    window [?, seekable=false, dynamic=true]
EventLogger             com.libopus_test                D  ]
EventLogger             com.libopus_test                D  mediaItem [eventTime=0.01, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
EventLogger             com.libopus_test                D  state [eventTime=0.01, mediaPos=0.00, window=0, BUFFERING]
TrafficStats            com.libopus_test                D  tagSocket(110) with statsTag=0xffffffff, statsUid=-1
EventLogger             com.libopus_test                D  playWhenReady [eventTime=0.02, mediaPos=0.00, window=0, true, USER_REQUEST]
ViewRootImpl            com.libopus_test                D  update {(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x1030300
                                                             fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
                                                             pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
                                                             bhv=DEFAULT
                                                             fitSides=} by setView
Choreographer           com.libopus_test                I  Skipped 31 frames!  The application may be doing too much work on its main thread.
AdrenoGLES-0            com.libopus_test                I  QUALCOMM build                   : eaa701cd06, I183f6321f0
                                                           Build Date                       : 10/27/22
                                                           OpenGL ES Shader Compiler Version: EV031.35.01.12
                                                           Local Branch                     : 
                                                           Remote Branch                    : 
                                                           Remote Branch                    : 
                                                           Reconstruct Branch               : 
AdrenoGLES-0            com.libopus_test                I  Build Config                     : S P 10.0.7 AArch64
AdrenoGLES-0            com.libopus_test                I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
AdrenoGLES-0            com.libopus_test                I  PFP: 0x016dc094, ME: 0x00000000
OpenGLRenderer          com.libopus_test                I  setGrContext nullptr-->validptr
EventLogger             com.libopus_test                D  surfaceSize [eventTime=0.11, mediaPos=0.00, window=0, 1080, 2250]
SurfaceSyncer           com.libopus_test                E  Failed to find sync for id=0
Parcel                  com.libopus_test                W  Expecting binder but got null!
EventLogger             com.libopus_test                D  timeline [eventTime=0.17, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
EventLogger             com.libopus_test                D    period [?]
EventLogger             com.libopus_test                D    window [?, seekable=false, dynamic=false]
EventLogger             com.libopus_test                D  ]
EventLogger             com.libopus_test                D  loading [eventTime=0.17, mediaPos=0.00, window=0, period=0, true]
TrafficStats            com.libopus_test                D  tagSocket(120) with statsTag=0xffffffff, statsUid=-1
EventLogger             com.libopus_test                D  timeline [eventTime=0.66, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
EventLogger             com.libopus_test                D    period [?]
EventLogger             com.libopus_test                D    window [?, seekable=false, dynamic=false]
EventLogger             com.libopus_test                D  ]
TrafficStats            com.libopus_test                D  tagSocket(140) with statsTag=0xffffffff, statsUid=-1
VideoCapabilities       com.libopus_test                W  Unrecognized profile/level 0/3 for video/mpeg2
VideoCapabilities       com.libopus_test                W  Unrecognized profile/level 0/3 for video/mpeg2
EventLogger             com.libopus_test                D  audioEnabled [eventTime=0.88, mediaPos=0.00, window=0, period=0]
DecoderAudioRenderer    com.libopus_test                E  Audio codec error
                                                             androidx.media3.decoder.opus.OpusDecoderException: Invalid initialization data size
                                                                 at androidx.media3.decoder.opus.OpusDecoder.<init>(OpusDecoder.java:96)
                                                                 at androidx.media3.decoder.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:117)
                                                                 at androidx.media3.decoder.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:34)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.maybeInitDecoder(DecoderAudioRenderer.java:729)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.onInputFormatChanged(DecoderAudioRenderer.java:782)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.render(DecoderAudioRenderer.java:298)
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1079)
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:529)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                 at android.os.Looper.loopOnce(Looper.java:238)
                                                                 at android.os.Looper.loop(Looper.java:357)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:85)
EventLogger             com.libopus_test                D  tracks [eventTime=0.88, mediaPos=0.00, window=0, period=0
EventLogger             com.libopus_test                D    group [
EventLogger             com.libopus_test                D      [X] Track:0, id=null, mimeType=audio/opus, channels=2, sample_rate=48000, supported=YES
EventLogger             com.libopus_test                D    ]
EventLogger             com.libopus_test                D  ]
ExoPlayerImplInternal   com.libopus_test                E  Playback error
                                                             androidx.media3.exoplayer.ExoPlaybackException: LibopusAudioRenderer error, index=1, format=Format(null, null, null, audio/opus, null, -1, null, [-1, -1, -1.0, null], [2, 48000]), format_supported=YES
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                 at android.os.Looper.loopOnce(Looper.java:238)
                                                                 at android.os.Looper.loop(Looper.java:357)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:85)
                                                             Caused by: androidx.media3.decoder.opus.OpusDecoderException: Invalid initialization data size
                                                                 at androidx.media3.decoder.opus.OpusDecoder.<init>(OpusDecoder.java:96)
                                                                 at androidx.media3.decoder.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:117)
                                                                 at androidx.media3.decoder.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:34)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.maybeInitDecoder(DecoderAudioRenderer.java:729)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.onInputFormatChanged(DecoderAudioRenderer.java:782)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.render(DecoderAudioRenderer.java:298)
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1079)
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:529)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                 at android.os.Looper.loopOnce(Looper.java:238)
                                                                 at android.os.Looper.loop(Looper.java:357)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:85)
EventLogger             com.libopus_test                D  audioDisabled [eventTime=0.90, mediaPos=0.00, window=0, period=0]
EventLogger             com.libopus_test                D  timeline [eventTime=0.90, mediaPos=0.00, window=0, period=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
EventLogger             com.libopus_test                D    period [?]
EventLogger             com.libopus_test                D    window [?, seekable=false, dynamic=false]
EventLogger             com.libopus_test                D  ]
EventLogger             com.libopus_test                E  playerFailed [eventTime=0.91, mediaPos=0.00, window=0, period=0, errorCode=ERROR_CODE_DECODER_INIT_FAILED
                                                             androidx.media3.exoplayer.ExoPlaybackException: LibopusAudioRenderer error, index=1, format=Format(null, null, null, audio/opus, null, -1, null, [-1, -1, -1.0, null], [2, 48000]), format_supported=YES
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                 at android.os.Looper.loopOnce(Looper.java:238)
                                                                 at android.os.Looper.loop(Looper.java:357)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:85)
                                                             Caused by: androidx.media3.decoder.opus.OpusDecoderException: Invalid initialization data size
                                                                 at androidx.media3.decoder.opus.OpusDecoder.<init>(OpusDecoder.java:96)
                                                                 at androidx.media3.decoder.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:117)
                                                                 at androidx.media3.decoder.opus.LibopusAudioRenderer.createDecoder(LibopusAudioRenderer.java:34)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.maybeInitDecoder(DecoderAudioRenderer.java:729)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.onInputFormatChanged(DecoderAudioRenderer.java:782)
                                                                 at androidx.media3.exoplayer.audio.DecoderAudioRenderer.render(DecoderAudioRenderer.java:298)
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1079)
                                                                 at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:529)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                 at android.os.Looper.loopOnce(Looper.java:238)
                                                                 at android.os.Looper.loop(Looper.java:357)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:85)
                                                           ]
EventLogger             com.libopus_test                D  loading [eventTime=0.92, mediaPos=0.00, window=0, period=0, false]
EventLogger             com.libopus_test                D  state [eventTime=0.92, mediaPos=0.00, window=0, period=0, IDLE]
ProfileInstaller        com.libopus_test                D  Installing profile for com.libopus_test
System                  com.libopus_test                W  A resource failed to call close. 
---------------------------- PROCESS ENDED (27928) for package com.libopus_test ----------------------------

```
and my code is just simple:

```
MediaItem mediaItem = new MediaItem.Builder().setUri(Uri.parse(url_media.toString()))
		.setMediaId("log-session-id")
		.setMimeType(MimeTypes.AUDIO_OPUS)
		.setMimeType(MimeTypes.APPLICATION_RTSP)
		.build(); 

renderersFactory = new DefaultRenderersFactory(this.getApplicationContext())
		.setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)
		.forceEnableMediaCodecAsynchronousQueueing();
		
exoPlayerView = this.findViewById(R.id.exoplayerui);
exoPlayerView.setPlayer(exoPlayer);
exoPlayer.addAnalyticsListener(new EventLogger());
exoPlayer.setMediaItem(mediaItem);
exoPlayer.prepare();
exoPlayer.setPlayWhenReady(true);
```

where with `DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER` it loads LibopusAudioRenderer as you can see in logcat: 

`DefaultRenderersFactory com.libopus_test                I  Loaded LibopusAudioRenderer.
`
maybe that initialization data is not related to the streaming? 
I made a little .pcap where I acquired the stream with Wireshark while I was playing it with VLC Player (which plays that opus streaming over RTSP without any problems)... I could attach that pcap 36Kb if needed...

**Comment by tonihei** [comment]
Just based on the initial exception you posted and the fact that the decoder can't find valid initialization data, I assume your stream is simply malformed. Assigning to @microkatz in case they have any additional insights into whether OPUS over RTSP is allowed to not have these headers.

**Comment by lonewolf73** [comment]
Hello @microkatz ! 

Any directions about that issue I was talking with @tonihei ?..... 

Thanks in advance! 
Cheers!! :-)

**Comment by lonewolf73** [comment]
Hello @Samrobbo ,

Looking at Media3's contributors I noticed you'd work on Media3 Exoplayer libraries .... don't know if you could have worked on LibopusAudioRenderer class so I am asking you too if you could have any directions about the issue I am facing and I reported earlier in latest replies in this thread about `androidx.media3.decoder.opus.OpusDecoderException: Invalid initialization data size` since I am trying to play pure Opus stream not contained in OGG... 

Thanks in advance! 
Cheers

**Comment by microkatz** [comment]
Hello @lonewolf73,

I looked over your issue. Thank you for bringing this to our attention. It appears that the RtpOpusReader assumes that the Opus packets are Ogg encapsulated and of which I believe that is not the case with your stream. We are working to figure out the best way to update RtpOpusReader. I'll update this issue when progress has been made. I really appreciate your patience!

**Comment by lonewolf73** [comment]
Hello @microkatz 

In the meanwhile I tried also to integrate LibopusAudioRenderer but looks like it doesn't play pure Opus but incapsulated into Ogg... I tried also to modify RtpOpusReader source to see if I could help to manage two ways , pure-Opus and Ogg-incapsulated-Opus and still trying to....
Maybe , if you have already modified/updated RtpOpusReader, are there any news about it? 

Thanks in advance! 
Cheers! 
lonewolf
