### ISSUE TITLE
Why Util.SDK_INT is equal to 33 for demo application while it is equal to 30 for Mp4PlaybackTest Unit Test?

### ISSUE THREAD

**Issue by ybai001** [androidx/media#892]
My test device is Pixel 5 and it runs on Android 13 (API version 33).

I build the demo app based on Media3 latest main branch. Everything is OK. If I set a breakpoint to do debug, I find Util.SDK_INT is equal to 33. This is same as my anticipation since it means SDK version of the software currently running on the hardware device.

If I run the test case in Mp4Playback Test.java and set a breakpoint in the code, I find Util.SDK_INT is equal to 30 but I didn't change my test device at all.

Could you help me to understand it? The background of this question is I find the multi-channel stream playback behavior is different between demo application and Mp4PlaybackTest.

And in Util.java,

```
  /**
   * Like {@link Build.VERSION#SDK_INT}, but in a place where it can be conveniently overridden for
   * local testing.
   */
  @UnstableApi public static final int SDK_INT = Build.VERSION.SDK_INT;
```
If I change this line to 
`  @UnstableApi public static final int SDK_INT = 33;`
Util.SDK_INT is equal to 33 but I got below error message in Mp4PlaybackTest test report. This is strange because AudioManager.getSpatializer() is available since Android API 32. I try to debug this issue but have not found the root cause. Could you give me some hint about it? Thanks a lot in advance.
```
test[sample_eac3joc.mp4]
java.lang.NoSuchMethodError: 'android.media.Spatializer android.media.AudioManager.getSpatializer()'
	at androidx.media3.exoplayer.trackselection.DefaultTrackSelector$SpatializerWrapperV32.tryCreateInstance(DefaultTrackSelector.java:4128)
	at androidx.media3.exoplayer.trackselection.DefaultTrackSelector.<init>(DefaultTrackSelector.java:2404)
	at androidx.media3.exoplayer.trackselection.DefaultTrackSelector.<init>(DefaultTrackSelector.java:2374)
	at androidx.media3.exoplayer.trackselection.DefaultTrackSelector.<init>(DefaultTrackSelector.java:2342)
	at androidx.media3.exoplayer.trackselection.DefaultTrackSelector.<init>(DefaultTrackSelector.java:2334)
	at androidx.media3.exoplayer.ExoPlayer$Builder.lambda$new$14(ExoPlayer.java:650)
	at androidx.media3.exoplayer.ExoPlayerImpl.<init>(ExoPlayerImpl.java:277)
	at androidx.media3.exoplayer.ExoPlayer$Builder.build(ExoPlayer.java:1202)
	at androidx.media3.exoplayer.e2etest.Mp4PlaybackTest.test(Mp4PlaybackTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

My Android Studio version is Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 10, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    GLSL (1.24)
    Batch Scripts Support (1.0.13)
    idea.plugin.protoeditor (231.9225.5)

**Comment by ybai001** [comment]
For the second question, I guess I got the point. In this project, some files use Build.VERSION.SDK_INT directly. That means if I change the value of Util.SDK_INT manually, it will result in the mismatch in different files.

For the first question, it is still unclear for me. But I find below code in constants.gradle.
```
    // Upgrading this requires [Internal ref: b/193254928] to be fixed, or some
    // additional robolectric config.
    targetSdkVersion = 30
```
It seems that Util.SDK_INT will be equal to this value for unit test. And due to an internal bug, we can't change this value to a higher vale. Is it my understanding right?

**Comment by icbaker** [comment]
I think you've answered your questions already, but to clarify:
* Robolectric tests do not run on a real device, so the Android version of your dev device is not relevant.
  * You can see this by disconnecting your dev device and re-running the test - it should run fine, showing it's not running on your dev device.
* By default, Robolectric tests run with [`Build.VERSION.SDK_INT`](https://developer.android.com/reference/android/os/Build.VERSION#SDK_INT) equal to the target SDK.
  * As you've seen, this is set to 30 for this library at the moment. 
* Tests can override this by using the [`@Config`](https://robolectric.org/javadoc/latest/org/robolectric/annotation/Config.html) annotation.
  * This might let you write the test you want? You can see an example of using this to run on API 31 here:
     https://github.com/androidx/media/blob/f6fe90f30ba022c7e04e14a3dc5c28c568a4d1e2/libraries/transformer/src/test/java/androidx/media3/transformer/EncoderUtilTest.java#L189-L191 
* The comment on Media3's `Util.SDK_INT` about overriding is only about testing internal behaviour of the library. Changing this value will have no effect on code outside media3 (e.g. Robolectric).

I'm going to close this because I think this resolves all the questions.
