### ISSUE TITLE
What is media3 MediaMetadata.displayTitle role?

### ISSUE THREAD

**Issue by yt8492** [androidx/media#927]
Before media3, Now Playing Card media title refers METADATA_KEY_DISPLAY_TITLE like this.

```kotlin
val mediaMetadataCompatBuilder = MediaMetadataCompat.Builder().apply {
      putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_TITLE, playable.title)
      putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_SUBTITLE, playable.subtitle)
      putString(MediaMetadataCompat.METADATA_KEY_ART_URI, playable.artUri)
}
```

But in media3, when I set displayTitle to MediaMetadata, it seems not working. here is reproducible example.
https://github.com/yt8492/media/commit/9c959e21bccdfedb8925844d071d8a8bc7cb360d
<image src="https://github.com/androidx/media/assets/39693306/2516fa21-04e2-450d-8159-f7c724c76d65" width="300" />

Is this behavior correct? If true, what is displayTitle role in media3?

**Comment by marcbaechinger** [comment]
Thanks for your report.

Media3 is using `MediaMetadata.title` and converts from and to legacy keys [here](https://github.com/androidx/media/blob/main/libraries/session/src/main/java/androidx/media3/session/LegacyConversions.java#L441-L445) and [here](https://github.com/androidx/media/blob/main/libraries/session/src/main/java/androidx/media3/session/LegacyConversions.java#L575-L578).

So as a Media3 user you can just use `MediaMetadata.title`. This remove some ambiguity for Media3 users and you are still backwards compatible for users of the legacy or platform controller API that need to check both variants.

This behavior seems to be sensible to me. Are you using different values for `displayTitle` and `title` in your app and if you do, what is the reason to do so?

**Comment by yt8492** [comment]
@marcbaechinger 
Thank you for the answer.

> Are you using different values for displayTitle and title in your app and if you do, what is the reason to do so?

In my case, I only set a value for displayTitle and not for title. There is no particular reason, I simply replaced from ExoPlayer2 to Media3.

This worked fine most of the cases, but some devices (Xperia, OPPO, etc.) were crashing because they could not get the title from the MediaMetadata.

```
17:19:20.643  E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
--------- beginning of crash
17:19:24.875  E  FATAL EXCEPTION: SysUiBg
                 Process: com.android.systemui, PID: 22574
                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.media.MediaMetadata.getString(java.lang.String)' on a null object reference
                 	at com.android.systemui.media.MediaDataManager.loadMediaDataInBg(MediaDataManager.kt:500)
                 	at com.android.systemui.media.MediaDataManager.access$loadMediaDataInBg(MediaDataManager.kt:103)
                 	at com.android.systemui.media.MediaDataManager$loadMediaData$1.run(MediaDataManager.kt:308)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:233)
                 	at android.os.Looper.loop(Looper.java:344)
                 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

I think this is a bug on the custom os side because `MediaDataManager.loadMediaDataInBg` in AOSP does a null check, so the NPE should not occur.
I tried setting the value to title as well as displayTitle, and this improved things.

> So as a Media3 user you can just use MediaMetadata.title. This removes ambiguity for Media3 users and you are still backwards compatible for users of the legacy or platform controller API that need to check both variants.

I understand. Maybe my fixes in #928 will help in the migration from ExoPlayer2 to Media3, but I think it's not necessary.

**Comment by yt8492** [comment]
Or, if `displayTitle` has no role, we can remove `displayTitle` property from MediaMetadata.

**Comment by marcbaechinger** [comment]
I'm closing this assuming this is fixed with https://github.com/androidx/media/commit/2c912aa6971c88e6a0f43d3281df229fdb6a35db

Please open a new issue if this is required.
