### ISSUE TITLE
java.util.concurrent.TimeoutException: android.media.MediaDrm.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by cusriousandy** [androidx/media#945]
### Version

Older (unsupported)

### More version details

Exoplayer Version 2.11.8

### Devices that reproduce the issue

Mi A2 running Android OS 10
Motorola One Power running Android OS 10
Zenfone Max Pro M1 running on Android OS 9

### Reproducible in the demo app?

No

### Reproduction steps

Its reported mostly in background in Crashlytics.

### Expected result

Application should not crash

### Actual result

Crash recorded in analytics tool and crashlytics with following stacktrace

Fatal Exception: java.util.concurrent.TimeoutException: android.media.MediaDrm.finalize() timed out after 10 seconds
       at android.media.MediaDrm.native_release(MediaDrm.java)
       at android.media.MediaDrm.release(MediaDrm.java:1631)
       at android.media.MediaDrm.finalize(MediaDrm.java:1602)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
       at java.lang.Daemons$Daemon.run(Daemons.java:103)
       at java.lang.Thread.run(Thread.java:764)

### Media

Not available

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rrfrias** [comment]
Might it be possible to share a bugreport [android-media-github@google.com](mailto:android-media-github@google.com), steps to reproduce
