### ISSUE TITLE
How to play ads server side

### ISSUE THREAD

**Issue by yoobi** [androidx/media#974]
Hello, 
I've only recently begin to play with SSAI. I've seen than media3 can play and manage ads correctly (ad markers on timebar and ads do not play again when scrubbing on it) when using ssai:// urls

My issue is that when I'm using dash urls with https:// the ads marker do not display on the player, and the ad are replayed everytime. I've used the media3-demo application to test this.
Is it possible to have the same management of ads when using https protocol ?

The dash manifest looks like: 
<details>

```xml
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:scte35="urn:scte:scte35:2013:xml" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" minBufferTime="PT1S" profiles="urn:mpeg:dash:profile:isoff-main:2011" type="static" mediaPresentationDuration="PT2523.080S">
	<BaseURL>redacted</BaseURL>
	<Period id="ad1" start="PT0S" duration="PT14.960S">
		<AdaptationSet id="0" mimeType="video/mp4" contentType="video" segmentAlignment="true" startWithSAP="1">
		...
		</AdaptationSet>
		<AdaptationSet id="1" mimeType="audio/mp4" contentType="audio" lang="en" codecs="mp4a.40.2" segmentAlignment="true" startWithSAP="1">
		...
		</AdaptationSet>
	</Period>
	<Period id="ad2" duration="PT29.960S">
		<AdaptationSet id="0" mimeType="video/mp4" contentType="video" segmentAlignment="true" startWithSAP="1">
		...
		</AdaptationSet>
		<AdaptationSet id="1" mimeType="audio/mp4" contentType="audio" lang="en" codecs="mp4a.40.2" segmentAlignment="true" startWithSAP="1">
		...
		</AdaptationSet>
	</Period>
	<Period id="main" duration="PT2478.160S">
		<AdaptationSet id="0" mimeType="video/mp4" contentType="video" segmentAlignment="true" startWithSAP="1">
		...
		</AdaptationSet>
		<AdaptationSet id="1" mimeType="audio/mp4" contentType="audio" lang="en" codecs="mp4a.40.2" segmentAlignment="true" startWithSAP="1">
		...
		</AdaptationSet>
	</Period>
</MPD>
```

</details>

If the dash manifest needs to be updated in order to have access to the ads management of ima-extension, please do tell.

**Comment by marcbaechinger** [comment]
URIs with the `ssai` scheme are specific to playing ads with the `ImaServerSideAdInsertionMediaSource` that is using the DAI SDK from IMA. The `DefaultMediaSourceFactory` turns media items with such a URI into an IMA source.

To integrate your own sources that doesn't use IMA you can use `ServerSideAdInsertionMediaSource`. 
In a nutshell: Pass the `Dash` source to the constructor with your implementation of `AdPlaybackStateUpdater` and then set the `ServerSideAdInsertionMediaSource` to the player. When the player has completed preparation of the source, the `Timeline` of the content source (DASH) is passed to the updater. You can then create an `ImmutableMap` of `AdPlaybackState`s and pass it to `ServerSideAdInsertionMediaSource.setAdPlaybackStates(map, contentTimeline)`.

In your case of the multi-period DASH manifest of above, the map has 3 entries. The keys are the `Period.uid`s that you get from the `contentTimeline`, the values are the `AdPlaybackState` instances for each period. For the ad periods in the manifest above, the `AdPlaybackState` has a single ad that has the duration of the period, while the content period has an `AdPlaybacKState.NONE`, indicating the entire period is content.

Something similar to this (this obviously hardcodes the knowledge I get from readin the manifest. Your code need to have a way to recognize which periods in the manifest are actually ads. If you own the manifest, this should be easy to mark):

```
AdPlaybackState statePeriod0 =
    new AdPlaybackState(/* adsId= */ "adsId", 0)
        .withAdCount(/* adGroupIndex= */ 0, /* adCount= */ 1)
        .withAdDurationsUs(/* adGroupIndex= */ 0, /* adDurationsUs...= */ 14_960_000L)
        .withIsServerSideInserted(/* adGroupIndex= */ 0, true);

AdPlaybackState statePeriod1 =
    new AdPlaybackState(/* adsId= */ "adsId", 0)
        .withAdCount(/* adGroupIndex= */ 1, /* adCount= */ 1)
        .withAdDurationsUs(/* adGroupIndex= */ 1, /* adDurationsUs...= */ 29_960_000L)
        .withIsServerSideInserted(/* adGroupIndex= */ 1, true);

ImmutableMap<Object, AdPlaybackState> stateMap =
    ImmutableMap.of(
        contentTimeline.getPeriod(
            /* periodIndex= */ 0, new Timeline.Period(), /* setIds= */ true)
            .uid,
        statePeriod0,
        contentTimeline.getPeriod(
            /* periodIndex= */ 1, new Timeline.Period(), /* setIds= */ true)
            .uid,
        statePeriod1,
        contentTimeline.getPeriod(
            /* periodIndex= */ 2, new Timeline.Period(), /* setIds= */ true)
            .uid,
        AdPlaybackState.NONE);

ssaiSource.setPlaybackStates(stateMap, contentTimeline);
```

When an ad period has been played (probably best to use `PlayerListener.onPositinDiscontinuity()` to get informed about this), you need to update the `AdPlaybackState` for the given period, set the ad state to `AD_STATE_PLAYED` and the update the ad playback state map with calling `setAdPlaybackStates(map, contentTimeline)` again with the  updated states.

```
statePeriod0.withPlayedAd(/* adGroupIndex= */ 0, /* adIndexInAdGroup= */ 0);

ssaiSource.setPlaybackStates(stateMap, contentTimeline);
```

Can you give that a try? Happy to give some more guidance after you have taken a first look. You can also look into `ImaServerSideAdInsertionMediaSource` that uses the `ServerSideAdInsertionMediaSource` as well. Although, it's much more complicated because it handles all kinds of content sources including live and it also integrates with the IMA SDK that sends the required data that you can much more easily read directly out of the manifest.

**Comment by yoobi** [comment]
Hello,

Thank you for your detailed answer, I've begin to implement what you suggested but I'm getting some small issue along the way. To test the concept I'm not reading the manifest and I'm using hardcoded value.
```kotlin
override fun onAdPlaybackStateUpdateRequested(contentTimeline: Timeline): Boolean {
    val firstAd = AdPlaybackState( /* adsId= */"adsId", 0L)
        .withAdCount( /* adGroupIndex= */0,  /* adCount= */1)
        .withAdDurationsUs( /* adGroupIndex= */0,  /* ...adDurationsUs = */14_960_000L)
        .withIsServerSideInserted( /* adGroupIndex= */0, true)

    val secondAd = AdPlaybackState( /* adsId= */"adsId", 0L)
        .withAdCount( /* adGroupIndex= */1,  /* adCount= */1)
        .withAdDurationsUs( /* adGroupIndex= */1,  /* ...adDurationsUs= */29_960_000L)
        .withIsServerSideInserted( /* adGroupIndex= */1, true)

    val map: ImmutableMap<Any, AdPlaybackState> = ImmutableMap.of(
        contentTimeline.getPeriod(0, Timeline.Period(), true).uid, firstAd,
        contentTimeline.getPeriod(1, Timeline.Period(), true).uid, secondAd,
        contentTimeline.getPeriod(2, Timeline.Period(), true).uid, AdPlaybackState("adsId"),
    )
    serverSideAdInsertionMediaSource.setAdPlaybackStates(map, contentTimeline)
    return true
}
```
But I'm getting an issue for the `secondAd.withAdCount()` which leads to https://github.com/androidx/media/blob/f6fe90f30ba022c7e04e14a3dc5c28c568a4d1e2/libraries/common/src/main/java/androidx/media3/common/AdPlaybackState.java#L750
```
Unexpected exception handling load completed
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at androidx.media3.common.AdPlaybackState.withAdCount(AdPlaybackState.java:750)
        at androidx.media3.demo.main.POCServerSideAdInsertionMediaSource.onAdPlaybackStateUpdateRequested(POCServerSideAdInsertionMediaSource.kt:50)
        at androidx.media3.exoplayer.source.ads.ServerSideAdInsertionMediaSource.onSourceInfoRefreshed(ServerSideAdInsertionMediaSource.java:263)
        at androidx.media3.exoplayer.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:90)
```

I'm not sure to understand what `adGroupIndex` is supposed to represent. If I got 2 ads in my content, must they have to have the same index ?

I had an issue with `AdPlaybackState.NONE` for the content, as `AdPlaybackState.NONE` has adsId set to null and the `[checkArgument](https://github.com/androidx/media/blob/f6fe90f30ba022c7e04e14a3dc5c28c568a4d1e2/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/ads/ServerSideAdInsertionMediaSource.java#L163C9-L163C9)` would throw an `IllegalArgumentException`

**Comment by marcbaechinger** [comment]
Ah, sorry for not being precise and not having checked whether this runs.

> java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

That was a typo in my comment, that I corrected above. 

The exception was thrown by the second ad playback state that wanted to set the `adCount` of the `adGroupIndex=1`, while in fact each of the states has only a single ad group.

The constructor has a vararg argument that passes N `adGroupTimes`. For each of the `adGroupTime` a ad group is created, so we get N ad groups.

```
AdPlaybackState( /* adsId= */ "adsId", /* adGroupTimes */ 0L, 10_000_000L, C.TIME_END_OF_SOURCE);
```

For your purpose you only need a single ad group for each `AdPlaybackState`, so the exception was because I mistakenly told you to us `adGroupIndex=1` for the second state which is wrong. You should use 0 for each state because each state has a single ad that spans the whole period. Correct is using `adGroupIndex=0` here:

```
val secondAd = AdPlaybackState( /* adsId= */"adsId", 0L)
        .withAdCount( /* adGroupIndex= */ 0,  /* adCount= */1)
        .withAdDurationsUs( /* adGroupIndex= */ 0,  /* ...adDurationsUs= */29_960_000L)
        .withIsServerSideInserted( /* adGroupIndex= */ 0, true)
```

> If I got 2 ads in my content, must they have to have the same index ?

Each period gets an `AdPlaybackState` instance. So each period has only a single ad for your case of a multi-period stream.

> AdPlaybackState.NONE has adsId set to null 

Yeah, sorry, this can only be used for internal purposes. Instead I think you can just do `new AdPlaybackState("adsId")` which results in an empty state with adGroupCount=0.

**Comment by yoobi** [comment]
Sure no problem ! I have managed to mark ads as played with:
```kotlin
class POCServerSideAdInsertionMediaSource(
    mediaItem: MediaItem,
    private val contentMediaSourceFactory: MediaSource.Factory,
): MediaSource.Factory, ServerSideAdInsertionMediaSource.AdPlaybackStateUpdater, Player.Listener {

    private var adPlaybackStates: ImmutableMap<Any, AdPlaybackState> = ImmutableMap.of()
    private var contentTimeline: Timeline? = null
    private val serverSideAdInsertionMediaSource = ServerSideAdInsertionMediaSource(
        contentMediaSourceFactory.createMediaSource(mediaItem), this
    )
    ...
    // ServerSideAdInsertionMediaSource.AdPlaybackStateUpdater
    override fun onAdPlaybackStateUpdateRequested(contentTimeline: Timeline): Boolean {
        val firstAd = AdPlaybackState( /* adsId= */"adsId", 0L)
            .withAdCount( /* adGroupIndex= */0,  /* adCount= */1)
            .withAdDurationsUs( /* adGroupIndex= */0,  /* ...adDurationsUs = */14_960_000L)
            .withIsServerSideInserted( /* adGroupIndex= */0, true)

        val secondAd = AdPlaybackState( /* adsId= */"adsId", 0L)
            .withAdCount(/* adGroupIndex= */0,  /* adCount= */1)
            .withAdDurationsUs( /* adGroupIndex= */0,  /* ...adDurationsUs= */29_960_000L)
            .withIsServerSideInserted( /* adGroupIndex= */0, true)

        val map: ImmutableMap<Any, AdPlaybackState> = ImmutableMap.of(
            contentTimeline.getPeriod(0, Timeline.Period(), true).uid, firstAd,
            contentTimeline.getPeriod(1, Timeline.Period(), true).uid, secondAd,
            contentTimeline.getPeriod(2, Timeline.Period(), true).uid, AdPlaybackState("adsId"),
        )
        this.adPlaybackStates = adPlaybackStates
        this.contentTimeline = contentTimeline
        serverSideAdInsertionMediaSource.setAdPlaybackStates(adPlaybackStates, contentTimeline)
        return true
    }

    override fun onPositionDiscontinuity(oldPosition: Player.PositionInfo, newPosition: Player.PositionInfo, reason: Int) {
        super.onPositionDiscontinuity(oldPosition, newPosition, reason)
        if(oldPosition.adGroupIndex == C.INDEX_UNSET) return
        val newPlaybackState = mutableMapOf<Any, AdPlaybackState>()
        val ads = adPlaybackStates.values.find { it.getAdGroup(oldPosition.adGroupIndex).hasUnplayedAds() }
        adPlaybackStates.forEach { (key, value) ->
            val newValue = if(value == ads) value.withPlayedAd(0, 0) else value
            newPlaybackState[key] = newValue
        }
        this.adPlaybackStates = adPlaybackStates
        this.contentTimeline = contentTimeline
        serverSideAdInsertionMediaSource.setAdPlaybackStates(adPlaybackStates, contentTimeline)
    }
}
```

I have taken a look at `ImaUtils` and there is some function to split and mark adPlaybackState as played using the contentTimeline. Should I recreate the adPlaybackStates using ImmutableMap or is it okay to simply update the map as I did ?

**Comment by marcbaechinger** [comment]
I think I'd create a new `ImmutableMap` just to be sure. The reason is that `onPositionDiscontinuity` is called an the app thread and the media source accesses the map on the playback thread. I think for your case of a VOD stream that never changes `period.uid`s it would work either way, but I'd be careful. The ad playback state itself is immutable and you create a copy with `value.withPlayedAd(0, 0)` so that's fine. But recreating the map is probably a bit more on the safe side (fine to call me paranoid :)).

`ImaUtils` is complicated because the IMA SDK gives us the ad metadata for the entire stream and in case of multi-period DASH this needs to be mapped to multiple periods. This is introduced by the SDK that delivers the data in the same way for single-period HLS and multi-period DASH. When you can read directly from the manifest this is much easier.

**Comment by yoobi** [comment]
I see, I'll create a new `ImmutableMap` to be safe as we might integrate this with live stream later.

Thank you very much for your time and the detailed answer which helps me a lot.

**Comment by yoobi** [comment]
Hello ! I'm back with more questions if you don't mind :)

I have started thinking about ads event, is there a way to listen to ads error ? I'm thinking about `override fun onPlayerError(error: PlaybackException)` but there is no info about which ad is failing, or I need to track it back with `player.currentPosition` and check which period is within that position ?

**Comment by marcbaechinger** [comment]
> is there a way to listen to ads error

I'd say yes if with 'ad error' you mean a playback error while an ad period is playing.

Your example is using `Player.Listener.onPlayerError(error)`. If you use `AnalyticsListener.onPlayerError(EventTime, errror)` you get the `EventTime` for free which helps you to figure out in more detail when the error was thrown. It gives you the `Timeline` at the time of the event as well as  things like `currentMediaPeriodId` and friends. The `MediaPeriodId` then has the period UID as well as the ad information if case the period is an ad.

Would this help for your case?

**Comment by marcbaechinger** [comment]
> I can't start the player again, ...

The player transitions into `STATE_IDLE` after the error. I assume you mark the ad as `AD_STATE_ERROR` and call `prepare()` again on the player to restart (while not resetting the ad state).  If you don't change the player's position I'd think this just prepares from where it was left off.

> ..., or make it skip the broken ad

The player should then evaluate the timeline for which period to pick at the current position. This time it should ignore the ad period in state ERROR and continue from the period after it. 

That's briefly how it should work. 

To verify, you could repro again with an `EventLogger` attached. Then filter for `positionDiscontinuity` which should give you the sequence of period transitions (ads marked as a such). If you include the lines grep'd with "state [" you get the state changes caused by the error (STATE_IDLE). The following  `positionDiscontinuity` events are the interesting ones and any further `EventLogger` output after the error.

It's fine to post these logs here also if you want us to look into this.

**Comment by yoobi** [comment]
Hello, thank you for your help, here is the log I got where the player
```xml
onAdPlaybackStateUpdateRequested
generate: {0=AdPlaybackState(adsId=adsId, adResumePositionUs=0, adGroups=[adGroup(timeUs=0, ads=[ad(state=_, durationUs=14960000)])]), 1=AdPlaybackState(adsId=adsId, adResumePositionUs=0, adGroups=[adGroup(timeUs=0, ads=[ad(state=_, durationUs=29960000)])]), 2=AdPlaybackState(adsId=adsId, adResumePositionUs=0, adGroups=[])}
internalError [eventTime=0.32, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
internalError [eventTime=0.32, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
internalError [eventTime=0.33, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
internalError [eventTime=0.33, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
internalError [eventTime=1.34, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
internalError [eventTime=1.34, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
internalError [eventTime=3.35, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
Playback error UnknownHostException (no network
internalError [eventTime=3.35, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, loadError UnknownHostException (no network)]
playerFailed [eventTime=3.39, mediaPos=0.00, window=0, period=0, adGroup=0, ad=0, errorCode=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED UnknownHostException (no network)]
update: {0=AdPlaybackState(adsId=adsId, adResumePositionUs=0, adGroups=[adGroup(timeUs=0, ads=[ad(state=!, durationUs=14960000)])]), 1=AdPlaybackState(adsId=adsId, adResumePositionUs=0, adGroups=[adGroup(timeUs=0, ads=[ad(state=_, durationUs=29960000)])]), 2=AdPlaybackState(adsId=adsId, adResumePositionUs=0, adGroups=[])}
```

When updating my code with a `seekTo()` and `prepare()` it now passes to the next content
