### ISSUE TITLE
How to unit test ExoPlaybackException.TYPE_RENDERER?

### ISSUE THREAD

**Issue by cdongieux** [androidx/media#975]
Hi,

I'd like to make a unit test for checking a retry policy I'm working on (AndroidX Media 3 1.2.0), but I can't make this test work:

```
    @Test
    fun test_ExoPlaybackException_TypeRenderer() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        val mediaSource = FakeMediaSource(FakeTimeline(), ExoPlayerTestRunner.AUDIO_FORMAT)
        val testRunner = ExoPlayerTestRunner.Builder(context)
            .setMediaSources(mediaSource)
            .setRenderers(object : FakeRenderer(C.TRACK_TYPE_AUDIO) {
                override fun render(positionUs: Long, elapsedRealtimeUs: Long) {
                    createRendererException(
                        /* cause */ RuntimeException("boom!"),
                        /* format */ ExoPlayerTestRunner.AUDIO_FORMAT,
                        /* errorCode */ PlaybackException.ERROR_CODE_UNSPECIFIED
                    )
                }
            })
            .setAnalyticsListener(analyticsListener)
            .build()

        val exception = Assert.assertThrows(ExoPlaybackException::class.java) {
            testRunner
                .start()
                .blockUntilEnded(10_000L)
        }
        assertEquals(ExoPlaybackException.TYPE_RENDERER, exception.type)
        verify(exactly = 0) {
            analyticsListener.onLoadError(any(), any(), any(), any(), any())
        }
        verify(exactly = 1) {
            analyticsListener.onPlayerError(any(), any())
        }
    }
```

Test fails with this:

```
java.lang.AssertionError: unexpected exception type thrown; expected:<androidx.media3.exoplayer.ExoPlaybackException> but was:<java.util.concurrent.TimeoutException>
at org.junit.Assert.assertThrows(Assert.java:1020)
at org.junit.Assert.assertThrows(Assert.java:981)
at net.xxx.player.exoplayer.ExoPlayerRetryTest.test_ExoPlaybackException_TypeRenderer(ExoPlayerRetryTest.kt:457)
... 32 trimmed
Caused by: java.util.concurrent.TimeoutException: Test playback timed out waiting for playback to end.
at androidx.media3.test.utils.ExoPlayerTestRunner.blockUntilEnded(ExoPlayerTestRunner.java:530)
```

It's like the Renderer is never called. And EventLogger gives this output:

```
01-15 10:04:08.636 11105 11196 D EventLogger: playWhenReady [eventTime=-1425.87, mediaPos=0.00, window=0, true, USER_REQUEST]
01-15 10:04:08.649 11105 11196 D EventLogger: timeline [eventTime=-1425.87, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
01-15 10:04:08.650 11105 11196 D EventLogger:   period [?]
01-15 10:04:08.650 11105 11196 D EventLogger:   window [?, seekable=false, dynamic=true]
01-15 10:04:08.650 11105 11196 D EventLogger: ]
01-15 10:04:08.652 11105 11196 D EventLogger: mediaItem [eventTime=-1425.87, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
01-15 10:04:08.659 11105 11196 D EventLogger: state [eventTime=-1425.87, mediaPos=0.00, window=0, BUFFERING]
01-15 10:04:08.708 11105 11196 D EventLogger: timeline [eventTime=-1425.87, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=SOURCE_UPDATE
01-15 10:04:08.708 11105 11196 D EventLogger:   period [133.00]
01-15 10:04:08.708 11105 11196 D EventLogger:   window [10.00, seekable=true, dynamic=false]
01-15 10:04:08.709 11105 11196 D EventLogger: ]
01-15 10:04:08.882 11105 11196 D EventLogger: loading [eventTime=-1425.87, mediaPos=0.00, window=0, period=0, true]
01-15 10:04:08.888 11105 11196 D EventLogger: tracks [eventTime=-1425.87, mediaPos=0.00, window=0, period=0
01-15 10:04:08.888 11105 11196 D EventLogger:   group [
01-15 10:04:08.888 11105 11196 D EventLogger:     [X] Track:0, id=null, mimeType=audio/mp4a-latm, bitrate=100000, channels=2, sample_rate=44100, supported=YES
01-15 10:04:08.888 11105 11196 D EventLogger:   ]
01-15 10:04:08.888 11105 11196 D EventLogger: ]
01-15 10:04:08.899 11105 11196 D EventLogger: loading [eventTime=-1425.86, mediaPos=0.00, window=0, period=0, false]
01-15 10:04:08.901 11105 11196 D EventLogger: state [eventTime=-1425.86, mediaPos=0.00, window=0, period=0, READY]
01-15 10:04:08.903 11105 11196 D EventLogger: isPlaying [eventTime=-1425.86, mediaPos=0.00, window=0, period=0, true]
```

What am I missing?

**Comment by microkatz** [comment]
Hello @cdongieux 

First of all, it looks like your unit test is failing due to timeout in your block condition. Second of all, you don't appear to calling your player to `prepare()`. Since the player is not prepared, it won't move to calling `renderer.render()` and hitting your error condition.

May I suggest looking at some of the unit tests in [ExoPlayerTest.java](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/test/java/androidx/media3/exoplayer/ExoPlayerTest.java) for inspiration?

Hope that helps!

**Comment by microkatz** [comment]
I'm going to close this issue as hopefully the above comment assisted you. Please reopen or create a new issue if you have additional questions!
