### ISSUE TITLE
AES clearkey video plays, but won't download

### ISSUE THREAD

**Issue by Ste-RH** [androidx/media#984]
### Version

Media3 1.1.0

### Devices that reproduce the issue

Xiaomi Mi 10T running Android 12

### Reproducible in the demo app?

Yes

### Reproduction steps

Using the DownloadManager and DownloadHelper classes, create a DownloadRequest (downloadHelper.getDownloadRequest(uri.getPath(), null)) and add it to be downloaded (addDownload( downloadRequest )).

### Expected result

The download should succeed.

Note that the same URL plays back just fine.

### Actual result

The video fails to download, thoring the folling to logcat:

`Task failed: null:/UnitySupport/AVProVideo/Media/AES_test_1/oceans_aes_test.m3u8, false
                                                                                                      androidx.media3.datasource.HttpDataSource$HttpDataSourceException: java.net.MalformedURLException: unknown protocol: data
                                                                                                          at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:404)
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:798)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:611)
                                                                                                          at androidx.media3.datasource.cache.CacheWriter.readBlockToCache(CacheWriter.java:174)
                                                                                                          at androidx.media3.datasource.cache.CacheWriter.cache(CacheWriter.java:136)
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader$SegmentDownloadRunnable.doWork(SegmentDownloader.java:507)
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader$SegmentDownloadRunnable.doWork(SegmentDownloader.java:484)
                                                                                                          at androidx.media3.common.util.RunnableFutureTask.run(RunnableFutureTask.java:126)
                                                                                                          at com.renderheads.AVPro.Video.-$$Lambda$_14QHG018Z6p13d3hzJuGTWnNeo.execute(Unknown Source:0)
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader.download(SegmentDownloader.java:242)
                                                                                                          at androidx.media3.exoplayer.offline.DownloadManager$Task.run(DownloadManager.java:1341)
                                                                                                      Caused by: java.net.MalformedURLException: unknown protocol: data
                                                                                                          at java.net.URL.<init>(URL.java:608)
                                                                                                          at java.net.URL.<init>(URL.java:498)
                                                                                                          at java.net.URL.<init>(URL.java:447)
                                                                                                          at androidx.media3.datasource.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:548)
                                                                                                          at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:398)
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:798) 
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:611) 
                                                                                                          at androidx.media3.datasource.cache.CacheWriter.readBlockToCache(CacheWriter.java:174) 
                                                                                                          at androidx.media3.datasource.cache.CacheWriter.cache(CacheWriter.java:136) 
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader$SegmentDownloadRunnable.doWork(SegmentDownloader.java:507) 
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader$SegmentDownloadRunnable.doWork(SegmentDownloader.java:484) 
                                                                                                          at androidx.media3.common.util.RunnableFutureTask.run(RunnableFutureTask.java:126) 
                                                                                                          at com.renderheads.AVPro.Video.-$$Lambda$_14QHG018Z6p13d3hzJuGTWnNeo.execute(Unknown Source:0) 
                                                                                                          at androidx.media3.exoplayer.offline.SegmentDownloader.download(SegmentDownloader.java:242) 
                                                                                                          at androidx.media3.exoplayer.offline.DownloadManager$Task.run(DownloadManager.java:1341) `

### Media

https://rh-clients.s3.amazonaws.com/UnitySupport/AVProVideo/Media/AES_test_1/oceans_aes_test.m3u8

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by microkatz** [comment]
@Ste-RH 

Are you setting up your download manager with an DefaultHttpDataSource.Factory()? The DefaultHttpDataSource assumes that the URI provided in the .m3u8 file is an HTTP URI. Does it work if you change your DownloadManager to use DefaultDataSourceFactory?

**Comment by Ste-RH** [comment]
Yes indeed I am using the DefaultHttpDataSource.Factory !

I am not in front of a PC at the moment that I can change and test change to DefaultDataSource.Factory, but will test that change as soon as I can. Would there be any limitations for that change?

**Comment by microkatz** [comment]
@Ste-RH 
Great! Let me know if that change works for you. It should not limit you as for if the content should be downloaded via an HTTP, then DefaultDataSource.Factory would use a form of "http" data source to download. You can also configure DefaultDataSource.Factory to use a specific "Http" data source type if you so choose.

Hope you were able to test and that fixed your issue!

**Comment by microkatz** [comment]
Since I have not heard back I'm hoping that this has fixed your issue. I will close this issue. If you are still having problems then open up a new one. Thanks!
